### ISSUE TITLE
Improve the Python API

### ISSUE THREAD

**Issue by asmeurer** [msoos/cryptominisat#161]
I suggest you don't make the same mistakes as pycosat in the Python API (c.f. https://github.com/ContinuumIO/pycosat/issues/14). It's better to return builtin types representing the output, not strings. I would return `None` for unsatisfiable (or `[[]]`, though that may confuse a lot of people), and raise an exception for unknown (probably some custom PropogationLimit exception subclassed from `Exception`).

**Comment by msoos** [comment]
Took me a while, but I did it! Only a year and a half :D Thanks a LOT for these suggestions!
