### ISSUE TITLE
Symmetry breaking (no issue, rather a question)

### ISSUE THREAD

**Issue by a1880** [msoos/cryptominisat#194]
Hi Mate,
I have been experimenting with symmetry detection and symmetry breaking constraints to bring the solution time down. I've experimented with "saucy 3" (http://vlsicad.eecs.umich.edu/BK/SAUCY/). Saucy is able to detect many symmetries(and could be easily added to a SAT solver). However, the symmetry breaking clauses seem to be more a burden than a remedy. For simple examples, adding symmetry breaking constraints actually prevented Cryptominisat from finding a solution. The attempted speed-up did not happen.
Do you have any experiences or plans in this direction?

Greetings

Axel

**Comment by msoos** [comment]
I am closing since this is stale :( I have no time to re-read them unfortunately. If you managed to and have some experimental code running, it'd be nice if you could share -- please re-open in that case. Thanks!

**Comment by a1880** [comment]
OK. My experiments have not shown improvements by adding symmetry breaking constraints. At least not for my (highly symmetrical) examples.
