### ISSUE TITLE
Bad_alloc?

### ISSUE THREAD

**Issue by iceman1001** [msoos/cryptominisat#204]
Is the cryptominisat running out of memory?

user@ubuntuvm:~/grainofsalt-1.2.1/build/satfiles$ cryptominisat --version
c CryptoMiniSat version 4.2.0 (GIT not found)
c CryptoMiniSat SHA revision d60517bdf05e3661bab5c8c914c134ab8a1ff00a
c compiled with gcc version 4.8.2

The CNF file:  
----
p cnf 1912 26400
----
user@ubuntuvm:~/grainofsalt-1.2.1/build/satfiles$ cryptominisat 64.cnf --verb 0
 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by msoos** [comment]
Yup, this has been fixed, actually. We no longer learn indefinitely.

**Comment by iceman1001** [comment]
It is better to close old issues, especially since you fixed it ;)  Great work!
