### ISSUE TITLE
HOWTO_WEB file is outdated?

### ISSUE THREAD

**Issue by msgmaxim** [msoos/cryptominisat#210]
Hello Mate,

I was trying to get the web stuff running and followed the HOWTO_WEB guide, but the file web/tablestructure.sql from step 4 
> "run mysql -u cryptomsuser cryptoms < web/tablestructure.sql"

is missing. I assumed cmsat_tablestructure.sql is the same thing, but then I don't have table restartDB from step 5 
>"you can now play around with the data in mysql: ... select * from restartDB;"

Anyway, when I run
> build/cryptominisat --sql 2 problem.cnf

I don't get any SQL error, but the database tables remain empty.

Thanks,
Maxim

**Comment by msoos** [comment]
It will create sqlite data by default. You have to adjust the --wsql parameter. I am so sorry for being so late :( I usually respond within a day...

**Comment by msoos** [comment]
It is now auto-generated and hence never out of date. Also, it is part of the continuous integration system and so should be checked all the time! :) All should be good!
