### ISSUE TITLE
Segfault on maxtime exit when proven SAT, but no fully assigned model

### ISSUE THREAD

**Issue by re-curse** [msoos/cryptominisat#220]
Hey Mate,

I have some rather complicated formulas I don't necessarily care about coming up with a model, but rather just determining UNSAT/SAT.

Currently, given enough maxtime and threads it can get to the point to prove SAT, but hasn't fully commited to the actual satisfying assignments. With not enough multithreaded maxtime (or just single threaded), CMS exits cleanly with indeterminate status.

There's a small bug. When printing statistics after proven SAT but aborted prematurely due to maxtime, CMS will segfault trying to access the model since no model exists in memory yet. Maybe needs a check to ignore printing the model when exiting with a model-less SAT status?

I can link you the .cnf if you feel you need to test it. It's a somewhat large file though. Just let me know :)

Thanks,
Joel

**Comment by msoos** [comment]
> I have some rather complicated formulas I don't necessarily care about coming up with a model, but rather just determining UNSAT/SAT.

-> current SAT solvers always give a model.

> There's a small bug. When printing statistics after proven SAT but aborted prematurely due to maxtime, CMS will segfault trying to access the model since no model exists in memory yet. Maybe needs a check to ignore printing the model when exiting with a model-less SAT status?

Sure, sorry, I'll fix that this weekend (lots of work nowadays).

No need for the CNF, should be easily reproducible. 

Thanks for the bugreport,

Mate

**Comment by capiman** [comment]
Hi Joel,
can you retest with latest sources if problem still occurs?
Can you provide CNF and how you call cryptominisat? Which command line options were used?
Best regards,
Martin

**Comment by re-curse** [comment]
I think it's been fixed, now.

The same CNFs that were causing me trouble before with time limiting now exit with a decent Indeterminate status instead of segfaulting.

Sorry didn't close the bug before. Will do that now :) Thanks.
