### ISSUE TITLE
sudo make install on Raspberry Pi 2 installs no lib?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#221]
I just compiled cryptominisat successfully on a Raspberry Pi 2 (OS: Raspian)
(after changing compiler gcc/g++ 4.6 to 4.8)

sudo make install

seems to work, but when I start cryptominisat outside of "build"-directory,
it reports:

cryptominisat: error while loading shared libraries: libcryptominisat4.so: cannot open shared object file: No such file or directory

I assume that "sudo make install" copies the executables, but not the library?

**Comment by msoos** [comment]
Can you please try typing:

`sudo ldconfig`

and then try to execute it again outside of the build directory? Maybe that fixes it :)

**Comment by capiman** [comment]
This worked!

Is this something missing in makefile?

Or is it missing on description?
http://www.msoos.org/cryptominisat4/

Or just something, you must know as Linux user?

**Comment by msoos** [comment]
It's build system stuff and I don't really know how to solve it -- it seems to plague other projects, too. A log-out + log-in solves it. Restart solves it. So usually it's OK. but I don't know how to properly solve it such that it works out of the box without breaking the build on other systems (e.g. Windows). If you have an idea how to solve it, I'm happy to fix it of course :)

**Comment by capiman** [comment]
Ok, many thanks for your answer!
