### ISSUE TITLE
error when --dumpirred=filename used with solvable problems

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#223]
I have a solvable problem I use for testing.  When I set execution flags to:
--bva=0 --dumpred=filename.red --dumpirred=filename.irred --dumpresult=filename.result

I get the following error message:

Cannot open file 'filename.irred' for writing. exiting

But an empty filename.irred file is created.

If I remove the --dumpirred command fro the execution flags,  cryptominisat runs correctly.  It appears that the software has trouble when there is nothing irreducible to save to a file.

**Comment by msoos** [comment]
Thanks for reporting!
