### ISSUE TITLE
new seg fault when using either --dumpred or --dumpirred commands

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#224]
When I run cryptominisat on a solvable problem and include either --dumpred=filename,red or --dumpirred=filename.irred, a segment fault is generated.  The following is an example command:

cryptominisat_v4 --verb=0 --verbstat=0 --printsol=1      --bva=0 --dumpred=filename.red --dumpirred=filename.irred --dumpresult=filename.result filename.sat

I must remove both --dumpred and --dumpirred commands to stop the segment fault.  The --dumpresult command seems to be fine.

I am using cryptominisat version ef81c370b1 which is only about 1 hour old.

**Comment by msoos** [comment]
Damn, sorry, it was a wrong fix. This should do the trick! Thanks again!
