### ISSUE TITLE
minor problem:  duplicated entries when using --dumpirred

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#225]
When using the --dumpirred=filename command many of the entries in the resulting file are duplicated.

**Comment by msoos** [comment]
Please create more meaningful bugreports :) With what example input(s)? Were these clauses duplicated in the input? Can you provide the output? Point out where the duplication occurred? With what exact command line?

**Comment by baston007** [comment]
I have not been able to reproduce the duplication of lines in the
    filename.irred file.  Please close this for now.  If it happens
    again, I will save everything so I can pass along any and all useful
    information.
    
    Rob
    
    On 24/03/15 09:50 AM, Mate Soos wrote:
    
    
      Please create more meaningful bugreports :) With what example
        input(s)? Were these clauses duplicated in the input? Can you
        provide the output? Point out where the duplication occurred?
        With what exact command line?
      —
        Reply to this email directly or view
          it on GitHub.
