### ISSUE TITLE
A question about gauss eliminattion in cryptominisat 2.9.x

### ISSUE THREAD

**Issue by jaenjames** [msoos/cryptominisat#226]
Maybe it is a really old version of cryptominisat, but I encountered a problem when using it .Given a system of linear equaltions(1128 vars ,more than 1000 equaltions),I want to solve it using the option "--gaussuntil".(For it is too slow using the defualt command).How can I set an appropriate parameter for the option?

**Comment by msoos** [comment]
Unfortunately, you need to guess. Put in 100 and then if that doesn't work, put in 500, 1000, etc. Get back to me with the results :)

**Comment by jaenjames** [comment]
If I set an inappropriate parameter ,the program will return a wrong result?

**Comment by jaenjames** [comment]
I mean that  when solving a solvable system of equaltions the pargram return unsolvable.

**Comment by msoos** [comment]
Man, just do it :) It will always return a valid result, it might take a long while, though!

**Comment by jaenjames** [comment]
I have already did it.I cut down some equaltions (reduced to 100 equaltions ,1128vars),when set --gaussuntil=100,10,1128,it returned unsolvable,but when using the default command it returned solvable taking a longer time.

**Comment by jaenjames** [comment]
the version I used is 2.9.6.

**Comment by msoos** [comment]
WOW, that's a bug. Can you please send me the input formula (i.e. CNF), and the exact execution parameters? Also, I need to know where you downloaded the 2.9.6 from, and if possible, the tarball that you used (there were some different versions circulating around) if you still have them. Please send these to: soos.mate@gmail.com. I will reply immediately and I will debug this over the course of the next week or so.

Thanks for all!

Mate

**Comment by jaenjames** [comment]
I am so sorry that I cannot give the input file to you for it is involved some undone work. I download the  the 2.9.6 from https://gforge.inria.fr/frs/?group_id=1992. I downloaded a compiled file:cryptominisat-2.9.6-win32.exe.

**Comment by jaenjames** [comment]
So ,thank you allthe same.

**Comment by msoos** [comment]
OK. Unfortunately, I can't debug then. Thanks anyway!

Mate
