### ISSUE TITLE
error loading libcryptominisat4.so.4.2.0

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#230]
When attempting to run cryptominisat version 673180894a I see the following error message:

cryptominisat: error while loading shared libraries: libcryptominisat4.so.4.2.0: cannot open shared object file: No such file or directory

I then uninstalled cryptominisat which generated this message:

[root@localhost build]# make uninstall
-- Uninstalling "/usr/local/bin/cryptominisat_simple"
-- Uninstalling "/usr/local/bin/cryptominisat"
-- Uninstalling "/usr/local/lib/libcryptominisat4.a"
-- Uninstalling "/usr/local/include/cryptominisat4/solvertypesmini.h"
-- Uninstalling "/usr/local/include/cryptominisat4/cryptominisat.h"
-- Uninstalling "/usr/local/lib/libcryptominisat4.so"
-- Uninstalling "/usr/local/lib/libcryptominisat4.so.4.2.0"
-- Uninstalling "/usr/local/lib/cmake/cryptominisat4/cryptominisat4Targets-relwithdebinfo.cmake"
-- Uninstalling "/usr/local/lib/cmake/cryptominisat4/cryptominisat4Targets.cmake"
-- Uninstalling "/usr/local/lib/cmake/cryptominisat4/cryptominisat4Config.cmake"
Built target uninstall
[root@localhost build]#

  The library file appears to have been loaded correctly during the install, but cryptominisat could not find it for some reason.  Is the tool looking in the wrong place, or is there a spelling mistake somewhere?

Rob

**Comment by baston007** [comment]
More information.

I also ran ldconfig, but the same error message was generated.

Both the April 5 (9d0f57c745) version of cryptominisat and the April 13 (673180894a) are the same size, but contain different data.

**Comment by baston007** [comment]
Still investigating

**Comment by msoos** [comment]
Please do : 
```
sudo make uninstall
sudo make clean
make
sudo make install
sudo ldconfig
```

It should then work when you execute

```
cryptominisat example.cnf
```

Please try to do the above and get back to me about the results. If no luck, I need:
* distribution
* gcc version number
* `ls /usr/local/lib | grep crypto`
* `ls /usr/lib | grep crypto`
* `ldd cryptominisat`
* `which cryptominisat`

Thanks,

Mate

**Comment by baston007** [comment]
[root@localhost build]# make install
Copying cryptominisat.h to /home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/build/include/cryptominisat4
Copying solvertypesmini.h to /home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/build/include/cryptominisat4
[  0%] Built target CopyPublicHeaders
[ 87%] Built target temp_lib
[ 87%] Built target libcryptominisat4
[ 92%] Built target cryptominisat
[ 97%] Built target cryptominisat_simple
[ 97%] Built target libcryptominisat4_static
[100%] Generating build/timestamp
running build_ext
[100%] Built target pytarget
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/local/lib/cmake/cryptominisat4/cryptominisat4Config.cmake
-- Installing: /usr/local/lib/cmake/cryptominisat4/cryptominisat4Targets.cmake
-- Installing: /usr/local/lib/cmake/cryptominisat4/cryptominisat4Targets-relwithdebinfo.cmake
-- Installing: /usr/local/lib/libcryptominisat4.so.4.2.0
-- Installing: /usr/local/lib/libcryptominisat4.so
-- Installing: /usr/local/include/cryptominisat4/cryptominisat.h
-- Installing: /usr/local/include/cryptominisat4/solvertypesmini.h
-- Installing: /usr/local/lib/libcryptominisat4.a
-- Installing: /usr/local/bin/cryptominisat
-- Removed runtime path from "/usr/local/bin/cryptominisat"
-- Installing: /usr/local/bin/cryptominisat_simple
-- Removed runtime path from "/usr/local/bin/cryptominisat_simple"
running install
running build
running build_py
file test_pycryptosat.py (for module test_pycryptosat) not found
file test_pycryptosat.py (for module test_pycryptosat) not found
running build_ext
running install_lib
running install_egg_info
Removing /usr/lib64/python2.7/site-packages/pycryptosat-4.2.0-py2.7.egg-info
Writing /usr/lib64/python2.7/site-packages/pycryptosat-4.2.0-py2.7.egg-info
file test_pycryptosat.py (for module test_pycryptosat) not found
writing list of installed files to 'files.txt'
[root@localhost build]#

[baston@localhost build]$ make
Copying cryptominisat.h to /home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/build/include/cryptominisat4
Copying solvertypesmini.h to /home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/build/include/cryptominisat4
[  0%] Built target CopyPublicHeaders
[  2%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/cnf.cpp.o
[  4%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/propengine.cpp.o
[  7%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/varreplacer.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/varreplacer.cpp:98:36: warning: unused parameter ‘outerToInter’ [-Wunused-parameter]
     const std::vector< uint32_t >& outerToInter
                                    ^
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/varreplacer.cpp:99:38: warning: unused parameter ‘interToOuter’ [-Wunused-parameter]
     , const std::vector< uint32_t >& interToOuter
                                      ^
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/varreplacer.cpp:843:17: warning: unused parameter ‘lit2’ [-Wunused-parameter]
     , const Lit lit2
                 ^
[  9%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/clausecleaner.cpp.o
[ 12%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/clauseusagestats.cpp.o
[ 14%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/prober.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/prober.cpp:295:20: warning: unused parameter ‘poss_choice’ [-Wunused-parameter]
     , vector<Var>& poss_choice
                    ^
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/prober.cpp:296:29: warning: unused parameter ‘fast_rnd_lookup’ [-Wunused-parameter]
     , const vector<size_t>& fast_rnd_lookup
                             ^
[ 17%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/simplifier.cpp.o
[ 19%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/subsumestrengthen.cpp.o
[ 21%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/clauseallocator.cpp.o
[ 24%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/sccfinder.cpp.o
[ 26%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/solverconf.cpp.o
[ 29%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/distiller.cpp.o
[ 31%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/strengthener.cpp.o
[ 34%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/calcdefpolars.cpp.o
[ 36%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/solutionextender.cpp.o
[ 39%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/completedetachreattacher.cpp.o
[ 41%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/searcher.cpp.o
In file included from /home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/searcher.h:25:0,
                 from /home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/searcher.cpp:22:
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/propengine.h: In instantiation of ‘uint32_t CMSat::PropEngine::calc_glue_using_seen2_upper_bit_no_zero_lev(const T&) [with T = CMSat::Clause; uint32_t = unsigned int]’:
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/searcher.cpp:388:78:   required from here
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/propengine.h:323:32: warning: unused variable ‘l’ [-Wunused-variable]
     typename T::const_iterator l, end;
                                ^
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/propengine.h:323:35: warning: unused variable ‘end’ [-Wunused-variable]
     typename T::const_iterator l, end;
                                   ^
[ 43%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/solver.cpp.o
[ 46%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/gatefinder.cpp.o
[ 48%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/sqlstats.cpp.o
[ 51%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/implcache.cpp.o
[ 53%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/stamp.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/stamp.cpp:74:24: warning: unused parameter ‘outerToInter’ [-Wunused-parameter]
     const vector<Var>& outerToInter
                        ^
[ 56%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/compfinder.cpp.o
[ 58%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/comphandler.cpp.o
[ 60%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/hyperengine.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/hyperengine.cpp:246:17: warning: unused parameter ‘root’ [-Wunused-parameter]
     , const Lit root
                 ^
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/hyperengine.cpp:1118:18: warning: unused parameter ‘red’ [-Wunused-parameter]
     , const bool red
                  ^
[ 63%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/subsumeimplicit.cpp.o
[ 65%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/cryptominisat.cpp.o
[ 68%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/cleaningstats.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/cleaningstats.cpp:32:40: warning: unused parameter ‘nbReduceDB’ [-Wunused-parameter]
 void CleaningStats::print(const size_t nbReduceDB, const double total_cpu_time) const
                                        ^
[ 70%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/datasync.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/datasync.cpp:69:29: warning: unused parameter ‘outerToInter’ [-Wunused-parameter]
     const vector<uint32_t>& outerToInter
                             ^
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/datasync.cpp:70:31: warning: unused parameter ‘interToOuter’ [-Wunused-parameter]
     , const vector<uint32_t>& interToOuter
                               ^
[ 73%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/reducedb.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/reducedb.cpp:421:16: warning: unused parameter ‘sumConfl’ [-Wunused-parameter]
     , uint64_t sumConfl
                ^
[ 75%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/clausedumper.cpp.o
[ 78%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/bva.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/bva.cpp: In lambda function:
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/bva.cpp:146:19: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
             switch(atype) {
                   ^
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/bva.cpp: In member function ‘void CMSat::BVA::remove_duplicates_from_m_cls()’:
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/bva.cpp:196:15: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
         switch(prev.getType()) {
               ^
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/bva.cpp: In member function ‘void CMSat::BVA::fill_m_cls_lits_and_red()’:
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/bva.cpp:393:15: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
         switch(cl.ws.getType()) {
               ^
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/bva.cpp: In member function ‘bool CMSat::BVA::add_longer_clause(CMSat::Lit, const CMSat::OccurClause&)’:
/home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/cryptominisat4/bva.cpp:510:11: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
     switch(cl.ws.getType()) {
           ^
[ 80%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/intree.cpp.o
[ 82%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/sql_tablestructure.cpp.o
[ 85%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/GitSHA1.cpp.o
[ 87%] Building CXX object cmsat4-src/CMakeFiles/temp_lib.dir/xorfinder.cpp.o
[ 87%] Built target temp_lib
Linking CXX shared library ../lib/libcryptominisat4.so
[ 87%] Built target libcryptominisat4
[ 90%] Building CXX object cmsat4-src/CMakeFiles/cryptominisat.dir/dimacsparser.cpp.o
[ 92%] Building CXX object cmsat4-src/CMakeFiles/cryptominisat.dir/main.cpp.o
Linking CXX executable ../cryptominisat
[ 92%] Built target cryptominisat
[ 95%] Building CXX object cmsat4-src/CMakeFiles/cryptominisat_simple.dir/dimacsparser.cpp.o
[ 97%] Building CXX object cmsat4-src/CMakeFiles/cryptominisat_simple.dir/main_simple.cpp.o
Linking CXX executable ../cryptominisat_simple
[ 97%] Built target cryptominisat_simple
Linking CXX static library ../lib/libcryptominisat4.a
[ 97%] Built target libcryptominisat4_static
[100%] Generating build/timestamp
running build_ext
[100%] Built target pytarget
[baston@localhost build]$

[baston@localhost sudoku]$ sudoku < a

Board layout is:
----------------------
|      |6   1 |8 4   |
|2 8   |4     |1 6   |
|1     |8     |  3 5 |
----------------------
|6     |    4 |    7 |
|7     |1     |9 5   |
|      |    5 |4     |
----------------------
|3 6 9 |5   8 |      |
|8   5 |    2 |6     |
|  7   |3   6 |  9   |
----------------------

cryptominisat: error while loading shared libraries: libcryptominisat4.so.4.2.0: cannot open shared object file: No such file or directory
EOF encountered while looking for SAT or UNSAT, aborting.
Neither SAT nor UNSAT found.
Oops, busted:  did not find either SAT nor UNSAT, aborting.

**********************************************************
***                                                    ***
***                 No Solution Found                  ***
***                                                    ***
**********************************************************
[baston@localhost sudoku]$

[root@localhost ~]# cd /home/baston/kryptonite/misc/cryptominisat-master_apr13_2015_673180894a/build
[root@localhost build]# make uninstall
-- Uninstalling "/usr/local/bin/cryptominisat_simple"
-- File "/usr/local/bin/cryptominisat_simple" does not exist.
-- Uninstalling "/usr/local/bin/cryptominisat"
-- File "/usr/local/bin/cryptominisat" does not exist.
-- Uninstalling "/usr/local/lib/libcryptominisat4.a"
-- File "/usr/local/lib/libcryptominisat4.a" does not exist.
-- Uninstalling "/usr/local/include/cryptominisat4/solvertypesmini.h"
-- File "/usr/local/include/cryptominisat4/solvertypesmini.h" does not exist.
-- Uninstalling "/usr/local/include/cryptominisat4/cryptominisat.h"
-- File "/usr/local/include/cryptominisat4/cryptominisat.h" does not exist.
-- Uninstalling "/usr/local/lib/libcryptominisat4.so"
-- File "/usr/local/lib/libcryptominisat4.so" does not exist.
-- Uninstalling "/usr/local/lib/libcryptominisat4.so.4.2.0"
-- File "/usr/local/lib/libcryptominisat4.so.4.2.0" does not exist.
-- Uninstalling "/usr/local/lib/cmake/cryptominisat4/cryptominisat4Targets-relwithdebinfo.cmake"
-- File "/usr/local/lib/cmake/cryptominisat4/cryptominisat4Targets-relwithdebinfo.cmake" does not exist.
-- Uninstalling "/usr/local/lib/cmake/cryptominisat4/cryptominisat4Targets.cmake"
-- File "/usr/local/lib/cmake/cryptominisat4/cryptominisat4Targets.cmake" does not exist.
-- Uninstalling "/usr/local/lib/cmake/cryptominisat4/cryptominisat4Config.cmake"
-- File "/usr/local/lib/cmake/cryptominisat4/cryptominisat4Config.cmake" does not exist.
Built target uninstall
[root@localhost build]#

**Comment by baston007** [comment]
[baston@localhost sudoku]$ sudoku < a

Board layout is:
----------------------
|      |6   1 |8 4   |
|2 8   |4     |1 6   |
|1     |8     |  3 5 |
----------------------
|6     |    4 |    7 |
|7     |1     |9 5   |
|      |    5 |4     |
----------------------
|3 6 9 |5   8 |      |
|8   5 |    2 |6     |
|  7   |3   6 |  9   |
----------------------


Solution is:
----------------------
|5 9 7 |6 3 1 |8 4 2 |
|2 8 3 |4 5 7 |1 6 9 |
|1 4 6 |8 2 9 |7 3 5 |
----------------------
|6 5 1 |2 9 4 |3 8 7 |
|7 2 4 |1 8 3 |9 5 6 |
|9 3 8 |7 6 5 |4 2 1 |
----------------------
|3 6 9 |5 7 8 |2 1 4 |
|8 1 5 |9 4 2 |6 7 3 |
|4 7 2 |3 1 6 |5 9 8 |
----------------------

[baston@localhost sudoku]$

**Comment by baston007** [comment]
The updates version of cryptominisat (8d5cee5e0d) fixes the problem.  Thank you.

**Comment by msoos** [comment]
Great, I'm glad! :)
