### ISSUE TITLE
nit: wrong build badge in README.markdown

### ISSUE THREAD

**Issue by mtrberzi** [msoos/cryptominisat#233]
In README.markdown, the badge for the build status is included as `[![Build Status](https://travis-ci.org/stp/stp.svg?branch=master)](https://travis-ci.org/stp/stp)`. Actually this is the build status for STP. (Bad copy+paste?)

You probably want something like `[![Build Status](https://travis-ci.org/msoos/cryptominisat.svg?branch=master)](https://travis-ci.org/msoos/cryptominisat)`

**Comment by msoos** [comment]
Thanks, fixed!
