### ISSUE TITLE
EXPORT macro breaks MSVC compilation

### ISSUE THREAD

**Issue by a1880** [msoos/cryptominisat#237]
The following macro in solverconf.cpp (and on one other place, which I can't remember right now), is relying on GNU extensions and does not compile under Microsoft VC++:

    #define EXPORT __attribute__ ((visibility("default")))

Suggested replacement:
//  cf. https://gcc.gnu.org/wiki/Visibility

    #if __GNUC__ >= 4
        #define DLL_PUBLIC __attribute__ ((visibility ("default")))
        #define DLL_LOCAL  __attribute__ ((visibility ("hidden")))
    #else
        #define DLL_PUBLIC
        #define DLL_LOCAL
    #endif

**Comment by msoos** [comment]
Thanks! I should build on Windows, too, but TravisCI doesn't do that yet :(
