### ISSUE TITLE
MSVC does not support noexcept

### ISSUE THREAD

**Issue by a1880** [msoos/cryptominisat#240]
In shareddata.h near line 50 I had to get rid of noexcept to compile under VC++ 2013:

As-is:
            Spec(Spec&& other) noexcept :
                data(std::move(other.data))
            {
                other.data = NULL;
            }

Suggested:

#if _MSC_VER
			Spec(Spec&& other) :
			data(std::move(other.data))
			{
				other.data = NULL;
			}
#else
            Spec(Spec&& other) noexcept :
                data(std::move(other.data))
            {
                other.data = NULL;
            }
#endif

**Comment by msoos** [comment]
Well, that thing is needed or we make a copy when we move. So it's super-slow if you don't have it there. I can 'fix' this but it's like band-aid on cancer.

**Comment by a1880** [comment]
So, cryptomonisat could be much faster than I have compiled it now?
I have not understood what the effect is to leave noexcept out.

**Comment by msoos** [comment]
No, not much faster, just this one part. I would need to debug, but currently I am trying to get CMS to the SAT competition, so I have a lot of things to do. I will get this fixed after end-of-month deadline.

**Comment by a1880** [comment]
Fair enough! Keep this issue on hold for the time being.

To mark a function in VC++ as not throwing any exceptions, one can add a "throw()" as explained here: https://msdn.microsoft.com/en-us/library/wfa0edys.aspx

Example:

void f5(void) throw() {
   try {
      f1();
   }
   catch(...) {
      handler();
    }
}

**Comment by msoos** [comment]
That's not the same. The noexcept is a strong guarantee and allows move constructors to behave in a certain way. Sorry about that.

**Comment by a1880** [comment]
noexcept won't be supported by Microsoft before Visual C++ 2015
VC++ 2015 was published as beta in April 2015, but the official version is still VC++ 2013

Details:
http://blogs.msdn.com/b/vcblog/archive/2015/04/29/c-11-14-17-features-in-vs-2015-rc.aspx
