### ISSUE TITLE
MinGW reports error with DLL_PUBLIC

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#241]
Something like 

solverconf.cpp:30:12: error: function 'CMSat::SolverConf::SolverConf()' definition is marked dllimport
 DLL_PUBLIC SolverConf::SolverConf() :
            ^
cryptominisat.cpp:104:12: error: function 'CMSat::SATSolver::SATSolver(void*, bool*)' definition is marked dllimport
 DLL_PUBLIC SATSolver::SATSolver(void* config, bool* interrupt_asap)
            ^
cryptominisat.cpp:110:12: error: function 'CMSat::SATSolver::~SATSolver()' definition is marked dllimport
 DLL_PUBLIC SATSolver::~SATSolver()
            ^
cryptominisat.cpp:181:17: error: function 'void CMSat::SATSolver::set_num_threads(unsigned int)' definition is marked dllimpo
rt
 DLL_PUBLIC void SATSolver::set_num_threads(const unsigned num)

What do you want to do with DLL_PUBLIC? Possibly export the functions?

Perhaps the following code

#if defined _WIN32 || defined __CYGWIN__
    #ifdef __GNUC__
        #define DLL_PUBLIC __attribute__ ((dllimport))
    #else
        #define DLL_PUBLIC __declspec(dllimport)
    #endif
    #define DLL_LOCAL
#else
    #define DLL_PUBLIC __attribute__ ((visibility ("default")))
    #define DLL_LOCAL  __attribute__ ((visibility ("hidden")))
#endif

must be changed (two times "dllimport" to "dllexport") to

#if defined _WIN32 || defined __CYGWIN__
    #ifdef __GNUC__
        #define DLL_PUBLIC __attribute__ ((dllexport))
    #else
        #define DLL_PUBLIC __declspec(dllexport)
    #endif
    #define DLL_LOCAL
#else
    #define DLL_PUBLIC __attribute__ ((visibility ("default")))
    #define DLL_LOCAL  __attribute__ ((visibility ("hidden")))
#endif

At least the error disappears, but I have not tried if it works as DLL.

**Comment by msoos** [comment]
Hey, thanks! Trying to fix it.

BTW: Please use the triple-backtick operator (see "mardkown supported" button) when submitting reports. It's super-hard to read them this way :(

**Comment by msoos** [comment]
Fingers crossed that it fixes it :) Thanks again!
