### ISSUE TITLE
Long loading of very big CNF 

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#242]
I have a CNF which is 2,9 GByte in size. It has around 400000 variable,
a lot clauses (160M), most of them binaries.

When using CMS from 27.05.2014 and earlier, I see that the CNF is imported.
Each second around 10 to 20 MByte/s is read in. 
It takes around 4 minutes to read. (on machine doing also a lot other things)

When using CMS from today (or even from 07.06.2014), it takes endless.
I see a reading rate of 1,5 MByte/s every 15 seconds.
It takes 17 minutes till calculation starts. (on machine doing also a lot other things)

After analyzing a bit, it comes from 

solver->add_clause(lits);

Going deeper and deeper again, the problematic calls seem to be the three line here:

https://github.com/msoos/cryptominisat/blob/master/cryptominisat4/cnf.cpp#L108

interToOuterMain.reserve(interToOuterMain.size() + n);
outerToInterMain.reserve(outerToInterMain.size() + n);
outer_to_with_bva_map.reserve(outer_to_with_bva_map.size() + n);

Each one takes 500us on each new variable.

Perhaps the following for-next-loop is also problematic when number of vars goes higher and higher:

https://github.com/msoos/cryptominisat/blob/master/cryptominisat4/cnf.cpp#L111

More analysis outstanding.

**Comment by capiman** [comment]
More information:
The CNF uses 130180 variable en block, directly at the first clauses.
Then from clauses to clauses new variables are used. 
Therefore 130180 variables are reserved in 1 go.
Afterwards 400000 - 130180 = 270000 variables are allocated one-by-one,
which calls the above 3 reserve functions 270000.
Just to have a base of calculation: Each reserve take ~ 500us, so 3 together 1,5ms.
1.5ms * 270 = 1,5s * 270 = 400s, which is around 6 min 40seconds.
So these reserve consume almost 7 minutes.

I have done a test:
I call the 3 function and reserve 400000 when xxx+n is smaller than 400000.

```
    uint32_t tmp;  // Correct?

    tmp = interToOuterMain.size() + n;
    if(tmp < 400000) tmp = 400000;
    interToOuterMain.reserve(tmp);

    tmp = outerToInterMain.size() + n;
    if(tmp < 400000) tmp = 400000;
    outerToInterMain.reserve(tmp);

    tmp = outer_to_with_bva_map.size() + n;
    if(tmp < 400000) tmp = 400000;
    outer_to_with_bva_map.reserve(tmp);
```

Now it reads it again in around 4 minutes. So it looks like the long time is coming from
the "reserve" calls.

Note:
The loop seems to be not a problem, because it is not called as often as variables are existing,
but as often as variables are added. Because in my case, only 1 variable is added each turn,
the loop is only executed once each turn.

**Comment by capiman** [comment]
Perhaps there is also space for optimization in case BVA is turned off (--bva=0).
Perhaps some of the calls/structure are then not more needed and don't need to be maintained.

**Comment by msoos** [comment]
Thanks, this _really_ helped! Can you please check if the fix I added is OK? Thanks!

**Comment by capiman** [comment]
See note here:
https://github.com/msoos/cryptominisat/commit/fcb913b0f9e1a431428b64d62c5645f4a72e6fc9

**Comment by capiman** [comment]
Bugfix seems to work, above CNF can now be read in fast and calculation starts.
Many thanks for the quick bugfix! 
Issue entry can be closed.

**Comment by msoos** [comment]
Cool, thanks for checking!
