### ISSUE TITLE
Python bindings failed to build on OS X

### ISSUE THREAD

**Issue by rgov** [msoos/cryptominisat#245]
```
c++ -shared -g -W -Wall -Wno-deprecated build/temp.macosx-10.11-x86_64-2.7/tmp/cryptominisat/python/pycryptosat.o -L. -L/usr/local/lib -L/tmp/cryptominisat/build/lib -L../lib -lcryptominisat4 -o /private/tmp/cryptominisat/build/py-lib/pycryptosat.so
```

This failed for me. I worked around it by just not building the python bindings.

**Comment by msoos** [comment]
Thanks! :( Can you tell me what was the failure message? Maybe just some header missing, I'd like to fix it :)

**Comment by rgov** [comment]
It's a linking issue. All of the Python/C API symbols, e.g., `_PyArg_ParseTupleAndKeywords` are missing.

**Comment by aodinaev** [comment]
partially fixed in https://github.com/msoos/cryptominisat/pull/268

but issue is way deeper than I imagined. I'm not fluent with configuring ```setup.py``` to reconcile the difference between symbols generated by python build script and same command issued from command line.

**Comment by 4tXJ7f** [comment]
With a4c1ad28520697b2dd5a046701d600de266ea8c5, the code compiles on OS X (tested on 10.11 but should work on older versions, too).

**Comment by msoos** [comment]
Thanks to everyone involved, fixed now! :)
