### ISSUE TITLE
lchmod function not implemented

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#247]
After downloading the zip file and running unzip to expand the directory, the last line displayed is as follows:
lchmod (file attributes) error: Function not implemented

   Is this lchmod command an aliased command or is something actually missing?   This has been happening for some time.  I have been ignoring the message as a working cryptominisat binary is still produced.

Rob

**Comment by msoos** [comment]
Sorry, it's something to do with symlinks and Windows. It should not be an issue, things should work fine, as I hope they do! Please close this issue if you don't observe any files missing and you can still compile :)

Cheers,

Mate
