### ISSUE TITLE
undefined reference compile error

### ISSUE THREAD

**Issue by Owlz** [msoos/cryptominisat#248]
Hello,

I was able to build and install cryptominisat just fine through the git repo. However, when I go to use it I get the following error:

g++ -o conftest -g -O2  test.cpp -lstp -lminisat -L/home/jess/opt/stp/include
/usr/local/lib/libstp.a(CryptoMinisat4.cpp.o): In function `stp::CryptoMinisat4::~CryptoMinisat4()':
/home/jess/opt/stp/lib/Sat/CryptoMinisat4.cpp:45: undefined reference to `CMSat::SATSolver::~SATSolver()'

The error actually repeats with many different calls, but it's the same error for all the CMSat stuff. The includes seems to be correct in those files and they are within the normal search path, so I'm not sure why their either not being found, or being ignored.

The test file I'm using is:
#include "stp/c_interface.h"
#include <assert.h>

int main(int argc, char **argv) {
  VC vc = vc_createValidityChecker();

  // 32-bit variable 'c'
  Expr c = vc_varExpr(vc, "c", vc_bvType(vc, 32));

  // 32 bit constant value 5
  Expr a = vc_bvConstExprFromInt(vc, 32, 5);

  // 32 bit constant value 6
  Expr b = vc_bvConstExprFromInt(vc, 32, 6);

  // a+b!=c
  Expr xp1 = vc_bvPlusExpr(vc, 32, a, b);
  Expr eq = vc_eqExpr(vc, xp1, c);
  Expr eq2 = vc_notExpr(vc, eq);

  //Is a+b!=c always correct?
  int ret = vc_query(vc, eq2);

  //No, c=a+b is a counterexample
  assert(ret == false);

  //print c = 11 counterexample
  vc_printCounterExample(vc);

  //Delete validity checker
  vc_Destroy(vc);

  return 0;
}

**Comment by msoos** [comment]
Hey,

You need to include cryptominisat when you link :) It's not enough to have "-lminisat" you also need "-lcryptominisat".

I hope this helps. Please get back to me either way (and close the issue if it's good).

Thanks,

Mate

**Comment by Owlz** [comment]
Doh! You're right. Only problem now is that it doesn't look like my build created a .so file to link against. Did a system find on it and can't find anything like "cryptominisat*so*".

**Comment by Owlz** [comment]
Got it. Turns out it had "lib" in front of the name. Solved my problem by doing this:

sudo ln -s /usr/local/lib/libcryptominisat4.so.4.5 /usr/local/lib/cryptominisat4.so

Thanks for the help!
