### ISSUE TITLE
Makefile failed for version b6d63cdc48

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#249]
Latest build failed to complete totally, but a working cryptominisat4 file was generated.  The following are the massages produced when make -j16 was run.

Rob

[baston@desk build]$ make -j16
Scanning dependencies of target tablestruct
Scanning dependencies of target CopyPublicHeaders
[  1%] Generating sql_tablestructure.cpp
Copying cryptominisat.h to /home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/build/include/cryptominisat4
[  1%] Built target tablestruct
Copying solvertypesmini.h to /home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/build/include/cryptominisat4
Scanning dependencies of target temp_lib_norm
Scanning dependencies of target temp_lib_ipasir
[  1%] Built target CopyPublicHeaders
[  4%] [  4%] [  5%] [  5%] [  6%] [  8%] [  9%] [ 10%] [ 11%] [ 12%] [ 13%] [ 14%] [ 16%] [ 17%] [ 18%] [ 19%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/cnf.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/varreplacer.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/propengine.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/subsumestrengthen.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/cnf.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/clauseusagestats.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/propengine.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/varreplacer.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/prober.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/clausecleaner.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/occsimplifier.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/clauseallocator.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/clauseusagestats.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/prober.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/clausecleaner.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/sccfinder.cpp.o
[ 20%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/solverconf.cpp.o
[ 21%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/distiller.cpp.o
In file included from /home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/solverconf.cpp:24:0:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/solverconf.h: In constructor ‘CMSat::SolverConf::SolverConf()’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/solverconf.h:291:16: warning: ‘CMSat::SolverConf::occsimp_schedule_nonstartup’ will be initialized after [-Wreorder]
         string   occsimp_schedule_nonstartup;
                ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/solverconf.h:290:16: warning:   ‘std::string CMSat::SolverConf::occsimp_schedule_startup’ [-Wreorder]
         string   occsimp_schedule_startup;
                ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/solverconf.cpp:30:42: warning:   when initialized here [-Wreorder]
[ 22%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/strengthener.cpp.o
[ 24%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/occsimplifier.cpp.o
[ 25%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/calcdefpolars.cpp.o
[ 26%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/solutionextender.cpp.o
[ 27%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/completedetachreattacher.cpp.o
[ 28%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/searcher.cpp.o
[ 29%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/subsumestrengthen.cpp.o
[ 31%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/solver.cpp.o
[ 32%] [ 33%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/gatefinder.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/clauseallocator.cpp.o
[ 34%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/sccfinder.cpp.o
[ 35%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/solverconf.cpp.o
In file included from /home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/solverconf.cpp:24:0:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/solverconf.h: In constructor ‘CMSat::SolverConf::SolverConf()’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/solverconf.h:291:16: warning: ‘CMSat::SolverConf::occsimp_schedule_nonstartup’ will be initialized after [-Wreorder]
         string   occsimp_schedule_nonstartup;
                ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/solverconf.h:290:16: warning:   ‘std::string CMSat::SolverConf::occsimp_schedule_startup’ [-Wreorder]
         string   occsimp_schedule_startup;
                ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/solverconf.cpp:30:42: warning:   when initialized here [-Wreorder]
[ 36%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/distiller.cpp.o
[ 37%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/sqlstats.cpp.o
[ 39%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/strengthener.cpp.o
[ 40%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/calcdefpolars.cpp.o
[ 41%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/solutionextender.cpp.o
[ 42%] [ 43%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/implcache.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/stamp.cpp.o
[ 44%] [ 45%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/compfinder.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/comphandler.cpp.o
[ 47%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/hyperengine.cpp.o
[ 48%] [ 49%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/subsumeimplicit.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/cleaningstats.cpp.o
[ 50%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/completedetachreattacher.cpp.o
[ 51%] [ 52%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/searcher.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/solver.cpp.o
[ 54%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/gatefinder.cpp.o
[ 55%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/datasync.cpp.o
[ 56%] [ 57%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/sqlstats.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/reducedb.cpp.o
[ 58%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/implcache.cpp.o
[ 59%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/stamp.cpp.o
[ 60%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/compfinder.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/hyperengine.cpp:246:17: warning: unused parameter ‘root’ [-Wunused-parameter]
     , const Lit root
                 ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/hyperengine.cpp: In member function ‘CMSat::Lit CMSat::HyperEngine::analyzeFail(CMSat::PropBy)’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/hyperengine.cpp:820:11: warning: enumeration value ‘xor_t’ not handled in switch [-Wswitch]
     switch(propBy.getType()) {
           ^
[ 62%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/clausedumper.cpp.o
[ 63%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/bva.cpp.o
[ 64%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/comphandler.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/occsimplifier.cpp: In member function ‘bool CMSat::OccSimplifier::simplify(bool)’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/occsimplifier.cpp:949:1: warning: label ‘end’ defined but not used [-Wunused-label]
 end:
 ^
[ 66%] [ 66%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/intree.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/sql_tablestructure.cpp.o
[ 67%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/features_calc.cpp.o
[ 68%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/features_to_reconf.cpp.o
[ 70%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/features.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_to_reconf.cpp:12:46: warning: unused parameter ‘feat’ [-Wunused-parameter]
 int get_reconf_from_features(const Features& feat, const int verb)
                                              ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_to_reconf.cpp:12:62: warning: unused parameter ‘verb’ [-Wunused-parameter]
 int get_reconf_from_features(const Features& feat, const int verb)
                                                              ^
[ 71%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/GitSHA1.cpp.o
[ 72%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/xorfinder.cpp.o
[ 73%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_norm.dir/cryptominisat.cpp.o
[ 74%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/hyperengine.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/hyperengine.cpp:246:17: warning: unused parameter ‘root’ [-Wunused-parameter]
     , const Lit root
                 ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/hyperengine.cpp: In member function ‘CMSat::Lit CMSat::HyperEngine::analyzeFail(CMSat::PropBy)’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/hyperengine.cpp:820:11: warning: enumeration value ‘xor_t’ not handled in switch [-Wswitch]
     switch(propBy.getType()) {
           ^
[ 75%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/subsumeimplicit.cpp.o
[ 77%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/cleaningstats.cpp.o
[ 78%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/datasync.cpp.o
[ 79%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/reducedb.cpp.o
[ 80%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/clausedumper.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/occsimplifier.cpp: In member function ‘bool CMSat::OccSimplifier::simplify(bool)’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/occsimplifier.cpp:949:1: warning: label ‘end’ defined but not used [-Wunused-label]
 end:
 ^
[ 81%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/bva.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/searcher.cpp: In member function ‘void CMSat::Searcher::debug_print_resolving_clause(CMSat::PropBy) const’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/searcher.cpp:354:11: warning: enumeration value ‘xor_t’ not handled in switch [-Wswitch]
     switch(confl.getType()) {
           ^
[ 82%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/intree.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp: In instantiation of ‘void CMSat::FeaturesCalc::for_one_clause(const CMSat::Watched&, CMSat::Lit, Function, Function2) const [with Function = CMSat::FeaturesCalc::fill_vars_cls()::<lambda(unsigned int, unsigned int, unsigned int)>; Function2 = CMSat::FeaturesCalc::fill_vars_cls()::<lambda(CMSat::Lit, unsigned int, unsigned int, unsigned int)>]’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:97:13:   required from ‘void CMSat::FeaturesCalc::for_all_clauses(Function, Function2) const [with Function = CMSat::FeaturesCalc::fill_vars_cls()::<lambda(unsigned int, unsigned int, unsigned int)>; Function2 = CMSat::FeaturesCalc::fill_vars_cls()::<lambda(CMSat::Lit, unsigned int, unsigned int, unsigned int)>]’
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:125:48:   required from here
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:21:5: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
     switch (cl.getType()) {
     ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp: In instantiation of ‘void CMSat::FeaturesCalc::for_one_clause(const CMSat::Watched&, CMSat::Lit, Function, Function2) const [with Function = CMSat::FeaturesCalc::calculate_clause_stats()::<lambda(unsigned int, unsigned int, unsigned int)>; Function2 = CMSat::FeaturesCalc::calculate_clause_stats()::<lambda(CMSat::Lit, unsigned int, unsigned int, unsigned int)>]’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:97:13:   required from ‘void CMSat::FeaturesCalc::for_all_clauses(Function, Function2) const [with Function = CMSat::FeaturesCalc::calculate_clause_stats()::<lambda(unsigned int, unsigned int, unsigned int)>; Function2 = CMSat::FeaturesCalc::calculate_clause_stats()::<lambda(CMSat::Lit, unsigned int, unsigned int, unsigned int)>]’
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:146:45:   required from here
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:21:5: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp: In instantiation of ‘void CMSat::FeaturesCalc::for_one_clause(const CMSat::Watched&, CMSat::Lit, Function, Function2) const [with Function = CMSat::FeaturesCalc::calculate_extra_clause_stats()::<lambda(unsigned int, unsigned int, unsigned int)>; Function2 = CMSat::FeaturesCalc::calculate_extra_clause_stats()::<lambda(CMSat::Lit, unsigned int, unsigned int, unsigned int)>]’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:97:13:   required from ‘void CMSat::FeaturesCalc::for_all_clauses(Function, Function2) const [with Function = CMSat::FeaturesCalc::calculate_extra_clause_stats()::<lambda(unsigned int, unsigned int, unsigned int)>; Function2 = CMSat::FeaturesCalc::calculate_extra_clause_stats()::<lambda(CMSat::Lit, unsigned int, unsigned int, unsigned int)>]’
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:211:44:   required from here
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:21:5: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
[ 83%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/sql_tablestructure.cpp.o
[ 85%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/features_calc.cpp.o
[ 86%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/features_to_reconf.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp: In instantiation of ‘void CMSat::FeaturesCalc::for_one_clause(const CMSat::Watched&, CMSat::Lit, Function, Function2) const [with Function = CMSat::FeaturesCalc::fill_vars_cls()::<lambda(unsigned int, unsigned int, unsigned int)>; Function2 = CMSat::FeaturesCalc::fill_vars_cls()::<lambda(CMSat::Lit, unsigned int, unsigned int, unsigned int)>]’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:97:13:   required from ‘void CMSat::FeaturesCalc::for_all_clauses(Function, Function2) const [with Function = CMSat::FeaturesCalc::fill_vars_cls()::<lambda(unsigned int, unsigned int, unsigned int)>; Function2 = CMSat::FeaturesCalc::fill_vars_cls()::<lambda(CMSat::Lit, unsigned int, unsigned int, unsigned int)>]’
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:125:48:   required from here
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:21:5: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
     switch (cl.getType()) {
     ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp: In instantiation of ‘void CMSat::FeaturesCalc::for_one_clause(const CMSat::Watched&, CMSat::Lit, Function, Function2) const [with Function = CMSat::FeaturesCalc::calculate_clause_stats()::<lambda(unsigned int, unsigned int, unsigned int)>; Function2 = CMSat::FeaturesCalc::calculate_clause_stats()::<lambda(CMSat::Lit, unsigned int, unsigned int, unsigned int)>]’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:97:13:   required from ‘void CMSat::FeaturesCalc::for_all_clauses(Function, Function2) const [with Function = CMSat::FeaturesCalc::calculate_clause_stats()::<lambda(unsigned int, unsigned int, unsigned int)>; Function2 = CMSat::FeaturesCalc::calculate_clause_stats()::<lambda(CMSat::Lit, unsigned int, unsigned int, unsigned int)>]’
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:146:45:   required from here
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:21:5: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp: In instantiation of ‘void CMSat::FeaturesCalc::for_one_clause(const CMSat::Watched&, CMSat::Lit, Function, Function2) const [with Function = CMSat::FeaturesCalc::calculate_extra_clause_stats()::<lambda(unsigned int, unsigned int, unsigned int)>; Function2 = CMSat::FeaturesCalc::calculate_extra_clause_stats()::<lambda(CMSat::Lit, unsigned int, unsigned int, unsigned int)>]’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:97:13:   required from ‘void CMSat::FeaturesCalc::for_all_clauses(Function, Function2) const [with Function = CMSat::FeaturesCalc::calculate_extra_clause_stats()::<lambda(unsigned int, unsigned int, unsigned int)>; Function2 = CMSat::FeaturesCalc::calculate_extra_clause_stats()::<lambda(CMSat::Lit, unsigned int, unsigned int, unsigned int)>]’
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:211:44:   required from here
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_calc.cpp:21:5: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
[ 87%] /home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_to_reconf.cpp:12:46: warning: unused parameter ‘feat’ [-Wunused-parameter]
 int get_reconf_from_features(const Features& feat, const int verb)
                                              ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/features_to_reconf.cpp:12:62: warning: unused parameter ‘verb’ [-Wunused-parameter]
 int get_reconf_from_features(const Features& feat, const int verb)
                                                              ^
Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/features.cpp.o
[ 88%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/GitSHA1.cpp.o
[ 89%] [ 90%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/cryptominisat.cpp.o
Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/xorfinder.cpp.o
[ 91%] Building CXX object cmsat4-src/CMakeFiles/temp_lib_ipasir.dir/ipasir.cpp.o
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/ipasir.cpp:199:76: warning: unused parameter ‘solver’ [-Wunused-parameter]
 DLL_PUBLIC void ipasir_set_terminate (void * solver, void * state, int (*terminate)(void * state))
                                                                            ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/ipasir.cpp:199:91: warning: unused parameter ‘state’ [-Wunused-parameter]
 DLL_PUBLIC void ipasir_set_terminate (void * solver, void * state, int (*terminate)(void * state))
                                                                                           ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/ipasir.cpp:199:127: warning: unused parameter ‘terminate’ [-Wunused-parameter]
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp: In lambda function:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp:147:19: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
             switch(atype) {
                   ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp: In member function ‘void CMSat::BVA::remove_duplicates_from_m_cls()’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp:197:15: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
         switch(prev.getType()) {
               ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp: In member function ‘void CMSat::BVA::fill_m_cls_lits_and_red()’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp:396:15: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
         switch(cl.ws.getType()) {
               ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp: In member function ‘bool CMSat::BVA::add_longer_clause(CMSat::Lit, const CMSat::OccurClause&)’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp:513:11: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
     switch(cl.ws.getType()) {
           ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/searcher.cpp: In member function ‘void CMSat::Searcher::debug_print_resolving_clause(CMSat::PropBy) const’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/searcher.cpp:354:11: warning: enumeration value ‘xor_t’ not handled in switch [-Wswitch]
     switch(confl.getType()) {
           ^
[ 93%] Built target temp_lib_norm
Scanning dependencies of target libcryptominisat4
Scanning dependencies of target libcryptominisat4_static
Linking CXX shared library ../lib/libcryptominisat4.so
Linking CXX static library ../lib/libcryptominisat4.a
[ 93%] Built target libcryptominisat4_static
[ 93%] Built target libcryptominisat4
Scanning dependencies of target pytarget
[ 94%] Generating build/timestamp
Scanning dependencies of target cryptominisat4_simple
Scanning dependencies of target cryptominisat4
[ 96%] [ 96%] [ 97%] [ 98%] Building CXX object cmsat4-src/CMakeFiles/cryptominisat4_simple.dir/main_simple.cpp.o
Building CXX object cmsat4-src/CMakeFiles/cryptominisat4.dir/main.cpp.o
Building CXX object cmsat4-src/CMakeFiles/cryptominisat4.dir/dimacsparser.cpp.o
Building CXX object cmsat4-src/CMakeFiles/cryptominisat4_simple.dir/dimacsparser.cpp.o
running build_ext
building 'pycryptosat' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/home
creating build/temp.linux-x86_64-2.7/home/baston
creating build/temp.linux-x86_64-2.7/home/baston/kryptonite
creating build/temp.linux-x86_64-2.7/home/baston/kryptonite/misc
creating build/temp.linux-x86_64-2.7/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48
creating build/temp.linux-x86_64-2.7/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/python
gcc -pthread -g -W -Wall -Wno-deprecated -fPIC -I/usr/include/python2.7 -c /home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/python/pycryptosat.cpp -o build/temp.linux-x86_64-2.7/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/python/pycryptosat.o -I/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/python/pycryptosat.cpp:33:42: fatal error: cryptominisat4/cryptominisat.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
py-lib/CMakeFiles/pytarget.dir/build.make:51: recipe for target 'py-lib/build/timestamp' failed
make[2]: *** [py-lib/build/timestamp] Error 1
CMakeFiles/Makefile2:489: recipe for target 'py-lib/CMakeFiles/pytarget.dir/all' failed
make[1]: *** [py-lib/CMakeFiles/pytarget.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp: In lambda function:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp:147:19: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
             switch(atype) {
                   ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp: In member function ‘void CMSat::BVA::remove_duplicates_from_m_cls()’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp:197:15: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
         switch(prev.getType()) {
               ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp: In member function ‘void CMSat::BVA::fill_m_cls_lits_and_red()’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp:396:15: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
         switch(cl.ws.getType()) {
               ^
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp: In member function ‘bool CMSat::BVA::add_longer_clause(CMSat::Lit, const CMSat::OccurClause&)’:
/home/baston/kryptonite/misc/cryptominisat-master_aug26_2015_b6d63cdc48/cryptominisat4/bva.cpp:513:11: warning: enumeration value ‘watch_idx_t’ not handled in switch [-Wswitch]
     switch(cl.ws.getType()) {
           ^
Linking CXX executable ../cryptominisat4_simple
[ 98%] Built target cryptominisat4_simple
[100%] Built target temp_lib_ipasir
Linking CXX executable ../cryptominisat4
[100%] Built target cryptominisat4
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
[baston@desk build]$

**Comment by msoos** [comment]
Hey Rob,

Thanks! I'm working on a release and broke a lot of stuff. I hope it's fixed now! :)

Cheers,

Mate

**Comment by baston007** [comment]
Hi Mate,
   Things are now working in version fb6f45fcc4.  Thanks.  Keep up the great work.

Rob
