### ISSUE TITLE
include <cryptominisat4/cryptominisat.h> in readme.markdown

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#251]
```
include <cryptominisat4/cryptominisat.h>
```
must be
```
include <src/cryptominisat.h>
```
?

**Comment by msoos** [comment]
As far as I know, no. If you use the cmake system (please install it) then it auto-generates, copies and does all the necessary things to make that work at build-time. Later, at install time, that is the correct place of course.

**Comment by msoos** [comment]
Please close this case unless you used cmake to build the system and you got error messages!

**Comment by capiman** [comment]
Not used cmake. Entry can be closed, sorry.
