### ISSUE TITLE
Is output e.g. "toDecrease: -59264" correct?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#252]
c --> Executing OCC strategy token: backw-sub-str
c [sub] tri upI: 178 subs w tri: 0 str w bin: 2 subs w bin: 0 str w tri: 0 tried: 35237 str: 0 toDecrease: -69468 0-depth ass
: 0 time: 0.75
c [sub] tri upI: 178 subs w tri: 0 str w bin: 0 subs w bin: 0 str w tri: 0 tried: 49499 str: 0 toDecrease: -59264 0-depth ass
: 0 time: 0.90

Is output e.g. "toDecrease: -59264" correct? Negative number.

**Comment by msoos** [comment]
:) Thanks, that is work in progress, I'll clean it up!

Try using point releases -- I will try to make point releases every time something new is inside the solver. I know I haven't been very good at that, but I am trying to add more tests to make sure it's much easier to make a release :) Fingers crossed!

Thanks again,

Mate
