### ISSUE TITLE
ENABLE_TESTING=1 build is broken

### ISSUE THREAD

**Issue by aodinaev** [msoos/cryptominisat#259]
Tried to build project with unit tests. Ran ```cmake ../ -DENABLE_TESTING=1```

```
CMake Error at tests/CMakeLists.txt:17 (message):
  Could not find lit tool.  Try setting LIT_TOOL to the full path for lit
```

cmake didn't proceed.

**Comment by msoos** [comment]
Not broken. Please install git submodules. As I mentioned before, please read .travis.yml  :)

**Comment by msoos** [comment]
It's not broken :) Please take a look at .travis.yml and travis-cmake.sh to see how to make it work. You need the git submodules. The -DENABLE_TESTING=1 is used all the time with the TravisCI continuous integration setup, so it's always working except when Travis says otherwise :)

**Comment by msoos** [comment]
Actually, you need the lit-tool to be installed. I was wrong, sorry.

**Comment by msoos** [comment]
Okay, the errors are now more informative!  Thanks! :)
