### ISSUE TITLE
Multithreaded, multisolutions, abort by key, then finding a solution

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#266]
Using CMS4 with multithread and multisolutions settings.

It must be checked: I think I have seen cases, where I aborted by key (Ctrl-C),
then it takes a while till calculation are finished,
then a solution is found. Now the abort by key is ignored.

This is just a marker for further testing about the steps to reproduce for further testing.

**Comment by msoos** [comment]
I won't be able to fix this and almost nobody needs this. I'm sorry there are about 100 problems with the system that are really serious, like being damn slow, that I need to tend to first. This is an issue that will hit very few people. Most systems can't even handle the Ctrl+C in any meaningful way when in parallel mode. And most can't even find multiple solutions.
