### ISSUE TITLE
Small enhancements to make multithreaded debugging easier

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#267]
There is the following code in cryptominisat.cpp:

```
void operator()()
    {
        if (print_thread_start_and_finish) {
            data_for_thread.update_mutex->lock();
            cout << "Starting thread" << tid << endl;
            data_for_thread.update_mutex->unlock();
        }

        OneThreadAddCls cls_adder(data_for_thread, tid);
        cls_adder();
        lbool ret = data_for_thread.solvers[tid]->solve_with_assumptions(data_for_thread.assumptions);

        if (print_thread_start_and_finish) {
            data_for_thread.update_mutex->lock();
            cout << "Finished tread " << tid << " with result: " << ret << endl;
            data_for_thread.update_mutex->unlock();
        }
...
```

There is variable print_thread_start_and_finish, which is a helpful thing, when doing debugging
of multithreaded multisolution calculations.

I suggest the following enhancements:

1) Typo in debug output
"tread" to "thread"

2) One time with a space, one time without space. This prevent search for "thread0" or "thread 0".
Please make it unique.
Suggested solution (added space to starting debug output):
cout << "Starting thread " << tid << endl;
cout << "Finished thread " << tid << " with result: " << ret << endl;

3) Please add a timestamp when a start is started and when it finished:
(setting time to 2 or 3 decimal digits would be good, otherwise it depends on last (stat) output)
cout << cpuTime() << " Starting thread " << tid << endl;
cout << cpuTime() << " Finished thread " << tid << " with result: " << ret << endl;

Now you are able to search e.g. for "thread " and see

135.55 Starting thread 0
135.65 Starting thread 1
135.72 Starting thread 2
135.74 Finished thread 2 with result: l_True
135.74 Finished thread 1 with result: l_Undef

e.g. in this test (was only a local test, afterwards solution printing), that
thread 0 has not finished (or it was not waited for it, for whatever reason), 
before solution was printed.

**Comment by msoos** [comment]
Here we go :) I decided to comment out the "starting thread" as it had no meaningful data inside. But now the time it takes for a thread to finish is printed and the printing is automatic in case the verbosity is >= 2 (almost always). It's much more user-friendly now and I think it gives you the data you wanted.

Please close this issue if you feel this is good :)

**Comment by msoos** [comment]
Oh, and thanks a ton for this and the previous issue. Really helped!

**Comment by capiman** [comment]
Retested, is working and looking good! Many thanks!
Entry can be closed.
