### ISSUE TITLE
Multithreaded: backward_sub_str() takes a long time, even when must_interrupt_asap()

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#270]
Hi Mate,
I found out that backward_sub_str() could take a few minutes till execution finishes 
even when must_interrupt_asap() already signals end of execution.
Does this already help or must I go further in detail?

I see that OccSimplifier::backward_sub_str()
itself calls some other function like
- backward_sub_str_with_bins_tris()
- backward_subsumption_long_with_long()
- backward_strengthen_long_with_long()
- handle_sub_str_with()
- free_clauses_to_free()
- clean_occur_from_removed_clauses_only_smudged()
which I don't know yet if they take a long time and 
if it is worth adding a check for must_interrupt_asap()
or if this is possible at all to do an early abort?
Best regards,
Martin

**Comment by capiman** [comment]
Latest analysis: Let's start with "SubsumeStrengthen::handle_sub_str_with()".

**Comment by msoos** [comment]
First of all, thanks for the bugreport! Please check if the latest set of changes fixes the issue for you. I fixed handle_sub_str_with which was quite experimental and hence lacked a timeout :( Thanks for notifying me of it!

**Comment by capiman** [comment]
According to my test overnight (before your bugfixes), I would say, that changes in 440b914 
are not enough. It is already inside SubsumeStrengthen::handle_sub_str_with() and does not return. 
I think there must be a check inside this function.

It seems to run in the loop from https://github.com/msoos/cryptominisat/blob/master/src/subsumestrengthen.cpp#L452 to https://github.com/msoos/cryptominisat/blob/master/src/subsumestrengthen.cpp#L467.

Looking at the latest sources, I think this is still the case. 
Is it possible to add a check for abort inside this loop?
Many thanks for the help!

**Comment by msoos** [comment]
Those are not the only changes are made, I have made changes to `handle_sub_str_with()`. Please check again. If you look at the lines you linked at above, you'll see I put in a check. Thanks for looking at it!

Mate

**Comment by capiman** [comment]
I took the latest version today morning (with all your changes) and retested,
but it looks like it is not working.
Can you describe me, how it works to abort the above mentioned loop?
Ok, there is "limit_to_decrease", but this only limits runtime, 
does not handle must_interrupt_asap to about almost immediately.
Have I overseen something?

**Comment by msoos** [comment]
Thanks, you were right! It now aborts. Please check  and if it works, close the issue! Thanks! :)

**Comment by msoos** [comment]
I think it should be good now. I aborts for me, so I'm closing. Please re-open in case it doesn't for you :)
