### ISSUE TITLE
Slow speed due to ClauseCleaner::clean_clauses(...)?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#283]
I have a set of CNFs which when called takes a lot of time (a few hours...) almost after starting.
(I know it takes endless time to solve, but one of the first steps even take so long)

They can be downloaded from here (~47 MByte, decompressed ~ 500 MByte):

http://www.engelschall.com/~martin/slowspeed.zip

I called CMS4 this way:

cryptominisat4 --bva=0 --input=set_15.cnf --input=10x10_arc_all_not_ready.cnf --input=10x10_irred_12.cnf --dumpres=10x10_arc_set_15_testtime2.res --maxdump=3 --dumpred=10x10_arc_set_15_red_1_testtime2.cnf --dumpirred=10x10_arc_set_15_irred_1_testtime2.cnf

It seems to be due to ClauseCleaner::clean_clauses(...) where 
c --> Executing strategy token: scc-vrepl is outputted.
It is working on the command clean_clauses(solver->longIrredCls);

Background: 
There are three CNFs inside:
10x10_arc_all_not_ready.cnf
10x10_irred_12.cnf
set_15.cnf

The set_15.cnf has only one clause which set variable nr 15 to 1:
15 0 

The file 10x10_irred_12.cnf contains a clause which sets variable nr 1 to 1 and a lot other things.

The file 10x10_arc_all_not_ready.cnf contains a lot (99%?) clauses, 
which need variable 1 and 15 set, which is not the case due to the other CNFs:

-1 -14 -30 -84 -122 -129 -171 -194 -228 -236 -243 0
-1 -14 -31 -81 -93 -139 -158 -212 -231 -236 -243 0
-1 -14 -31 -81 -93 -139 -158 -212 -231 -236 -244 0
-1 -14 -31 -81 -96 -139 -158 -212 -231 -236 -239 0
...

Therefore almost all clauses from 10x10_arc_all_not_ready.cnf can be removed/discarded.
And this seems to take so much time.

I benchmarked the loop (in ClauseCleaner::clean_clauses()):
```
    int mystatctr = 0;

    for (s = ss = cs.begin(), end = cs.end();  s != end; ++s, ++at) {
        if (at + 1 < cs.size()) {
            Clause* pre_cl = solver->cl_alloc.ptr(cs[at+1]);
            __builtin_prefetch(pre_cl);
        }

        Clause& cl = *solver->cl_alloc.ptr(*s);
        if (clean_clause(cl)) {
            solver->cl_alloc.clauseFree(*s);
        } else {
            *ss++ = *s;
        }

        mystatctr++;

        if(mystatctr >= 1000)
        {
          mystatctr = 0;
          std::cout << cpuTime() << "ClauseCleaner::clean_clauses Pos 1A " << cs.size() << " " << s-ss << std::endl;
        }
    }
```

and each 1000 loops take minimum around 5 seconds. When computer is busy it even
takes 16 seconds. Due to my case, where almost 6 million clauses are removed,
it takes hours.

Can you try if this takes the same long time on your system? I am using different 
Windows system, compiled with MinGW 64 bit, gcc 4.8.1, -O2.

Perhaps due to long time calculation and reboot such long ago,
the memory is so fragmented. But it is not failing to get memory, just taking so long...

Second thing on this: It can't be interrupted by Ctrl-C, because there is 
no check must_interrupt_asap() inside.

**Comment by capiman** [comment]
This is the output:

c Reading file 'set_15.cnf'
c -- clauses added: 1
c -- xor clauses added: 0
c -- vars added 15
c Reading file '10x10_arc_all_not_ready.cnf'
c -- clauses added: 5937431
c -- xor clauses added: 0
c -- vars added 2177
c Reading file '10x10_irred_12.cnf'
c -- clauses added: 11884505
c -- xor clauses added: 0
c -- vars added 14864
c Parsing time: 28.50 s
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 tri: 0 (stamp: 0, cache: 0) T: 1.03 T-out: Y w-visit: 4970
c --> Executing strategy token: scc-vrepl

then nothing more for hours...

**Comment by msoos** [comment]
Niiiice! I like this one! Thanks, I have managed to fix a massive issue in there. It wasn't doing anything _wrong_ it was just doing it in a very stupid way, one-by-one. I fixed it the same way I fixed reduceDB: by marking the clauses to detach and detaching them in one go instead of one-by-one. Commit to follow...

**Comment by msoos** [comment]
Yaaay! Fixed :) That was a nice one. I also cleaned up a ton of stuff. Things should be quite a bit faster now on large instances. This was nice thanks again!

**Comment by capiman** [comment]
Wow, you are very fast! It is now working, going fast and saves a lot of hours :-)
Many thanks!!!
