### ISSUE TITLE
Stricter CNF checks, in case of error: no error reported, just aborted

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#285]
I just downloaded current sources which already contains stricter CNF checks.
I used a file (set_15.cnf same as used in my "slowspeed" bugreport), which contains
"15 0 \n" (pay attention, there is a space after 0).

I used it, current CMS4 just exits, no error message, what was wrong or even that something was wrong.

I then removed the " " and now it is working, so it seems to be the additional space.

Reporting additional space is ok, but at least there shall be an error message.
Perhaps missing return value check?

**Comment by msoos** [comment]
Thanks! Fixed :)
