### ISSUE TITLE
IS --bva=0 working???

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#289]
When using latest git version of cryptominisat:

c CryptoMiniSat version 4.5.3
c CryptoMiniSat SHA revision 248421a5bb715554ba005f963c8f6eb63f4ae302

If I include "--bva=0 --dumpred=aes.red --dumpirred=aes.irred --dumpresult=aes.result" in the command line calling cryptominisat I get the error message:

              ERROR: cannot make meaningful dump with BVA turned on.

But I turned "bva" off!!!  If I remove the "--dumpred" and "--dumpirred" entries from the command line no error message is generated.  Do the "--dumpred" or "--dumpirred" commands turn "bva" back on?  Is this something new?  It's reasonable that I don't understand how "bva" works or what it's doing.

Rob

**Comment by msoos** [comment]
This is not working in the GIT version. I will release sometime soonish and then this will be fixed. For the moment, you can use the current github version that seems to work for me.

**Comment by msoos** [comment]
Also, please use one question mark instead of 3 next time :)
