### ISSUE TITLE
Display when exiting strategy token and time for this token

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#292]
Something like (first line already there, second is additional, I assume easy to implement):
c --> Executing strategy token: sub-str-cls-with-bin
...
c --> Strategy token: sub-str-cls-with-bin done, took x seconds

**Comment by capiman** [comment]
Perhaps at same verbose level like printing times for threads?

**Comment by msoos** [comment]
Hmmm this is actually not a bad idea at all. I'll do that in the coming days. Sorry, I am still recovering from my vacation so it will take a bit of time :)

**Comment by msoos** [comment]
I am now relying in SQLite times most of the time. All the times printed should be OK, no need to count the tally more than once, printing token times as well. If there are any times not printed, please open a separate issue. But all times within a token should be printed now.
