### ISSUE TITLE
std::thread has not been declared

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#294]
I just did a git pull, then cd into the build directory, cmake .. and then make.  The following error message was generated:

$ make
[  1%] Built target tablestruct
[ 30%] Built target temp_lib_norm
[ 31%] Built target libcryptominisat4
[ 32%] Generating build/timestamp
running build_ext
[ 32%] Built target python_interface
Copying cryptominisat.h to /home/baston/kryptonite/git/cryptominisat/build/include/cryptominisat4
Copying solvertypesmini.h to /home/baston/kryptonite/git/cryptominisat/build/include/cryptominisat4
[ 32%] Built target CopyPublicHeaders
[ 33%] Building CXX object cmsat4-src/CMakeFiles/cryptominisat4.dir/main.cpp.o
/home/baston/kryptonite/git/cryptominisat/src/main.cpp: In member function ‘void Main::check_num_threads_sanity(unsigned int) const’:
/home/baston/kryptonite/git/cryptominisat/src/main.cpp:1197:37: error: ‘std::thread’ has not been declared
     const unsigned num_cores = std::thread::hardware_concurrency();
                                     ^
cmsat4-src/CMakeFiles/cryptominisat4.dir/build.make:62: recipe for target 'cmsat4-src/CMakeFiles/cryptominisat4.dir/main.cpp.o' failed
make[2]: *** [cmsat4-src/CMakeFiles/cryptominisat4.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:227: recipe for target 'cmsat4-src/CMakeFiles/cryptominisat4.dir/all' failed
make[1]: *** [cmsat4-src/CMakeFiles/cryptominisat4.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
[baston@desk build]$

I think this git pull matches version 92822fa

Rob

**Comment by baston007** [comment]
I also downloaded the zip file and generated the same result.

Rob

**Comment by baston007** [comment]
The previous version "2ffe904" builds and runs correctly.  I did see that with the src directory, the main.cpp file no longer includes the <thread> library.  Could this missing #include be the problem?

Rob

**Comment by msoos** [comment]
Thank you. Whenever the TravisCI build indicates an issue (in the main page at https://github.com/msoos/cryptominisat in RED currently), I know about it :) I will fix it today!

Cheers and thanks,
Mate

**Comment by msoos** [comment]
Fixed :) Thanks again!
