### ISSUE TITLE
Timeout from ApproxMC has been left out

### ISSUE THREAD

**Issue by msoos** [msoos/cryptominisat#297]
As per Kuldeep S Meel: We need timeout functionality for per call of BoundedSAT and BoundedSATCount since sometimes random XORs added might be too difficult and experimentally it makes sense to abort the calls.

**Comment by msoos** [comment]
Latest head should do the trick I believe. There is a new binary when you build it, you must use that:

./cups CNF

It supports all the options of cryptominisat4 but it also takes into account the ApproxMC options.

The problem I have right now is that I have no idea how to test this thing, if I managed to implement it the right way. You must give me some inputs and expected outputs for each. Unfortunately, the timeout system makes it _very_ hard to make things reproducible. Using "max conflicts" feature would have been significantly better. Maybe we should transition there because then things are _full_ reproducible that way! That's nice because testing is really important if you want this to be actually used by industry.

So, I currently need some feedback about whether it does what you expect it to do, and if not, what needs to be changed. I can give you instructions how you can change the code and then submit to me the changeset so I can apply it. Basically, you need to clone the repo in github and then submit a pull request. You can read about that on the internet, it's quite easy. http://stackoverflow.com/questions/14680711/how-to-do-a-github-pull-request

Another question is what you want to use as a binary name.

**Comment by kuldeepmeel** [comment]
I agree we should move to maxconflicts. Will the current binary support maxconflicts? If yes, I can run experiments based on it. 

Also, what are typical way of computing the value of maxconflicts (perhaps some heuristic answer based on number of variables, number of clauses and number of xors). 

Measuring whether the resulting distribution is indeed uniform or not is very very hard. I usually do stress testing on benchmarks with few thousands of solutions and compute various divergence metrices. I will try to add those scripts.

**Comment by msoos** [comment]
Maxconflicts has no heuristic. You set some fixed value and you hope for the best. Using variables or the number of clauses is a _very_ bad way of approximating absolutely anything. Treat number of variables and number of conflicts as if they were unknown, random numbers. They essentially are. As you discovered with XORs, you add a couple of XORs and it becomes impossible to solve. So, just set some number (10k?) and it should be fine.

By the way, I believe I have added the timeout support back. Please check :)

**Comment by kuldeepmeel** [comment]
I have to run some stress tests to test the timeout feature (as you mentioned, its very tricky to check) -- will take me couple of days. 

I think I will probably do some profiling on the set of benchmarks to see what is the typical number of conflicts on our set of benchmarks and then try to set some number and see its impact on performance

**Comment by msoos** [comment]
Actually, I would much rather prefer you just running some manually and seeing if it timeouts. By the way, the 3000s is hard-coded into the code -- but some places it's configurable (in SolverConf) and other places it's really compiled in (cups.cpp). I'm pretty sure that's a bug. Please check. I suggest you first manually check if my porting is OK before running heavy-duty stress test on it. I'm pretty sure there are some small mistakes in there.

**Comment by msoos** [comment]
Merry Christmas and Happy New Year! I hope your vacations went well :) Mine did and I'm officially back, yay :) So, let me know if you have any questions regarding the way I ported your code. I hope it works, but I suggest you run some small tests on it and then some more and finally the benchmarks. I'm afraid it has some issues, as porting is never trivial (but I think it's worth it)

Cheers and looking forward to your input!

**Comment by kuldeepmeel** [comment]
Happy New Year to you too, Mate. 
I know I have not been able to push changes I want to but I am still traveling (for another two weeks) with very limited remote access to linux based machine. There are few things I need to check in (some minor porting issues). 

Sorry for delay from my side.

**Comment by msoos** [comment]
Hey Kuldeep!

I hope your travels went well! Can you please take a look at the ApproxMC implementation? Thanks in advance!

Mate

**Comment by msoos** [comment]
Has been fixed. Closing.
