### ISSUE TITLE
What is meaning of "glue"? Is increasing value meaning something?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#298]
Not completely up-to-date solver reports (this is version which has search status line not printed):

c [DBclean] locked:0 marked: 9996 glue: 1086699 ttl:979 locked_solver:10
c [DBclean] locked:0 marked: 9985 glue: 1086741 ttl:1096 locked_solver:31
c [DBclean] locked:0 marked: 9988 glue: 1086779 ttl:1125 locked_solver:24
c [DBclean] locked:0 marked: 9989 glue: 1086820 ttl:973 locked_solver:25
c [DBclean] locked:0 marked: 9983 glue: 1086872 ttl:1047 locked_solver:35
c [DBclean] locked:0 marked: 9982 glue: 1086925 ttl:1027 locked_solver:36
c [DBclean] locked:0 marked: 9982 glue: 1086982 ttl:904 locked_solver:39
c [DBclean] locked:0 marked: 9991 glue: 1087027 ttl:1052 locked_solver:21
c [DBclean] locked:0 marked: 9986 glue: 1087090 ttl:1158 locked_solver:30
c [DBclean] locked:0 marked: 9988 glue: 1087138 ttl:919 locked_solver:24
c [DBclean] locked:0 marked: 9988 glue: 1087179 ttl:1635 locked_solver:27

When I look at the "glue" number, it is going up from line to line.
Is it just a counter, like conflict or restart counter, or is there some meaning
behind it, so some kind of "doing at least some progress in the background"?

**Comment by msoos** [comment]
Sorry, glue is essentially undefined -- it's defined by the algorithm you see there. Nobody knows what it means so I cannot tell you. Lower value is supposed to be good. Also, this is _not_ an issue.

Cheers,

Mate
