### ISSUE TITLE
Problem causing Parse Error and --verb option isn't working with cryptominisat4_simple

### ISSUE THREAD

**Issue by arey0pushpa** [msoos/cryptominisat#299]
I'm using CBMC as one that generating DIMAC format and using that as input in file named "foo" to use that on crypominisat as file input, first : 

# cryptominisat4_simple  --verb 0 foo 
   ERROR! unknown flag --verb

# cryptominisat4_simple foo working perfectly

# cryptominisat4_simple  foo
  c CryptoMiniSat version 4.5.3
  c compiled with gcc version 4.9.1
  c -- header says num vars:        1111485
  c -- header says num clauses:     4152266
 
  PARSE ERROR! Unexpected char (dec: '
) At line 212083 we expected a number

Line 212083 has only numbers, whether there is constrained on length of input / file line length ??? 
Is there any limit .
[foo.zip](https://github.com/msoos/cryptominisat/files/57827/foo.zip)

**Comment by msoos** [comment]
Usage is:

```
./cryptominisat4_simple --verb=4  CNF
```

And your line is _obviously_ wrong, it needs a zero at the end:

```
140584 140585 140586 140587 140588 140589 140590 140591 140592 140593 140594 140595 140596 140597 140598 140599 140600 
```

It has no zero at the end. I hope the above helps!

Mate

**Comment by arey0pushpa** [comment]
Actually format is correct only its overflowing to new line. Is this the case that Solver (as you witnessed) don't support line breaks. Because this is the form :                                                                                    -7146 7147 7148 7149 7150 7151 7152 7153 7154 7155 7156 7157 7158 7159 7160 7161 7162 
7163 7164 7165 7166 7167 7168 7169 7170 7171 7172 7173 7174 7175 7176 7177 602639 
0                                                          

The format breaking to 3 lines. Is there any way out ?? Or this does't supports.               
Thank you

**Comment by msoos** [comment]
No, that is incorrect. Please read the DIMACS specification http://www.satcompetition.org/2009/format-benchmarks2009.html No linebreaks alowed by any SAT solver I have ever seen or heard of. Supporting that would be non-standard, misleading, and plain wrong. I suggest you fix your input :)

**Comment by msoos** [comment]
I will now be printing the DIMACS specification link for every error so next time someone bumps into this, they can read the spec :) Thanks for the bug report, pretty useful actually!

**Comment by msoos** [comment]
There, should be useful :)

**Comment by arey0pushpa** [comment]
Thanks. I forgot to look back to comments. Helpful.
