### ISSUE TITLE
Run of CMS4 without M4RI

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#301]
When I compile CMS4 without M4RI, what is internal handling for XORs?
Are they not handled/detected at all? Or only slower work on them?
I see e.g. the following line:

c --> Executing OCC strategy token: occ-xor
c [impl str] lit bin: 0 lit tri: 0 (by tri: 0) (by stamp: 0) set-var: 0 T: 0.84 T-out: Y T-r: -0.00% w-visit: 10001
c --> Executing strategy token: cache-clean

Is it correct to assume XOR handling is not activated, but [impl str] is executed?
Needed? Useful? Or just easier to implement?

Or would it be possible to detect XORs so to have a clue that it could run faster
when M4RI is activated?

Or other way round: If I use a linux build with M4RI activated, can I see,
if M4RI does really help and improve solving for a certain CNF?

**Comment by msoos** [comment]
occ-xor is not performed. It is printed that the strategy is next, but nothing is printed with [occ-xor] as nothing has been done.
