### ISSUE TITLE
How to interpret output of "occ-gates"?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#302]
I have used "--gates=1". I get e.g. the following output:

```
c --> Executing OCC strategy token: occ-gates
c [occ-gates] found irred:9 avg-s: 2.0 red: 0 T: 0.55 T-out: N T-r: 51.59%
c [occ-gates] shorten cl:     0 l-rem:      0 T: 0.10 T-out: N T-r: 100.00%
c [occ-gates] rem cl: 0 avg s: 0.0 T: 0.00 T-out: N T-r: 100.00%
c [occ-gates] eqlit v-rep:   0 T: 0.00
```

It seems it found 9 irred "gates" with average size of 2. All other clauses numbers are 0.
What is the meaning of these 9 irreds? 
If they are ANDs: Is it like two (or more) variables, and both (more more) must be set to True?
Can you perhaps give a small example?

But it looks like they are not suitable to do further work/simplification on clauses?
Why? Too short? Other missing property?

**Comment by capiman** [comment]
Started again with "--printgatedot=1":

D:\cryptominisat-20151213\src>type Gates0.dot
digraph G {
}

D:\cryptominisat-20151213\src>type Gates1.dot
digraph G {
}

D:\cryptominisat-20151213\src>type Gates2.dot
digraph G {
}

```
c --> Executing OCC strategy token: occ-gates
c [occ-gates] found irred:6 avg-s: 2.0 red: 0 T: 0.14 T-out: Y T-r: -0.01%
c [occ-gates] shorten cl:     8 l-rem:      8 T: 0.13 T-out: N T-r: 99.99%
c [occ-gates] rem cl: 1 avg s: 3.0 T: 0.00 T-out: N T-r: 100.00%
c [occ-gates] eqlit v-rep:   0 T: 0.00
c Printed gate structure to file Gates3.dot
```

D:\cryptominisat-20151213\src>type Gates3.dot
digraph G {
Gate6 [ shape="point", size = 0.8, style="filled", color="darkseagreen"];
}

```
c [occ-gates] found irred:9 avg-s: 2.0 red: 0 T: 0.13 T-out: Y T-r: -0.00%
c [occ-gates] shorten cl:     5 l-rem:      5 T: 0.11 T-out: N T-r: 99.99%
c [occ-gates] rem cl: 1 avg s: 8.0 T: 0.00 T-out: N T-r: 99.99%
c [occ-gates] eqlit v-rep:   0 T: 0.00
c Printed gate structure to file Gates4.dot
```

D:\cryptominisat-20151213\src>type Gates4.dot
digraph G {
Gate9 [ shape="point", size = 0.8, style="filled", color="darkseagreen"];
}

```
c --> Executing OCC strategy token: occ-gates
c [occ-gates] found irred:9 avg-s: 2.0 red: 0 T: 0.31 T-out: Y T-r: -0.01%
c [occ-gates] shorten cl:     0 l-rem:      0 T: 0.19 T-out: N T-r: 100.00%
c [occ-gates] rem cl: 0 avg s: 0.0 T: 0.00 T-out: N T-r: 100.00%
c [occ-gates] eqlit v-rep:   0 T: 0.00
c Printed gate structure to file Gates5.dot
```

D:\cryptominisat-20151213\src>type Gates5.dot
digraph G {
Gate9 [ shape="point", size = 0.8, style="filled", color="darkseagreen"];
}

**Comment by msoos** [comment]
Gates are not useful therefore I will probably be removing them. As you discovered, they do not help. I will remove.
