### ISSUE TITLE
More missing includes (dimacsparser{cpp,h}: cmath cstdlib)

### ISSUE THREAD

**Issue by koobs** [msoos/cryptominisat#304]
System: FreeBSD 9.3-RELEASE
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5

Clang works fine

Missing include cmath in dimacsparser.cpp

```
    /wrkdirs/usr/ports/math/cryptominisat/work/cryptominisat-4.5.3/src/dimacsparser.cpp: In member function 'void DimacsParser::readClause(StreamBuffer&)':
    /wrkdirs/usr/ports/math/cryptominisat/work/cryptominisat-4.5.3/src/dimacsparser.cpp:129:29: error: 'abs' was not declared in this scope
             var = abs(parsed_lit)-1;
                                 ^
    /wrkdirs/usr/ports/math/cryptominisat/work/cryptominisat-4.5.3/src/dimacsparser.cpp:129:29: note: suggested alternative:
    In file included from /wrkdirs/usr/ports/math/cryptominisat/work/cryptominisat-4.5.3/src/dimacsparser.cpp:30:0:
    /usr/local/lib/gcc48/include/c++/complex:599:5: note:   'std::abs'
         abs(const complex<_Tp>& __z) { return __complex_abs(__z); }
         ^
```

Missing include cstdlib in dimacsparser.h

```
/wrkdirs/usr/ports/math/cryptominisat/work/cryptominisat-4.5.3/src/dimacsparser.cpp:258:9: error: 'exit' is not a member of 'std'
         std::exit(15);
         ^
```

Props to @bbqsrc for the isolation and fixes

**Comment by bbqsrc** [comment]
I like to help.

**Comment by a1880** [comment]
cmath is typically included within <complex> which is included in dimacsparser.cpp

**Comment by bbqsrc** [comment]
Except, without this patch, it doesn't compile, because what is typical doesn't necessarily mean what is standard. Explicit > implicit.

**Comment by msoos** [comment]
Thanks for these, wow! Also, thanks for the patches above, they look pretty great, I'll try to integrate them into the code and will only close this issue once that's done. Great work and thanks for being patient! I was on vacation and nobody else has commit rights.

I am of course always happy to fix missing includes. They don't break anything and can fix things for users of different compilers/distributions, etc.

**Comment by msoos** [comment]
I believe I have integrated the only other change that is non-automatic, the `abs()` to `std::abs()`. Please tell me if I missed something! Thanks!

**Comment by bbqsrc** [comment]
:+1: :smile:
