### ISSUE TITLE
Unable to link `readme_test.cpp`.

### ISSUE THREAD

**Issue by Elfrania** [msoos/cryptominisat#305]
I tried to run the C++ interface as an independent main file, i.e. readme_test.cpp, under folder /cryptominisat-4.5.3/tests/: g++ trial_test.cpp -o trial  However, just as I had tried the same with basic_test.cpp, it cannot link. Could you advise me how to run it as an independent main with the option "-lcryptominisat4"?

**Comment by msoos** [comment]
```
$ g++ -std=c++11 readme_test.cpp -lcryptominisat4 -o readme_test 
$ ./readme_test 
Solution is: l_True, l_False, l_True
```

That is how you compile :)

**Comment by Elfrania** [comment]
This is excellent.
Thank you.

**Comment by msoos** [comment]
Cool, I'm glad it helped! Closing issue :)

**Comment by msoos** [comment]
And thanks for the feedback! It's now a permanent part of CryptoMiniSat4's readme_test.cpp so others will have an easier time :)
