### ISSUE TITLE
drup/drat - question output: correct?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#307]
mytest.cnf:
1 0
-2 0
-1 -2 0
-1 2 0
1 -2 0

cryptominisat64 --drup=mytestdrup.cnf --input=mytest.cnf

mytestdrup.cnf:
d -1 -2 0
0
d -1 2 0

Now using drat-trim from 
http://www.cs.utexas.edu/~marijn/drat-trim/
It needed some (hopefully correct) changes to get it compiling on Windows.

>drat-trim mytest.cnf mytestdrup.cnf
c MATCHING ERROR: [268442979] -2 -1 0

I am sorry, I can't interpret the error to say, if I have done something wrong, not allowed,
or CMS4 is doing something wrong, or drat-trim or both.

I tried the example on the webpage of drat-trim and this seems to work,
no such error message.

**Comment by msoos** [comment]
The DRAT parser is wrong. Even with a single "0" in the DRAT output (which is definitely correct) in the DRAT output it fails. Please report to the DRAT (newer version of DRUP) maintainer.

**Comment by msoos** [comment]
OOOps, of course your CNF is all wrong. Completely, utterly wrong. Please read:

http://www.satcompetition.org/2009/format-benchmarks2009.html

Please read it carefully.

**Comment by capiman** [comment]
You mean the "p cnf 2 5" is missing in the header of the CNF?
I have added it and now drat-trim seems to work. Many thanks for the hint.
My example was an almost completely reduced example, 
which was a previously generated irred file.
It seems also the irred file (via --dumpirred=xxx) has no correct header anymore.

**Comment by msoos** [comment]
That irred generator is not tested and not perfect. It might work, but if it was up to me, I'd remove it. I kept it in for you :) But it doesn't generate proper headers :(

**Comment by capiman** [comment]
Ok, thanks. It does a great job. Removing would be a big loss, a unique feature of CMS.
I have added a header manually to the irred file and then drat-trim does it job:

d:\vc\drat-trim>drat-trim test.cnf testdrup.cnf -c CORE -l LEMMAS -r TRACE
c finished parsing
c detected empty clause; start verification via backward checking
c 1377 of 12332172 clauses in core
c 114 of 26516 lemmas in core using 1931 resolution steps
c 0 RAT lemmas in core; 0 redundant literals in core lemmas
s VERIFIED

Again many thanks for the hint!
