### ISSUE TITLE
Output of space wrong in drup.h

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#308]
```
            case DrupFlag::fin:
                if (must_delete_next) {
                    todel << "0"
                    #ifdef STATS_NEEDED
                    " 0"
                    #endif
                    "\n";
                    delete_filled = true;
                } else {
                    *file << "0 "         <-- Line 146
                    #ifdef STATS_NEEDED
                    << ID
                    #endif
                    << "\n";
                }
```

Line 146:

If STATS_NEEDED is not defined it prints "0 \n" (with one space too much before \n).

I think, this is better, but not tested:

                    *file << "0"
                    #ifdef STATS_NEEDED
                    << " " << ID
                    #endif
                    << "\n";

**Comment by msoos** [comment]
This is intentional and is a research project. It will be explained later. In the meanwhile, the best is not to compile with STATS_NEEDED.

**Comment by capiman** [comment]
I think this is a mis-understanding. The problem occurs only without (!) STATS_NEEDED.
It is only a cosmetic thing, all (delete) lines have a space and then a CR.
And it is different between if case and else case.
Are you sure this is intentional?
