### ISSUE TITLE
CrytoMinisat with Visual Studio 2012

### ISSUE THREAD

**Issue by babak-yadegari** [msoos/cryptominisat#309]
Hello, 

I downloaded the visual studio project for the CryptoMinisat form : https://github.com/msoos/cryptominisat/issues/159 but I get a lot of errors and warnings when trying to compile the code on Windows 7 and Visual Studio 2012. I have attached the log file for the Visual Studio build.

Thanks.
[akCryptoMiniSat4.log.txt](https://github.com/msoos/cryptominisat/files/114399/akCryptoMiniSat4.log.txt)

**Comment by msoos** [comment]
Please turn on C++11. Also, I cannot do complete hand-holding. You need to google the errors. C++11 will fix some. The others, I need you to google and in case you cannot find a solution, please write here. Note that you do NOT need cryptominisat for STP. It can compile without CryptoMiniSat fine.

Also, have you tried outputting a VisualC++ project using cmake? Please google it and try using it.

Good luck!

Mate
