### ISSUE TITLE
How to find multiple solutions using the CryptoMiniSat library?

### ISSUE THREAD

**Issue by Elfrania** [msoos/cryptominisat#310]
Hi Mate, 

There was an example on the `cryptominisat4` using `--maxsol` asking to return 10 maximal possible solutions:
./cryptominisat4 --verb 0 --maxsol 10 file.cnf

How do we call the same for the independent test?

**Comment by msoos** [comment]
Hm... what do you mean by independent test? That command line should run without much issue, right? I don't understand by what you mean "independent test". Can you please elaborate? Thanks!

**Comment by Elfrania** [comment]
I did this on readme_test.cpp and changed the equations where there should be giving more than 1 solutions, however, I am only getting only one. How can I ask it to give me all the solutions in the source code?

Thank you, Mate.

**Comment by msoos** [comment]
You need to ban the solution found in a for loop. See line 1278 in main.cpp: https://github.com/msoos/cryptominisat/blob/master/src/main.cpp#L1278

I hope that helps!

Mate

**Comment by msoos** [comment]
Readme has been updated. Please take a look!

**Comment by Elfrania** [comment]
Hi Soos,

That was what I did.
However, I got the respond:
Segmentation fault (core dumped)

Thank you for your help.

Michael

[trial_01.cpp.txt](https://github.com/msoos/cryptominisat/files/129469/trial_01.cpp.txt)

**Comment by Elfrania** [comment]
Hi Soos,

That was what I did.
[trial_02.cpp.txt](https://github.com/msoos/cryptominisat/files/129539/trial_02.cpp.txt)

Thank you for your help.

Michael

**Comment by msoos** [comment]
Sorry, that file is not accessible. You have to give me the file for me to see. Please upload to github gist.

**Comment by capiman** [comment]
Don't know but I can access it:

```
/******************************************
***********************************************/

#include <cryptominisat4/cryptominisat.h>
#include <assert.h>
#include <vector>

using std::vector;
using namespace CMSat;

int main()
{
    SATSolver* solver;
    solver = new SATSolver();
    /*
    SolverConf conf;

    conf.verbosity = 2;
    conf.verbStats = 1;

    solver = new SATSolver((void*)&conf);
    */
    vector<Lit> clause;

    //We need 3 variables
    solver->new_var();
    solver->new_var();
    solver->new_var();

    /*
        p cnf 3 2
        -2 0
        -1 2 3 0
    */

    //adds "-2 0"
    clause.push_back(Lit(1, true));
    solver->add_clause(clause);


    //adds "-1 2 3 0"
    clause.clear();
    clause.push_back(Lit(0, true));
    clause.push_back(Lit(1, false));
    clause.push_back(Lit(2, false));
    solver->add_clause(clause);

    // Notes: adding this back to reject the previous answer does not seem to work
    //adds "1 2 3 0"  // from 1st round answer, now we reject: "1 -2 3 0"
    clause.clear();
    clause.push_back(Lit(0, false));
    clause.push_back(Lit(1, true));
    clause.push_back(Lit(2, false));
    solver->add_clause(clause);
/*
    lbool ret = solver->solve();

    assert(ret == l_True);
    //assert(solver.get_model()[0] == l_True);
    //assert(solver.get_model()[1] == l_False);
    //assert(solver.get_model()[2] == l_True);

    std::cout
    << "Solution is: "
    << solver->get_model()[0]
    << ", " << solver->get_model()[1]
    << ", " << solver->get_model()[2]
    << std::endl;
*/
    while(true) {
        lbool ret = solver->solve();
        if (ret != l_True) {
            assert(ret == l_False);
            //All solutions found.
            exit(0);
        }

        //Use solution here. print it, for example.
        std::cout
            << "Solution is: "
            << solver->get_model()[0]
            << ", " << solver->get_model()[1]
            << ", " << solver->get_model()[2]
            << std::endl;

        //Banning found solution
        vector<Lit> ban_solution;
        for (uint32_t var = 0; var < solver->nVars(); var++) {
            if (solver->get_model()[var] != l_Undef) {
                ban_solution.push_back(
                    Lit(var, (solver->get_model()[var] == l_True)? true : false));
            }
        }
        solver->add_clause(ban_solution);
    }


    return 0;
}
```

**Comment by msoos** [comment]
This compiles and runs without any issue whatsoever:

./trial 
Solution is: l_True, l_False, l_True
Solution is: l_False, l_False, l_False
Solution is: l_False, l_False, l_True

You need to:

* give me a full stack trace
* run it under valgrind
* give me full output
* which cryptominisat release you are using
* what operating system you are using

Without  __all__ of the above, I will not be able to help. Please provide each and every single one. Thank you.

**Comment by Elfrania** [comment]
Hi Soos,

Yes, it's working now.  Thank you for your help.

I can't recall some of my github commands. Give me sometime to catch up. I
hope this code can also be added for more help samples.

I am liking Cryptominisat a lot. Thank you for the wonderful experience.

Sincerely,
Michael
