### ISSUE TITLE
Could you provide an example like `read_me.cpp` but solves for `-maxsol`?

### ISSUE THREAD

**Issue by Elfrania** [msoos/cryptominisat#313]
Hi Mate,

I just got a newer version which contains a sample to solve for multiple solutions.  I tried to imitate your codes and placed a new source (under folder `tests`) to solve for multiple solutions, however, I am unfamiliar with some configurations. Could you provide an example that extends `read_me.cpp` but solves for `-maxsol`?

Thanks.

**Comment by msoos** [comment]
Please see and use template in https://github.com/msoos/cryptominisat/blob/master/tests/multisol_test.cpp

I hope this helps!

Mate
