### ISSUE TITLE
Select variables to check not randomly, but...

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#316]
Please correct me if I am wrong or this is a completely silly idea...

This is just an enhancement idea, sorry, when I can't write in full detail how to implement it.
As far as I know CMS4 selects variables more or less randomly.
When RND is good enough (I think this is the case), each variable is taken equal often to others.

Problem: You will find new (reducable) clauses (knowledge) in all areas, but not very deep.
But when you have have a lot new clauses in the same area, clauses get shorter or even
leads to fixing variables to a certain state.

I have combined a backtracker with CMS. Backtracker selects the first e.g. 10 variables 
(at variable depth, but always same path), 
and the CMS checks if it is possible to find a solution with theses fixed variables.
If it is UNSAT, backtracker selects a new "state" of these variables.
CMS4 runs faster, because more variables are already fixed.
But CMS4 itself must run more often, because backtracker does not only find 1 variant
of the 10 variables.
So you find more and more clauses around these 10 variables,
which leads to reduction due to more and more combinations leading to UNSAT.

Backtracker not always checks 10 variables, but already backtracks
e.g. when only 5 of them lead to UNSAT.

I think there is a small similarity to  earlier "branch" command, which was
used to limit solving to certain variables like a key in an encryption CNF?

**Comment by msoos** [comment]
"When RND is good enough (I think this is the case), each variable is taken equal often to others."

This is very-very wrong. Please google "VSIDS SAT" and read _all_ papers. Thank you.
