### ISSUE TITLE
Big used memory takes a long time to free (via destructors?), fast exit via exit(x)?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#318]
When using a lot of memory, it takes a long time till all the memory is freed afterwards.
I assume a lot small memory blocks (millions of binaries) take so much time to get freed?
When everything is exported, SAT/UNSAT + possible solution(s) are written to result file,
would it not be just possible to do a hard exit?
Or if it is not the case, why not? Perhaps command line would be useful (also useful for SAT competitions)
to use hard exit and let the OS clean up all used memory instead of spending time
to do it itself...

**Comment by capiman** [comment]
Note: First I thought of just press Ctrl-C after all clauses were exported and statistics is printed,
but then perhaps #317 makes problems, because files are perhaps not yet completely written.

BTW: Just some numbers: I have solving running with 2 threads and ~24 GBytes memory in use.
The "freeing memory" step takes ~ 25 minutes, which I hope to save with a fast exit.

**Comment by msoos** [comment]
Wow. 25 minutes is crazy. The problem with hard exit is that it's not very nice... It's the watchlists that take so much to free by the way. I'll look into this, thank you!

**Comment by msoos** [comment]
I have significantly improved some of the memory management. Please re-test. Until then, I'm closing this because I think things have _really_ improved.
