### ISSUE TITLE
Adding interface functions do help CMS gaining knowledge while running?

### ISSUE THREAD

**Issue by SmallLars** [msoos/cryptominisat#320]
Hello,

I am working on my master thesis and using CMS (4.5.3) to analyse SHA256. Therefore I do different runs and try to evaluate new clauses I get from different dumps. After that I try to multiply possibly valuable clauses in 2 directions: rounds (64) and bit width (32). With this strategy I was able to find a lot of more possibly valuable clauses. At this time I do this steps by hand and thinking about a better solution:

I think its not a good way to extend CMS in a direct way to do this work, because the problem is very 
specific. But how about an extension of the interface in a general way, to make it possible to use external knowledge? I think about an interface function, where I can add a function pointer to CMS.
Every time CMS finds a new clause (redundant, irredundant or assumption based) CMS call this function to ask what to do. It should be possible to throw the clause away, confirm usage or add more clauses to CMS. With this method it would also be possible, to try new evaluation strategies for clauses, without touching the internal code of CMS or adding a lot of new options.

I would be happy when you can tell me what you think about this, before I start a lot of useless work.
Is it possible to implement this in a reasonable easy way? Would you be interested to add this on CMS or merge a possible pull request?

Thank you very much
   Lars

**Comment by msoos** [comment]
Sounds possible and not horrible. However, note that your function will have to run _very_ fast. It will be called >20'000 times a second. Throwing away the clause is not really possible, but we can set its "glue" very high and so it will not be retained for long. Adding extra clauses through that callback function will be _very_ tricky. Making the clause permanent is easy, though, you can again manipulate its glue, setting it low, and thereby not removing it.

Here is where the callback should be and you should set the glue here:


```
    minimize_learnt_clause();
    glue = calc_glue_using_seen2(learnt_clause);
    mimimize_learnt_clause_more_maybe(glue);
```

AFTER the `glue = ...` you should put your function call, and basically do:

```
glue = my_function(learnt_clause)
```

Return a value of 2 in case you want to keep it, and return a value of 50 in case you'd rather not.

**Comment by rw** [comment]
In a similar way, is it possible to customize the order in which variables (CNF inputs) are selected for evaluation?

**Comment by msoos** [comment]
Sure. Look at the `pickBranchLit` function :) Note that variables are renumbered internally (kinda randomly), so you probably want to pass `--renumber 0`. Good luck!

**Comment by rw** [comment]
@msoos Great, thanks!

**Comment by msoos** [comment]
I hope I helped everyone :) Thanks for everyone for their help and encouragement! Cheers!
