### ISSUE TITLE
difficulty building cryptominisat on Mac OS X

### ISSUE THREAD

**Issue by wvnicholson** [msoos/cryptominisat#322]
I previously posted this to Mate Soos; but although he replied he wanted me to repost on github.

I tried building and installing cryptominisat on a Mac OS X system (10.9.5).  I was able to get further with the tar.gz file with the source rather than fetching the source with "git clone".  Eventually the build failed with link errors when building the Python library.  It appears it did compile the cryptominisat binary for the command line program.  Mate Soos suggested then trying:

1) clean your build directory (rm -rf build && mkdir build && cd build)
2) run "cmake -v .."
3) run "make VERBOSE=1"
4) put the FULL output of BOTH into a shiny new github issue
5) please also add "python -v" and maybe some other python-related stuff

I'm doing my test by starting from scratch in a new directory so I skipped the "cleaning" part of step 1.  Step 2 was done with:
cmake -v .. -DM4RI_LIBRARIES:STRING=/Users/u1374090/software/m4ri/m4ri-20140914/.libs/libm4ri.dylib -DM4RI_INCLUDE_DIRS:STRING=/Users/u1374090/software/m4ri/m4ri-20140914
so M4RI-related stuff can be found.

I've attached the output from the cmake:
[cmake_errs_log.txt](https://github.com/msoos/cryptominisat/files/167633/cmake_errs_log.txt)

Then I did "make VERBOSE=1" and the output is attached:
[make_errs_log.txt](https://github.com/msoos/cryptominisat/files/167638/make_errs_log.txt)

The "python -v" output is:
[python_v_log.txt](https://github.com/msoos/cryptominisat/files/167640/python_v_log.txt)

**Comment by msoos** [comment]
Can you please check if this fixes the issue? If not, can you please attach all of the above again? Thanks!

**Comment by msoos** [comment]
I am closing as I am getting no response :( Sorry! In case you are still there, please check if my fix helped :) Thanks!
