### ISSUE TITLE
Multi-threading with solutions banning

### ISSUE THREAD

**Issue by Elfrania** [msoos/cryptominisat#323]
Hi Soos,

As known, here is an example of adding a clause to the solver without multi-threading:

void add_clause_to_all_threads(Clause clause) {
  for(int i = 0; i < threads; i++) {
    solver[i].add_clause(clause);
  }
}

Is there a sample code to create and destroy threads safely, especially when multiple solutions are included via the solutions banning?

Michael

**Comment by msoos** [comment]
Please use the API. `add_clause_to_all_threads` is not part of the API. Please use function from `cryptominisat.h` **only**. And that will take care of threads, etc. Unless you are good at C++11 **do not read any other file than `cryptominisat.h`**. Note that `cryptominisat.h` does not contain `add_clause_to_all_threads`.

**Comment by msoos** [comment]
Also, I will not maintain any compatibility with anything else other than in the API. Unless you want to roll your own cryptominisat distribution and backport everything I do into that distribution (about 4h a week job), I suggest you don't roll your own.

**Comment by Elfrania** [comment]
I understand.
Thank you, Soos.

**Comment by msoos** [comment]
My name is "Mate Soos", so you can either call me "Mate" (much preferred) or "Mr. Soos" (not preferred at all)

Mate

**Comment by Elfrania** [comment]
Ah, pardon.
I got it. 
Thank you, Mate.
