### ISSUE TITLE
Long running task not abortable due to timeout in multi threading run

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#324]
> cryptominisat64 --polar=true --maxtime=14400 --threads=6 --bva=0 --maxsol=1000000 --input=...
> ...
> c Finished thread 4 with result: l_Undef T-diff: 14213.73
> c Finished thread 3 with result: l_Undef T-diff: 14220.05
> c Finished thread 1 with result: l_Undef T-diff: 14223.36
> c Finished thread 5 with result: l_Undef T-diff: 14223.85
> c Finished thread 2 with result: l_Undef T-diff: 14261.34
> c [sub] rem cl: 2043 tried: 8399650/839965 (1000.0%) T: 373.61 T-out: N
> c [str] sub: 156 str: 11338 tried: 2400141/839965 (285.7)  T: 541.51 T-out: Y
> c [occ-substr] sub_str_with sub: 2 str: 1 0-depth ass: 0 T: 4.05 T-out: N T-r: 99.24%
> c [consolidate] T: 0.05
> c calculated reachability. T: 0.000
> c Finished thread 0 with result: l_Undef T-diff: 14872.92
> ...dumping...

So thread 0 took over 400 seconds to be aborted. Timeout seems to be ignored during

c [sub] rem cl: 2043 tried: 8399650/839965 (1000.0%) T: 373.61 T-out: N
c [str] sub: 156 str: 11338 tried: 2400141/839965 (285.7)  T: 541.51 T-out: Y
c [occ-substr] sub_str_with sub: 2 str: 1 0-depth ass: 0 T: 4.05 T-out: N T-r: 99.24%

**Comment by msoos** [comment]
Sorry, no idea what caused it, but I now put in more data printed here, so we will know if you execute it again. Can you try doing that please? Sorry. Also, it should never execute for 500s unless there is huge load on the system and you are getting about 10% of the CPU or less.

**Comment by capiman** [comment]
This is with tonights sources (16e2f57). Timeout was again 14400:
```
c  4842 8842K    1537  5396 11178  6854   11.17    4.59 1049K     2     0   33.93   33.93
c [DBclean] locked:0 marked: 9991 glue: 1034059 ttl:714 locked_solver:19 T: 0.22
c [consolidate] T: 0.00
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC  RedL  RedT  RedB l/longC  l/allC
c  4845 8849K    1537  5396 11178  6854   11.17    4.59 1046K     2     0   33.89   33.89
c recursive minimization cost OK: 5140Kcost/(% lits removed)
c --> Executing strategy token: handle-comps
c [clean] T: 0.0930 s
c [comp] Found component(s): 1 BP: 2.35M T: 0.10 T-out: N T-r: 100.00%
c --> Executing strategy token: scc-vrepl
c [scc] new: 0 BP 0M T: 0.00
c --> Executing strategy token: cache-clean
c [cache] cleaned. Updated:       0 K Cleaned:       0 K Freed:       0 K T: 0.00
c --> Executing strategy token: cache-tryboth
c [bcache]  0-depth ass: 0 BXprop: 0 T: 0.00
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 tri: 0 (stamp: 0, cache: 0) T: 0.05 T-out: N w-visit: 3074
c --> Executing strategy token: intree-probe
c [clean] T: 0.0930 s
c [scc] new: 0 BP 0M T: 0.00
c [clean] T: 0.1010 s
c [vrep] vars 0 lits 0 rem-bin-cls 0 rem-tri-cls 0 rem-long-cls 0 BP 3M T: 0.19
c [intree] Set 0 vars hyper-added: 0 trans-irred::0 trans-red::0 T: 0.78 T-out: N T-r: 99.99%
c --> Executing strategy token: probe
c [clean] T: 0.0870 s
c [probe] lits : 35.80M act vars: 1.54K BP+HP todo: 768.00M
c [probe] NumProps after perf multi: 384.00M after numcall multi: 1311.53M (<- final)
c [probe] 0-depth assigns: 0 bsame: 0 Flit: 0 Visited: 3069/3074(99.8%)
c [probe] probed: 1712(55.7%) hyperBin:0 transR-Irred:0 transR-Red:0
c [probe] BP: 55.8M HP: 0.4M T: 0.74 T-out: N T-r: 95.70%
c [probe] time spent updating cache during probing: 0.0%
c --> Executing strategy token: sub-str-cls-with-bin
c [clean] T: 0.0970 s
c [distill] cache-based irred--  cl tried    10792 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.63 T-out: N
c [distill] cache-based   red--  cl tried   135402 cl-sh 15300 cl-rem    0 lit-rem 111421 T: 25.49 T-out: Y
c --> Executing strategy token: distill-cls
c [distill] longirred tried: 5396/5396 cl-r:0 lit-r:0 T: 51.68 T-out: N T-r: 19.58%
c [distill] tri+long useful: 0/5396/5396 lits-rem: 0 0-depth-assigns: 0 T: 51.69 T-out: N
c --> Executing strategy token: scc-vrepl
c [scc] new: 0 BP 0M T: 0.00
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 tri: 0 (stamp: 0, cache: 0) T: 0.03 T-out: N w-visit: 3074
c --> Executing strategy token: str-impl
c [impl str] lit bin: 0 lit tri: 0 (by tri: 0) (by stamp: 0) set-var: 0 T: 0.01 T-out: N T-r: 99.99% w-visit: 3074
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 tri: 0 (stamp: 0, cache: 0) T: 0.05 T-out: N w-visit: 3074
c --> Executing strategy token: str-impl
c --> Executing OCC strategy token(s): 'occ-backw-sub-str,occ-clean-implicit,occ-bve,occ-bva,occ-gates,occ-xor,'
c [clean] T: 0.1600 s
c [simp] mem usage for occur      1 MB
c [simp] Not linked in 0/5396 (0.00 %)
c [simp] mem usage for occur    543 MB
c [simp] Not linked in 2/1052322 (0.00 %)
c Mem for watch alloc      : 339         MB (0.00      %)
c Mem for watch array      : 0           MB (0.00      %)
c --> Executing OCC strategy token: occ-backw-sub-str
c [sub] tri upI: 74 subs w bin: 0 str w bin: 63268 subs w tri: 0 str w tri: 23453 tried: 371842 str: 0 0-depth ass: 0 T: 7.40 T-out: Y T-r: -0.01%
c Finished thread 4 with result: l_Undef T-diff: 14400.05
c Finished thread 1 with result: l_Undef T-diff: 14404.12
c [sub] rem cl: 1328 tried: 3634181/1057718 (343.6%) T: 334.98 T-out: Y T-r: -0.00%
c Finished thread 3 with result: l_Undef T-diff: 14464.68
c Finished thread 2 with result: l_Undef T-diff: 14578.89
c [str] sub: 33 str: 11456 tried: 556320/1057718 (52.60)  T: 236.84 T-out: Y T-r: -0.00%
c [occ-substr] sub_str_with sub: 131 str: 977 0-depth ass: 0 T: 19.40 T-out: N T-r: 93.00%
c [consolidate] T: 0.07
c calculated reachability. T: 0.000
c Finished thread 0 with result: l_Undef T-diff: 14698.23
c Dumped redundant clauses
```
It is running on a machine, which has 8 core (4 real core *2 because of HT, Skylake i7-6700K)
and 2 times CMS4 (once with 6 threads, once with 2 threads).
What do you see, where to look in additional output?

**Comment by capiman** [comment]
In this report I am searching for multiple solutions. Could it be that the time checked is the
time since a thread is started, not the total time since startup of CMS4 (or at least when solving starts 
the first time)? So time is resetted every time a solution is found and a new 14400 timeout starts.

But it could be two different errors. In the above posts I see times over 14400, which seems to 
be a missing check or perhaps "a check and returning", but called function is not handling abort
case and calls function again and again.

**Comment by capiman** [comment]
Is there no need for something like

solver->must_interrupt_asap()

in "while" in subsumestrengthen.cpp line 282?
(perhaps like in line 468, check it only each 256th time)

Same in "for" in subsumestrengthen.cpp line 143? 
Or is second part so fast, that there is no need for an additional check?
Or must it run so fast, that in sub-function there can't be a check
without influencing normal solving speed?

**Comment by msoos** [comment]
The bug is this line:

```
c [sub] rem cl: 1328 tried: 3634181/1057718 (343.6%) T: 334.98 T-out: Y T-r: -0.00%
```

I am marking this as a bug. I'll dig deeper later. Thanks for the report!

**Comment by TheLoneWolfling** [comment]
I was going to add this as a bug (percentages > 100%?), but it seems to be the same thing:

```
c [sub] rem cl: 859 tried: 4858756/952107 (510.3%) T: 6.12 T-out: Y T-r: -0.00%
```

**Comment by msoos** [comment]
Sorry, this is too out-of-ordinary, I think I'll need to concentrate on things that everybody bounces into. I'll get back to multi-threading later and maybe re-architect some things. That will fix this. For the moment, I need to concentrate on other stuff.
