### ISSUE TITLE
CMS4 got slower the last 5 days?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#326]
Hi Mate,

I had downloaded and built a version of CMS4 in the morning of 26th March 2016.
And today morning I downloaded again the current version, 31th March 2016.

The version from today seems to got a lot slower, at least with finding multiple solution of 6x6.cnf.

When running 6x6.cnf and searching for the 260 solutions (--maxsol=1000),
the old one took 

9261s (first test) and 8539s (second test),

whereas the newer one took 

13377s (first test) and 11864s (second test).

Best regards,
Martin

**Comment by msoos** [comment]
I have some ideas, but try running with "-n1" option. It should be much better.

**Comment by capiman** [comment]
I added "-n" to both CMS4 (old and new one), test not yet finished,
but old one has already 174 solutions found, new one only 98.

Perhaps an idea: In old one I see partly multiple solutions which are found directly after each other
in one second, the new one displays a solution then it takes a few seconds, till some new output occurs
and a lot longer till next solution is found. Perhaps something changed when solver is restarted?

**Comment by capiman** [comment]
I assume due to background load, the cpu time was not as high in second run (of -n1) as in first run,
but here are both results with "-n1" from both version of CMS4:

Old solver (26.03.2016): First run: 22637s, Second run: 25066s
New solver (31.03.2016): First run: 26426s, Second run: 29391s

Even when times vary a lot, the tendency seems to be that with "-n1" times got even a lot longer.

If more correct times are really needed, I think I must restart the tests with an almost empty computer
(background task at minimum).

BTW: Old and new CMS4 in this test were both running at the same time, so if there was less cpu time
on the computer due to background task, I think both were affected.

**Comment by capiman** [comment]
I have done some additional tests:
(I measured the time to find 4 solutions (of the 260 solutions) 
of the 6x6.cnf, with different CMS4 versions)

```
f345740 Date:   Sat Mar 26 17:25:50 2016 +0000 ->  32s /  31s
a7c41da Date:   Sun Mar 27 02:08:50 2016 +0100 ->  32s /  32s
d09e323 Date:   Sun Mar 27 02:09:09 2016 +0100 -> 110s / 106s
e4c7d6b Date:   Sun Mar 27 02:09:45 2016 +0100 -> 110s / 105s
7fd7786 Date:   Sun Mar 27 02:10:07 2016 +0100 -> 112s / 112s
59e2a8a Date:   Sun Mar 27 02:10:46 2016 +0100 -> 111s / 107s
3b8a5f2 Date:   Sun Mar 27 02:11:14 2016 +0100 -> 110s / 108s
a2a002b Date:   Sun Mar 27 02:15:24 2016 +0100 -> 111s / 109s
7a0ee75 Date:   Sun Mar 27 02:15:56 2016 +0100 -> crashing
e837e97 Date:   Sun Mar 27 02:24:46 2016 +0100 -> crashing
32dda64 Date:   Sun Mar 27 02:58:30 2016 +0100 -> 107s / 110s
94d74d8 Date:   Sun Mar 27 03:14:24 2016 +0100 -> 112s / 107s
dcde910 Date:   Sun Mar 27 03:14:44 2016 +0100 ->  47s /  42s
5ebfda3 Date:   Sun Mar 27 03:14:57 2016 +0100 ->  36s /  22s
bbbe214 Date:   Sun Mar 27 03:15:12 2016 +0100 ->  57s /  53s
1424eda Date:   Sun Mar 27 11:36:05 2016 +0100 ->  12s /  11s
d75d47f Date:   Sun Mar 27 11:52:38 2016 +0100 ->  69s /  62s
c05c4f4 Date:   Sun Mar 27 11:59:22 2016 +0100 ->  87s /  82s
ea8d9e4 Date:   Sun Mar 27 12:15:56 2016 +0100 ->  12s /  11s
75497c8 Date:   Sun Mar 27 12:16:32 2016 +0100 ->  11s /  11s
052be5e Date:   Sun Mar 27 12:17:17 2016 +0100 ->  14s /  13s
f2d4d8b Date:   Sun Mar 27 12:37:42 2016 +0100 ->  11s /  11s 
c69b0b2 Date:   Sun Mar 27 12:38:24 2016 +0100 ->  59s /  53s
cfb9b35 Date:   Sun Mar 27 21:39:39 2016 +0100 ->  54s /  51s
3ee3fab Date:   Sun Mar 27 21:39:52 2016 +0100 ->  54s /  51s
7c519e3 Date:   Sun Mar 27 21:40:43 2016 +0100 ->  51s /  52s
f7240d3 Date:   Sun Mar 27 21:43:47 2016 +0100 ->  32s /  28s
4cfc417 Date:   Mon Mar 28 20:45:34 2016 +0100 ->  28s /  26s
bfa121f Date:   Mon Mar 28 20:46:00 2016 +0100 ->  72s /  71s
19670d7 Date:   Mon Mar 28 20:50:51 2016 +0100 ->  70s /  68s
eb45bdc Date:   Mon Mar 28 20:52:14 2016 +0100 ->  70s /  67s
0bbf9aa Date:   Mon Mar 28 20:59:09 2016 +0100 ->  69s /  71s
3d5cf43 Date:   Mon Mar 28 21:15:15 2016 +0100 ->  69s /  68s
b05e787 Date:   Mon Mar 28 21:52:41 2016 +0100 ->  69s /  74s
46683a2 Date:   Mon Mar 28 22:22:43 2016 +0100 ->  69s /  69s
d7435d7 Date:   Tue Mar 29 22:50:20 2016 +0100 ->  66s /  66s 
bceefa4 Date:   Wed Mar 30 02:24:34 2016 +0100 ->  66s /  66s
4679659 Date:   Thu Mar 31 20:41:27 2016 +0100 ->  68s /  65s
039a877 Date:   Fri Apr  1 00:21:59 2016 +0100 ->  67s /  64s
c6c18a1 Date:   Sun Apr  3 01:40:55 2016 +0100 -> 109s / 103s
```

SHA1, Date/Time -> Time of first run (in the morning) / Time of second run (in the afternoon)

I have not tried/measured every commit, but perhaps the small statistics is helpful?
(all measurements done on Windows Vista 64 bit, other apps were running and consuming cpu time,
but times in second run were almost similar to first run so I think they are not too bad).

**Comment by msoos** [comment]
Sorry, there were a number of bugs in there. I have been working hard on trying to remove them. Please wait a little and I'll update you soon when I feel like I have fixed them. I have done some testing over the past weeks and I see things, too :) But it takes a little while to get things back on track. I'll get back to you shortly!

**Comment by capiman** [comment]
Many thanks for your answer. No pressure from my side. 
Take the time you need. If you need some testing on my side, please tell me. 
I hoped the above list would help you to find some bugs easier.
It is difficult because an improvement in one CNF can make worse another CNF.
Best would be if all CNF get improvements.
And don't forget: You make an excellent job with CMS.

Perhaps interesting commit in above list: d09e323
( https://github.com/msoos/cryptominisat/commit/d09e323e7ccb6a61b46f4d58c08ec4b05aed0046 )
"Only update polarity when needed"
-> seems to be a good improvement (from my very limited knowledge), 
but looks like it switched off something which is at least good for searching multiple solutions of 6x6.cnf.
But I must admit that multiple solution is something special, but I hope comparable to searching 
for a single solution (behaviour/improvements on both sides) or searching for UNSAT.

Is there perhaps a different CNF which I shall use for such testing, more suitable
for races like SAT-competition, which does not take too long and which is a good example
for a lot other kind of CNF used for SAT-competition?

Is such a runtime statistics interesting at all? Or do you perhaps get the same info
much easier with one of the already existing ways (AWS?) you are already using?

**Comment by msoos** [comment]
I'm sorry, but this feedback is not very useful right now. I am still tuning the solver, so things are very hazy. The SAT competition deadline is near. In case you see a substantial difference (more than 50%) that'd be intersting. But 25k sec vs. 30k sec is not that big of a deal. It could be absolutely random -- you could potentially just run the old solver with `--rand XX` and get the same effect. Let me close this and we can discuss about performance after the competition deadline is over. I have blown over 70 USD on running lots of tests on AWS, so I am trying to be on top of performance, I can assure you :)
