### ISSUE TITLE
Support more variables/overflow when adding variables

### ISSUE THREAD

**Issue by agreatnate** [msoos/cryptominisat#341]
I'm using cryptominisat4 in an application requiring potentially quite a few variables.  It is working very well, requiring essentially no memory or time to solve the system as I add additional variables/clauses until it suddenly appears to have an integer overflow somewhere.  

In particular, it works fine solving a system with 131071 variables and 474954 clauses, it only takes a few seconds to give me a valid solution, however upon increasing the number of variables to 131072 (and introducing a handful of additional clauses) I get the error:  

`ERROR: Variable 2147483648 inserted, but max var is 131072
gpf.out: /home/nathan/sat/cryptominisat-4.5.3/src/solver.cpp:3171 void CMSat::Solver::check_to_large_variable_number(const std::vector<CMSat::Lit>&) const: Assertion 'false' failed.`
`Aborted`

Based on the solution the solver found for 131071 variables, that solution can be trivially extended to a solution with 131072 variables, so something having to do with solvability of the system shouldn't be the problem.

**Comment by a1880** [comment]
I guess that the "p" line in your CNF input file still has the old number of variables. You might want to verify that p header line and subsequent CNF clauses are consistent.

**Comment by msoos** [comment]
Well, most likely you inserted a variable that is being printed by
cryptominisat. There is no plan on supporting 2147483648 variables. If you
need that many it's probably an issue with modelling. Are you sure you need
2147483648 (i.e. about 2.1 billion) variables?

**Comment by msoos** [comment]
I am closing because it's almost certainly an issue with the caller. That number, 2147483648 is an INT_MAX for 32b. So probably uninitialized variable. Just run it under valgrind and you will probably get an error. Closing.
