### ISSUE TITLE
Crash AppVeyor (source 665cfad, 4 days ago) when doing "occ-bve"

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#342]
I just downloaded cryptominisat_simple.exe produced by AppVeyor
(source 665cfad )
and tried it against different CNFs.
I get always a crash more or less fast at same position:

```
>d:\cryptominisat4_simple.exe f:\6x6\6x6.cnf
c CryptoMiniSat version 4.5.3
c compiled with non-gcc compiler
c WARNING: Empty line at line number 1 -- this is not part of the DIMACS specifications (http://www.
satcompetition.org/2009/format-benchmarks2009.html). Ignoring.
c WARNING: Empty line at line number 8 -- this is not part of the DIMACS specifications (http://www.
satcompetition.org/2009/format-benchmarks2009.html). Ignoring.
c WARNING: Empty line at line number 10 -- this is not part of the DIMACS specifications (http://www
.satcompetition.org/2009/format-benchmarks2009.html). Ignoring.
c WARNING: Empty line at line number 156723 -- this is not part of the DIMACS specifications (http:/
/www.satcompetition.org/2009/format-benchmarks2009.html). Ignoring.
c -- clauses added: 155432
c -- xor clauses added: 0
c -- vars added 1280
c  Parsing time: 0.16         s
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 tri: 0 (stamp: 0, cache: 0) T: 0.02 T-out: N w-visit: 2560
c --> Executing strategy token: scc-vrepl
c --> Executing OCC strategy token(s): 'occ-backw-sub-str,occ-clean-implicit,occ-bve,'
c [clean] T: 0.0030 s
c [simp] mem usage for occur      0 MB
c [simp] Not linked in 0/36 (0.00 %)
c [simp] mem usage for occur      0 MB
c [simp] Not linked in 0/0 (0.00 %)
c Mem for watch alloc      : 3           MB (0.00      %)
c Mem for watch array      : 0           MB (0.00      %)
c --> Executing OCC strategy token: occ-backw-sub-str
c [sub] tri upI: 2038 subs w bin: 0 str w bin: 0 subs w tri: 0 str w tri: 0 tried: 155396 str: 0 0-d
epth ass: 0 T: 0.07 T-out: N T-r: 94.27%
c [sub] rem cl: 0 tried: 360/36 (1000.0%) T: 0.00 T-out: N T-r: 99.99%
c [str] sub: 0 str: 0 tried: 108/36 (300.0)  T: 0.00 T-out: N T-r: 99.98%
c [occ-substr] sub_str_with sub: 0 str: 0 0-depth ass: 0 T: 0.00 T-out: N T-r: 100.00%
c --> Executing OCC strategy token: occ-clean-implicit
c --> Executing OCC strategy token: occ-bve
```

Correction: Can only see it on 1 machine (which still has Windows Vista on it...).
On two others (Windows 7 and Windows 10) it seems to be working.

**Comment by capiman** [comment]
This seems to come from __popcnt(x) when Microsoft compiler is used.

https://msdn.microsoft.com/en-us/library/bb385231(v=vs.140).aspx

Old machine does not seem to support it...and application crashes.
There seems to be some processor specific query routine (via __cpuid() and check certain bits),
but not sure if this is the right way.

"To determine hardware support for the popcnt instruction, call the __cpuid intrinsic with InfoType=0x00000001 and check bit 23 of CPUInfo[2] (ECX). This bit is 1 if the instruction is supported, and 0 otherwise. If you run code that uses this intrinsic on hardware that does not support the popcnt instruction, the results are unpredictable."

It is not compiler specific, not executable specific, but specific on which platform the executable is executed.
Is this often called? Really neeed by CMS4? Must it be very fast? If not supported, replace by slower software implementation? It looks like MinGW64 gcc does not use this instruction,
because executable compiled with it (compared to latest Microsoft compiler) runs on all platforms.

**Comment by capiman** [comment]
__cpuid is related to x86/x86_64 (Intel, AMD), 
I think it is not working for e.g. ARM processors and other ones.

**Comment by capiman** [comment]
__popcnt(x) not (!) working on Intel Q9550.
__popcnt(x) working on Intel i7-2600K and i7-6700K.

Example to query support (slightly modified/corrected):

```
#include <nmmintrin.h>

main()
{
    int is_capable;
    int CPUInfo[4] = {-1};
    __cpuid(CPUInfo, 1);
    is_capable = (CPUInfo[2] >> 23) & 1;
    if(is_capable) printf("Supports __popcnt()\n");
    else printf("Does NOT support __popcnt() !!!\n");
}
```

**Comment by msoos** [comment]
I hope this does the job! :) Please re-open if not!

**Comment by msoos** [comment]
Thanks for all the effort above! Great work, as usual.

**Comment by capiman** [comment]
Hi Mate, many thanks for the quick merge. 
Can you please merge to master branch, so app veyor build it?
Your change went to branch axelbranch (or so).
Would it also be possible to already take Axel's Command Line Parsing to master branch.
Shall it go into cryptominisat4_simple or regular cryptominisat4?
Best regards and have a nice weekend!
Martin

**Comment by msoos** [comment]
Thanks,merged. I am working on Axel's stuff :)

**Comment by capiman** [comment]
my_popcnt: Multiple times defined:
(I assume each time the header file is included. Move partly to popcnt.cpp?)

  searcher.obj : warning LNK4006: "int __cdecl CMSat::my_popcnt(unsigned __int64)" (?my_popcnt@CMSat@@YAH_K@Z) already
defined in solver.obj; second definition ignored [D:\cryptominisat-20160618\cmsat4-src\libcryptominisat4.vcxproj]
  occsimplifier.obj : warning LNK4006: "int __cdecl CMSat::my_popcnt(unsigned __int64)" (?my_popcnt@CMSat@@YAH_K@Z) alr
eady defined in solver.obj; second definition ignored [D:\cryptominisat-20160618\cmsat4-src\libcryptominisat4.vcxproj]

**Comment by msoos** [comment]
Great catch, thanks! :)

**Comment by msoos** [comment]
(fixed, hopefully)

**Comment by capiman** [comment]
The good news is, the current sources seem to run again on the machine, 
where the error occurred previously. 
The bad news: AppVeyor is "red", does not compile and deliver an executable.
It just says error at end of log, but not what error occured.
There also seems to be no external file (like a build-log), where an (detailed) error is reported.
But it displays a "green" on github-readme-page.

**Comment by capiman** [comment]
BTW: Do you know why xxd-missing-error is not reported on AppVeyor?
I also get the error when doing a fresh download and must create a dummy xxd...

**Comment by msoos** [comment]
Yeah, I'm reverting. I will not make this work on Q9550. That is a CPU that came out in 2008. It's 2016 now. That will fix AppVeyor and it will make sure we don't have this essentially useless jmp instruction before the popcnt. I hope that's OK.

**Comment by capiman** [comment]
I agree. Would it perhaps be an idea to add some simple check (call) of popcnt, just in the beginning 
of main, perhaps before CNF is read? It would make it much easier to analyze when it does crash, t
that it does not crash somewhere/sometime during calculation but just at the beginning, 
perhaps even before the CNF is read.

**Comment by msoos** [comment]
I'm happy to accept well-tested patches :)

Mate
