### ISSUE TITLE
No Windows x64 build instructions

### ISSUE THREAD

**Issue by nmz787** [msoos/cryptominisat#345]
I seem to be hitting a brick wall with pycosat (extended it to allow adding clauses independent of solving, as I have more than 234 million clauses and passing them all at once to pycosat was not working) so I would like to try this. I found these binaries, but they have old date stamps:
https://gforge.inria.fr/frs/?group_id=1992&release_id=8137#cryptominisat-_3.3-title-content

Any ideas?

**Comment by msoos** [comment]
Ahh, that is old :) For Linux we build cryptominisat + pycryptosat. However, for Windows, currently we only build a static executable: https://ci.appveyor.com/project/msoos/cryptominisat

Let me try to do something about this :) It was pretty damn hard to get cryptominisat to compile for Windows. But making the python library may be a lot easier. I'll look into this, thanks!

**Comment by msoos** [comment]
CryptoMiniSat 5 has just been released. You can try building similar to the README file, please make sure to have python libraries and **development headers** installed. Please report back if there is any problem. This might/might not work:

```
$ unzip cryptominisat-version.zip
$ cd cryptominisat-version
$ cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 14 2015 Win64"
$ msbuild INSTALL.vcxproj
```

Please try and get back with what you got and what you could/had to change to fix it. It should be relatively easy and quick! Try playing around with these flags:

```
    add_compile_options(/DEBUG)
    add_compile_options(/GS)
    add_compile_options(/W1)
    add_compile_options(/Zc:inline)
    add_compile_options(/fp:precise)
    add_compile_options(/EHsc)
    add_compile_options(/MT)

    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} /INCREMENTAL:NO")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /PDBCOMPRESS")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /STACK:1572864")
```

Thanks and looking forward to what you found!

**Comment by nmz787** [comment]
Would you be able to wrap a `setup.py` script around the compilation stuff? I don't know much about Visual Studio or all the compiler and linker options... make and cmake always confuse me. Somehow though, packages on *pypi* will kickoff Visual Studio compilation through something called `vcvarsall.bat`.

If you can't provide that, can you at least provide more information on the build environment? For example, I don't have cmake installed on Windows... and I don't know where to download it from (I only imagine cygwin or the likes, which won't allow me to compile for normal Windows Python programs, I think)

**Comment by capiman** [comment]
Perhaps this helps:
https://cmake.org/download/

**Comment by nmz787** [comment]
Thanks msoos and capiman, I might be able to make some progress compiling things with that info. I will let you know. Otherwise, I actually went to the 'Release' page and saw there was a Windows x64 binary, and it seems it was able to take my 8 gigabyte clause file and solve it. I am still reviewing and understanding the output, but it seem like it took 212.83 seconds to parse and 5.185 seconds to solve?

```
c CryptoMiniSat version 5.0.0
c compiled with non-gcc compiler
c -- header says num vars:         516048
c -- header says num clauses:   390166280
c -- clauses added: 390166280
c -- xor clauses added: 0
c -- vars added 516048
c  Parsing time: 212.83       s
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 tri: 0 (stamp: 0, cache: 0) T: 0.37 T-out: Y w-visit: 9833
c --> Executing strategy token: scc-vrepl
c --> Executing OCC strategy token(s): 'occ-backw-sub-str,occ-clean-implicit,occ-bve,'
c [clean] T: 5.1850 s
c [simp] mem usage for occur     47 MB
c [simp] Not linked in 0/1000 (0.00 %)
c [simp] mem usage for occur     39 MB
c [simp] Not linked in 0/0 (0.00 %)
c Mem for watch alloc      : 8326        MB (0.00      %)
c Mem for watch array      : 23          MB (0.00      %)
c --> Executing OCC strategy token: occ-backw-sub-str
c [sub] tri upI: 823488 subs w bin: 0 str w bin: 0 subs w tri: 0 str w tri: 0 tried: 306719 str: 0 0-depth ass: 0 T: 1.13 T-out: Y T-r: -0.00%
c [sub] rem cl: 0 tried: 10000/1000 (1000.0%) T: 0.02 T-out: N T-r: 97.96%
c [str] sub: 0 str: 0 tried: 3000/1000 (300.0)  T: 0.02 T-out: N T-r: 97.17%
c [occ-substr] sub_str_with sub: 0 str: 0 0-depth ass: 0 T: 0.00 T-out: N T-r: 100.00%
c --> Executing OCC strategy token: occ-clean-implicit
c --> Executing OCC strategy token: occ-bve
c Empty resolvent elimed: 0 T: 0.32 T-out: Y
c  #try to eliminate: 0
c  #var-elim: 0
c  #T-o: Y
c  #T-r: -0.00%
c  #T: 3.25
c [occur] 7.37 is overhead
c [occur] link-in T: 7.37 cleanup T: 0.00
c [scc] new: 1048 BP 195M T: 9.19
c [clean] T: 5.1090 s
c [vrep] vars 1048 lits 3137128 rem-bin-cls 4208 rem-tri-cls 0 rem-long-cls 0 BP 781M T: 14.45
c --> Executing strategy token: sub-str-cls-with-bin
c [clean] T: 5.2470 s
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 0.02 T-out: N T-r: 90.08%
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 0.03 T-out: N T-r: 74.96%
c [distill] cache-based irred--  cl tried     2000 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.05 T-out: N
c [distill] cache-based   red--  cl tried        0 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.00 T-out: N
c [consolidate] T: 0.00
c [extend] Extended 0 var-elim clauses
c ------- FINAL TOTAL SEARCH STATS ---------
c UIP search time          : 1.83        (0.67      % time)
c restarts                 : 10          (183.00    confls per restart)
c blocked restarts         : 0           (0.00      per normal restart)
c time                     : 1.83
c decisions                : 779190      (0.00      % random)
c propagations             : 5867739
c decisions/conflicts      : 425.79
c conflicts                : 1830        (997.82    / sec)
c conf lits non-minim      : 10956529    (5987.17   lit/confl)
c conf lits final          : 5986.40
c guess different          : 11          (0.60      % of confl)
c cache hit re-learnt cl   : 0           (0.00      % of confl)
c red which0               : 0           (0.00      % of confl)
c props/decision           : 0.00
c props/conflict           : 0.00
c 0-depth assigns          : 0           (0.00      % vars)
c probing time             : 0.00        (0.00      % time)
c OccSimplifier time       : 8.66        (3.18      % time)
c SCC time                 : 9.19        (3.37      % time)
c [scc] new: 1048 BP 195M  T: 9.19
c distill time             : 0.00        (0.00      % time)
c strength cache-irred time: 0.05        (0.02      % time)
c strength cache-red time  : 0.00        (0.00      % time)
c Conflicts in UIP         : 1830        (6.71      confl/TOTAL_TIME_SEC)
c Total time               : 272.62
c Mem used                 : 0.00        MB
s SATISFIABLE
v -1 -2 -3 -4 ............. 
```

My biggest problem with this is, I didn't direct the output to a file and my terminal was really lagging since I have a few hundred thousand variables being emitted (mostly negative). Will add a redirect now and run again
 :)
 :+1:

**Comment by a1880** [comment]
Try option --polar=false . This might speed-up the search for solutions with a majority of false variables.

**Comment by nmz787** [comment]
> Try option --polar=false . This might speed-up the search for solutions with a majority of false variables.

Hmm, I might need to wait until I can build with Boost on my own machine, as the binaries I am testing with from the Release page (`cryptominisat5_fewoptions_Win64.exe`) don't seem to have `--polar` as an option as it produces `ERROR! unknown flag --polar=false`

**Comment by a1880** [comment]
Yes, that's right. The released Windows binary is just a "simple" solver which is restricted to very few options.

**Comment by nmz787** [comment]
I got boost installed, set BOOST_ROOT env var, opened a "Visual C++ 2015 x64 Native Build Tools Command Prompt", typed the commands @msoos gave, after a lot of messing around I am able to get an EXE to be built and placed in `C:\Program Files\cryptominisat5\bin` but when I open it, it fails and errors with `The program can't start because cryptominisat5.dll is missing from your computer. Try reinstalling the program to fix this problem.`  I also see that the CMakeLists.txt doesn't seem to allow compiling Python extensions. I am not sure if this is because the CMake doesn't know how to generate files for Visual Studio 2008 (this is what Python 2.7 is compiled with). CMake is super-confusing and hard for me to understand, so I am struggling, but trying to make some progress.

**Comment by nmz787** [comment]
using `cryptominisat5_fewoptions_Win64.exe` from the Release page, is there a way to keep the program open, as I want to request many solutions from the solver, so I can sort them by harder-to-encode metrics and choose the 'best' one. Currently I generate a CNF text file, pass that to cryptominisat, then parse the stdout of that, negate the solution vars, append that to my clauses, and again call cryptominisat... doing this repeatedly. I can imagine loading all the clauses, and setting up the solver takes some time that I could be somehow saving to more quickly gather these solutions.

**Comment by nmz787** [comment]
I just saw the main github readme shows a different set of commands, after trying `cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 14 2015 Win64" -DSTATICCOMPILE=ON` I got a program that didn't crash with the DLL not found error.

Running with help I get:
```
C:\Program Files\cryptominisat5\bin>cryptominisat5_simple.exe -h
USAGE: cryptominisat5_simple.exe [options] <input-file>

  where input is plain DIMACS.

OPTIONS:

  --verb          = [0...] Sets verbosity level. Anything higher
                           than 2 will give debug log
  --drat          = {0,1}  Sets whether DRAT should be dumped to
                           the console as per SAT COMPETITION'14 guidelines
  --threads       = [1...] Sets number of threads
```

Is this to be expected with BOOST libs? Or should I see more options? Any suggestions for next steps?


Here is my cmake output:
```
c:\Users\myUserName\Documents\cryptominisat\bld>set BOOST_ROOT=C:\local\boost_1_61_0
c:\Users\myUserName\Documents\cryptominisat\bld>rm -r *
c:\Users\myUserName\Documents\cryptominisat\bld>cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 14 2015 Win64" -DSTATICCOMPILE=ON ..
-- Doing a Release build
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- build type is Release
-- Performing Test HAVE_FLAG_-fno-stack-protector
-- Performing Test HAVE_FLAG_-fno-stack-protector - Failed
-- No pthread will be used
-- GIT hash found: f64d2e87e5b47b14d59508db7c1af63d7ec10fc9
-- PROJECT_VERSION: 5.0.0
-- PROJECT_VERSION_MAJOR: 5
-- PROJECT_VERSION_MINOR: 0
-- PROJECT_VERSION_PATCH: 0
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Not compiling detailed statistics. Leads to faster system
-- Valgrind Prefix:
-- Could NOT find VALGRIND (missing:  VALGRIND_INCLUDE_DIR VALGRIND_PROGRAM)
-- Cannot find valgrind or it's disabled, we will not be able to mark memory pool objects as undefined
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Could NOT find m4ri (missing:  M4RI_LIBRARIES M4RI_INCLUDE_DIRS)
CMake Warning at CMakeLists.txt:365 (MESSAGE):
  Did not find M4RI, XOR detection&manipulation disabled


-- All defines at startup:  -DNDEBUG -D_FORTIFY_SOURCE=0 -DUSE_PTHREADS
-- Found PythonInterp: C:/Python27_64compiling/python.exe (found suitable version "2.7.12", minimum required is "2.7")
-- Found PythonLibs: C:/Python27_64compiling/libs/python27.lib (found suitable version "2.7.12", minimum required is "2.7")
CMake Warning at CMakeLists.txt:423 (message):
  Cannot find python interpreter, libs and header files, cannot build python
  interface


-- Only building executable with few command-line options because the boost program_options library were not available
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
CMake Warning at CMakeLists.txt:485 (message):
  Testing is disabled


-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/myUserName/Documents/cryptominisat/bld

```

**Comment by nmz787** [comment]
Hmm, maybe I have the wrong version of Boost, re-compiling for x64, here is the last command, seems to be getting closer:
`c:\Users\ntmccork\Documents\cryptominisat\bld2>cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 14 2015 Win64" -DSTATICCOMPILE=ON -DBoost_PROGRAM_OPTIONS_LIBRARY_RELEASE="C:\local\boost_1_61_0\libs\boost_program_options-vc100-mt-gd-1_61.lib" ..`

**Comment by msoos** [comment]
the "_simple" executable doesn't make use of boost. So there you got the executable that doesn't use boost. That's a huge step forward! You can now essentially build the normal one, just take the main.cpp and compile it with boost libraries linked in :) If you can find a way to do that, that'd be awesome! You just have to take a look at how the cryptominisat5_simple.exe is created and tweak it to create the cryptomnisat5.exe from the main.cpp and using boost! Good luck!

**Comment by nmz787** [comment]
I tried commenting this out from CMakeFiles.txt
```
# if (STATICCOMPILE)
#     set(ONLY_SIMPLE ON)
# endif()
```
but no matter what I do regarding compiling boost... I just get some link error... this is the latest:
` LINK : fatal error LNK1104: cannot open file 'libboost_program_options-vc140-mt-s-1_61.lib' [C:\Users\ntmccork\Documents\cryptominisat\bld2\cmsat5-src\cryptominisat5.vcxproj]`

I am not really going about this in any intelligent fashion, I am brute force trying random paths... it's been about 8 hours of getting nowhere so far (at least other than the 'simple' binary).

**Comment by msoos** [comment]
That sounds pretty good to me :) I think you just need to make sure that library file is there and can be opened and read by the user compiling!

**Comment by msoos** [comment]
I'm sorry, I still don't have windows  and can't debug. I wish I could. I'm closing this now until I get to have a machine where I could debug this.

Mate
