### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by Storyyeller** [msoos/cryptominisat#347]
The readme list the following code

    //We need 3 variables
    solver.new_vars(3);

    //Let's use 4 threads
    solver.set_num_threads(4);

However, if I try to actually use it, I get the error
ERROR: You must first call set_num_threads() and only then add clauses and variables

**Comment by msoos** [comment]
Thanks a ton for this! I'm sorry. I fixed it and I added some extra tests so it won't happen again :)

Cheers and please let me know if and how CryptoMiniSat helped!

Mate
