### ISSUE TITLE
Add some info in final statistic, if "c [occ-xor]" (via USE_GAUSS=on) was helpful?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#349]
Would it be possible/helpful to add some hint in final statistic if "c [occ-xor]"
(via USE_GAUSS=on) was helpful?
At the moment I can only collect the log output and search for "c [occ-xor]"
to see if there was some progress using it or can be skipped next time.

**Comment by msoos** [comment]
Sorry, I'm too busy doing stuff that can impact the solving in a positive way. You can always recover this information by grepping the output. You can get some extra information from `--verbstat 1` but it will not print anything about xors. Grepping is easy, though :) Good luck!
