### ISSUE TITLE
Dies with SIGFPE

### ISSUE THREAD

**Issue by sliedes** [msoos/cryptominisat#351]
cryptominisat5 -t4 aes-top-22-symmetryBreaking.dimacs, where the file is from http://aprove.informatik.rwth-aachen.de/eval/slp.zip , died with Floating point exception after running for some (< 12) hours.

Here's the last lines of the output:

c [distill-with-bin-ext] bintri-based lit-rem: 274 cl-sub: 6
c [distill-with-bin-ext] cache-based lit-rem: 4172 cl-sub: 0
c [distill-with-bin-ext] T: 9.91 T-out: N T-r: 100.00%
c [distill] cache-based irred--  cl tried    21888 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.10 T-out: N
c [distill] cache-based   red--  cl tried  1018482 cl-sh   988 cl-rem   14 lit-rem   4446 T: 17.98 T-out: N
c --> Executing strategy token: distill-cls
c [distill] longirred tried: 10944/10944 cl-r:0 lit-r:0 T: 3.87 T-out: N T-r: 0.00%
c [distill] tri+long useful: 0/10944/10944 lits-rem: 0 0-depth-assigns: 0 T: 3.87 T-out: N
c --> Executing strategy token: scc-vrepl
c [scc] new: 0 BP 0M T: 0.00
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 tri: 0 (stamp: 0, cache: 0) T: 0.02 T-out: N w-visit: 14302
c --> Executing strategy token: str-impl
c [impl str] lit bin: 0 lit tri: 0 (by tri: 0) (by stamp: 0) set-var: 0 T: 0.01 T-out: N T-r: 100.00% w-visit: 14302
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 tri: 0 (stamp: 0, cache: 0) T: 0.02 T-out: N w-visit: 14302
c --> Executing strategy token: str-impl
c --> Executing OCC strategy token(s): 'occ-backw-sub-str,occ-clean-implicit,occ-bve,occ-bva,occ-xor,'
c [clean] T: 0.0530 s
c [simp] mem usage for occur      1 MB
c [simp] Not linked in 0/10944 (0.00 %)
c [simp] mem usage for occur    107 MB
c [simp] Not linked in 0/509224 (0.00 %)
c Mem for watch alloc      : 74          MB (6.52      %)
c Mem for watch array      : 0           MB (0.03      %)
c --> Executing OCC strategy token: occ-backw-sub-str
c [sub] tri upI: 2712 subs w bin: 0 str w bin: 0 subs w tri: 4 str w tri: 1 tried: 8599793 str: 0 0-depth ass: 0 T: 0.99 T-out: N T-r: 54.17%
c [sub] rem cl: 88 tried: 5406060/540606 (1000.0%) T: 35.04 T-out: N T-r: 100.00%
c [str] sub: 10 str: 294 tried: 1621818/540606 (300.0)  T: 29.25 T-out: N T-r: 100.00%
c [occ-substr] sub_str_with sub: 0 str: 0 0-depth ass: 0 T: 0.01 T-out: N T-r: 100.00%
c --> Executing OCC strategy token: occ-clean-implicit
c --> Executing OCC strategy token: occ-bve
c Empty resolvent elimed: 0 T: 0.04 T-out: N
c [occ-substr] sub_str_with sub: 0 str: 0 0-depth ass: 0 T: 0.00 T-out: N T-r: 100.00%
c [occ-bve] process impls_sub_lits  T: 0.00
c [occ-bve] iter v-elim 0
c  #try to eliminate: 6650
c  #var-elim: 0
c  #T-o: N
c  #T-r: 100.00%
c  #T: 0.43
c [occur] 0.41 is overhead
c [occur] link-in T: 0.41 cleanup T: 0.00
c --> Executing OCC strategy token: occ-bva
c [impl sub] bin: 0 tri: 0 (stamp: 0, cache: 0) T: 0.10 T-out: N w-visit: 14302
c [occ-bva] added: 0 simp: 0 2lit: Y T: 2.53 T-out: N T-r: 100.00%
c --> Executing OCC strategy token: occ-xor
c [occ-xor] found    912 avg sz  3.0 T: 5.77 T-out: N
c Sum vars in blocks: 1027
c [occ-xor] cut into 8 blcks.  Vars in blcks: 1027 T: 0.00
c [occ-xor] extr info.  unit: 0 bin: 0 0-depth-ass: 0 T: 0.00
c [impl str] lit bin: 0 lit tri: 0 (by tri: 0) (by stamp: 0) set-var: 0 T: 0.02 T-out: N T-r: 100.00% w-visit: 14302
c --> Executing strategy token: cache-clean
c [cache] cleaned. Updated:       0 K Cleaned:       0 K Freed:       0 K T: 0.00
c --> Executing strategy token: sub-str-cls-with-bin
c [clean] T: 0.0580 s
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 0.04 T-out: N T-r: 100.00%
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 9.16 T-out: N T-r: 100.00%
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 0.04 T-out: N T-r: 100.00%
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 17 cl-sub: 0
c [distill-with-bin-ext] T: 10.00 T-out: N T-r: 100.00%
c [distill] cache-based irred--  cl tried    21888 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.08 T-out: N
c [distill] cache-based   red--  cl tried  1018276 cl-sh     5 cl-rem    0 lit-rem     17 T: 19.16 T-out: N
c --> Executing strategy token: distill-cls
c [distill] longirred tried: 10944/10944 cl-r:0 lit-r:0 T: 5.27 T-out: N T-r: 0.00%
c [distill] tri+long useful: 0/10944/10944 lits-rem: 0 0-depth-assigns: 0 T: 5.27 T-out: N
c --> Executing strategy token: scc-vrepl
c [scc] new: 0 BP 0M T: 0.00
c --> Executing strategy token: check-cache-size
c --> Executing strategy token: renumber
c [cache] cleaned. Updated:       0 K Cleaned:       0 K Freed:       0 K T: 0.00
c [consolidate] T: 0.00
c clause size stats. size4: 4995 size5: 2187 larger: 3762
c 300-long burst search  learnt units:0 learnt bins: 0 T: 0.53
c 61931 32106K    6650 10944 16436  7493    6.07    3.75  509K   21K  7184  7395   15.05   14.72
c 61940 32113K    6650 10944 16436  7493    6.07    3.75  509K   28K  7184  7395   15.39   15.05
c [DBclean] marked: 15000 ttl:2003 locked_solver:2 T: 0.02
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c 61944 32120K    6650 10944 16436  7493    6.07    3.75  509K   21K  7184  7395   14.93   14.60
c 61944 32127K    6650 10944 16436  7493    6.07    3.75  509K   28K  7184  7395   15.33   14.99
c [DBclean] marked: 15000 ttl:3149 locked_solver:6 T: 0.01
c 61944 32134K    6650 10944 16436  7493    6.07    3.75  509K   23K  7184  7395   15.27   14.93
c [DBclean] marked: 15000 ttl:3949 locked_solver:6 T: 0.01
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c 61944 32141K    6650 10944 16436  7493    6.07    3.75  509K 19023  7184  7395   14.96   14.62
c 61944 32148K    6650 10944 16436  7493    6.07    3.75  509K   25K  7184  7395   15.32   14.98
c [DBclean] marked: 15000 ttl:4132 locked_solver:8 T: 0.01
c [mem] Consolidated memory  old size 13703K new size 10612K T: 0.06
c 61944 32155K    6650 10944 16436  7493    6.07    3.75  509K   21K  7184  7395   14.99   14.66
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c 61944 32162K    6650 10944 16436  7493    6.07    3.75  509K   28K  7184  7395   15.33   14.99
c [DBclean] marked: 15000 ttl:2927 locked_solver:7 T: 0.01
c 61946 32169K    6650 10944 16436  7493    6.07    3.75  509K   22K  7184  7395   15.06   14.73
c 61961 32176K    6650 10944 16436  7493    6.07    3.75  509K   29K  7184  7395   15.60   15.25
c [DBclean] marked: 15000 ttl:2472 locked_solver:3 T: 0.01
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c 61980 32183K    6650 10944 16436  7493    6.07    3.75  509K   23K  7184  7395   15.28   14.94
c [DBclean] marked: 15000 ttl:2746 locked_solver:7 T: 0.01
c 61980 32190K    6650 10944 16436  7493    6.07    3.75  509K 18117  7184  7395   14.85   14.52
c 61980 32197K    6650 10944 16436  7493    6.07    3.75  509K   24K  7184  7395   15.14   14.80
c [DBclean] marked: 15000 ttl:3043 locked_solver:5 T: 0.02
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c 61980 32204K    6650 10944 16436  7493    6.07    3.75  509K 19297  7184  7395   14.60   14.27
c 62018 32211K    6650 10944 16436  7493    6.07    3.75  509K   26K  7185  7395   15.06   14.73
c [DBclean] marked: 15000 ttl:2259 locked_solver:9 T: 0.01
c [mem] Consolidated memory  old size 13551K new size 10551K T: 0.06
c 62048 32218K    6650 10944 16436  7493    6.07    3.75  509K   20K  7185  7395   14.98   14.65
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c 62051 32225K    6650 10944 16436  7493    6.07    3.75  509K   26K  7186  7395   15.41   15.07
c [DBclean] marked: 15000 ttl:2853 locked_solver:3 T: 0.02
c 62051 32232K    6650 10944 16436  7493    6.07    3.75  509K   21K  7186  7395   15.30   14.96
c 62051 32239K    6650 10944 16436  7493    6.07    3.75  509K   28K  7186  7395   15.82   15.47
c [DBclean] marked: 15000 ttl:3399 locked_solver:6 T: 0.02
c  rest  conf freevar  IrrL  IrrT  IrrB l/longC  l/allC RedL0 RedL1  RedT  RedB l/longC  l/allC
c 62051 32246K    6650 10944 16436  7493    6.07    3.75  510K   23K  7186  7395   15.51   15.16
c [DBclean] marked: 15000 ttl:3190 locked_solver:2 T: 0.01
c 62051 32253K    6650 10944 16436  7493    6.07    3.75  510K 18470  7186  7395   15.18   14.84
c recursive minimization cost OK: 832Kcost/(% lits removed)
c --> Executing strategy token: handle-comps
c [clean] T: 0.0640 s
c [comp] Found component(s): 1 BP: 1.82M T: 0.07 T-out: N T-r: 100.00%
c --> Executing strategy token: scc-vrepl
c [scc] new: 0 BP 0M T: 0.01
c --> Executing strategy token: cache-clean
c [cache] cleaned. Updated:       0 K Cleaned:       0 K Freed:       0 K T: 0.00
c --> Executing strategy token: cache-tryboth
c [bcache]  0-depth ass: 0 BXprop: 0 T: 0.01
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 tri: 0 (stamp: 0, cache: 0) T: 0.02 T-out: N w-visit: 14302
c --> Executing strategy token: intree-probe
c [clean] T: 0.0700 s
c [scc] new: 0 BP 0M T: 0.01
c [clean] T: 0.0690 s
c [vrep] vars 0 lits 0 rem-bin-cls 0 rem-tri-cls 0 rem-long-cls 0 BP 1M T: 0.15
Floating point exception

**Comment by msoos** [comment]
First of all, thanks for the detailed bug report!

There is definitely a (minor) issue you caught :( The problem is that the above is with multi-threading enabled so I cannot reproduce it in a straightforward way. I'll try. In the meanwhile, can you please try running the system under gdb next time? You can do it like this:

```
gdb cryptominisat5
(gdb) run -t4 aes-top-22-symmetryBreaking.dimacs
[...]
(gdb) generate-core-file
Saved corefile core.xyz
```

I will then need the (compressed) corefile `core.xyz` and I can debug :) In case that is a lot of hassle, you can always just disable the check by commenting this out:

```
feenableexcept(FE_INVALID   |
                   FE_DIVBYZERO |
                   FE_OVERFLOW
    );
```

But I'd prefer the GDB option of course :) I am doing some debugging in the meanwhile, maybe I can find it too!

Thanks for the detailed report again,

Mate

**Comment by msoos** [comment]
Wow, so this was not easy! I ran the thing for about 10h on my machine and I bumped into the same issue. Having had gdb running, though, I could examine the state and I actually found a really important bug. Well done! So it should be fixed now :) Thanks again!
