### ISSUE TITLE
new_vars is not checked for overflow

### ISSUE THREAD

**Issue by Storyyeller** [msoos/cryptominisat#353]
Adding vars to a solver does not check for overflow or for the maximum variable count (1<<28). The variable count is only checked when you try to create a clause or call solve(). 

This means that stuff like
solver.new_vars(1<<30);
solver.new_vars(1<<30);
solver.new_vars(1<<30);
solver.new_vars(1<<30);

runs without error. nVars() is essentially meaningless in this case.

**Comment by msoos** [comment]
That is later checked when clauses are actually inserted:

```
void CNF::new_vars(const size_t n)
{
    if (nVars() + n >= 1ULL<<28) {
        cout << "ERROR! Variable requested is far too large" << endl;
        std::exit(-1);
    }
```

Of course if you add more than 2**32 variables, it will overflow and the check will not trigger. However, that should be anticipated as the number of varibles returned is a uint32_t.

**Comment by msoos** [comment]
Okay, I was too defensive here, you had a point :) I fixed it with:

https://github.com/msoos/cryptominisat/commit/bff5e4586878363aa2df00396a4c95ccbfd7adf1

I also added tests so we catch if this kind of thing happens by accident. Thanks!

**Comment by msoos** [comment]
OK, fixed, thanks!
