### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by Storyyeller** [msoos/cryptominisat#356]
Under testing, it says to run git submodules init. This should be submodule, not submodules.

Also, make test doesn't seem to work.
> make: *** No rule to make target `test'.  Stop.

**Comment by msoos** [comment]
Thanks!

**Comment by Storyyeller** [comment]
Do you know how to actually run tests? As mentioned, make test didn't work for me.

**Comment by msoos** [comment]
Please read the TravisCI scripts (.travisci). It runs there, you can even see the full logs if you click on the TravisCI button on the main page. Good luck!
