### ISSUE TITLE
Value of maxTime (and maxConfl) seems to get lost, when calling Solver::solve() multiple times?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#363]
When  calling Solver::solve() multiple times, e.g. (I assume, not tested) when searching for 
multiple solutions or multiple times, because of working with assumptions,
the timeout is not more active. Assumption (when not UNSAT/SAT) is perhaps tested endless, 
instead of given timeout value, when it is called more than once.

After adding some debug output, I think I have found the reason. There are the following lines
at end of Solver::solve()

```
    conf.maxConfl = std::numeric_limits<long>::max();
    conf.maxTime = std::numeric_limits<double>::max();
```

Wouldn't it be not better to set it back to initial value instead of using max for both of them,
which is like disabling the checks. I agree that each call to solve must get it fresh values,
but not sure if max values are the best one...

Or do I need to set all (which? how?) config values again and again, when calling solve()?
Before calling solve? Or perhaps better after returning from solve?
Use a copy of conf to replace meanwhile changed values?
(BTW: testing this with/inside cryptominisat executable, not CMS library)

**Comment by msoos** [comment]
It should be set here:

```
//Set timeout information
    if (data->timeout != std::numeric_limits<double>::max()) {
        for (size_t i = 0; i < data->solvers.size(); ++i) {
            Solver& s = *data->solvers[i];
            s.conf.maxTime = cpuTime() + data->timeout;
        }
    }
```

in cryptominisat.cpp. It's called when `data->timeout` is set, which is set by `set_timeout_all_calls`.

Can you please tell me what you see inside conf.maxTime that is not correct?

Thanks,

Mate

**Comment by capiman** [comment]
First time, I see in conf.maxTime the value which I have set via command line --maxTime,
e.g. 120 seconds. After one round I see a very big number, which goes over 2 lines, seems to be
double max.

set_timeout_all_calls seems to be only used for scalmc? Or have I overseen, where it is called?

From debug output added to code you mentioned above, I reach calc in every round, but I would say, data->timeout seems to be never unequal double max, therefore not reaching "for" and also not assignment to s.conf.MaxTime.
So it still has the old value which was set to double max.
(PS: I tried to set conf.MaxTime to cpuTime() + 120.0 and then timeout works. But is only a quick hack...)

**Comment by capiman** [comment]
You can reproduce it in the following way:
Add a debug output into Solver::solve() like 
```
cout << "Timeout=" << conf.maxTime << endl;
```

Then call it via 
cryptominisat5 --maxsol=3 --input=6x6.cnf --maxtime=120

First output is 120, second and all other outputs are very big number.

**Comment by msoos** [comment]
Oh, so it's the main.cpp usage. It should not be used with multiple-solution (--maxsol). I will assert-fail on that so it crashes immediately instead of giving weird results. Thanks!

**Comment by msoos** [comment]
I don't see the reason why you'd limit time when doing multiple solutions. It's only mostly a hack anyway. I'm sorry, but I just don't see the use-case here. I'm closing this.
