### ISSUE TITLE
 OccSimplifier::test_elim_and_fill_resolvents() takes long

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#366]
I am currently debugging an error, where it seems like I enter
OccSimplifier::test_elim_and_fill_resolvents(), but never return...
(or it takes so long, and there is no further output during this long action)

Special things: Using very big CNF, 2 threads, --intree=0 --comps=0.
I see each thread is going the same way (but different vars) into test_elim_and_fill_resolvents 
and both are not returning.
Problem occurs first after around 20 minutes, but already reproduced it 3 times with 3 runs.
gdb is unfortunately too slow. CNF too big to transfer.

Notice for me: Using "766 sky uniq".

```
c  4106 1204K  106814 1040K 2129K  576M    4.10    2.01  6930 19025   820     4 2855.83 2768.05
c --> Executing strategy token: handle-comps
c --> Executing strategy token: scc-vrepl
c [scc] new: 1 BP 312M T: 1.80
c --> Executing strategy token: cache-clean
c [cache] cleaned. Updated:       0 K Cleaned:       0 K Freed:       0 K T: 0.46
c --> Executing strategy token: cache-tryboth
c [bcache]  0-depth ass: 0 BXprop: 393216 T: 1.67
c --> Executing strategy token: sub-impl
c [impl sub] bin: 10885 tri: 0 (stamp: 0, cache: 0) T: 0.06 T-out: Y w-visit: 3
c --> Executing strategy token: intree-probe
c --> Executing strategy token: probe
c [clean] T: 6.5170 s
c [probe] lits : 83.12M act vars: 106.81K BP+HP todo: 160.00M
c [probe] NumProps after perf multi: 80.00M after numcall multi: 154.65M (<- final)
c [probe] 0-depth assigns: 0 bsame: 0 Flit: 0 Visited: 109830/213628(51.4%)
c [probe] probed: 5560(2.6%) hyperBin:0 transR-Irred:0 transR-Red:0
c [probe] BP: 92.0M HP: 0.0M T: 2.01 T-out: Y T-r: -0.00%
c [probe] time spent updating cache during probing: 0.0%
c --> Executing strategy token: sub-str-cls-with-bin
c [clean] T: 6.5080 s
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 3
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 0.08 T-out: Y T-r: -0.01%
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 0.15 T-out: Y T-r: -0.01%
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 0 cl-sub: 2
c [distill-with-bin-ext] cache-based lit-rem: 0 cl-sub: 0
c [distill-with-bin-ext] T: 0.06 T-out: Y T-r: -0.09%
c [distill-with-bin-ext] stamp-based lit-rem: 0 inv-lit-rem: 0 stamp-cl-rem: 0
c [distill-with-bin-ext] bintri-based lit-rem: 84248 cl-sub: 0
c [distill-with-bin-ext] cache-based lit-rem: 21815 cl-sub: 0
c [distill-with-bin-ext] T: 0.11 T-out: Y T-r: -0.04%
c [distill] cache-based irred--  cl tried     1170 cl-sh     0 cl-rem    5 lit-rem      0 T: 0.14 T-out: Y
c [distill] cache-based   red--  cl tried     3204 cl-sh   264 cl-rem    0 lit-rem 106063 T: 0.26 T-out: Y
c --> Executing strategy token: distill-cls
c [distill] longirred tried: 494/1040277 cl-r:1 lit-r:1 T: 0.60 T-out: Y T-r: 100.13%
c [distill] tri+long useful: 1/494/1040278 lits-rem: 1 0-depth-assigns: 0 T: 0.60 T-out: Y
c --> Executing strategy token: scc-vrepl
c [scc] new: 1 BP 315M T: 1.81
c --> Executing strategy token: sub-impl
c [impl sub] bin: 13692 tri: 0 (stamp: 0, cache: 0) T: 0.07 T-out: Y w-visit: 6
c --> Executing strategy token: str-impl
c [impl str] lit bin: 0 lit tri: 0 (by tri: 0) (by stamp: 0) set-var: 0 T: 0.90 T-out: Y T-r: -0.00% w-visit: 5954
c --> Executing strategy token: sub-impl
c [impl sub] bin: 10537 tri: 0 (stamp: 0, cache: 0) T: 0.06 T-out: Y w-visit: 3
c --> Executing strategy token: str-impl
c --> Executing OCC strategy token(s): 'occ-backw-sub-str,occ-clean-implicit,occ-bve,occ-bva,occ-xor,'
c [clean] T: 6.5180 s
c [simp] mem usage for occur     73 MB
c [simp] Not linked in 0/1040277 (0.00 %)
c [simp] mem usage for occur     24 MB
c [simp] Not linked in 1305/6923 (18.85 %)
c Mem for watch alloc      : 11154       MB (0.00      %)
c Mem for watch array      : 5           MB (0.00      %)
c --> Executing OCC strategy token: occ-backw-sub-str
c [sub] tri upI: 245140 subs w bin: 0 str w bin: 2 subs w tri: 0 str w tri: 0 tried: 1075951 str: 0 0-depth ass: 0 T: 0.51 T-out: Y T-r: -0.00%
c [sub] rem cl: 30 tried: 81937/1067258 (7.7%) T: 0.16 T-out: Y T-r: -0.00%
c [str] sub: 14 str: 30 tried: 46110/1067258 (4.3)  T: 0.21 T-out: Y T-r: -0.00%
c [occ-substr] sub_str_with sub: 1 str: 0 0-depth ass: 0 T: 0.00 T-out: N T-r: 99.98%
c --> Executing OCC strategy token: occ-clean-implicit
c --> Executing OCC strategy token: occ-bve
c Empty resolvent elimed: 0 T: 0.07 T-out: Y
c MMMM Just before 1. loop of OccSimplifier::eliminate_vars 1 710305 250585382
c MMMM Just in 1. loop of OccSimplifier::eliminate_vars 1 710305 250585382
c MMMM Inside 2. loop of OccSimplifier::eliminate_vars var=15095
c MMMM Inside 2. loop of OccSimplifier::eliminate_vars Pos X1
c MMMM Inside 2. loop of OccSimplifier::eliminate_vars Pos X3
c MMMM I am in OccSimplifier::maybe_eliminate var=15095
c MMMM I am in OccSimplifier::maybe_eliminate Pos A1
c MMMM Just before 1. loop of OccSimplifier::eliminate_vars 1 1014733 250945229
c MMMM Just in 1. loop of OccSimplifier::eliminate_vars 1 1014733 250945229
c MMMM Inside 2. loop of OccSimplifier::eliminate_vars var=15095
c MMMM Inside 2. loop of OccSimplifier::eliminate_vars Pos X1
c MMMM Inside 2. loop of OccSimplifier::eliminate_vars Pos X3
c MMMM I am in OccSimplifier::maybe_eliminate var=15095
c MMMM I am in OccSimplifier::maybe_eliminate Pos A1
c
```

**Comment by capiman** [comment]
Just saw "BXprop: 393216"???

**Comment by msoos** [comment]
Unfortunately, I cannot support CNFs that have over half a billion(!) binary clauses. That's too much for any solver and so I can't fix this for you. In case you find a way of doing bogoprop counting that is more accurate and will time out on this (and won't impact other things), that's great. However, instead of that, I suggest you switch off variable elimination (`--varelim 0`) or just put a check that if there are more than 300 million binary clauses, then turn off varelim automatically. I will be happy to merge that patch if you send it to me as a pull request.

Please give me a pull request with the 300M limit and I'll be happy to merge it :) Thanks!

**Comment by capiman** [comment]
I think I have found the "problem":
In https://github.com/msoos/cryptominisat/blob/master/src/occsimplifier.cpp#L1757
there are two calls to get positive and negative clauses. They are multiplied each other
and check against a cutoff value.
solver->conf.varelim_cutoff_too_many_clauses has a default value of 2000.
totalCls of HeuristicData ( see here https://github.com/msoos/cryptominisat/blob/2daecf0c2b1c027ad72bc0adc5ca755b4426fa85/src/occsimplifier.h#L458 )
returns an uint32_t. In my error case both values were 524288 which seem to generate an overflow,
not triggering the return statement. Then it continues to two loops in each other, 
each is done 524288 times and also each steps takes some time.
So the whole calculation just took to long.

I think it can be solved by casting the returned value (of totalCls) to uint64_t (or similar)
before doing the multiplication and comparison. Local test was successful.
I was able to continue after the problem.

Minor thing:
https://github.com/msoos/cryptominisat/blob/master/src/occsimplifier.cpp#L1851
There are 3 places where a multiplication with 3 is done. Two of them are
casted with (int), the third one in the middle has no cast.

**Comment by msoos** [comment]
Thanks, that was very helpful! It's been fixed :) Crap, you did do a really good job, and I was very dismissive. Sorry about that :( I'll try my best to be more attentive next time.

**Comment by msoos** [comment]
Can you please check if this fixes the issue? Please close if it does!

**Comment by capiman** [comment]
I will retest (could take some days, but I think, I have similar working in local version
and in my opinion your changes looks good.)

Perhaps two things, hopefully (at least the first) easy for you to clarify:

1) When running with multiple threads, do we have 1 or more instances of OccSimplifier?
I think it is only one. How about "global" variables (variables in instance of the class)?
When running with 2 threads, can both threads access any function any time
or is there some synchronisation? I think I have seen a vector "dummy" ("dummy" is used multiple
times with different types...). Where I am not sure is if it could not be accessed from different
threads at the same time?

2) This is just a behaviour, I want to share. Don't know if it is a bug or ok...
Can you describe a bit how "BXprop: 393216" is detected? Looks to be cache, implcache?
Where does it come from?
As you have seen I have multiple 100 Mega Binaries in this CNF. 
Suddenly this algo gives me a lot of irred binaries, 
like additional 100, 200 or even 800 mega irred bins in one step/line of output.
This takes so much memory (also as CNF) that I assume something is wrong.
It is luck and disaster at the same time :-)
I now went back before I got the binaries and turned caching off (--cache=0).
But it is just a test, don't know yet how to handle it.
BTW: Even with big CNFs I get red binaries which fully make sense, so I think
calculation of even such big CNFs is not that bad.

**Comment by msoos** [comment]
1) There are two solvers when there are two threads. They share nothing in common except DataSync, where they synchronise data.

2) BXProp is fine -- it will run SCC afterwards and then variable replacement, which will replace the variables and these binary clauses should all go away. It adds these clauses only so that SCC can find them and remove them. It should be OK.
