### ISSUE TITLE
Make it possible to compile python bindings without CMake.

### ISSUE THREAD

**Issue by arrowd** [msoos/cryptominisat#367]
Preprocessing done by CMake on `setup.py.in` is mostly unnecessary, but it causes some [inconveniences for packagers](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211460#c1). Here is what we are currently doing to avoid that: https://svnweb.freebsd.org/ports/head/math/py-cryptominisat/files/patch-setup.py.in?view=markup

Could it be possible to convert `setup.py.in` into a plain `setup.py` ready to be consumed by PyPi?

**Comment by msoos** [comment]
First of all, thanks for the heads up and the work! I am having trouble here, because this thing is supposed to work under 4 operating systems: Linux, Windows, MacOS, and FreeBSD. I can't possibly do that without some magic. CMake does a lot of the heavy-lifting and I love it for that. Is it an issue to keep that patch around for FreeBSD? I can add it to the source code if you feel like that makes sense. Unfortunately, I can't test it though, but I can try to make sure it at least applies cleanly, though I haven't changed that file for a while. Is there some kind of compromise we can do maybe? Thanks!

Mate

**Comment by arrowd** [comment]
This is what i came out with: https://github.com/arrowd/cryptominisat/tree/python_without_cmake

With this i've managed to build python bindings as part of CMake build, as well as separate build against installed cmsat.

I'd like to see your comments on this.

**Comment by msoos** [comment]
Thanks! Here are some issues:
* Unfortunately, cmake 3.1 is a bit too new. Though I think it might work with 2.8.8 as well?
* I'm afraid it will not work on Mac OS X.

However! We can have both a version of both setup.py and setup.py.in in there somehow, so it would work anyway. I'll think about how to best keep them both, so when cmake is not there, it would still work.

By the way, how is cryptominisat compiled without cmake? I'm wondering if removing cmake dependency  from the setup.py is useful, as cryptominisat itself would still need cmake :S

**Comment by arrowd** [comment]
> Though I think it might work with 2.8.8 as well?

Alas, no. The `-E env` command first appeared in CMake 3.1.

> I'm afraid it will not work on Mac OS X.

Why do you think so?

> By the way, how is cryptominisat compiled without cmake?

Cmsat itself is compiled using CMake, of course, but we package python bindings separately from the mail package. Due to that, python bindings are compiled separately from cmsat and this is where CMake dependency kicks in. Having it only to pass some env vars is a bit of overkill.

**Comment by arrowd** [comment]
@msoos Any progress on this?

I can't test this on Mac OS X, since i don't have it, but i'll be glad to help if you post exact errors.

**Comment by msoos** [comment]
I'm sorry, but I don't have time to work on CryptoMiniSat. It will need to be done another time, maybe by someone else.

**Comment by msoos** [comment]
Soon this should work. It's almost working already :)

**Comment by msoos** [comment]
Sorry, but I realised this is not going to work. The build system is over >1000 lines of code and porting that to automake or anything else would be a lot of work. I cannot possibly do that work, my time is limited :(
