### ISSUE TITLE
Python 3 binding

### ISSUE THREAD

**Issue by tobiasBora** [msoos/cryptominisat#369]
Hello,

First thank you for your program. I would like to know, when I install cryptominisat with cmake it installs pycryptosat for Python2, but not for Python 3. Is there any reason not doing that ?

Thank you,

TobiasBora.

**Comment by msoos** [comment]
Not really. I'd be really happy if you could fix that! Just let me know how you did it, e.g. by cloning the repository, pushing your changes, then asking for a pull request:

https://help.github.com/articles/about-pull-requests/

Looking forward to the pull request!

Mate

**Comment by msoos** [comment]
So I guess this is fixed, right? I'm closing, but please re-open in case there are issues :) Thanks a LOT for the pull request, really great work!
