### ISSUE TITLE
Small bug in AddHash function for scalmc

### ISSUE THREAD

**Issue by ziqiaozhou** [msoos/cryptominisat#372]
I found a bug in AddHash function line 182, it should be "rhs=(randomBits[(independent_vars.size() + 1) \* i] == '1');" or  binary(..)  function should be modified to push back 0+(x & 1) instead of '0'+(x & 1). The result seems not affected by this problem, but I think it should be a bug

**Comment by msoos** [comment]
Thanks for looking at the code! I believe that '0' + (x&1) is different from 0 + (x & 1). Also, we are pushing back to a string, so pushing back 0 will not work. Hence, this is not a bug. Also note, that ord('0') returns 48.
