### ISSUE TITLE
Feature Request: Solving for min-Ones

### ISSUE THREAD

**Issue by ambasta** [msoos/cryptominisat#379]
Hi,

While the solver works brilliantly to find out a solution for a SAT problem, min-Ones is of great practical benefit for real world scenarios such as networks.

Additionally, for a subset of the min-ones problem the solution is Poly-APX-complete or better and it would be a great addition to cryptominisat

**Comment by msoos** [comment]
Sorry, but that's too specific. CryptoMiniSat is a SAT solver, it does not aim to solve all problems that are related to SAT. It is possible write a python/C++/C system that can do the min-ones problem based on research papers. If you do that and commit it as a standalone application using the cryptominisat library, I am happy to do a git merge!

Cheers and good luck,

Mate

**Comment by Storyyeller** [comment]
Can't you encode min-ones by just adding a few extra constraints and variables to a given SAT instance? It won't be as efficient as a dedicated solver, but you can do it if you need to.

**Comment by msoos** [comment]
I am sorry, but I cannot help with this. You need to read some literature, I am not an expert on min-ones.

Good luck!

Mate
