### ISSUE TITLE
Trouble compiling and installing Python API

### ISSUE THREAD

**Issue by TheRealNebus** [msoos/cryptominisat#380]
I'm trying to install the python API on my Lubuntu but I haven't been successful so far.
I've managed to install cryptominisat (version 5.0.1) without any issue following the instructions in the README file. The instructions on how to install the python API are unclear however. Here's what I've been trying to do so far after compiling and installing cryptominisat:

```
$ cd python
$ mkdir build
$ cd build
$ cmake ..
$ make -j4
```

I get the following error:

```
make[2]: *** No rule to make target '../libcryptominisat5', needed by 'build/timestamp'.  Stop.
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/python_interface.dir/all' failed
make[1]: *** [CMakeFiles/python_interface.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

What am I doing wrong?

Thank you in advance.

**Comment by msoos** [comment]
Thanks for the feedback! Yeah, you cannot really compile it like that. You have to have the python development headers and libraries installed and then you need to recompile CryptoMiniSat. I have updated the README in the python folder. Please take a look:

https://github.com/msoos/cryptominisat/tree/master/python

It should explain in detail how you are supposed to compile pycryptosat. Please try doing that, and come back here and give some feedback how it went :) In case it all went well, please close the issue! Thanks in advance,

Mate

**Comment by TheRealNebus** [comment]
The python-dev package was missing. It is working now, thank you very much! =)
