### ISSUE TITLE
Pycryptosat question

### ISSUE THREAD

**Issue by texasflood902** [msoos/cryptominisat#381]
Hello there! Had a quick question. Does pycryptosat, by any chance, allow variable freezing so that they don't get eliminated?

**Comment by msoos** [comment]
You don't need to freeze and thaw. Everything always works, your variables
will always appear to be there and it will always work. CryptoMiniSat is
not like other solvers, it needs no freezing and thawing and all. It just
works. Check it out :)

Mate

**Comment by msoos** [comment]
I'm closing because this is resolved and there was no feedback for over 2 months now :) Hope it works for you!
