### ISSUE TITLE
Switching Gaussian Elimination on and off

### ISSUE THREAD

**Issue by kash23** [msoos/cryptominisat#385]
Hi there,

I am having difficulty switching the Gaussian elimination on and off. I've made two builds, one that sets the parameter `-DUSE_GAUSS=ON` and one with `OFF`. However, it seems that both builds have` -DUSE_GAUSS` compiled. Is there some way to completely disable this feature, or perhaps limit it?

Thanks,
K

**Comment by a1880** [comment]
If you don't define `cmake` variable `USE_GAUSS` at all, support for Gaussian elimination should be omitted. I tried a recent `cryptominisat5 `and found no Gaussian features in the` --hhelp` output.

On `c++` level, the `c++` macro `USE_GAUSS` is undefined unless Gaussian elimination is explicitely configured.

You might want to add output statements in the `CMakeLists.txt` cmake source and in the `c++` code to actually see what's going on.

**Comment by msoos** [comment]
Axel is right. Please use a released version such as 5.0.1. Good luck!
