### ISSUE TITLE
XOR Logic Propagation

### ISSUE THREAD

**Issue by anma77** [msoos/cryptominisat#390]
seems that the older Version 2.9.6 could do better with CNF-Instances including XOR-Clauses.

**Comment by msoos** [comment]
I would need to test that with a bunch of examples. If you could supply say 10-20 examples that are worse in the 5.0 series than the 2.9.6 series, then I could fix it :) Note, about 10-20% difference is OK, since the 5.0 series does a lot better with general instances.

**Comment by anma77** [comment]
Are you interested in Small-AES-64-Bits Instances ? I have some with three rounds (simulating known text attacks). How many instances would you need?

**Comment by a1880** [comment]
I ran three examples in a loop with cryptomonisat2.9.5 and cryptomonisat5 (Windows, 64bit, 4 threads).
cms2.9.5 took 180+ seconds while cms5 took about 10 seconds.

No scientific comparison, but an indication that there is definitely some improvement.
My examples have quite a lot xor in them.

The CNFs and test scripts: [download](https://drive.google.com/open?id=0Bx3pMISAsrqSWlZ4OGhPVGJZNmc)

**Comment by msoos** [comment]
@a1880 Thanks for checking!

@anma77  What may be happening is that you didn't compile with "-DUSE_GAUSS=ON" when doing the cmake? You also may want to tune the gauss parameters? Like the max number of matrixes or forcing it to be "on" all the time. Could you please try that and get back here with the results? Just run "--hhelp" after you have compiled with "-DUSE_GAUSS=ON" and check for all the available options for guass. Looking forward to the results! Thanks in advance!

**Comment by anma77** [comment]
Dear Axel thank you for your input and the data. I will come back to it later.
Dear Mate, I did compile with  "-DUSE_GAUSS=ON". Max number of matrices I have tried also. I have to see how big are the instances of Axel. I am afraid that switches-configuration doesn't scale with the magnitude of the problem. With the 2.9.5 Version I could perfectly handle smaller problems which are now solvable in shorter time without "XORs" when using the  5 Version. The old Version used with --nosimplify was the best combination if parity clauses were in the CNF (XORs) as far as smaller problems are concerned. If for example I try to solve instances of the Format "p cnf 29440 136032" I have no luck. A big issue is also the ANF2CNF converter I use. When enabling XORs it is not possible to create a sparse CNF-Instance. It is always a combination of switches in the conversion to CNF and switches in the solver. 
Best regards,
A.

**Comment by anma77** [comment]
@a1880 Hello Axel, in your examples you have no explicit XOR clauses. XOR clauses begin with an X.
Can it be that your Instances have many solutions, at least more than one!? :-/
Yes, the improvement it obvious taking your Instances as an example!
Best regards and thank you!

**Comment by a1880** [comment]
@anma77 My examples contain 144 xor (with 11 inputs) each. They are not written as X clauses, but I figure that cryptomininsat quickly detects and utilizes such xor. Gaussian elimination is hopeless for my examples, as the xor do not share common inputs. I will re-run my tests with xcnf input. Stay tuned!

**Comment by a1880** [comment]
I regenerated my examples and re-ran the tests.

The results:

```
               cnf        xcnf
cms 5          15s        17s
cms 2.9.5      timeout    64s
```
It is a surprise, that xcnf is slower for my examples for cms5 compared to cnf.
As discussed [here](http://stackoverflow.com/questions/33599616/xor-parity-constraint-with-more-than-two-variables), the translation of xor expressions to cnf has many variants which are quite influental on the solution time.

For cms2.9.5 xcnf for my examples is much faster than cnf, but still almost four times slower than cms5.

The files: [download](https://drive.google.com/open?id=0Bx3pMISAsrqSUXcyMGdROUk1OTA)

**Comment by msoos** [comment]
I cannot fix this anymore than it has already been fixed. Propagation speed may be slightly slower, but it's overall faster and much-much more reliable and better.

**Comment by anma77** [comment]
it is a pity because I was about to send an example to demonstrate the opposite...

**Comment by msoos** [comment]
You are more than welcome to do so!

**Comment by anma77** [comment]
@Mate the file is "p cnf 13440 61472" (1.6 MB). How could I set it at your disposal? Thank you!

**Comment by msoos** [comment]
Email is best. But one file is very-very little evidence. We need at least 20, and they should all be UNSAT. We need to run them both with the old and the new solver. There is so much that changed that attributing that to the XORs would be like saying that Windows 10 is slower than DOS because of a BIOS setting. 2.9.x and 5.0 are _very_ different beasts. I would be _very_ surprised if the difference has anything to do with XOR clauses. It most likely has everything to do with solving strategies, which has changed radically. I would recommend you opening a new issue for that, attaching the CNF (if it's public) or sending me the CNF. However, trying to optimise to a single CNF is not a good idea, given that there are almost infinite number of problems out there. In any case, I can take a look, but 10-20% slowdown may be acceptable in some circumstances. For single files, slowdown is very possible and normal. Huge slowdowns (5-10x slower) is an issue, though. Please send me the file with the time-to-solve for both 2.9.x and 5.x and I'll see what I can do.

**Comment by anma77** [comment]
Mate thank you! We have different approaches because we deal with different problems. I focus on problems from cryptography. I accept your interpretation that explicit XOR is probably not the problem.
You can close the issue and I will come back again soon. Goodmorning!
