### ISSUE TITLE
building pycryptosat extension compile stalls

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#398]
I have just pulled the latest git update from the tree then attempted to run:
cd build
cmake -DUSE_GAUSS=ON ..
make

The last message I see is:

building 'pycryptosat' extension
gcc -pthread -fno-strict-aliasing -pipe -Wall -Werror=format-security -Wp, -fexceptions --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -pipe -Wall -Werror=format-security -Wp, -fexceptions --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBRARY_VERSION="5.0.1" -I/home/baston/kryptonite/git/cryptominisat/build/pycryptosat/src -I/home/baston/kryptonite/git/cryptominisat/build/pycryptosat -I/usr/include/python2.7 -c /home/baston/kryptonite/git/cryptominisat/build/pycryptosat/src/pycryptosat.cpp -o build/temp.linux-x86_64-2.7/home/baston/kryptonite/git/cryptominisat/build/pycryptosat/src/pycryptosat.o -pthread -DUSE_PTHREADS -flto -std=c++11 -Wno-unused-variable -Wno-unused-but-set-variable -fwrapv -march=native -mtune=native -Ofast -DNDEBUG

At this point the build process stalls.  Rerunning without the gaussian flag produces the same results.

if I run:

cpp pycryptosat.cpp

from the build directory, I receive a fatal error message that Python.h is missing.  Looking into /usr/include/python2.7 I see Python.h

Before this last git pull I was able to build the tool.  Are there any suggestions for a fix, or work-around?

Rob

**Comment by baston007** [comment]
Update

I have also downloaded git version d22ad94, unzipped the file, ran "cmake .", then "make".  This build also stalls at the same place.

Rob

**Comment by capiman** [comment]
Whch gcc are you using? 
gcc --version
Does it stall also if you execute above (long) command by hand?
If yes, can you execute 
gdb --xargs gcc -pthread -fno-strict-aliasing ...
(hopefully right syntax, from mind...)
Then "run". If it stalls, Ctrl-C and bt. You shall see a backtrace, hopefully with infos where it stalls.

**Comment by msoos** [comment]
I think I might have fixed this. Can you try the newest one please? Thanks!

**Comment by baston007** [comment]
I have just downloaded, via git pull, the latest version.  I have also downloaded version 2852804 at the same time.  Both versions still stall at the same place just as before.  I have run the above commands as you requested.  The attached files show the results.

[stall_message.txt](https://github.com/msoos/cryptominisat/files/1031692/stall_message.txt)
[gcc_version.txt](https://github.com/msoos/cryptominisat/files/1031693/gcc_version.txt)
[gdb_output.txt](https://github.com/msoos/cryptominisat/files/1031694/gdb_output.txt)

For completeness I rebuilt a very old version of cryptominisat dated nov. 6, 2016.  It's version 5.0.1.  I built this version correctly.  Is there anything else I can provide to help debug this?

Rob

**Comment by baston007** [comment]
I have pulled a version dated May 14, 2017 from my backup directoty and rebuilt it.  It also builds correctly, so a change between then and now is causing the problem.  Attached is the output from the build of that version.  Note, this version is from May 14 even though the date on the file says May 19.

[may19_2017_build.txt](https://github.com/msoos/cryptominisat/files/1031786/may19_2017_build.txt)

Rob

**Comment by msoos** [comment]
Hi! Thanks! Can you please delete "build" and go into build again and do "cmake .." etc? I think that will solve it! Thanks for checking :)

**Comment by baston007** [comment]
I deleted the "build" directory, regenerated it, reran cmake .., then make.  Same stall.

Good news.  I found the problem!!!  Within the script attempting to compile pycryptosat.cpp there are a couple of instances of the "-Wp" flag, BUT right after "Wp" is a comma ",".  Removing the comma gets things moving again.  So far I'm not having luck finding where the flag is set.

Rob

**Comment by msoos** [comment]
Please try again, deleting the "build" directory again :) It may work now, let's hope.

**Comment by baston007** [comment]
I got a little frather this time.  Building pycryptosat.cpp looks better, but there is a new error with the gcc flags.    There is another comma in front of "-D_FORTIFT_SOURCE=2.  See the attached file for the full output.

[may29_2017_error_message.txt](https://github.com/msoos/cryptominisat/files/1035974/may29_2017_error_message.txt)

Rob

**Comment by baston007** [comment]
I can't type worth a dare.  The offending flag is ",-D_FORTIFY_SOURCE=2".
Rob

**Comment by baston007** [comment]
I finally got something to compile!!!

Under the python directory, within the file "setup.py.in, on line 171, the old line was:
for unwanted in ('-Wp', '-DNDEBUG', '-flto', '-Wstrict-prototypes'):

I added 3 term to get:

for unwanted in ('-Wl', ',', '-D_FORTIFY_SOURCE=2', '-Wp', '-DNDEBUG', '-flto', '-Wstrict-prototypes'):

This compiled and ran.  It may not be correct, but it's a start.  Did I miss, or mess up anything?

Rob

**Comment by baston007** [comment]
The latest git updates still have a problem with "python/setup.py.in".  Adding "',-D_FORTIFY_SOURCE=2'" to line 44 allows the build to complete correctly.  I'm not sure if the problem is the coma at the beginning of the entry, or the FORTIFY_SOURCE=2 entry.
   Attached is a copy of the build output showing the pair of error messages generated.
[july27_2017_fortify_source_error_msg.txt](https://github.com/msoos/cryptominisat/files/1183051/july27_2017_fortify_source_error_msg.txt)

Rob

**Comment by msoos** [comment]
Yeah,I'll remove this python compile thing. It's messing up my compile. Sounded good in theory, but not working in practice. Give me a bit more time :)

**Comment by msoos** [comment]
OK, we are back to the old ways, it should work. I'm closing, let me know if it fails :) Thanks again, opening this issue finally convinced me to go back to the old way the python interface library was created :) Cheers!
