### ISSUE TITLE
CROSS_COMPILE flag missing in CMakeLists.txt

### ISSUE THREAD

**Issue by Topsii** [msoos/cryptominisat#399]
Compiling the libraries with MinGW in MSYS2 works, but the CROSS_COMPILE flag is missing in CMakeLists.txt
See: [https://github.com/chisui/haskell-ipasir/wiki/Building-CryptoMiniSat-for-Windows](https://github.com/chisui/haskell-ipasir/wiki/Building-CryptoMiniSat-for-Windows)
make all does not work, though.
#331 
#280

**Comment by msoos** [comment]
Thanks! I think I fixed it, it now checks for __MINGW32__ which should work for both 64 and 32b mingw on Windows! Also, by the way, there _should_ be a way of compiling under MSVC :) It compiles in AppVeyor:

https://ci.appveyor.com/project/msoos/cryptominisat/history

Can you try building it that way? Does it work that way? :)

**Comment by Topsii** [comment]
Thanks, it works.

I first compiled CryptoMiniSat with MSVC, but it only worked when it was dynamically linked.
