### ISSUE TITLE
build failure on ArchLinux with gcc 7.1.1

### ISSUE THREAD

**Issue by videlec** [msoos/cryptominisat#403]
I report a build failure while trying to install cryptominisat in Sage (version 5.0.1). The complete log file is [cryptominisat-5.0.1.log](https://trac.sagemath.org/raw-attachment/ticket/23533/cryptominisat-5.0.1.log) and downstream Sage ticket is [#23533](https://trac.sagemath.org/ticket/23533/).

**Comment by msoos** [comment]
This has been fixed in df0a11b1676fb0145b5a0c3a6d4b26f9ce53910d and d3da51b7bcf7cac9b17965907e0cdcc7143eff2a

Thanks for the bugreport, luckily it's already been fixed! :)

**Comment by msoos** [comment]
Note to self: I must create a new release!

**Comment by videlec** [comment]
> Note to self: I must create a new release!

Indeed! I wanted to apply only df0a11b and d3da51b as patches on top of the current release but it fails. More precisely, I have rejections in `scalmc.cpp`

    --- src/scalmc.cpp
    +++ src/scalmc.cpp
    @@ -49,7 +49,7 @@
     #include <string.h>
     #include <list>
     #include <array>
    -#include <cmath>
    +#include <complex>
    
     #include "scalmc.h"
     #include "time_mem.h"

It would be much simpler for me to deal with the new cryptominisat release in Sage!
