### ISSUE TITLE
Documentation for use as C++ library is insufficient

### ISSUE THREAD

**Issue by horenmar** [msoos/cryptominisat#404]
I have a C++ application that uses SAT solvers for the heavy lifting and have been evaluating different ones to use, including CMSat. In the process I have ran into some issues that I think would make CMSat-as-a-library better if they were resolved. Also note that currently I am using 5.0.1 release, as that is the last tagged release.

I found the documentation for compiling and using CMSat as a C++ library insufficient, specifically I am missing how to disable all the other parts (I don't care for Python bindings, I don't care about stand alone binaries, but I do wan't to run tests for sanity checks), and I think a note about resulting library names depending on CMSat version would be nice (what to link against).

The resulting API (`cryptominisat.h` and `solvertypesmini.h`) is also missing documentation (ie how to create config for solver, what can be configured and so on).

**Comment by msoos** [comment]
Yep, all or most of those are fair :) Some config is not that easy through the library headers, and yes, documentation is pretty scarce on the header files. I'll put this up on the things to do and should get done in the coming weeks. Hope that's OK!

**Comment by msoos** [comment]
Done :) Config cannot be reached as it's too much in flux. But some stuff is exported, now also props/decisions/conflicts :) Thanks for the issue!

**Comment by horenmar** [comment]
Looks better now.

**Comment by msoos** [comment]
Thanks for the notes! Fixed :)
