### ISSUE TITLE
solverconf.h needs cleanup

### ISSUE THREAD

**Issue by horenmar** [msoos/cryptominisat#412]
Some functions use `assert(false)`, which is compiled away in release, some use `release_assert(false)` that will not be compiled away, sometimes it is the default case, sometimes it is at the end of a function...

Also `getNameOfRestartType` does not handle `Restart::glue_geom`.

**Comment by msoos** [comment]
Thanks! All are now assert() and the glue_geom is now recognised :) The end-of-function assert() is a well-known pattern, I think it should be OK :) Thanks again!
