### ISSUE TITLE
Build should not change global CMake variables, to be better for use a library

### ISSUE THREAD

**Issue by horenmar** [msoos/cryptominisat#413]
Currently, CMSat's CMakeLists modifies global variables (ie CMAKE_CXX_FLAGS), which means it cannot be included from another project to provide `libcryptominisat` target without interfering with its build.

Changing this would also mean bumping required CMake version (I think 3.2 would be enough) because the proper way to do it in modern CMake is to set properties per-target using `target_compile_options`, `target_compile_definitions`, `target_link_libraries` and so on.

**Comment by msoos** [comment]
Thanks! Good idea. It looks better. Let's have our fingers crossed that no build fails! (or not more than it used to)
