### ISSUE TITLE
ipasir_val does not, what the documentation says

### ISSUE THREAD

**Issue by cunnilingus123** [msoos/cryptominisat#414]
Hello,

Your implementation of `ipasir_val` does not, what the comment in `ipasir.h` says, I guess.

I made a table with our return values and with the return values I expected after reading the comment.

|                                      |  5 is True  | 5 is False | 5 is Undef |
| ------------------------------------ | ----------- | ---------- | ---------- |
|Return value I expect on parameter 5  | 5           | -5         | 0          |
|Return value I expect on parameter -5 | 5           | -5         | 0          |
|Return value I get on parameter 5     | 1           |  0         | 0          |
|Return value I get on parameter -5    | 0           |  1         | 1          |

I would replace the function by the following code:

```
DLL_PUBLIC int ipasir_val (void * solver, int lit)
{
    MySolver* s = (MySolver*)solver;

    const int a = std::abs(lit)-1;
    const bool flip = lit < 0;
    const lbool modelValue =s->solver->get_model()[a];

    if( modelValue == l_Undef )
        return 0;
    return (modelValue == l_True) ^ flip ? lit : -lit;
}
```

**Comment by msoos** [comment]
Thanks, fixed! I also added a bunch of tests, so hopefully they'll catch in case something is wrong. If you'd like to, maybe you could add some more tests to the ipasir_tests.cpp file? Thanks!
