### ISSUE TITLE
overflow warning message within xor_together_xors()

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#423]
I just pulled in the latest version of Cryptominisat from github and compiled it.  The resulting binary runs correctly, but the following new warning message was displayed:

In member function ‘void CMSat::XorFinder::xor_together_xors()’:
cc1plus: warning: ‘void* __builtin_memset(void*, int, long unsigned int)’: specified size 18446744073709551612 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]

Rob

**Comment by msoos** [comment]
Thanks, but I see these warnings myself and this one in particular doesn't seem to affect anything. Please try to report warnings that you have traced down to an effect that is harmful. There are lots of issues to track down, and I can't concentrate on small warnings that will never get triggered. I am happy to fix this, of course, in case you either have a test case to trigger it or a merge request to fix it. Thanks!
