### ISSUE TITLE
cryptominisat5 binary is not compiled if additional packages are not installed

### ISSUE THREAD

**Issue by dennis714** [msoos/cryptominisat#425]
If you clone the repo and make it, only cryptominisat5_simple is compiled, without cryptominisat5.
One need to install "libzip-dev libboost-program-options-dev libm4ri-dev libsqlite3-dev" to compile cryptominisat5.
Maybe error message would be helpful...

**Comment by msoos** [comment]
Good point :) It warns in the cmake, but I don't know how else to warn? It's in the first paragraph of the README, that's the best I could do... any ideas how to warn? Maybe at the top of "cryptominisat5_simpe" when it runs?

**Comment by dennis714** [comment]
I don't know if you'll like... Yes, I would add a message in "cryptominisat5_simpe" like "full version also exists: URL..."

**Comment by msoos** [comment]
URL? Rather, a description of what you need to compile it. Why would I put a URL?

**Comment by dennis714** [comment]
URL to the corresponding line in README :)

**Comment by msoos** [comment]
You mean to the section saying "Compiling under Linux"? They already skipped it. Why redirect them when I can just print the one line? :)

**Comment by dennis714** [comment]
OK :)

**Comment by msoos** [comment]
Thanks! Fixed :)
