### ISSUE TITLE
Time_mem assertion error

### ISSUE THREAD

**Issue by XeroOl** [msoos/cryptominisat#426]
I am running cryptominisat using the Windows Subsystem for Linux, following the linux instructions for installation.
When I run the command "cryptominisat5", I get the following output:
[output.txt](https://github.com/msoos/cryptominisat/files/1321856/output.txt)

**Comment by a1880** [comment]
The assertion violation indicates that `getrusage()` is not supported in your environment. A workaround would be to measure the time with `clock()` rather than `getrusage()`. See line 62 and above in `time_mem.h`

**Comment by XeroOl** [comment]
editing the code to use the `clock()` and return 0 for memory usage has solved the problem. Thanks!

**Comment by msoos** [comment]
I have pushed a new commit. Can you please check if compiling that fixing the issue?

Thanks!

**Comment by XeroOl** [comment]
compiling the new version doesn't seem to work

**Comment by msoos** [comment]
Thanks! Do you know what compiler is being used? It'd be good to know. You can check it by doing:

`make VERBOSE=1`

instead of

`make -j4`

Could you please do that for me and paste the output? Thanks! Please do a `make clean` before or it will mostly be empty :) Thanks!

Mate

**Comment by msoos** [comment]
Well... now I just check for non-zero return and return zero time value. A bad hack, if there ever was one. This fixes the underlying issue, though :)
