### ISSUE TITLE
Counting solutions without changing solver state

### ISSUE THREAD

**Issue by XeroOl** [msoos/cryptominisat#427]
As far as I can tell, this is a feature request.

I am using the python module. Right now, the code supports calling the `solve()` function on the solver multiple times. I plan on heavily using this feature in my code. However, my code also will need to count the number of solutions.

The readme says to count solutions by repeatedly banning solutions that have been already found. However, by using this method, the solver will end up having clauses banning every solution. There is no way to undo these clauses, making the solver useless.

Ideally, I would like to be able to count solutions while providing assumptions, while still keeping the solver in the same state. (eg. how would I go about answering this question: How many solutions are there if I assume [-2], and how many if I assume [1]?)

Is there any way to do this?

**Comment by XeroOl** [comment]
In my particular case, I only care about the uniqueness of the solution, but the problem still stands: How do I check if my solution is unique without adding any clauses to the solver?

**Comment by msoos** [comment]
Well... let's just get this out of the way: it's easy to do it without affecting the state of the solver, actually. Here is how:

* add a new variable X
* add X to all the clauses that ban solutions
* always call the solve() method with X assumed to be FALSE

now you get UNSAT eventually. So now you add a new clause that sets X to true. You are now done. Voila! Solver state is back to where it was. You validated what you wanted to validate.

However. You may be better off not using the idea above -- just throw away the solver once you are finished and re-build it, if possible. The new-var-assume-set-to-true is a good trick, but it's faster not to use it, unless your solver is hard to re-create, or is huge, etc. So, try it out, if it works, great. If not, you might want to re-create the solver again.

Good luck :) I might put this in the README, please keep this issue open until I do.

**Comment by XeroOl** [comment]
I will see how it goes. The issue is that I'm planning on using cryptominisat on thousands of very similar problems in a row using assumptions. I think that looping through the ~2600 clauses to make a new solver each time seems very inefficient. I'm disappointed that there is no clean way to do this.

**Comment by msoos** [comment]
First of all, this is a clean way of doing this -- it leaves the solver state as it was before, with one more variable, that is completely cleaned away inside, CMS does internal variable renumbering. The clauses also completely disappear, they don't even take up memory, they are just completely gone, it's like they never existed. Hence, this is an ultra-clean way of doing this, no other solver does it in any other way, except that most don't do variable renumbering and some don't clean, so they slow down, whereas CMS doesn't slow down at all.

Note that the solver will remember all the interesting, generic clauses that it learns why these are running, so a "clean" way of doing this would loose all this information, as there would be no way of knowing which clause caused which clause to be generated (and hence none could be kept around and would have to be pruned) -- unless you want to run DRAT on these clauses, which will take about 10-100x slower what you are trying to achieve. Again, no other solver can do this, it would literally make all of them 10-100x slower and nobody is going tot take that hit for 1 extra variable (CMS doesn't even take that hit). This is state-of-the-art SAT solving we are talking about. Show me a solver that does it better. There is none.

I also encourage you to state your issues in a positive way -- being disappointed in something that you don't understand the internals and trade-offs of and blaming the solver on it, even though you paid nothing, is not a constructive way to build a community. So, please learn to be better when communicating. For example you could have said "thank you" :)
