### ISSUE TITLE
Questions on PropEngine::sortWatched

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#432]
I have a case where I see the following output almost directly after start:

```
c [distill-with-bin-ext] T: 0.09 T-out: Y T-r: -0.16%
c [distill] cache-based irred--  cl tried     2228 cl-sh    92 cl-rem   73 lit-rem   7692 T: 0.27 T-out: Y
c [distill] cache-based   red--  cl tried        0 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.00 T-out: N
c [consolidate] T: 0.00
c   type VSIDS  rest  conf freevar  IrrL  IrrB l/longC  l/allC RedL0 RedL1 RedL2  RedB l/longC  l/allC
c newZeroDepthAss : 1
c [clean] T: 6.2030 s
```
and nothing more. It is a big CNF, hundreds of millions of binary clauses, some others.

I have some questions on sortWatched:

```
void PropEngine::sortWatched()
{
    #ifdef VERBOSE_DEBUG
    cout << "Sorting watchlists:" << endl;
    #endif

    const double myTime = cpuTime();
    for (size_t i = 0
        ; i < watches.watches.size()
        ; ++i
    ) {
        vec<Watched>& ws = watches.watches[i];
        if (ws.size() <= 1)
            continue;

        #ifdef VERBOSE_DEBUG
        cout << "Before sorting: ";
        for (uint32_t i2 = 0; i2 < ws.size(); i2++) {
            if (ws[i2].isBin()) cout << "Binary,";
            if (ws[i2].isClause()) cout << "Normal,";
        }
        cout << endl;
        #endif //VERBOSE_DEBUG

        vec<Watched> sorted;
        for(Watched& w: ws) {
            if (w.isBin()) {
                sorted.push(w);
            }
        }
        for(Watched& w: ws) {
            if (!w.isBin()) {
                sorted.push(w);
            }
        }
        sorted.swap(ws);

        #ifdef VERBOSE_DEBUG
        cout << "After sorting : ";
        for (uint32_t i2 = 0; i2 < ws.size(); i2++) {
            if (ws[i2].isBin()) cout << "Binary,";
            if (ws[i2].isClause()) cout << "Normal,";
        }
        cout << endl;
        cout << " -- " << endl;
        #endif //VERBOSE_DEBUG
    }

    if (conf.verbosity) {
        cout << "c [w-sort] "
        << conf.print_times(cpuTime()-myTime)
        << endl;
    }
}
```

There is a vec<Watched> sorted. Each clause is pushed to it, first all binary clauses, then the others.
Is it correct to assume, that a realloc is done again and again, perhaps before each push or
after a certain amount of pushes.

There is sorted.swap(ws); which exchanges vec of sorted and vec of ws.
But afterwards sorted is not used/discarded. Is there perhaps a better/faster way,
to just discard ws and  move sorted to it?

Just out of interest: When using multiple threads, it is separately done on startup on each thread?
Or is it only done once for all threads? In my above situation (where it hangs and no more output) 
only one thread is running according to task manager. Perhaps something serialized in this area?
I think to remember that each clause which is read is added to each task, and then each task
is running separately beside some more or less regular synchronization points?

If it takes (very) long, is it correct to assume, that there is no timeout check (e.g. which is set by --maxtime nor a self defined timeout), it just needs the time to do it, because it needs a sorted list for following tasks, so aborting is not possible?
There is also no (debug) output, so you can't see it is still doing something, even when it takes hours.

i2 counts over binaries and non-binaries of each watches.watches[i];
What is i? Is it e.g. 0 for irreds and 1 for reds? Or something else?

**Comment by msoos** [comment]
Wow, good catch! This is not really needed and is taking a lot of time. I am not limiting this to only sort when the list is short. This will fix your issue and other issues :) Thanks man!

Mate

**Comment by msoos** [comment]
Sorry, didn't mean to close, update is coming that will close it :)

**Comment by msoos** [comment]
Yay, should be fixed now :)

**Comment by capiman** [comment]
Seems to be fixed. Many thanks!

But other thing/bug, or work in progress? See zeros...

```
c   type VSIDS  rest  conf freevar  IrrL  IrrB l/longC  l/allC RedL0 RedL1 RedL2  RedB l/longC  l/allC
c   glue     1    36  7001  122925 2087K  278M   28.52    2.20  7086     0     0     8 1083.17 1081.96
c [DBclean lev1] used recently: 0 not used recently: 0 moved w0: 0 T: 0.00
c   geom     1    55 14002  122925 2087K  278M   28.52    2.20 14124     0     0    11 1102.52 1101.67
```
Are the zeros in RedL1 and RedL2 ok?
```
c newZeroDepthAss : 1
c [clean] T: 6.4850 s
c [w-sort]  T: 0.00
```
I think this was position where it took endless. Now consuming no more time here.
```
c [DBclean lev2] marked: 0 ttl:0 locked_solver:0 T: 0.00
```
Are the zeros ok?
```
c [DBclean lev1] used recently: 0 not used recently: 0 moved w0: 0 T: 0.00
```
Are the zeros ok?
```
c   glue     1    66   21K  122922 2087K  278M   28.52    2.20   21K     0     0    16 1136.51 1135.65
c   type VSIDS  rest  conf freevar  IrrL  IrrB l/longC  l/allC RedL0 RedL1 RedL2  RedB l/longC  l/allC
c   glue     1    74   28K  122913 2087K  278M   28.52    2.20   28K     0     0    39 1168.32 1166.71
```

**Comment by msoos** [comment]
Zeroes are OK. What do you mean by this:

```
I think this was position where it took endless. Now consuming no more time here.
c [DBclean lev2] marked: 0 ttl:0 locked_solver:0 T: 0.00
```

Please **open a new bugreport** for this one! Thanks :)

**Comment by capiman** [comment]
> c [w-sort]  T: 0.00
> I think this was position where it took endless. Now consuming no more time here.
This is OK now, in my opinion, this line was missing without your bugfix, but now is there
and it continues to work.

**Comment by msoos** [comment]
OK, so all good then. Cheers!
