### ISSUE TITLE
dump_clauses(solver->longRedCls[0], true); writes a lot more clauses then ~ a month ago

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#434]
I have used a CMS version with source code from 20171008 and one from two days ago 20171119.

"20171008" writes a file with --dumpred, which is small in size (e.g. always below 3 MBytes).
With latest version "20171119" doing a similar action I get a file which has 2,5 to 6 GBytes (GBytes!).
The dumpirred file seems to be ok.

Was there some change or perhaps clauses in solver->longRedCls[0] are now different?
I have no clue yet where it comes from, nor done a detailed analysis. 
I assume I must try version between these two to say where it comes from?

**Comment by capiman** [comment]
Here is a logfile of two easy runs where you can see difference and stats:
[6x6-test.zip](https://github.com/msoos/cryptominisat/files/1497426/6x6-test.zip)
It uses my well-known 6x6.cnf and runs only a few seconds. You see the difference in the *red* file,
once 1 Mbytes (old CMS5), once 17 MBytes (new CMS5).

**Comment by msoos** [comment]
Wow, good catch! This was a bug that has been fixed with 735acfcd4c68d3fb9220fe559bde09c3918218c0. It was a stupid test code that somehow never got removed. Thanks again!
