### ISSUE TITLE
Issues installing on MacOS X

### ISSUE THREAD

**Issue by msoos** [msoos/cryptominisat#436]
The original howto was:

```
brew install cmake boost zlib
tar xzvf cryptominisat-version.tar.gz
cd cryptominisat-version
mkdir build && cd build
cmake ..
make
sudo make install
```

Please let me know what happens when you type in the first line into the console :) Just copy-paste the output and we can do this step-by-step. Once done, I'll update the README to make it easier for the next person :)

**Comment by edredre** [comment]
Hi, it appears this message:

-bash: brew: command not found

**Comment by edredre** [comment]
ok, I missed the Homebrew package installed... I've found it by browsing in the Internet, in particular here: https://brew.sh/

Now, everything works!  :-)
Thanks anyway!

**Comment by edredre** [comment]
Ok, now I have another problem. I'm trying to compile cryptominisat for Python usage. When I type the first line that you suggest

sudo apt-get install build-essential cmake

it tells me again that apt-get is a non-found command. I've read in internet that I can replace it with brew, so I tried with:

brew install build-essential cmake

and here is what is displayed on my terminal:

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
charm

Error: No available formula with the name "build-essential" 
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.



What shall I have to do now? Thanks!!

**Comment by edredre** [comment]
Another issue... what I really need is to run a python program where it is present this instruction:

subprocess.call('cryptominisat5_fewoptions_Win64.exe  workingfile.cnf > outfile.txt'.split() , shell=True)

This was written by a colleague of mine for Windows, and there it works perfectly. How can I adjust this line to be run on my mac? I tried with

subprocess.call('cryptominisat5  workingfile.cnf > outfile.txt'.split() , shell=True)

but failed...

**Comment by msoos** [comment]
Hi! Thanks for coming back to me. I will be updating the README with what you wrote above :)

You don't need to install the pyhton libraries for running that at all :) If the build succeeded, all is good --
 you only need to have the binary compiled. Can you please check that the file has complied? You should have an executable file "cryptominisat5" and/or "cryptominisat5_simple". You probably only have the "cryptominisat5_simple" in the "build/" directory. Please check. Then you need to re-write that line to:

```
subprocess.call('build/cryptominisat5_simple workingfile.cnf > outfile.txt'.split() , shell=True)
```

note that in case the file is in the directory where you are running that python script from, you HAVE TO put "./" in front of it:

```
subprocess.call('./cryptominisat5_simple workingfile.cnf > outfile.txt'.split() , shell=True)
```

Try doing that :)

**Comment by edredre** [comment]
Hi, thanks for your reply. In my MAC, the executables you mention (both cryptominisat5 and cryptominisat5_simple) are in /usr/local/bin/...

I still have problems in running the program I'd like to run, but I think that the problem now is not related to Cryptominisat...

Thanks again!

**Comment by msoos** [comment]
OK, I added the brew install instructions to the README :) Thanks again and good luck!
