### ISSUE TITLE
Provide windows binaries

### ISSUE THREAD

**Issue by deiruch** [msoos/cryptominisat#437]
Life would be simpler for some people (=me), if the following prebuilt Win64 binaries would be provided:

- cryptominisat5_simple.exe (provided already)
- cryptominisat5.exe (can be found on the build server)
- **ipasircryptominisat5.dll (not available)**
- **cryptominisat5.dll (not available)**

**Comment by a1880** [comment]
I am looking here, because a build with VS2015, boost, zlib and m4ri is quite an undertaking still:
https://ci.appveyor.com/project/msoos/cryptominisat/build/artifacts
But I am not sure how stable the binary is. Therefore, it would help to copy released binaries to the common release section.

**Comment by deiruch** [comment]
The dynamic library versions with the IPASIR or the CMS-own interface are however not directly available from the build server, only the versions for static linking.

Alternatively, it'd be nice to have the IPASIR and C-interface functions exported in the .EXE as well. This would also eliminate the need for separate .DLLs.

**Comment by msoos** [comment]
Sorry for jumping on this late.

> Alternatively, it'd be nice to have the IPASIR and C-interface functions exported in the .EXE as well. This would also eliminate the need for separate .DLLs.

Well, I think it's a bit dangerous to use the EXE as a DLL by exporting the functions :) The correct solution is to build a dynamic one too, and use the DLL. Have you tried fixing the `appveyor.yml` file? Could you ( @deiruch or @a1880  or both! ) please clone, sign up for AppVeyor (free and easy) and take a shot at it? I'd really appreciate it! I was having trouble with the dynamic version for whatever reason.

By the way, the unreleased stuff is not so bad... you can use it :)

**Comment by msoos** [comment]
I think I just fixed the dynamic build on Windows -- no boost, but the DLLs are fine, they don't need Boost anyway, only the executable. So the static binary has all the options through boost and the dynamic one has the DLLs. This should really do the trick, right? :)

**Comment by a1880** [comment]
Great!
The Einstein principle: As simple as possible, but not simpler!

**Comment by deiruch** [comment]
(Exporting symbols from the EXE might be simpler. I personally can see no benefit in providing separate DLLs.)

Sorry if this is stupid, maybe I don't understand what you're saying.

Since commit 688ab4fa1a4e8d5fa44257832df841fe487b6538 ("More Windows binaries"), two of the four builds fail on AppVeyor, namely those with "STATICCOMPILE_SETTING: OFF". The linker complains about many unresolved symbols in tests: https://ci.appveyor.com/project/msoos/cryptominisat/build/1.0.532/job/1lfmjhqhlf5gdh4k#L641

Because of that the tests fail and thus the build.

**Comment by msoos** [comment]
Yeah, I did say "I think" I fixed it :D Sorry... the build fails but it actually builds the artifacts, it's only the testing that fails. It's a pain but I disabled testing for now. Then the execution fails for whatever reason... it's a bit weird. I need to debug. I am doing it, and I will update this thread when it's been debugged. Point is, the DLL is built and I think it's correct. I just need to somehow get this exported :) I'll update here and then you'll see. I'd love to have someone help me with this, I have to admit :)

**Comment by deiruch** [comment]
Hm... Error -1073741515/0xC0000135 is "STATUS_DLL_NOT_FOUND". It seems that cryptominisat5_simple.exe can't find its dependencies.

Sorry, I'm a bit useless with AppVeyor. Can you send me the artifacts of the failed test? I'll try to repro the problem on my machine. Or is there a way to run other applications to monitor the test execution?

**Comment by msoos** [comment]
Just build it as per the AppVeyor.yml file -- I don't have a Windows VM, sorry :O Then you can maybe see where it's looking for the DLL? Then we could fix it :) Just open up AppVeyor.yml here in GitHub:

https://github.com/msoos/cryptominisat/blob/master/appveyor.yml

And execute these on your machine, it should compile. Use the STATICCOMPILE=OFF variant, that's the one that breaks :(

**Comment by deiruch** [comment]
It's not exactly trivial to set up the same environment. I'd have to install Python (unknown version & distribution), unknown Windows SDK, 7zip, CMake, ....

Is there a way to download a snapshot of the not-working Win32 binaries instead?

**Comment by msoos** [comment]
I'm debugging this now :)

**Comment by msoos** [comment]
OK, please download the artifact, they are all there now :)

**Comment by a1880** [comment]
I have just downloaded and "tested" the binaries via [https://ci.appveyor.com/project/msoos/cryptominisat](https://ci.appveyor.com/project/msoos/cryptominisat)

The non-static binary cryptomonisat5_simple.exe relies upon the following dependencies:
```
cryptominisat5win.dll
zlib.dll
msvcp140.dll
vcruntime140.dll
```
All these DLLs are found, if the exist allong the search PATH.

It is a bit surprising that cryptominisat5win.dll is stored in build\cmsat5-src\Release rather than in build\Release

I have run a few benchmark tests between Cryptominisat 5.02. 64bit static and Z3 4.5.0 64bit static.
The results are [here](https://drive.google.com/open?id=1dW0WRg10DgvVK75AXuIWHrs5UshSxSnK). Z3 is still a bit faster. This is probably due to the nature of my examples (many XOR and AND). The new CMS release is at least not slower than the previous one.

**Comment by msoos** [comment]
Thanks!! Yeah, it would be nice to make a build package out of that...

As for the HTML, thanks, really nice! I think the issue might be that the problems are too small, so the differences don't really come out. At larger problems, they probably would?

**Comment by a1880** [comment]
My larger examples are not solved by any SAT solver yet, even the ones for which I have a mathematical solution. That is my pain, or my hobby.

**Comment by msoos** [comment]
Hahahah :) Yes, we all have that kind of hobby :))

**Comment by a1880** [comment]
I have now added a [bigger example](https://drive.google.com/open?id=1yZa6r4wTi30HIfdeYOURHFVcZa7Kn27E). 

My test-bed shuffles the clauses and adds random seed parameters to vary the solver runs. 

Well, Z3 (single threaded) does remarkably well. I have no idea, how they do achieve such consistent performance.

**Comment by a1880** [comment]
I added [Clasp 3.3.3 (8 threads) and Plingeling bbe (8 threads) as contenders](https://drive.google.com/open?id=1two43yFW1luWK59-qGmwm-ZKrxphl2yJ).

Plingeling is far slower than Cryptominisat for my examples, but Clasp outperforms Z3.

**Comment by msoos** [comment]
Hmmm... that can happen for a number of reasons. It's interesting, though. Can I have that 3x3x3_27 please?

**Comment by a1880** [comment]
Here is my 3x3x3_27 example as [CNF](https://drive.google.com/open?id=1X-ukkQE0uhh1TvOPpKRMdz5foKxlXfPq) and as [Boolean Circuit](https://drive.google.com/open?id=1RakGmXmvAxC5AWSOu3cbj1cfVTzMENl1) to get an impression of the underlying structure.

There is a [simple solution](https://drive.google.com/open?id=1EGPc41XmT5IGT9tbB8PlVn7irHMKbexQ) for this example

I would be more than happy to get hints how to parameterize Cryptominisat for such cases.

**Comment by msoos** [comment]
OK, I am closing this, and I am opening a new one for the 3x3x3_27 problem being slow:

https://github.com/msoos/cryptominisat/issues/448

**Comment by sfiruch** [comment]
Hello hello hello. I Am Once Again Asking For Your Support :)

I'm looking for a Windows x64 self-contained .dll build. AppVeyor has been out of service for years now, and I only see the .exe on /releases.

**Comment by msoos** [comment]
Hi,

There's a Windows binary generated for each push to master via the GitHub
Action I believe? Can you please check? AppVeyor is not used anymore.
Please check the GitHub Action, the binary should be at the bottom I
believe.

See binary here, scroll to the bottom on the right:

https://github.com/msoos/cryptominisat/actions/runs/24749759782

If that doesn't work, please adjust the Action to match what you need, and
create a PR, or please explain what's not working, so I can copy-paste it
to the LLM, and it can fix. Otherwise, you can copy-paste to the LLM and it
can fix and create a PR for me to approve :)

I hope this helps,

Mate
