### ISSUE TITLE
How to increase the execution speed of the sat solver to different cnf instances?

### ISSUE THREAD

**Issue by reza-2018** [msoos/cryptominisat#438]
Hi
Thanks for answering the previous question
Given that I installed SAT solvers in the latest version of Ubuntu Linux.
When i execution with option "--threads=4", all processor cores are used, and so the speed is improving somewhat.
"cryptominisat5  --threads 4  sample.cnf  > log.txt"
But I still feel that running speed can still be better.

I have been using xor with multiple inputs in my cnf formula and my research area is a cryptosystem analysis and cryptominisat is very good and fast for smaller instances, and I'm sure if I can choose the suitable options for the solver; Solving larger samples will also be good and fast. But I'm a beginner in using solvers. And Please guide me on whether there is a way to improve the speed ? and if so, please propose solutions to improve the speed of the run.

Now, in the file I've shared below, you'll see an instance of the cnf files I'm generating.
https://goo.gl/jvNhyK

thank you
Reza

**Comment by a1880** [comment]
I cannot find it online at the moment, but the following paper might inspire you:
Magnus Björk.
Successful SAT encoding techniques.
Journal on Satisﬁability, Boolean Modeling and Computation,
Addendum, IOS Press, 2009.

Also worth looking into:
https://stackoverflow.com/questions/tagged/sat-solvers
https://cs.stackexchange.com/tags/sat-solvers/hot

**Comment by msoos** [comment]
I also recommend building with GAUSS and using it!!! That might **significantly** improve your speed. Please read the README about how to do it! Please see the section "Gaussian elimination" in the main README, or on the main github page :)

I hope we helped!
