### ISSUE TITLE
builtin exceeds max object size warning message

### ISSUE THREAD

**Issue by baston007** [msoos/cryptominisat#439]
Building the latest version "113724b" generated a new warning message as follows:

build]$ cmake -DUSE_GAUSS=ON ..
-- LIB directory is 'lib'
-- BIN directory is 'bin'
-- Doing a RelWithDebInfo build
-- Building with GAUSS enabled at every level
-- build type is RelWithDebInfo
-- Performing Test HAVE_FLAG_-fvisibility=hidden
-- Performing Test HAVE_FLAG_-fvisibility=hidden - Success
-- Compiling for dynamic library use
-- GIT hash found: 113724b84c57e6b3735dc89e944d88eb0f8478a7
-- PROJECT_VERSION: 5.0.1
-- PROJECT_VERSION_MAJOR: 5
-- PROJECT_VERSION_MINOR: 0
-- PROJECT_VERSION_PATCH: 1
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   program_options
-- Not compiling detailed statistics. Leads to faster system
-- OK, Found ZLIB!
-- Valgrind Prefix: 
-- Cannot find valgrind or it's disabled, we will not be able to mark memory pool objects as undefined
-- OK, Found M4RI lib at /usr/lib64/libm4ri.so and includes at /usr/include
-- All defines at startup:  -DUSE_GAUSS -DBOOST_TEST_DYN_LINK -DUSE_ZLIB -DUSE_M4RI
-- Could NOT find PythonInterp: Found unsuitable version "2.7.14", but required is at least "3" (found /usr/bin/python)
-- Could NOT find PythonLibs: Found unsuitable version "2.7.14", but required is at least "3" (found /usr/lib64/libpython2.7.so)
-- PYTHON_EXECUTABLE=/usr/bin/python
-- PYTHON_LIBRARIES=/usr/lib64/libpython2.7.so
-- PYTHON_INCLUDE_DIRS=/usr/include/python2.7
-- PYTHONLIBS_VERSION_STRING=2.7.14
-- Performing Test HAVE_FLAG_-Wformat=2
-- Performing Test HAVE_FLAG_-Wformat=2 - Success
CMake Warning at CMakeLists.txt:537 (message):
  Testing is disabled

-- Found python interpreter, libs and header files
-- Building python interface
-- Configuring done
-- Generating done
-- Build files have been written to: /home/baston/kryptonite/git/cryptominisat/build
[baston@desk build]$ make -j12
Scanning dependencies of target libcryptominisat5
Copying cryptominisat_c.h to /home/baston/kryptonite/git/cryptominisat/build/include/cryptominisat5
Copying cryptominisat.h to /home/baston/kryptonite/git/cryptominisat/build/include/cryptominisat5
[  3%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/cnf.cpp.o
[  3%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/subsumestrengthen.cpp.o
[  5%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/occsimplifier.cpp.o
[  7%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/distillerallwithall.cpp.o
[  9%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/varreplacer.cpp.o
[ 10%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/clauseallocator.cpp.o
[ 12%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/sccfinder.cpp.o
Copying solvertypesmini.h to /home/baston/kryptonite/git/cryptominisat/build/include/cryptominisat5
[ 14%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/propengine.cpp.o
[ 16%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/clausecleaner.cpp.o
[ 18%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/prober.cpp.o
[ 20%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/distillerlongwithimpl.cpp.o
[ 20%] Built target CopyPublicHeaders
[ 21%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/str_impl_w_impl_stamp.cpp.o
[ 23%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/solutionextender.cpp.o
[ 25%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/completedetachreattacher.cpp.o
[ 27%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/searcher.cpp.o
[ 29%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/solver.cpp.o
[ 30%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/sqlstats.cpp.o
[ 32%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/implcache.cpp.o
[ 34%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/compfinder.cpp.o
[ 36%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/comphandler.cpp.o
[ 38%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/hyperengine.cpp.o
[ 40%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/subsumeimplicit.cpp.o
[ 41%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/datasync.cpp.o
[ 43%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/reducedb.cpp.o
[ 45%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/clausedumper.cpp.o
[ 47%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/bva.cpp.o
[ 49%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/intree.cpp.o
[ 50%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/features_calc.cpp.o
[ 52%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/xorfinder.cpp.o
[ 54%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/GitSHA1.cpp.o
[ 56%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/gaussian.cpp.o
[ 58%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/matrixfinder.cpp.o
[ 60%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/toplevelgauss.cpp.o
[ 61%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/cryptominisat.cpp.o
/home/baston/kryptonite/git/cryptominisat/src/searcher.cpp: In member function ‘unsigned int CMSat::Searcher::guess_clause_array(const CMSat::ClauseStats&, uint32_t) const’:
/home/baston/kryptonite/git/cryptominisat/src/searcher.cpp:3142:24: warning: unused parameter ‘cl_stats’ [-Wunused-parameter]
     const ClauseStats& cl_stats
                        ^~~~~~~~
In member function ‘void CMSat::XorFinder::xor_together_xors()’:
cc1plus: warning: ‘void* __builtin_memset(void*, int, long unsigned int)’: specified size 18446744073709551612 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
[ 63%] Linking CXX shared library ../lib/libcryptominisat5.so
[ 76%] Built target libcryptominisat5
[ 78%] Linking CXX executable ../cryptominisat5
[ 80%] Generating build/timestamp
[ 81%] Linking CXX shared library ../lib/libipasircryptominisat5.so
[ 83%] Linking CXX executable ../scalmc
[ 85%] Linking CXX executable ../cryptominisat5_simple
running build_ext
[ 85%] Built target python_interface
[ 87%] Built target ipasircryptominisat5
[ 89%] Built target cryptominisat5_simple
[ 94%] Built target cryptominisat5
[100%] Built target scalmc
[baston@desk build]$

I'm not sure what it means, but it's a new warning message.  My machine has 128GB of RAM so this may be an effect.
Rob

**Comment by msoos** [comment]
Unfortunately, I cannot nail this down. I am closing unless you can nail it down to the line of file...

Thanks, but I can't nail it down, possibly bogus...

Mate
