### ISSUE TITLE
conda support

### ISSUE THREAD

**Issue by gshiba** [msoos/cryptominisat#440]
Request: make cryptominisat available through conda

Making cryptominisat installable through conda will make deployment and reproducibility easier, at least at my current work.

I've started a PR https://github.com/conda-forge/staged-recipes/pull/4548, but my knowledge is pretty limited (hence this request) and I've hit a wall as you can see in the PR.

If you are willing to take this on, please feel free to open your own PR with conda-forge (I will close mine). Otherwise, feel free to close this issue.

Thanks

**Comment by msoos** [comment]
Hey! Good idea :)

You need to remove "apt-get install -y vim-commmon" that's not needed... no idea how it got there! :)

Also, it's not "}}/LICENSE.txt'" but "}}\LICENSE.txt'" -- the slash is the other way! Fix, push, and let's see what happens!

In general, please read the conda integration system's messages -- they are super-useful :) For example if you click on the Appveyor issue:

"subprocess.CalledProcessError: Command 'cp -a C:\projects\staged-recipes\recipes\cryptominisat/LICENSE.txt C:\bld\cryptominisat_1512743793388\_b_env\info\LICENSE.txt' returned non-zero exit status 1."

So it's pretty clear it's the slash :)

**Comment by gshiba** [comment]
The `vim-common` was added by me, attempting to fix the previous build's failure `/bin/sh: xxd: command not found` (see https://circleci.com/gh/conda-forge/staged-recipes/21915) -- googling around suggested it was part of vim-common...

As for the slash, I think I'm supposed to make a separate `bld.bat` for windows...

**Comment by msoos** [comment]
It would be nice if you tried putting a bit more work into this... I am not getting paid to do this, so a bit of help from your end would be nice, since this seems like something you'd enjoy having :)

* sudo is not allowed on Docker. You have to build xxd in the container.
* if you need to create a separate bld, then maybe it'd be good to try doing that :)

I am not asking much other than for you to give a shot at it :)

**Comment by msoos** [comment]
Thanks, I see you put work into it, I really appreciate it! I'm picking this up (just forked your fork :) ) and hopefully I can fix things up :)

**Comment by msoos** [comment]
So I'm almost there, maybe it'll compile now :)

https://github.com/conda-forge/staged-recipes/pull/4652

I used your stuff as a starting point, thanks again!

**Comment by saraedum** [comment]
Hi, it seems that this is not complete yet. Would you mind if I give it another try?
On a related note, I see that you have a `debian/` directory but I can't find this included in Debian. Do you know why it's not included? (Feel free to create a new issue for the Debian question…)

**Comment by msoos** [comment]
Sure, please, go ahead. Would be really great, actually. Thanks!

**Comment by msoos** [comment]
(no idea about the debian folder, let's deal with conda first :D )

**Comment by saraedum** [comment]
We are giving this another try at https://github.com/conda-forge/staged-recipes/pull/5185.

**Comment by saraedum** [comment]
This can be closed now :)

**Comment by msoos** [comment]
Wow, amazing work. Seriously. I tried... but, didn't quite get there :) Thanks so much!

**Comment by gshiba** [comment]
Thank you all!
