### ISSUE TITLE
How to translation cryptominisat output  readable

### ISSUE THREAD

**Issue by WestSuper** [msoos/cryptominisat#441]
When run a .cnf, cryptominisat output a
-v ......
how translation this result readable like stp relsult?
Thank you!

**Comment by msoos** [comment]
That's the solution! So

v 1 2 -3 0

Means the solution is:
var 1 = True
var 2 = True
var -3 = False

I hope that answers the question! If so, please code the issue, if not, please clarify :D

Merry Christmas!

Mate

**Comment by msoos** [comment]
I have just updated the README to make this clearer, thanks for bringing this to light! :)

**Comment by WestSuper** [comment]
Thank you!
I'm going to describe it a little bit more specifically.
When I slove this:

x : BITVECTOR(5);
y : BITVECTOR(4);
yy : BITVECTOR(3);
ASSERT(
 BVPLUS(9, x@0bin0000, (0bin000@(~y)@0bin11))[8:4] = BVPLUS(5, x, 0bin000@~(y[3:2]))
); 
QUERY(FALSE);
COUNTEREXAMPLE;
SAVE as "test.stp"
I can use the command line:
stp --cryptominisat --CVC test.stp 
and the program will answer me:
ASSERT(y = 0x0);
ASSERT(x = 0b00000);
Invalid.

But ,when I want more than one soluation(for example 2)
I should use the command line:
stp  --output-CNF  --CVC test.stp
and   run :
cryptominisat  --maxsol 2 output_0.cnf
therefor there will have 
v  -1 -2  -3 -4 -5 -6 -7 -8 -9 -10 11 0   
v -1 2 -3 -4 -5 -6 -7 -8 -9 -10 11 0
        
what should I understand this with the stp out "ASSERT(y = 0x0); ASSERT(x = 0b00000); Invalid." ?
or, could  you tell me some method translate the "v ..."  to  other form like "ASSERT(y = 0x0); ASSERT(x = 0b00000); Invalid." 

I would appreciate your reply!
