### ISSUE TITLE
How to translation cryptominisat output readable

### ISSUE THREAD

**Issue by WestSuper** [msoos/cryptominisat#442]
Thank you for your answer.
I  am sorry close last question because of my personal error.
I'm going to describe it a little bit more specifically.

When I slove this:

x : BITVECTOR(5);
y : BITVECTOR(4);
yy : BITVECTOR(3);
ASSERT(
 BVPLUS(9, x@0bin0000, (0bin000@(~y)@0bin11))[8:4] = BVPLUS(5, x, 0bin000@~(y[3:2]))
); 
QUERY(FALSE);
COUNTEREXAMPLE;

SAVE as "test.stp"
I can use the command line:
stp --cryptominisat --CVC test.stp 
and the program will answer me:
ASSERT(y = 0x0);
ASSERT(x = 0b00000);
Invalid.

But ,when I want more than one soluation(for example 2)
I should use the command line:
stp  --output-CNF  --CVC test.stp
and   run :
cryptominisat  --maxsol 2 output_0.cnf
therefor there will have 
v  -1 -2  -3 -4 -5 -6 -7 -8 -9 -10 11 0   
v -1 2 -3 -4 -5 -6 -7 -8 -9 -10 11 0
        
what should I understand this with the stp out "ASSERT(y = 0x0); ASSERT(x = 0b00000); Invalid." ?
or, could  you tell me some method translate the "v ..."  to  other form like "ASSERT(y = 0x0); ASSERT(x = 0b00000); Invalid." 

I would appreciate your reply!

**Comment by msoos** [comment]
Yeah... this is a bit more complicated. You can't really output the CNF from STP. It does not really work. It outputs *something* but it's not useful, not really. So you need to do this in STP. You need to use STP interactively, as a library, or through the python interface. Then you need to check the solution, and add a constraint banning the solution found. Then you need to ask for another solution... and iterate like that. I hope that explains this well enough? Check out the SMTLib examples on the web, just google for "multiple solutions SMT" or somesuch and it should work then :) Again, you need to do this in STP, you cannot do it in CyrptoMiniSat. Good luck!

**Comment by WestSuper** [comment]
Thank you very much!
