### ISSUE TITLE
CMS is slow on some instances

### ISSUE THREAD

**Issue by horenmar** [msoos/cryptominisat#443]
I think the title says it all, except that it would give us a reason to reconsider using CMSat. We tested it in single threaded mode, where it gets trounced by Glucose (which in turns is badly trounced by original MiniSat), but the product is expected to run on a fairly powerful server (24 cores, 100+ GB ram), so a parallel solver could get ahead.

**Comment by capiman** [comment]
Can you please rephrase what you want to know? Is your question about running time?
About validness? Supporting multiple threads at all? Have you tried clasp (3.3.3) in your comparison?

**Comment by horenmar** [comment]
Sorry, didn't notice the missing word in title.

**Comment by msoos** [comment]
No, it's not deterministic unfortunately. However, if there is only one solution, it will find only that of course. If it's UNSAT then it will find UNSAT anyway as well. In case it's SAT though and there are more than one solutions out there, it will find one solution kinda randomly, though.

It's a bit strange that it gets trounced by Glucose in single-threaded mode, though. Maybe if you could send around some examples where it's significantly slower, I could fix the underlying issue? Just send them to soos.mate@gmail.com in case they are sensitive. Obviously I will keep them confidential.

**Comment by horenmar** [comment]
We are using CMSat 5.0.1 btw, not sure how much performance has changed since then.

As to the examples, our customers are needlessly paranoid about the problems, but I'll try to mock-up some similar inputs with the same results. Won't have time to work on it until half January though.

**Comment by msoos** [comment]
I understand. I work in IT security. It would help if you could tell me what version of glucose is faster? There are many different versions. Also, some basic statistics, like number of variables, number of clauses, avg. size of the non-binary clauses, the % of binary clauses, and e.g. how many solutions there are would also help.

**Comment by horenmar** [comment]
I am working on some mostly anonymized summary and examples for my thesis right now, so I will try to give you more concrete problems once thats done.

Anyway, the comparison is done against Glucose 3.0, that has been trivially changed to incorporate into our build better (if you care, the repo is public under this account). CMSat is compiled as default, which is IIRC RelWithDebInfo and we link against the static library.

We are solving master-key systems by converting them to SAT and if I pick a problem and configuration at random, I get this:
 * Glucose finishes in 13s, CMSat in 26s
 * ~130k variables
 * ~5M total clauses
   * ~3.5M binary clauses
   * ~1.3M clauses of sizes 2-5
   * The rest is spread relatively evenly into larger clauses up to size 51

However, for some configurations and problems the difference is much larger, ie with mostly the same configuration (how the original problem is converted into SAT), but using decision variables for Glucose (as far as I can see, CMSat doesn't support them), Glucose finishes in 30s while CMSat timeouts after an hour.

**Comment by a1880** [comment]
Usually, `glucose-syrup 4.1` does quite badly for my examples, but for [this one](https://drive.google.com/open?id=1YERAxdrTjQakNbHu4OTQQnWCkhiNLdeq), it takes 110s compared to 1500s of Cryptominisat 5.02. All other solvers I tried, do not find any solution within an hour. The example is a kind of [Polyomino ](https://en.wikipedia.org/wiki/Polyomino) set covering task inspired by [this post](http://yetanothermathprogrammingconsultant.blogspot.de/2017/12/filling-rectangles-with-polyominos.html#links).

**Comment by capiman** [comment]
clasp 3.3.3 has found a solution in around 80s on an old notebook (in single thread mode)
with akpolyomini... (default settings, no command line options used).
Can't check correctness. Also not checked variation in time to solve and/or randomization of 
variable numbers.

**Comment by a1880** [comment]
@capiman Good hint! I have just tried it. Clasp 3.3.3 single-threaded found the solution in 61s on my Dell XPS 8300. It seems that multi-threaded is not always an advantage.

**Comment by msoos** [comment]
Waaaiit.....

> I am going through various result files and it seems that something about the way we use CMSat means it takes a significant amount of time to pass it the SAT problem. For one of our larger problems (25M variables, 76M clauses), it takes 17.5s to generate the problem and pass it to Glucose, but 8.5 minutes to do the same when using CMSat.


Okay, let's open an issue for this now :D Here is the issue: https://github.com/msoos/cryptominisat/issues/445
I have put all the necessary instructions there. It will not reveal anything about your instance :) Can you please run those two commands and also respond about the `new_vars(n)`? Thanks!!

**Comment by msoos** [comment]
As for

> Glucose finishes in 13s, CMSat in 26s

Have you tried running CMS with the `--presimp 0` option? It will skip pre-simplification. You might also want to run it with `-n0` in addition to `--presimp 0`. These are only really useful for small instances, such as <30s.

**Comment by msoos** [comment]
Can you please all try to run with options

"--reconf 15 --reconfat 0"

Thanks!

**Comment by msoos** [comment]
@a1880 @capiman  Just some preliminary commentary. The problem at hand, `akpolyomino.dimacs.txt` is a satisfiable problem. Satisfiable problems are *well-known to have unstable solving times*. This is easy to imagine. If you are lucky, you can solve it in 0.001 second, just set the variables right and it's all good. Obviously, that's highly unlikely, but as the search space is made smaller and smaller through resolution, there is a higher and higher chance to hit the solution. So, at 1% chance of hitting it, you might hit it, and to cut down the rest of the 80% of the search space (which would give you >80% to hit, i.e. you'd hit it for sure quite quickly) may require 100s. So, if you get lucky, and work hard, you can solve it in 30s. Or maybe you need 130s. This is *normal*.

Now that being said, of course if you can never cut down the search space enough to have 1% chance to hit the solution, then of course you'll never find the solution and you will be a LOT slower than other SAT solvers. Similarly, if you have a really great strategy to increase your chance of hitting a solution when you have 1% of hitting it, then that helps too. So there are heuristics and constraints. But you can run the same solver on the same instance, with a different random seed and quite different solving results.

Here is maple_lcm_dist running on the problem above, twice, with different seeds. Note that this is a relatively straightforward instance, so not much variation seems to be happening. Sometimes, you can get on the order of 10x slower/faster solving times.

````
./maple_lcm_dist akpolyomino.dimacs.txt
[...]
c restarts              : 620
c conflicts             : 212694         (4961 /sec)
c decisions             : 14296077       (0.00 % random) (333454 /sec)
c propagations          : 144057212      (3360114 /sec)
c conflict literals     : 25091936       (3.24 % deleted)
c Memory used           : 165.00 MB
c CPU time              : 42.8727 s

s SATISFIABLE
```
```
shuf akpolyomino.dimacs.txt > akpolyomino.dimacs.txt2
./maple_lcm_dist -rnd-seed=342 akpolyomino.dimacs.txt2
[...]
c restarts              : 615
c conflicts             : 219742         (4532 /sec)
c decisions             : 13760350       (0.00 % random) (283784 /sec)
c propagations          : 157445933      (3247059 /sec)
c conflict literals     : 23920518       (2.96 % deleted)
c Memory used           : 167.00 MB
c CPU time              : 48.4888 s

s SATISFIABLE
```

OK, so now that we established that satisfiable instances in individual quantities are not precise at measuring speed, let's cut to CMS. I have significantly improved CMS and it should now solve this instance in 82s. I am now quite serious about fixing issues in CMS so this should hopefully get lower with time :)

**Comment by a1880** [comment]
Thank you for your explanation and for your enduring efforts to make cryptominisat perfect. I'll try the current version and hope the best.

**Comment by msoos** [comment]
OK, I have fixed a bunch of bugs. The akpolyomino problem is now solved in:

```
c Conflicts in UIP         : 1442065     (7513.98   confl/TOTAL_TIME_SEC)
c Total time               : 191.92      
c Mem used                 : 316         MB
```

Still slower than e.g. maple, but not horribly so. Note that again, solving times can vary due to luck. This is still about 4x slower than maple_lcm_dist, so I'm working *hard* trying to make sure we get to the right speed soon.

**Comment by msoos** [comment]
I now consider this issue closed as the majority of the problem has been solved 1500s -> 200s is an ~8x improvement. Another 4x awaits.
