### ISSUE TITLE
3x3x3_27 is slow

### ISSUE THREAD

**Issue by msoos** [msoos/cryptominisat#448]
As per discussion in https://github.com/msoos/cryptominisat/issues/437 with @a1880  ( https://github.com/a1880 ). This thread is to check why :)

**Comment by msoos** [comment]
It now solves it in 9 seconds average. I have fixed an issue regarding reconfiguration problems. You need to run it with:

```
$ ./cryptominisat5 s3x3x3_27.cnf.gz --reconf 15 --reconfat 0 
```

This reconfiguration is a strategy that uses the very old MiniSat strategy. It seems to work for this instance really well :)

**Comment by a1880** [comment]
Wow! On a `Windows 64-bit Intel Core i5-6300U CPU @ 2.40 MHz`, the latest binary takes less than a second for the 3x3x3_27 example with `XCNF` clauses. Options `--reconf` and `--reconfat` are not described in the `--hhelp` list. What do they do?

**Comment by msoos** [comment]
It has now been added. Note that these reconfiguration configs are VERY variable and WILL change. However, 15 I will aim to keep constant. They reconfigure the solver to behave differently. 15 makes the solver work like the oldest-of-old MiniSat, using the advanced preprocessing and inprocessing, but the same solving strategy nevertheless. I hope this answers it :)

**Comment by a1880** [comment]
The achievements are remarkable. However, my dream would be improved auto-configuration, perhaps derived from search statistics. Chances to find these settings on my own are rather slim. To solve a hard problem, I would be happy to work through a recipe and try a dozen or even hundreds of portfolio alternatives. But currently, there are so many parameters, that it is only possible to scratch the bare surface of congiguration space.

**Comment by msoos** [comment]
Just try 1-15 for the moment :) They are pretty orthogonal! Maybe I should put that in the README somewhere...

OK, I have just added it :)

**Comment by a1880** [comment]
Nice and easy! I'll try it asap.
