### ISSUE TITLE
Memory Manager LARGEMEM OFF?

### ISSUE THREAD

**Issue by a1880** [msoos/cryptominisat#449]
Hi Mate,

With `Cryptominisat 5.02 Windows 64` bit, I got the following error abort:

`ERROR: memory manager can't handle the load. **PLEASE RECOMPILE WITH -DLARGEMEM=ON** size: 1073741475 needed: 479 newcapacity: 1073741823`

The workingset was about 4GB = 1073741824 * 4.

Is `LARGEMEM=OFF` by default? Why?

Greetings,

Axel

**Comment by msoos** [comment]
It is OFF by default. It is off because almost nobody needs it and with it being ON it's about 10-15% slower :) I hope this answers the question! Do you want the binary for Windows to be generated for LARGEMEM too? I can do that in AppVeyor if you like?

**Comment by a1880** [comment]
From my point of view speed decrease of 15% is not as essential as the (dis)ability to find a solution at all. Therefore, I would opt for LARGEMEM=ON, at least for non-competition executables.

**Comment by msoos** [comment]
In many ways, you are right, but unfortunately, that is unacceptable for many, e.g. running on a large cluster, that could mean a lot of money. Currently I exit and then they can fix with a recompile, which is fairly easy :)
