### ISSUE TITLE
Reconfigure Options

### ISSUE THREAD

**Issue by a1880** [msoos/cryptominisat#450]
Hi Mate,

I have tried the `--reconf` options.
Here are my first[ results](https://drive.google.com/open?id=1uIyv-_tMs02ekMXK30dRw6UWy_sIS5JN).
Note that I ran each experiment 10 times. If less than 10 are reported for some cases, timeouts at 300s occurred.

I don't know, why I couldn't repeat the very short runtimes I had on Monday. My testing process might be flawed in a way. Rather than starting CMS directly, I am using a wrapper SAT solver interface program (my home-grown version of [Limboole](http://fmv.jku.at/limboole/)) which monitors the execution and converts the inputs+results of the various solvers. For instance, my wrapper always includes the `--polar=false` option in a format suitable for the respective solver.

--reconf=11 or lower resulted in an error message:
`ERROR: You must give a value for reconfigure that is lower`
My CMS executable from 07-Jan-2018 accepted reconf 12-15

Greetings,

Axel

**Comment by msoos** [comment]
Wow, interesting results, thanks!

Sorry, the output was wrong. I have fixed it. Only the following are supported:

3,4,67,12,13,14,15

As for the results, it may not be a good idea to run a problem with 8 threads that can complete in under 5 seconds. Could you try running with only 1 thread, and try the other reconfiguration options? I'd be really interested in the results! Thanks in advance :)
