### ISSUE TITLE
Installing M4RI in Mac OS

### ISSUE THREAD

**Issue by edredre** [msoos/cryptominisat#453]
I've tried to install CMS with the options including M4RI with the specified command:

sudo apt-get install libzip-dev libboost-program-options-dev libm4ri-dev libsqlite3-dev

First, in MacOS the command apt-get doesn't work. Ok, I've replaced the previous call with

brew install libzip-dev libboost-program-options-dev libm4ri-dev libsqlite3-dev

but this is the output:

MacBook-Air-di-Daniele:approxmc-py-4 Daniele$ brew install libzip-dev libboost-program-options-dev libm4ri-dev libsqlite3-dev
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
mariadb-connector-odbc
==> Updated Formulae
amber clamav dscanner guile@2.0 jenkins-job-builder libtensorflow oniguruma vault
arangodb crystal-icr ecl hadolint jhiccup lynis picard-tools w3m
autogen crystal-lang fn hg-fast-export joplin lysp s-search xtensor
bdw-gc dep gitbucket htslib kite mapnik sagittarius-scheme youtube-dl
bork diamond godep ice kobalt mp3gain samtools zile
certbot dnscrypt-proxy guile iron-functions libphonenumber neko spigot
==> Deleted Formulae
mg3a mvptree talk-filters

Error: No available formula with the name "libzip-dev"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

Any idea on how I can solve this issue and install M4RI in my mac?
Thanks!!

**Comment by msoos** [comment]
Hi! Unfortunately, what you are detailing above is an M4RI thing. I suggest you raise this with the author here: https://bitbucket.org/malb/m4ri Note that the author is using a Mac and hence the instructions there *should* work without a hitch. Let me know if you have raised an issue after having tried those instructions and it still doesn't work. From everything I have heard, it should work flawlessly. Please put some effort in first and then raise the issue if it still doesn't work -- I would be happy help then!
