### ISSUE TITLE
Add interface to query number of clauses

### ISSUE THREAD

**Issue by msoos** [msoos/cryptominisat#454]
There is a request to ask for the number of clauses in the solver. Questions:
* Redundant or irredundant? (i..e learnt or non-learnt) I will return each separately, with a different function.
* Which solver? If there is more than one thread, it's non-trivial. The function will have a parameter indicating which one, e.g. `num_irred_clauses(unsigned thread)`
* How should it behave in case UNSAT has been found that is at decision level 0, i.e. irrecoverable (in other words, not through assumptions). I will make it so that it will throw a C++ exception. In such cases the number of (ir)redundant is wrong and may return any number, 0 or infinite or anything as the solver is in an incorrect state.

Note that the number of irredundant clauses can (and most likely will) *decrease* over the solving. This is due to variable elimination, equivalent literal replacement, etc.

**Comment by MPaulmier** [comment]
We originially thought of this as a way to (re)build the CNF file from the solver. This would be very convinient for the python interface for example. 
I think a function with the number of threads would fit multiple needs (not only ours with only 1 thread).
I don't know about the UNSAT scenario, we only thought of getting the number of (irredundant I guess) clauses before the solving and not after it, so I'm not sure I can give my point of view on this. 

As I told you, we are still only discovering the code and we may find other ways (I've just seen an open_file_and_dump_[ir]red_clauses function that may comme handy judging by its name) to do what we want to achieve.

**Comment by msoos** [comment]
Why is that convenient? I don't understand now. Why would you need to re-build it? What's the point? I mean, you insert the clauses so you know what you put in :D If you want to use it as a simplification engine, I understand, but that's a different thing. Do you want to use it as a simplifier? Then it would make sense :) Also note -- variable renumbering would make this VERY complicated in most cases. Are you sure you need this? What is the ultimate goal?

**Comment by MPaulmier** [comment]
What we're trying to achieve is being able to get the DRAT file through the python interface so we can verify an unsat proof and build a graph from this file. Since `DRAT-trim` takes a CNF file + the DRAT file we need to build this file since it doesn't exist in this case.

We're not exactly sure how we're going to do that. From what we understand, getting the DRAT file shouldn't be too much of a hard thing to implement (`solver->set_drat`). I must say now I've written this I'm not really sure that getting the number of clauses is really what we need but rather a way of accessing them (which we didn't find yet).

**Comment by msoos** [comment]
Waaaat. Why don't you just record every clause that you add with add_clause(), put it in a CNF file and then supply DRAT-trim with the created CNF and the DRAT file? That would be the way to go. Definitely. Otherwise, when you "get" the clauses from the solver, it will already be a simplified set of clauses, which may have had an error inserted by the SAT solver! You must verify the ORIGINAL set of clauses and you will *never* be able to do that by getting the clauses from the solver. You have to just create a new function that simply writes the clause to a file and then calls add_clause(). That should be *trivial* to do. Please do that. I am closing this issue because you just need to create a wrapper to add_clause that creates a CNF. Me adding functionality to the solver would not only be a lot more complicated, it would actually be *incorrect* and DRAT might not validate at all. You MUST do this *at the time the clause is added by you*.
