### ISSUE TITLE
floating point exception (CMS-df0a11b1676fb)

### ISSUE THREAD

**Issue by anma77** [msoos/cryptominisat#455]
Hello Mate, I had a "floating point exception" with a hard random instance which I downloaded from the last SAT-Solver competition (2017). My CMS-version is from 14 July 2017 (df0a11b1676fb).
The Instance is: 
RandomSat/unif-k7-r87.79-v98-c8603-S1013303228989944376.cnf
I have used default switches 👍  
cryptominisat5-df0a11b1676fb014 --verb=4 --threads=48 unif-k7-r87.79-v98-c8603-S1013303228989944376.cnf
Could it help to send you the log-file?
Best regards and thanks,
A

**Comment by msoos** [comment]
Wow, Thanks for the detailed report! I'll look into it tonight. It
shouldn't happen, thanks for catching it!

**Comment by msoos** [comment]
Yes, could you please send me the log file? And the crash place too, if you have it? It usually prints a backtrace. If you could send that that would REALLY help. Since you used multi-threaded solving, there is only about 20% I can solve this without the backtrace (i.e. where the exception occurred, which line).

Thanks in advance!

**Comment by msoos** [comment]
Yep, I can't reproduce it, due to the multi-threading giving non-reproducible runs. Do you have the log and the backtrace/detailed error by any chance? I think it will help :) Thanks!

**Comment by msoos** [comment]
Unfortunately, I can't reproduce this. Sorry. Closing.

**Comment by anma77** [comment]
I have a job at work running multithread with the debugger. I will see the results tomorrow.

**Comment by msoos** [comment]
That would be awesome! The problem is, CMS is non-deterministic when it comes to multi-threading. So you may well not hit the bug again... I couldn't hit it :(

**Comment by msoos** [comment]
By the way, most likely, the issue was `--verb 4` if you don't put that in, it will most likely work like a charm, without any issues :) I am now fuzzing with `--verb 4 ` so I have not completely shelved this issue, and I am changing the fuzzer to put `--verb 4` in there once in a while :)

**Comment by anma77** [comment]
I use the --verb 4 because I track down internal statistics of the solver in his effort to solve cryptographic instances. I believe I have some remarkably good results which I intend to send to the SAT-Solver conference ("pragmatics") this year. Maybe we make CMS even more famous ;-)
Cheers, A.

**Comment by msoos** [comment]
Wow, that's great. Also, I'm happy the stats are useful. Can you tell me what stats you are interested in? Maybe I can expose that differently, or take more care about them, etc. I just want to know how the solver is being used so I can help users more :)

**Comment by msoos** [comment]
I couldn't reproduce the issue, I have been fuzzing for a while. I am still interested how you are using the statistics, though. Can you please let me know in an email? Thanks, would be nice to know!
