### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by saraedum** [msoos/cryptominisat#456]
cryptominisat is not packaged for Debian yet.

What needs to be done to package this?

**Comment by msoos** [comment]
OK, so release time is basically here. I need some feedback if the current "master" has any issues that you can find. Obviously I have fuzzed this to eternety and have ran it on a cluster a few hundred times so it's supposed to be OK. However, I don't have a too heterogenous environment. All the AppVeyor and TravisCI stuff passes so at least it builds on Ubuntu and MacOS and Windows. Can you please take a look?

**Comment by msoos** [comment]
The 5.6.0 has been tagged as a pre-release. Please let me know if you have any trouble packaging it, then I'll just make a 5.6.1. Thanks!

https://github.com/msoos/cryptominisat/releases/tag/5.6.0

**Comment by saraedum** [comment]
I haven't really started packaging this yet. But I might give this another try now.

**Comment by msoos** [comment]
OK, release is out:

https://www.msoos.org/2018/06/cryptominisat-5-6-3-released/

Yaaaay!! Can you please package this? Let me know if you have *any* issues, I'm very much in favour of packaging this as easily as possible :)

**Comment by saraedum** [comment]
Would you mind dropping the `debian/` directory? It's not recommended by Debian to have such a directory (and I am going to replace it anyway.)

**Comment by msoos** [comment]
OK, I now pulled your request, I think this is closed again now :) Thanks so much for helping me along the way :)

Mate

**Comment by slel** [comment]
Reference: https://github.com/msoos/cryptominisat/pull/501

**Comment by saraedum** [comment]
@msoos can we open this one again until there's actually a Debian package?

**Comment by msoos** [comment]
Sure :) I'll try to make you the owner but not sure that's possible :) But
yeah, just open it! Thanks again for taking care of this, it's
super-helpful. Also please let me know if I can do anything in terms of
automation or adding files to the repo that could help. If you have a build
file/set of files, please let me know where you are keeping them, I want to
link to it in case someone wants to build the package themselves. Also you
it could be useful as a test to see things build in Debian as part of a
Continuous Integration test. Thanks!

**Comment by saraedum** [comment]
I lack the permissions to reopen this one it seems.

**Comment by msoos** [comment]
Reopened :)

**Comment by saraedum** [comment]
Here is what I have so far https://salsa.debian.org/saraedum-guest/cryptominisat. It would be great if you could create a new release, so I can drop the patches and simplify the copyright file.

**Comment by msoos** [comment]
Wow, that sounds cool! I have tagged 5.6.4 and released it. I had a look at your work, looks perfect. A shame that the "docs/" had to go. It's irrelevant, but damn, licensing is hard. Should probably be a different repository to be honest.

Thanks so much again and looking forward to having CMS 5.6.4 in Debian :)

**Comment by saraedum** [comment]
The latest package is here https://mentors.debian.net/package/cryptominisat. I am now waiting for feedback from debian-science.

**Comment by msoos** [comment]
Wow, cool! Thank you so much! I should put this link somewhere... it's cool, actually.

**Comment by msoos** [comment]
Wow, that amazing! We have a new version out btw (nothing serious, minor
changes). So once this gets in the queue and all is approved, newer
versions will be easier to push through, right? Is there some doc you could
point me to so I can understand how this approval system works? Thanks so
much for all your hard work!

**Comment by msoos** [comment]
So I'm closing this as I think this kinda sorts this issue out :) Thanks so much! Please open a new one in case I need to do something. I think there is no action here to be done so that's why I want to close :)
