### ISSUE TITLE
Include OSX fixes from conda

### ISSUE THREAD

**Issue by saraedum** [msoos/cryptominisat#457]
@msoos would you mind incorporating the changes in https://github.com/conda-forge/staged-recipes/pull/5185 to your upstream source?

**Comment by msoos** [comment]
Wow, such a trick!! This one I love!

```
execute_process(COMMAND ${PYTHON_EXECUTABLE} -c "import sysconfig; print(sysconfig.get_config_var('CFLAGS'), end='')" OUTPUT_VARIABLE PY_C_CONFIG)
```

Back when python 2 was supported, I was doing all sorts of hackery to get python-config to run the right python version (2 or 3, depending). I am now only supporting 3... will that break conda? I can go back to both 2&3 if that would break conda.

**Comment by saraedum** [comment]
I also did not know until recently that `python-config` is not the right way to get flags to build extension modules. I think that this approach should also work for Python2.

**Comment by saraedum** [comment]
Conda builds the extension module only for Python3. I don't know how important you deem it to provide the module for Python2? Cryptominisat is going to work now (from the command line) with conda no matter the Python version.
Actually, Sage runs Python2 and loads (as an optional module) `pycrpytosat`…I'll create a followup issue.

**Comment by msoos** [comment]
Well, I'd prefer if everything used Python 3 -- the newer versions of CMS only build the Python3 module actually. It's easier and cleaner...

**Comment by msoos** [comment]
Ahh, actually, that `end=''` doesn't work on python2 because print is not a function :) So this is a fix for it:

```
execute_process(COMMAND ${PYTHON_EXECUTABLE} -c "
from __future__ import print_function;
import sysconfig;
print(sysconfig.get_config_var('CFLAGS'), end = '')"
    OUTPUT_VARIABLE PY_C_CONFIG)
```

The other is then:

```
execute_process(COMMAND ${PYTHON_EXECUTABLE} -c "
from __future__ import print_function;
import sysconfig;
print(sysconfig.get_config_var('LDSHARED').split(maxsplit=1)[1], end = '')"
    OUTPUT_VARIABLE PY_LD_CONFIG)
```
