### ISSUE TITLE
Build pycryptosat for Python 2

### ISSUE THREAD

**Issue by saraedum** [msoos/cryptominisat#459]
and not only for Python 3.

See #457 for a bit of discussion.

**Comment by msoos** [comment]
So this is because of Sage? I'm happy to do that for Sage, but if we can move Sage to Python 3, that'd be probably the optimal solution?

**Comment by saraedum** [comment]
Sage is moving to Python 3 but it's a massive project that already takes a few years in the making. I am quite sure it won't happen in 2018.

**Comment by msoos** [comment]
Note that the CMS that has been released and that the conda is packaged against supports Python2 I believe. I will now re-introduce Python 2 into CMS :)

**Comment by msoos** [comment]
This is definitely being tackled now and Travis will fail to build unless the Python2 module works. So this is effectively fixed because I get an email every time it isn't. Note that in local testing it works fine and preliminary testing in TravisCI also indicates it's good :)

**Comment by saraedum** [comment]
Great! Please let us know at https://github.com/conda-forge/cryptominisat-feedstock/issues/2 when this has been released officially.

**Comment by msoos** [comment]
Release time is close. Can you please check if the Python2 module is OK? Thanks!

**Comment by msoos** [comment]
The 5.6.0 has been tagged as a pre-release. Please let me know if you have any trouble packaging it, then I'll just make a 5.6.1. Thanks!

https://github.com/msoos/cryptominisat/releases/tag/5.6.0

**Comment by saraedum** [comment]
Ok. Let me check.

**Comment by saraedum** [comment]
Works fine.
