### ISSUE TITLE
appveyor Artifact download

### ISSUE THREAD

**Issue by a1880** [msoos/cryptominisat#461]
When I try to download a recent artifact like
https://ci.appveyor.com/api/buildjobs/n92gh40vd6q9sav8/artifacts/cryptominisat.zip
my browser grumbles about a certificate error.
I can get arround this using "wget --no-check-certificate", but this should not be necessary.

**Comment by msoos** [comment]
Your certificate store is probably off. Please update your browser to either Firefox or Chrome and/or make sure your certificate store is correct. The certificate issued to AppVeyor is by:

COMODO RSA Extended Validation Secure Server CA

It expires on:

9 December 2018

which is an EV certificate, so it's probably quite expensive and should work everywhere. This works for me and should work for everyone. In case the problem persists, please raise it with AppVeyor. unfortunately, I have no control over this certificate.

**Comment by a1880** [comment]
Well, I tried Internet Explorer 11, Google Chrome and Firefox, all up-to-date. Could it be that COMODO certficates are banned from Windows/Microsoft? I'll try from my company notebook tomorrow.

**Comment by msoos** [comment]
It may be your certificate store. Check how to fix that in Windows -- I don't use Windows so I don't know. In either case, please raise this issue with AppVeyor, as I cannot control the certificate they are using :(

**Comment by a1880** [comment]
At the risk of boring you: Today it worked right away, both in my office and at home. My suspicion is that AppVeyor is using a Content Delivery Network, where certain CDN nodes do not deliver a complete chain of PKI certificates.
