### ISSUE TITLE
release

### ISSUE THREAD

**Issue by videlec** [msoos/cryptominisat#463]
cryptominisat is broken (at least ion my computer) since already 7 months (see [ticket 23533](https://trac.sagemath.org/ticket/23533 ticket 23533). We would like to move forward in Sage and might package cryptominisat 5.0.2. However, it is marked as a prerelease. Is there any plan for a release soon?

**Comment by msoos** [comment]
OK, so CMS correctly and definitely works with both Python2 and Python3. As for the release... there are some performance bugs. That's the only issue. I am trying to fix them.

**Comment by msoos** [comment]
Just discovered a bug, I gotta fix this... I'll get back to you once it's fixed :)

**Comment by msoos** [comment]
Heads up, release in 5 days :) I have tagged a few but I will release the final one on Tuesday.

**Comment by cipherboy** [comment]
@msoos What's the status on this? I see a couple of newer tags, but not a "release' on GitHub. 

I'll poke the Fedora packager, but we'll probably be late for the Fedora 28 release (Tuesday).

**Comment by msoos** [comment]
Ah crap. Sorry. Yes, I plan to release one super-soon. I have made a lot of changes that really improve many-many things. So I'm happy for a new release to come along but I need to first performance-test it. I don't want to release a crappy version accidentally where the options haven't been tuned right.

**Comment by anma77** [comment]
Good evening from Bonn! Release f5c0c69572f9a86a terminates with a floating point exception when run with --threads = 25, 31, 35 threads. It is compiled on Debian Linux sid with 
cmake -DCMAKE_BUILD_TYPE=Release -DUSE_GAUSS=ON -DLARGEMEM=ON .
21 Threads seem to run much longer but hasn't found a solution yet.
scooby do something!

**Comment by anma77** [comment]
the magical limit seems to be 23 threads which runs! From 24 threads and on it crashes for at least two different CNF-Files, one of which has been solved successfully with your older CMS-versions: 3843 38cc8c24

**Comment by msoos** [comment]
Sorry, I can't reproduce that. Can you please run it under GDB and find the thread that produced the fault and tell me what line of code it does it on? It would be _very_ helpful. I can't reproduce it :( Thank you so much in advance!

**Comment by anma77** [comment]
Hello, compiling with
```
cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_GAUSS=ON -DLARGEMEM=ON .
make -j16 cryptominisat5
```
running with gdb results reproducibly in
```
gdb --args cryptominisat5 --threads=24 s-4r-ab-1kpa.cnf.gz
...
Thread 25 "cryptominisat5-" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffb27fc700 (LWP 82257)]
0x00007ffff7aed60e in CMSat::Solver::iterate_until_solved (this=0x5555558fd2b0)
    at /home/opt/cryptominisat.git-f5c0c69572f9a86a-lm/src/solver.cpp:1670
1670	            long modulo = ((long)iteration_num-1) % conf.modulo_maple_iter;
(gdb) print iteration_num
$2 = 1
(gdb) print conf.modulo_maple_iter
$3 = 0
```
I hope this helps.

**Comment by msoos** [comment]
Yep, I'm an idiot, thanks, fixed!

**Comment by anma77** [comment]
I also took a look at `update_config()` in `cryptominisat.cpp`. The problem seems to be that you use `thread_num` in the `case default` although you changed it at the beginning of the function:
```
    thread_num = thread_num % 23;
```
Wouldn't it be better to omit this line and instead write
```
    switch(thread_num % 23) {
```
?

**Comment by msoos** [comment]
OK, done :) Thanks!

**Comment by msoos** [comment]
The 5.6.0 has been tagged as a pre-release. Please let me know if you have any trouble using or packaging it, then I'll just make a 5.6.1. Thanks!

https://github.com/msoos/cryptominisat/releases/tag/5.6.0

**Comment by msoos** [comment]
OK, release is out:

https://www.msoos.org/2018/06/cryptominisat-5-6-3-released/

Yaaaay!!
