### ISSUE TITLE
Wrong target names for libraries in cryptominisat5Config.cmake.in

### ISSUE THREAD

**Issue by rgov** [msoos/cryptominisat#464]
When I build CryptoMiniSat from master, I noticed that it sets

```
set(CRYPTOMINISAT5_LIBRARIES cryptominisat5)
```

I believe that should be an absolute path. The documentation for [`link_directories`](https://cmake.org/cmake/help/v3.0/command/link_directories.html) says: "Library locations returned by `find_package()` and `find_library()` are absolute paths."

**Comment by rgov** [comment]
I think it is definitely wrong but the CMake documentation is all over the place on this.

**Comment by rgov** [comment]
ngladitz on #cmake pointed out that this value for `CRYPTOMINISAT5_LIBRARIES` doesn't make sense since `cryptominisat5` is not the name of the target, it's `libcryptominisat5`.

    set(CRYPTOMINISAT5_LIBRARIES libcryptominisat5)
    set(CRYPTOMINISAT5_STATIC_LIBRARIES libcryptominisat5)

When I make those changes, it works.

**Comment by msoos** [comment]
Thanks for the heads-up, fixed!

Mate

**Comment by rgov** [comment]
Not exactly, you can't just prefix every target named with `lib`, it has to match what's in the cryptominisat5Targets.cmake file, e.g., `ipasircryptominisat5` and not `libipasircryptominisat5`.

**Comment by msoos** [comment]
Okay, I think it should work now!

**Comment by msoos** [comment]
Please close if this is OK :)

**Comment by rgov** [comment]
End-to-end build of STP worked fine.

**Comment by msoos** [comment]
Thanks!
