### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by saraedum** [msoos/cryptominisat#466]
Does cryptominisat have a man page? I think it would be nice if it had one.

**Comment by a1880** [comment]
With "--hhelp" you get 293 lines of automatically generated help text as a long version of "--help".

Some parameters are really complicated to explain. A man page would be helpful but rather hard to keep up-to-date. Do you know of any other SAT solver which could serve as role model in terms of man pages?

**Comment by saraedum** [comment]
Hm, no I don't. I just worked on a Debian package and `lintian` is complaining about the missing man-page. I will have a look around to see if there's an easy solution that does not add a maintenance burden.

**Comment by saraedum** [comment]
There's [`help2man`](https://www.gnu.org/software/help2man/). I'll try to see if I can modify the output of `--hhelp` a bit to make the generated man page look reasonable.

**Comment by msoos** [comment]
Wow, thanks to the both of you, great input! I'm creating a section in the cmake file that will auto-create the manpage based on `help2man` and install it automatically :) Should fix the underlying issue in the right way! Thanks again! I'll comment here when it's done :)

**Comment by saraedum** [comment]
Thanks for looking into this @msoos! I think it would be nice to generate man pages for `cryptominisat`, `cryptominisat5`, `cryptominisat_simple`, and `cryptominisat5_simple`.
What is making things a bit complicated is that the output of `--version` is not understandable to `help2man` (because of the leading `c` mostly.)
So, here is what I had played with yesterday. This command produced almost reasonable output:
```
help2man --help-option=--hhelp ./cryptominisat -i name -N --version-string=5.1.2
```
I have `cryptominisat` symlinked to `cryptominisat5` and have a file `name` that contains
```
[NAME]
cryptominisat
```

**Comment by saraedum** [comment]
Let me know if you want to collaborate on that on some branch.

**Comment by msoos** [comment]
Nice! Yeah, I'm doing mostly that, but fixing the leading "c" etc. :) So things are progressing, I just don't want to push a half-baked solution. It's almost there... give me 20 more minutes :)

**Comment by msoos** [comment]
OK, a version has been pushed :) Please take a peek and close if appropriate. It does not work for Mac right now, I'm not sure it's trivial to make work.

**Comment by saraedum** [comment]
Great. I left a few comments on your commit. Not sure what we want to do about them. Anyway, this is bringing me much closer to do something about #456 :)

**Comment by msoos** [comment]
OK, added manpage for the "simple". Also, I realised I broke some config setups before. Fixed now, hopefully.

**Comment by msoos** [comment]
manpage is now auto-generated and installed for both binaries. This closes the issue. Thanks for this, I completely forgot and it's really cool actually. I can now do "man cryptominisat5"... easier than --hhelp with less :)

Thanks again for everyone!
