### ISSUE TITLE
AppVeyor Visual Studio 2017 version is VC++ 2015 inside

### ISSUE THREAD

**Issue by a1880** [msoos/cryptominisat#467]
Somehow, the Visual Studio version is not up-to-date. These days, a massive update of Visual Studio 2017 was rolled-out which promised better performance for the compiled binaries.

**Comment by msoos** [comment]
Yeah, sorry, it's not under my control :( Note that I compile with both
VC2015 and VC 2017. Check out the configs on Appveyor :) Please close
unless there is a way of changing this from our end. This seems to be an
Appveyor issue :S Try raising with them please!
