### ISSUE TITLE
Is this cryptominisat or cryptominisat5?

### ISSUE THREAD

**Issue by saraedum** [msoos/cryptominisat#468]
When distributing cryptominisat, should it be installed as `cryptominisat`, as `cryptominisat5`, or as both? What should we refer to in documentation such as man-pages? (see #466)

**Comment by saraedum** [comment]
In a similar direction: Should we distribute the `_simple` version at all? Is there a reason to install `cryptominisat5_simple` if `cryptominisat5` is available?

**Comment by msoos** [comment]
It's cryptominisat5, let's not call it cryptominisat, or we'll get into conflicts with old installations, etc. I prefer cryptominisat5.

**Comment by msoos** [comment]
There isn't a good reason to install _simple in case the full is available. It's usually installed anyway, but it is confusing, I agree

**Comment by saraedum** [comment]
Ok. I'll change the conda package accordingly.
