### ISSUE TITLE
Compilation error when building using Cygwin 64

### ISSUE THREAD

**Issue by ajohnson1** [msoos/cryptominisat#469]
Thank you for providing Cryptominisat - it looks to be a clever program.

I tried building cryptominisat from master on Windows 7 64-bit under Cygwin 64 following the Linux instructions.

I got a compilation error at the make stage:

[ 88%] Building CXX object cmsat5-src/CMakeFiles/libcryptominisat5.dir/cryptominisat.cpp.o
/cygdrive/c/Users/ADMIN/Downloads/cryptominisat-master/src/cryptominisat.cpp: In member function ‘void CMSat::SATSolver::set_gauss_config(const CMSat::GaussConf&)’:
/cygdrive/c/Users/ADMIN/Downloads/cryptominisat-master/src/cryptominisat.cpp:900:5: error: ‘cerr’ was not declared in this scope
     cerr << "ERROR: Gauss not compiled, cannot set gauss config." << endl;
     ^~~~
/cygdrive/c/Users/ADMIN/Downloads/cryptominisat-master/src/cryptominisat.cpp:900:5: note: suggested alternative:
In file included from /cygdrive/c/Users/ADMIN/Downloads/cryptominisat-master/build/cmsat5-src/cryptominisat5/cryptominisat.h:32:0,
                 from /cygdrive/c/Users/ADMIN/Downloads/cryptominisat-master/src/cryptominisat.cpp:24:
/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/include/c++/iostream:62:18: note:   ‘std::cerr’
   extern ostream cerr;  /// Linked to standard error (unbuffered)
                  ^~~~
make[2]: *** [cmsat5-src/CMakeFiles/libcryptominisat5.dir/build.make:951: cmsat5-src/CMakeFiles/libcryptominisat5.dir/cryptominisat.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:198: cmsat5-src/CMakeFiles/libcryptominisat5.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

I noticed that in cryptominisat.cpp all other uses of 'cerr' are 'std::cerr' so I changed it to that and the recompilation succeeded.

make install

then worked to install Cryptominisat into Cygwin, and then I could successfully run cryptominisat under Cygwin on Windows 7.

**Comment by ajohnson1** [comment]
Thanks for the change.

I also managed to get the full version to compile under Cygwin64 on Windows 7.

As I recall, the commands I used were as follows:

get boost from [Boost.org](www.boost.org) e.g. [boost_1_66_0.tar.gz](https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz)
$ tar xzvf cryptominisat-version.tar.gz
$ cd cryptominisat-version
$ mkdir build
$ cd build
$ gunzip -c ../../boost_1_66_0.tar.gz | tar -xvof -
$ cd boost_1_66_0/
$ ./bootstrap.sh --with-libraries=program_options
$ ./b2
$ export BOOST_ROOT=$(pwd)
$ cd ..
$ cmake ..
$ make
$ make install
$ cp ./boost_1_66_0/bin.v2/libs/program_options/build/gcc-gnu-6.4.0/release/threadapi-pthread/threading-multi/cygboost_program_options.dll /usr/local/bin


Then from another window:
```
$ cryptominisat5
c Outputting solution to console
c CryptoMiniSat version 5.2.1
c CryptoMiniSat SHA revision
c CryptoMiniSat compilation env CMAKE_CXX_COMPILER = /usr/bin/c++.exe | CMAKE_CXX_FLAGS =  -Wall -Wextra -Wunused -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -ggdb3 -Wlogical-op -Wnull-dereference -Wdouble-promotion -Wshadow -Wformat=2 -pedantic | COMPILE_DEFINES =  -DUSE_ZLIB | STATICCOMPILE = OFF | ONLY_SIMPLE = OFF | Boost_FOUND = 1 | STATS = OFF | SQLITE3_FOUND =  | ZLIB_FOUND = TRUE | VALGRIND_FOUND = FALSE | ENABLE_TESTING = OFF | M4RI_FOUND = FALSE | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = ON | PYTHON_EXECUTABLE = /usr/bin/python2 | PYTHON_LIBRARY = PYTHON_LIBRARY-NOTFOUND | PYTHON_INCLUDE_DIRS =  | MY_TARGETS =  | LARGEMEM = OFF | LIMITMEM = OFF | compilation date time = Mar 14 2018 14:20:38
c compiled with gcc version 6.4.0
c Executed with command line: cryptominisat5
c Reading from standard input... Use '-h' or '--help' for help.
```

**Comment by msoos** [comment]
Wow, thanks, I put your HOWTO in the readme and thanked you in the comment :) Thanks again!
