### ISSUE TITLE
[WIP] Floating Point Exception

### ISSUE THREAD

**Issue by cipherboy** [msoos/cryptominisat#476]
I've been running into a floating point exception issue similar to #455 and #351 that I'm working on reproducing. Unlike those, it happens in single threaded mode (default arguments) when a large number of other processes are running (different CMS threads running different jobs), and most frequently occurs on commit e4dc06478cbd687a968b668d5f569adde65693b7. Thoughts?

**Comment by cipherboy** [comment]
It happens on this [CNF](https://github.com/cipherboy/sat/tree/master/cms-issue-476) -- I've reproduced it once.

```
{'id': 30992608, 'checked_out': '2018-03-26 11:32:04.296254', 'compile_time': 52, 'compile_return': 0, 'run_time': 1193189, 'run_return': 136, 'finalize_time': 0, 'checked_back': '2018-03-26 11:51:57.538958', 'results': None}
```

I'm working on running this in GDB, but it appears to be much slower (currently >4x); I'll get you a core dump when it finishes.

**Comment by cipherboy** [comment]
I'm going to close this as a possible (reproducible) duplicate of #455; it is fixed on the latest master (12e23c1d5fc36f23af391d9211569418bfe2945f) for me, but I'll stick with e4dc064 for now until the next release is made. GDB is still running, so I'll post that if it finishes.

Thanks for your work!

**Comment by msoos** [comment]
Thanks! Yeah, I tried to fix a bunch of things in the past commits, I have found some issues myself too :) Let's hope it's fixed now. If you get the exact point it failed, I would of course be happy to check if the bug is still there :)

**Comment by msoos** [comment]
Thanks! I have just pushed a commit.  Please check if it solves the issue :)

Thanks!

**Comment by cipherboy** [comment]
Mate,

Running two checks now: latest master against the problem (which should pass since it did earlier but it does include the new empty checks), and e4dc06478cbd687a968b668d5f569adde65693b7 + cherry picked c2e88be532614beb97d68097bdaa64f3ac69dad9 to see if it addresses the root cause. If it works, I'll push it out to more workers and give it a better testing soon (across more problems).

This line should read empty, not empt, else the code doesn't compile:
https://github.com/msoos/cryptominisat/commit/c2e88be532614beb97d68097bdaa64f3ac69dad9#diff-ebbae61d963c536e5a552ce0bd9c0658R381

Thanks Mate! :)

**Comment by cipherboy** [comment]
I like the latest master and the cherry picked one seems to be working fine. Closing this issue and I'll deploy the master build around. Looking forward to your next release. Good luck at the competition!

**Comment by msoos** [comment]
Thanks! Cheers!
