### ISSUE TITLE
USE_GAUS instead of USE_GAUSS in ifdef?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#482]
https://github.com/msoos/cryptominisat/commit/10387761634fdcedb81eab3ec8445b8680c79b57#diff-12e9d4787317f22b8230f6fe68594463R442

There is 
#ifdef USE_GAUS
instead of
#ifdef USE_GAUSS
???

**Comment by msoos** [comment]
You are absolutely right!! Thanks!!
