### ISSUE TITLE
Usage of randInt()

### ISSUE THREAD

**Issue by jvpeetz** [msoos/cryptominisat#491]
Hi Mate,

regarding the usage of `MiniSatRnd::randInt()` in CMS, I have two remarks:

(1) I think you don't get what you expect in the way you use `randInt()`. For example `randInt(1)` returns almost surely 0 and not fifty-fifty 0 and 1. This is because of the cast in `randInt()` and because `randDblExc()` almost surely never returns 1.0, maybe even never. I did some experiments which never returned 1 for `randInt(1)`. This also concerns the usage where you want to pick one element from an array by chance. The last element is almost surely never chosen. I changed `randInt()` to `return (uint32_t)(randDblExc() * (size + 1))` instead, but saw no significant improvement yet.

(2) In CMS with multiple threads, the pseudo random number generators are seeded identically for all threads. Wouldn't it help the diversification of the threads, if every thread gets seeded differently? As far as I saw, the PRNG is used always in some of the simplification methods.

Regards,
Jörg.

**Comment by msoos** [comment]
WOW. That's some really good observation there! So MiniSat had pretty bad randInt? Here is there code:

```
static inline int irand(double& seed, int size) { return (int)(drand(seed) * size); }
```
That has the same bug as CMS. I should be more careful....

Thank you so much!  fixed them all, right? Commits:

0fd8c5b27b96896d249534d07388969f34c2acd8

51d4149164723bdd06fbbc9fbec435c9aadc1d34

Can you please check?  Thanks!

**Comment by msoos** [comment]
Yeah, you are right. No idea what to do. I am afraid of doing that thing because if the randDblExc() returns 1.0 then we will segfault. that is a bad-bad idea. Currently, it's also bad. Using another random number generator -- OK, but which one? I wanted to use C++11 mtrand but thenI need to use these uniform_int_distribution stuff and I'm not sure how expensive they are?

**Comment by jvpeetz** [comment]
A little test shows that the following variant of  *MiniSatRnd::randInt()` isn't noticeably slower:
```
      uint32_t r = (uint32_t)(randDblExc() * (size + 1));
      return r < size ? r : size;
```
The test program:
```
#include <iostream>
#include "minisat_rnd.h"

using namespace CMSat;
int main (void) {
  MiniSatRnd mtrand;
  mtrand.seed(85413178);
  int zeros = 0, limit = 1000000000;
  for (int j; j < limit; ++j) {
    int r = mtrand.randInt(2);
    if (r == 0) ++zeros;
  }
  std::cout << "yo\n" << "limit = " << limit << ", zeros/limit = " << (double)zeros / limit  << "\n";
  return 0;
}
```

**Comment by jvpeetz** [comment]
For example this C++ example
```
#include <iostream>
#include <random>

int main (void) {
  std::mt19937 mt;
  std::uniform_int_distribution<> dist(0, 2);
  int zeros = 0, limit =   1000000000;
  mt.seed(34671);
  for (int j; j < limit; ++j) {
    int r = dist(mt);
    if (r == 0) ++zeros;
  }
  std::cout << "yo\n" << "limit = " << limit << ", zeros/limit = " << (double)zeros / limit  << "\n";
  return 0;
}
```
takes double as long as `randInt()` but as far as I can tell there's no need for a more severe PRNG.

**Comment by msoos** [comment]
Wow, this was some strange rabbit hole. There was even a segfault bug(!!) where I was using that the random number generator never returned the last element. I think this was a super-wild ride and I'm thankful for your observation. I am now using MersenneTwister and adding a test as well. What the hell was I thinking.

**Comment by msoos** [comment]
Let me know if something is off. But I think that all should be OK now :) Your insight really brought forward some weird bugs. Thank you!

**Comment by jvpeetz** [comment]
I've tested also your Mersenne Twister implementation. That looks good and it's also a bit faster.

**Comment by msoos** [comment]
Thanks again!

**Comment by jvpeetz** [comment]
You're welcome.
