### ISSUE TITLE
Boost failure - Fedora 28 / CMake 3.11.2-1.fc28 / Boost 1.66.0-5.fc28

### ISSUE THREAD

**Issue by cipherboy** [msoos/cryptominisat#492]
When trying to build CMS under Fedora 28 / CMake 3.11.2-1.fc28 / Boost 1.66.0-5.fc28, I get the following warning:
```
$ mkdir build ; cd build ; cmake ..
<~snip~>
CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:398 (find_package)


-- Could NOT find Boost
```

As a result, only the `cryptominisat5_simple` binary is built. I'm not sure there's much you can do to fix this (outside of pulling `FindBoost` into the [build system](https://gitlab.kitware.com/cmake/cmake/merge_requests/1621), which is [messy](https://github.com/conan-community/conan-boost/issues/89)), so I guess the recommendation would be to leave it for now and see when this gets fixed in Fedora's versions. To reproduce:

1. Install a fresh F28 machine.
2. Install required packages:
```
dnf install -y cmake valgrind gcc gcc-c++ automake make autoconf help2man git
dnf install -y libzip-devel boost boost-devel boost-program-options m4ri-devel sqlite3-devel
dnf install -y python3-devel python3-pip python3-setuptools
```
3. Clone CMS and build.

**Comment by cipherboy** [comment]
Never mind, closing. I'm not sure what the issue was but `boost-devel` wasn't getting pulled in on my system. I'll submit a PR with Fedora build dependencies shortly.

**Comment by msoos** [comment]
OK, thanks for looking into the Fedora dependencies!
