### ISSUE TITLE
[Cosmetic] Final total search stats overflow

### ISSUE THREAD

**Issue by deiruch** [msoos/cryptominisat#497]
After a long run, CMS printed out the following stats:

![image](https://user-images.githubusercontent.com/4119188/41667887-57714cba-74ae-11e8-9459-7b297c41c77e.png)

UIP search time, UIP percentage and conflicts/sec seem to be affected by overflows.

**Comment by msoos** [comment]
Thanks! Is that Windows, Linux or MacOS? Is it a 32b or 64b system/executable? I need this so I can debug :) It certainly doesn't overflow in some circumstances so I need to know your exact setup :)

**Comment by deiruch** [comment]
Hope you had a nice vacation :)

The issue occurred on Linux/x64. I tested with the "official" cryptominisat5-linux-amd64-gauss release.

**Comment by msoos** [comment]
I can't reproduce this and so I cannot fix it. I have been looking through the code but I never had anything like this before. I am sorry :(

**Comment by msoos** [comment]
Damn, I can't find this, and I cannot reproduce it. Can you find a way to reproduce this for me? I can use the static binary but what CNF did you use? Can I please have it so I can run it, debug it and fix it? Thanks!

**Comment by deiruch** [comment]
I *think* it was this instance: [xmas1u-30x30-498-0.zip](https://github.com/msoos/cryptominisat/files/2384910/xmas1u-30x30-498-0.zip)

IIRC, I let CMS run on a 28-core machine (56 HT cores) for approx. two weeks.

**Comment by msoos** [comment]
Oh wow! And it didn't crash... that's something I think :D 206M conflicts on the thread so it went OK. Now see it's a timing issue, i.e. we think we used negative time. I have fixed a number of problems e.g. >100% vars set in the output, which is also wrong.

I will fix the timing. That issue has to do with the way we count in case of multi-threading.  I will separate the printing of total stats to per-thread and total wallclock time. Currently, it doesn't specify what it's dividing by. The system should use 2 different timings, one for per-thread and one for total :)

**Comment by msoos** [comment]
Ah, that was a nice catch! I think I managed to finally fix it. My testing is horrible when it comes to multi-threaded use. I basically cannot use my own solver in multi-threaded mode... Oops. I need to invest more time into this use-case. Thanks for pointing this out. Please let me know if you find anything else that is weird/wrong. Note that I have changed the way the CPU solving times are displayed, it's a bit clearer now.

**Comment by msoos** [comment]
Wow, this was more complicated than I thought. It's still not perfect, but it's a hell of a lot better than before. Thank you so much for this, it uncovered a bunch of weird bugs :)
