### ISSUE TITLE
cmsat doesn't build on aarch64

### ISSUE THREAD

**Issue by arrowd** [msoos/cryptominisat#509]
The flag added in

https://github.com/msoos/cryptominisat/blob/a72e161cd202073272a6ff9d4cb394fb3325e58b/CMakeLists.txt#L194

prevents cryptominisat from being compiled on aarch64, because this flag isn't supported on this arch. Here is the build log: http://thunderx1.nyi.freebsd.org/data/head-arm64-default/p472730_s335353/logs/errors/cryptominisat-5.6.1.log

**Comment by msoos** [comment]
Thanks, fixed!

**Comment by msoos** [comment]
Please re-open in case the fix is not sufficient :) And thanks again for reporting, helps a lot!
