### ISSUE TITLE
Solver API for CNF output

### ISSUE THREAD

**Issue by janmazak** [msoos/cryptominisat#511]
I would like to know if there is a public API for getting the CNF
formula from CMSat::Solver (in DIMACS format). It is easy to add
clauses to a solver, so that is probably the simplest way to construct the
formula, but I do not know how to get it into a file (or, preferably, into a
string or sstream, which would be even better in use cases where many "small" formulas are to be processed). Perhaps also with an option to
get a simplified formula, but I am not sure what simplify() does --
the documentation does not say much (or have I overlooked it?) and
I do not know enough details on how SAT solvers work to guess what simplify() does.
(Note: the simplification available from command line via -p option is definitely useful, saves about 30% time on subsequent solving by plingeling, at least for the few instances I tried.)

There is only open_file_and_dump_irred_clauses(), but the output is
not exactly DIMACS and I am not sure what it actually is, and it only
works after simplify() is called.

And there is clausedumper.h, but it does not seem to be "public" API.

**Comment by msoos** [comment]
You should be able to read in a file like:

```
void readInAFile(SATSolver* solver2, const string& filename)
{
    FILE * in = fopen(filename.c_str(), "rb");
    DimacsParser<StreamBuffer<FILE*, FN> > parser(solver, NULL, 2);
 
    if (in == NULL) {
        std::cerr
        << "ERROR! Could not open file '"
        << filename
        << "' for reading: " << strerror(errno) << endl;

        std::exit(1);
    }

    if (!parser.parse_DIMACS(in, false)) {
        exit(-1);
    }

    conf.independent_vars.swap(parser.independent_vars);

    #ifndef USE_ZLIB
        fclose(in);
    #else
        gzclose(in);
    #endif
}
```

If you include `dimacsparser.h`. It should be able to read in a string, too, if you use "CH" instead of FN and pass in a string. Check out stringbuffer.h and dimacsparser.h.

As for dumping a simplified file, it actually should now dump it correctly after simplification. Check it out, and let me know if it's wrong somehow. It should not be as far as I understand, there are even some tests for it I believe :) Let me know if the above helped enough or if you need more. Also, if it actually helped, may I ask you to write up a little how-to so I can put that into the README? I think others might benefit from your work :) Let me know if you have bumped into anything! Good luck!

**Comment by janmazak** [comment]
For dumping, I have tried `open_file_and_dump_irred_clauses()` and the dump file can be read back and solved by cryptominisat, but not by other SAT solvers since it is missing the header "p cnf ...". I would add it myself, but the number of clauses seems not trivial to determine (judging from `open_file_and_dump_irred_clauses_preprocessor()` in `clausedumper.cpp`), and `ClauseDumper` cannot be used since it needs some private data from `SATSolver` in the constructor. So I think I am missing some public API in `SATSolver` which will call `ClauseDumper::open_file_and_dump_irred_clauses_preprocessor()` subsequently resulting in a complete DIMACS file with an appropriate header.

In addition, I would prefer if the method took an output stream as a parameter, then I can not only dump it into a file, but also into a string for further in-memory processing. (I have a use case where formulas are small sometimes, and using file system would mean something like hundreds of file accesses per second, which kills performance.)

**Comment by msoos** [comment]
Ah, I thought the header issue has been fixed. A bit strange... I'll look
into it and fix it. In the meanwhile, can you take a shot at making it take
in a stream? Then we could either pass a stringstream or an open file :) If
you manage to fix it, just make a pull request, I promise to merge it ASAP
:)

**Comment by janmazak** [comment]
I can try to rewrite it to take a stream, but what about backwards compatibility?

**Comment by msoos** [comment]
Wow, thanks for the pull request, see my comments there for what I'd like you to fix so I can pull :)

As for the "p cnf" header. I had a look, the only thing missing is counting the clauses for:

```
dump_blocked_clauses
dump_component_clauses
dump_vars_appearing_inverted
```

I will do this, however, I would first like to pull your change (so as not to break your changes) and then I'll fix this and you'll have a correct header :) I hope that should do the trick! Thanks again!

**Comment by msoos** [comment]
Reopening as there is a bug that can be triggered with:

```
./fuzz_test.py --fuzzlim 1 --seed 84396777 --valgrindfreq 10 --small -m 100
```

I'll look into this later. It might only affect XOR clauses, but I can't be sure. I will have to fuzz this thing more and then I can see :)

**Comment by msoos** [comment]
Also buggy:

```
./fuzz_test.py --fuzzlim 1 --seed 60939567 --novalgrind --valgrindfreq 10 --small -m 100 
```

**Comment by msoos** [comment]
OK, found the bug, closing :) Let me know if it works!

**Comment by msoos** [comment]
Yaaaaay!! I now have JUST what you need :) The DimacsParser has been released and it can be used like this:

```

#include "cryptominisat5/dimacsparser.h"

void readInAFile(SATSolver* solver2, const string& filename)
{
    #ifndef USE_ZLIB
    FILE * in = fopen(filename.c_str(), "rb");
    DimacsParser<StreamBuffer<FILE*, FN> > parser(solver, NULL, 2);
    #else
    gzFile in = gzopen(filename.c_str(), "rb");
    DimacsParser<StreamBuffer<gzFile, GZ> > parser(solver, NULL, 2);
    #endif

    if (in == NULL) {
        std::cerr
        << "ERROR! Could not open file '"
        << filename
        << "' for reading: " << strerror(errno) << endl;

        std::exit(1);
    }

    if (!parser.parse_DIMACS(in, false)) {
        exit(-1);
    }

    conf.independent_vars.swap(parser.independent_vars);

    #ifndef USE_ZLIB
        fclose(in);
    #else
        gzclose(in);
    #endif
}

void readInStandardInput(SATSolver* solver2)
{
    cout
    << "c Reading from standard input... Use '-h' or '--help' for help."
    << endl;

    #ifndef USE_ZLIB
    FILE * in = stdin;
    #else
    gzFile in = gzdopen(0, "rb"); //opens stdin, which is 0
    #endif

    if (in == NULL) {
        std::cerr << "ERROR! Could not open standard input for reading" << endl;
        std::exit(1);
    }

    #ifndef USE_ZLIB
    DimacsParser<StreamBuffer<FILE*, FN> > parser(solver2, NULL, 2);
    #else
    DimacsParser<StreamBuffer<gzFile, GZ> > parser(solver2, NULL, 2);
    #endif

    if (!parser.parse_DIMACS(in, false)) {
        exit(-1);
    }

    #ifdef USE_ZLIB
        gzclose(in);
    #endif
}
```

**Comment by msoos** [comment]
Let me know if this helped :)

**Comment by msoos** [comment]
Hey, did this help? I hope it did! Please let me know. I am closing this issue now, but finally, I hope I could help you -- may be late but it in the end, it got there :)

**Comment by janmazak** [comment]
It does everything I want it to do at present, thanks.  :)
