### ISSUE TITLE
problematic definition of  l_True in solvertypesmini.h

### ISSUE THREAD

**Issue by janmazak** [msoos/cryptominisat#512]
The only way to use l_True is to globally use the namespace ("using namespace CMSat;") beforehand (otherwise g++ flags it as an error). I would expect that namespaces can be used "locally", e.g. CMSat::Lit. Either I just don't understand C++ enough to make it work, or the namespace mechanism does not work that well with #define and C-style preprocessing. Perhaps the definition of l_True (and l_False, l_Undef) can be changed to refer to lbool as CMSat::lbool?

**Comment by msoos** [comment]
Wow, what a find! Of course. Fixed. Please let me know if the fix is not OK. I actually changed it to:
```
#define l_True  ::CMSat::lbool((uint8_t)0) // gcc does not do constant propagation if these are real constants.
#define l_False ::CMSat::lbool((uint8_t)1)
#define l_Undef ::CMSat::lbool((uint8_t)2)
```

By the way, I hate this hack. I'll check on a cluster if I really need this. I was really surprised how this used to help with older compilers (just a few years ago). Maybe it's not needed anymore... I'll check, I promise. In the meanwhile, let me know if the above is OK.

Thanks again for finding this one!

**Comment by msoos** [comment]
OOps, I had to fix that to your suggestion :) The extra "::" made it die :S

**Comment by janmazak** [comment]
The latest commit (e3d5822) contains the version with ::CMSat, which fails to build because of errors like this one:
```
cryptominisat-master/build/cmsat5-src/cryptominisat5/solvertypesmini.h:121:17: error: expected unqualified-id before ‘::’ token
 #define l_Undef ::CMSat::lbool((uint8_t)2)
                 ^~
cryptominisat-master/src/main_common.h:38:48: note: in expansion of macro ‘l_Undef’
         if (solver->get_model()[var] != CMSat::l_Undef) {
                                                ^~~~~~~
```
Perhaps you can push the newest version without extra ::?

**Comment by msoos** [comment]
This has been fixed, please pull :) If it works, please close the issue, thanks!

**Comment by msoos** [comment]
Oh, okay, I found it and closed it, sorry! I fixed it in another branch :O

**Comment by msoos** [comment]
Ah, actually, I am reverthing all of this :) You need to use this as:

```
CMSat::l_True
```

That's it. That will solve all issues. I am using it that way too. Please let me know if this fixes the issue.

**Comment by janmazak** [comment]
Works now.
