### ISSUE TITLE
Create test on dumping CNF from outside interface

### ISSUE THREAD

**Issue by msoos** [msoos/cryptominisat#516]
This is a followup to #511

**Comment by janmazak** [comment]
I have tried it and the dump file created by `open_file_and_dump_irred_clauses()` has header `p cnf 0 4380`, which means zero variables (obviously nonsense) and 4380 clauses. Altogether, there are only 788 lines in the dump, and when I run it through solver via command line, it says
```
c -- header says num vars:              0
c -- header says num clauses:        4380
c -- clauses added: 780
c -- xor clauses added: 0
c -- vars added 100
```
[dump.zip](https://github.com/msoos/cryptominisat/files/2323954/dump.zip)

**Comment by janmazak** [comment]
Is there a way to dump the CNF formula before `simplify()` is called? To get just the formula fed to the solver via `add_clause()`? In particular, what are the reducible clauses that can be dumped, too?

**Comment by msoos** [comment]
I'll fix the header, sorry :) As for the new question, that's another
request, no? If you could explain that in detail in another, new, issue
that'd be great so I can fix it on its own :)

**Comment by msoos** [comment]
This has now been fixed I hope. There is some testing in `clausedumper.cpp` now that should check for header correctness.

The CNF formula should be able to be dumped before `simplify()` is called. I don't see how that should be a problem, so I created a test case for it, and it works. It does not dump the reducible clauses, as it's an irreducible clause dumping that I believe you asked for. Please open an issue and describe how you want the dumping for the reducible part :) Thanks! I am closing unless there is bug. Please let me know if there is a bug somewhere... note that due to BVA you must either disable BVA or you might have extra variables in the CNF that's output. Also, in case of XOR clauses, there will almost always be extra variables even if you disable BVA. However, if you don't use XOR clauses and you disable BVA, the number of variables will be OK.
