### ISSUE TITLE
Automatically increase the maxxorsize parameter if it's cheap

### ISSUE THREAD

**Issue by msoos** [msoos/cryptominisat#526]
Urquhart instances currently cannot be solved due to this issue -- the XOR clauses there are 7 long.

**Comment by msoos** [comment]
Fixed by having cheap-vs-noncheap XOR finding for smaller vs larger XOR clauses. This fixes the Urquhart problems.

**Comment by a1880** [comment]
Hi Mate,
my XOR clauses are 20+ literals long. Do I have to use a special setting to adjust CMS?

**Comment by msoos** [comment]
No, this is for discovering them when their cutting number is 5+ and they
have been blasted. No sane person uses a cutting number larger than 5. So
you are fine. When using XOR clauses this doesn't matter at all.

Please close is the above is sufficient :) Thanks,

Mate

**Comment by a1880** [comment]
Thank you! "close" please
