### ISSUE TITLE
Building static libraries without building a static binary

### ISSUE THREAD

**Issue by 4tXJ7f** [msoos/cryptominisat#529]
Hi @msoos,

It would be really great if it were possible to compile CMS' library statically without compiling a static binary, ideally through the standard [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/v3.3/variable/BUILD_SHARED_LIBS.html) variable. In the easiest case, it should be possible to leave out the `STATIC`/`SHARED` specifiers when calling `add_library()` to achieve this.

This feature would be great for CVC4 because a static library allows the user to not have to decide between dynamically linked or static binary when installing the dependencies. We currently build CMS with `-DSTATICCOMPILE=ON` in our CMS installation script but that causes issues on Fedora where the static versions of glibc and libstdc++ are not available by default and cause the linking of CMS to fail (see https://github.com/CVC4/CVC4/pull/2657).

Thanks!

**Comment by msoos** [comment]
Ah, sorry for the late response! Sure, this is very doable. I'll do it next
week, as I'm at a conference and then on a trip. Let me know if it cannot
wait until then :) It would be exciting if you used CMS in CVC4 as default
:) Have you tried? What kind of results are you getting?

**Comment by mpreiner** [comment]
@msoos I sent you the results a while ago :-)

**Comment by 4tXJ7f** [comment]
@msoos Thanks, really appreciate it! Since we have a workaround there is no hurry :)

**Comment by msoos** [comment]
First of all, thanks for highlighting this issue. I have a feeling this was a bit deeper than I thought. Note that cmake is a bit weird when it comes to shared/static libraries. I have my fingers crossed, though!

The fix might break compilation on some configurations, so I am waiting for the feedback from the CI/CD pipeline. Please let me know if it works for you.

**Comment by msoos** [comment]
Wait... all I do now is take into account `BUILD_SHARED_LIBS`. Should I add a flag to not build a binary? What should I call that? Would `NOBINARIES` work?

**Comment by 4tXJ7f** [comment]
From our side, taking into account `BUILD_SHARED_LIBS` is enough. I've seen that you've already removed the `STATIC`/`SHARED` specifiers from the `add_library()` call and this should actually do the trick. We would then just configure CMS with something like `cmake .. -DBUILD_SHARED_LIBS=OFF`.

**Comment by 4tXJ7f** [comment]
Also, thank you very much for addressing this issue so quickly!

**Comment by msoos** [comment]
Cool, glad it helped! Closing :)
