### ISSUE TITLE
assertion failed in xorfinder.h" with --maxxorsize 9

### ISSUE THREAD

**Issue by ajohnson1** [msoos/cryptominisat#530]
Command `$ cryptominisat5 erin7.sat --maxxorsize 9`

End of output:
```
c --> Executing strategy token: distill-cls
c [distill] long cls tried: 15137/16716 cl-short:3637 lit-r:64 T: 0.79 T-out: Y T-r: -0.01%
c [distill] long useful: 7274/30274/33432 lits-rem: 128 0-depth-assigns: 0 T: 1.59 T-out: Y
c --> Executing strategy token: scc-vrepl
c [scc] new: 0 BP 0M T: 0.00
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 T: 0.02 T-out: N w-visit: 2626
c --> Executing strategy token: str-impl
c [impl str] lit bin: 0 (by stamp: 0) set-var: 0 T: 0.00 T-out: N T-r: 99.96% w-visit: 2626
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 T: 0.00 T-out: N w-visit: 2626
c --> Executing OCC strategy token(s): 'occ-backw-sub-str,occ-clean-implicit,occ-bve,occ-bva,occ-xor,'
c [occ] mem usage for occur      1 MB
c [occ] mem usage for occur      1 MB
c Mem for watch alloc      : 3           MB (1.09      %)
c Mem for watch array      : 0           MB (0.02      %)
c --> Executing OCC strategy token: occ-backw-sub-str
c [occ-backw-sub-str-long-w-bins] subs: 0 str: 0 tried: 800 0-depth ass: 0 T: 0.00 T-out: N T-r: 99.88%
c [occ-sub-long-w-long] rem cl: 291 tried: 151456/75728 (200.0%) T: 0.08 T-out: N T-r: 74.05%
c [occ-sub-str-long-w-long] sub: 5 str: 460 tried: 227184/75728 (300.0)  T: 0.11 T-out: N T-r: 78.00%
c --> Executing OCC strategy token: occ-clean-implicit
c --> Executing OCC strategy token: occ-bve
c [occ-empty-res] Empty resolvent elimed: 0 T: 0.00 T-out: N
c [occ-bve] iter v-elim 0
c cl_inc_rate=1.0, var_dec_rate=1.0 (grow=0)
c Reduced to 1313 vars, 17108 cls (grow=0)
c x n vars       : 1313
c  #try to eliminate:   1313
c  #var-elim        :      0
c  #T-o: N
c  #T-r: 99.99%
c  #T  : 0.02
c [occur] 0.05 is overhead
c [occur] link-in T: 0.05 cleanup T: 0.00
c --> Executing OCC strategy token: occ-bva
c --> Executing OCC strategy token: occ-xor
c [occ-xor] sort occur list T: 0.02
assertion "cl.size() <= sizeof(origCl)/sizeof(Lit)" failed: file "/cygdrive/c/Users/XXXXX/Downloads/cryptominisat-master/src/xorfinder.h", line 66, function: void CMSat::PossibleXor::setup(const std::vector<CMSat::Lit>&, CMSat::ClOffset, cl_abst_type, std::vector<unsigned int>&)
Aborted (core dumped)
```

This is with
```
$ cryptominisat5 -v
c CryptoMiniSat version 5.6.5
c CMS Copyright Mate Soos (soos.mate@gmail.com)
c CMS SHA revision GIT-notfound
c CMS is MIT licensed
c Using code from 'When Boolean Satisfiability Meets Gauss-E. in a Simplex Way'
c       by C.-S. Han and J.-H. Roland Jiang in CAV 2012. Fixes by M. Soos
c CMS compilation env CMAKE_CXX_COMPILER = /usr/bin/c++.exe | CMAKE_CXX_FLAGS =  -mtune=native -Wall -Wextra -Wunused -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -ggdb3 -Wlogical-op -Wnull-dereference -Wdouble-promotion -Wshadow -Wformat=2 -pedantic | COMPILE_DEFINES =  -DUSE_GAUSS -DUSE_ZLIB | STATICCOMPILE = OFF | ONLY_SIMPLE = OFF | Boost_FOUND = 1 | STATS = OFF | SQLITE3_FOUND =  | ZLIB_FOUND = TRUE | VALGRIND_FOUND = FALSE | ENABLE_TESTING = OFF | M4RI_FOUND = FALSE | NOM4RI = OFF | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = ON | PYTHON_EXECUTABLE = /usr/bin/python2.7.exe | PYTHON_LIBRARY = PYTHON_LIBRARY-NOTFOUND | PYTHON_INCLUDE_DIRS =  | MY_TARGETS =  | LARGEMEM = OFF | LIMITMEM = OFF | compilation date time = Dec  8 2018 21:54:04
c CMS compiled with gcc version 6.4.0
```

compiled under Cygwin64 for Windows. I could not reproduce with `../cryptominisat5_fewoptions_Win64` as it didn't have the option.

I haven't had any other problem with CryptoMiniSat compiled under Cygwin but haven't been able to try it with Linux (to rule out a Cygwin specific problem).

The `erin7.sat` file starts:
```
p cnf 1313 17187
c literals 67029
```
but is 721059 bytes long, so might be too long to attach (even cutting the comments reduces it to 355359). I could sent it to you if required.

The file is related to some problems of mine which were selected as part of SAT Competition 2018. See Main.zip : final/Johnson for my problems, though I didn't see it on `sted1_0x0-330.cnf` and that takes longer to solve than `erin7.sat`.

The problem has quite a few natural XORs, so that is why I tried varying the `maxxorsize` option.

Thank you for providing CryptoMiniSat; it is a good solver and using a public repo. makes it easy to see what improvements are being made.

**Comment by msoos** [comment]
Oh wow, thanks, yes, please attach that file to the GitHub issue! (I think
it's possible? -- if not, can you please gzip it and upload somewhere?).
Also, can you please tell me what is the git SHA hash that you compiled?
It's "git rev-parse HEAD", please send that too. Also, did you compile with
-DGAUSS=ON (or any other cmake flags) ? I'm am super excited to fix this!
Thank you so much!

Mate

**Comment by ajohnson1** [comment]
Here is a compressed version of the test case, without comments.
[erin7c.sat.gz](https://github.com/msoos/cryptominisat/files/2690321/erin7c.sat.gz)
I don't have a Git version. I downloaded the zip on December 8 2018; the files inside seem to have a date of  20 November 2018, 23:14

I did recompile it with `-DGAUSS=ON` but not with any other flags.

I'll do a fresh download and rebuild in a clean directory to be sure what I built.

**Comment by ajohnson1** [comment]
Problem still happens with a fresh unzip and build.

Possibly this line is the problem as the size is fixed at 8. 
https://github.com/msoos/cryptominisat/blob/bccc0c2de8981fceab6726db89c1a00e84493783/src/xorfinder.h#L132

I am not sure how big maxxorsize can sensibly be so whether a bigger fixed size is suitable. It would seem unless maxxorsize is limited there will be problems as when I increased it to 32 but chose maxxorsize as 330 it then ran for much longer before failing with `VERBOSE_DEBUG_XOR_FINDER` as follows:
```
Adding to XOR: 48 -106 -463
FoundComb before:
foundComb[0]:
foundComb[1]:
foundComb[2]:
foundComb[3]:
foundComb[4]:
foundComb[5]:
foundComb[6]:
foundComb[7]:
----
Trying to create XOR from clause: -6 -18 -42 -44 -52 -103 131 -138 142 145 150 155 157 162 -173 179 185 187 188 191 193 207 214 235 237 -240 245 250 -252 255 259 263 268 269 -270 274 277 282 -284 291 292 293 -297 304 306 311 312 322 -323 -370 372 -377 -383 384 -401 402 408 -412 413 414 427 429 -435 440 466 -467 468 -473 474
assertion "cl.size() <= sizeof(origCl)/sizeof(Lit)" failed: file "/cygdrive/c/Users/IBM_ADMIN/Downloads/cryptominisat-master-5/src/xorfinder.h", line 66, function: void CMSat::PossibleXor::setup(const std::vector<CMSat::Lit>&, CMSat::ClOffset, cl_abst_type, std::vector<unsigned int>&)
Aborted (core dumped)
```
Whether it is worth dynamically allocating the buffer according to `solver->conf.maxxortofind` or just limiting `maxxorsize` is your call.

By the way - what does conf.maxxortofindslow do? It's not a command line option.

**Comment by ajohnson1** [comment]
Perhaps there is an assumption that maxxorsize <= 32 if size can be as big as maxxorsize:
https://github.com/msoos/cryptominisat/blob/bccc0c2de8981fceab6726db89c1a00e84493783/src/xorfinder.h#L106-L114
Making it bigger than 32 would use too much memory with the allocation resize of `1ULL<<size`.

**Comment by msoos** [comment]
Thanks! It now checks the option. You can bump up MAX_XOR_RECOVER_SIZE in constants.h if you need to.

By the way, having more than 8 long XOR in there, for me, shows that the CNF is not optimally converted and you could have gotten a lot faster solving times. You need to cut your XORs into smaller sizes (4 is best as far as I know) and use intermediate variable(s). Then, CryptoMiniSat could do some fancy things too :)

**Comment by ajohnson1** [comment]
Thank you for your very prompt attention to this.
I don't have a long XOR (they are all just 2 variables and a result, plus another another 2 variables guarding them) and was just exploring the options. I was just curious whether the solving process of my problems like erin7.sat exposed long XOR chains.

I see that having a large maxxorsize could be expensive to process, so 8 is a reasonable limit. It was hard to see from the debug output as `foundComb` was declared as `vector<char> foundComb;` but was set as a bool and appear in the debug output as unprintable chars.

The error message `"ERROR: The '--maxxorsize' parameter cannot be lager than` is useful, though `lager` should be `larger`.

It's still possible to force the assert with `-maxxorsize 8 --varsperxorcut 7` but that is unlikely to happen and I now know not to do that.

Thanks again.

**Comment by msoos** [comment]
Thanks, fixed all of these  :) Let me know if there is anything more!
