### ISSUE TITLE
max number of clauses

### ISSUE THREAD

**Issue by karakchi** [msoos/cryptominisat#537]
Hi, 

What is the maximum number of clauses in cnf that tool can run?

**Comment by a1880** [comment]
The DIMACS parser in cryptominisat uses an 32-bit signed int for `num_header_cls` . I can't tell, if clauses are administered with 64-bit counters internally.
In practice, 2^31 clauses would leed to excessive run-times and/or memory overflow.

**Comment by msoos** [comment]
Yeah, in general too many clauses (more than a few 10s of millions) mean
your modeling was probably not optimal :) Check how you could model things
differently! It will lead to significant runtime speedup for sure.

Good luck!

**Comment by msoos** [comment]
Closing as we are supporting over 100s of millions of clauses. Any other problem is mostly a modelling issue. Good luck!
