### ISSUE TITLE
walksat.cpp breaks build

### ISSUE THREAD

**Issue by a1880** [msoos/cryptominisat#538]
In walksat.cpp line 47, bít should be `_WIN32  `rather than `_WIN23 `
Macro `WINDOWS `referenced in line 56 is undefined. This leads to follow-up problems due to undefined macro `BIGFORMAT `
A workaround would be to replace `WINDOWS `by `_WIN32 || _WIN64`

Cheers!

Axel

**Comment by msoos** [comment]
Thanks. Yeah, that code was braindead. I hope it should be fixed now :) Thanks again!

**Comment by a1880** [comment]
Yes. The Windows build works ok now. Thank you for the quick action.
