### ISSUE TITLE
[pycryptosat] RFC: exposing conflicts

### ISSUE THREAD

**Issue by cipherboy** [msoos/cryptominisat#541]
I'd like to propose exposing conflicts in the Python API.

There's two routes we can take as I see it:

1. Expose it via a `(get_)conflicts` method. Safest option: extends the API and does not change the existing behavior.
2. Expose it via the `solution` parameter when `sat == False`. We could optionally gate this behind a `conflicts=False` optional `kwargs` parameter to `solve(...)`, so users would have to pass `solve(assumptions=assume, conflicts=True)` to have the second tuple parameter be conflicts instead of `None`.

(If you don't like two, we could use the gating flag to return a 3-length tuple of `(sat, solution, conflicts)`...).

Do you have a preference between either of these? If not, I'll probably implement option number two with gating flag.

Thanks!

--- 

Things I need to experiment with / figure out:

1. Is it always true that `len(assumptions) == len(conflicts)`?
2. Is it always true that `assumptions[var] = not conflicts[var]`?

**Comment by msoos** [comment]
What do you mean by `get_conflicts`? There is no `get_conflicts`.

Please be precise because I literally have no idea what you are talking about :( Do you mean

```
uint64_t get_last_conflicts(); //get total number of conflicts of last solve() or simplify() call
uint64_t get_sum_conflicts(); //get total number of conflicts of all time of all threads
```

or

```
const std::vector<Lit>& get_conflict() const; //get conflict in terms of the assumptions given in case the previous call to solve() was l_False
```
Or something completely different? Please be very-very precise. Thanks!

Anyway, any and all of it ought to be exposed as (1) I think. Not breaking anything, not changing return types, etc. Backward compatibility is king :)

**Comment by msoos** [comment]
To answer some of your questions:

* `len(assumptions) == len(conflicts)` -- Nope. But `len(assumptions) >= len(conflicts)` is true.
* Also, only assumptions can be in the conflict returned (hence the above inequality)

Cheers!

**Comment by cipherboy** [comment]
Ah sorry for the confusion. I meant `get_conflict()` -- I saw the `Vector<...>` in the type signature and my mind automatically pluralized it. I'll have a PR today hopefully. :)

**Comment by msoos** [comment]
Ah cool, looking forward! Thanks so much!
