### ISSUE TITLE
Cube and conquer

### ISSUE THREAD

**Issue by Storyyeller** [msoos/cryptominisat#546]
I just came across [this paper](https://www.cs.utexas.edu/~marijn/publications/CCshort.pdf) and was wondering if you thought it would be useful to implement. 

The basic idea is to break the problem into subproblems using lookahead search, and then solve each problem using normal CDCL. The result is faster than applying lookahead or CDCL by themselves.

**Comment by msoos** [comment]
Sure, it's a great idea! Please implement it and create a pull request. I'll be more than happy to review and give constructive feedback to the pull request. Please make sure that it complies on all architectures that CryptoMiniSat compiles on and also please make sure that it doesn't decrease parallel performance. Good luck! I'm closing for now, please re-open in case you have a working pull request ready! Thanks in advance,

Mate
