### ISSUE TITLE
Microsoft VC++ build broken due to variadic macros in Yals.c

### ISSUE THREAD

**Issue by a1880** [msoos/cryptominisat#548]
Hi Mate,
Armin Biere is using a gcc proprietary variadic macro construction in yals.c
This leads to compile errors in Microsoft VC++.
It should be more portable to rename yals.c to yals.cpp and replace "ARGS..." by "...".
Variadic macros are problematic if the parameter list is potentially empty.

In VC++ the following compiles and works for C and C++ files:

```
#define LOG(...) do { } while (0)

#define MYPRINT(format, ...) \
      printf(format, __VA_ARGS__)

```
Greetings!

Axel

**Comment by msoos** [comment]
Thanks! This should work instead :)

https://stackoverflow.com/questions/679979/how-to-make-a-variadic-macro-variable-number-of-arguments

Much easier :)
