### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by maxmitti** [msoos/cryptominisat#549]
Unfortunately, compiling for android with the NDK currently fails, because it doesn't have fpu_support.h.
I could get it compile successfully and also run the example from the readme correctly, once I removed those `#if defined(__linux__)` and their content in yals.c, that correspond to the fpu_support.h usage.
Although, I don't know exactly what the effect of removing it is.

Maybe it would make sense to check for the existence of fpu_support.h in CMake.

**Comment by msoos** [comment]
Ah that's all good!! Can you please send me the diff? That would be really awesome! I'd be really glad to make sure to include that diff! Also, let me know how it works in Android! I am really curious :)

**Comment by maxmitti** [comment]
[0001-Android-hack.patch.txt](https://github.com/msoos/cryptominisat/files/3036070/0001-Android-hack.patch.txt) this is the patch of my quick hack to make it work.

I can give you some real usage experience in a few months, as I'm currently only in the stage of planning to use CMS for a project.

**Comment by msoos** [comment]
Thanks so much! I have just pushed a diff that should do the trick. Can you please check if it works? Thanks!

Mate

**Comment by maxmitti** [comment]
That seems to do the trick.
Thank you very much for the quick fix.
