### ISSUE TITLE
STDIN skipped on Windows 7

### ISSUE THREAD

**Issue by BenBartsch** [msoos/cryptominisat#560]
Executing the precompiled exe-file "cryptominisat5-win-amd64-nogauss.exe" on
Windows 7 Home Premium (64 Bit, SP1) (Intel Celeron CPU 1037U) (4 GB RAM) 
the program does not ask the user for input. The programm skips immediately, informs that 0 Variables and clauses are read and prints "s SATISFIABLE" followed with "v 0".The problem does not arise on other window platforms.

What I tried so far (without success):
- executing shell with as admin 
- installing python (2 and 3)
- installing zlib
- using compatibility mode (vista, etc)

**Comment by a1880** [comment]
What are you trying to achieve?

Cryptominisat is right to state that a CNF with no clauses and no variables is satisfiable.
If you want to input a CNF, you are supposed to feed it into Cryptominisat. 

Use '-h' or '--help' for help, if required. 

Rather than being an interactive program, cryptominisat is a console application which receives its parameters via the commandline.

Example call:

`cryptominisat x.cnf.txt`

**Comment by BenBartsch** [comment]
Cryptominisat has two input modes. You can write the clauses into a file
and open it with CMS.

The second option is to send the clauses to CMS via STDIN. So the user or
another program may transfer the data this way.

I wrote a program which calls CMS severel thousend times and transfers the
clauses using STDIN and reads the result using STDOUT. I could use files,
but I don't want that because it is very very bad for the SSD-Harddrive.

Calling CMS this way worked for me using the precompiled file for linux. It
also worked using the precompiled exe file on windows, except the one
system I mentioned in the bug description. On this system CMS seems not to
wait (block) for user input, instead it directly starts with the
computation .


Axel Kemper <notifications@github.com> schrieb am Do., 30. Mai 2019, 13:05:

**Comment by msoos** [comment]
This seems like some form of miscompilation. The precompiled binaries work, which means MSVC works. I am very busy so I won't be able to spend more time on this issue:( No other report exists that reproduces this bug. This may be your setup :( Most people's compiled executable seem to be fine, and many using Windows use the precompiled binaries, which is the preferred method and seems to work well. Unfortunately, I have many other very pressing matters to attend to, so unfortunately, I will not be able to respond to this any further. Sorry :( Please create a pull request to fix in case you have found the bug! Would be nice to have a fix :) Thanks and good luck!

**Comment by msoos** [comment]
I am closing as this cannot be confirmed.
