### ISSUE TITLE
assertion failed in CMSat::vec<CMSat::GaussWatched>::shrink_

### ISSUE THREAD

**Issue by notwa** [msoos/cryptominisat#561]
I thought the last few commits may have already fixed this issue, but that does not appear to be the case.

I'm using commit 32cfd2d with `-DUSE_GAUSS=ON` and no CLI arguments. these are the last few lines:
```
c Found matrixes: 6 from 557 xors T: 0.01 T-out: N
c [xor-add-lem] added unit 0 bin 0 T: 0.00
c [xor-add-lem] added unit 0 bin 0 T: 0.00
c [xor-add-lem] added unit 0 bin 0 T: 0.00
c [xor-add-lem] added unit 0 bin 0 T: 0.00
c [xor-add-lem] added unit 0 bin 0 T: 0.00
c [xor-add-lem] added unit 0 bin 0 T: 0.00
cryptominisat5: /path/to/cryptominisat/src/Vec.h:114: void CMSat::vec<CMSat::GaussWatched>::shrink_(uint32_t) [T = CMSat::GaussWatched]: Assertion `nelems <= sz' failed.
```

[full logs](https://gist.github.com/notwa/058ee8c1dc8fe198a3fab57ce65a5276/raw/f635b22e7c3ec2dc867ca8a4e262e3254a7fa883/log.txt)
[full cnf](https://gist.github.com/notwa/058ee8c1dc8fe198a3fab57ce65a5276/raw/f635b22e7c3ec2dc867ca8a4e262e3254a7fa883/spacer_test.cnf) (4.2 MiB)
[problem generator script](https://gist.github.com/notwa/058ee8c1dc8fe198a3fab57ce65a5276/raw/f635b22e7c3ec2dc867ca8a4e262e3254a7fa883/spacer_test.py)

PS. thank you for all of your work!

**Comment by msoos** [comment]
Wooooooow!!! Problem generator script!!! Oh man, I needed this so badly! I need to fuzz this thing and I wrote a generator but it was poof at fuzzing multi-matrix setups. This is amazing, thank you so much. Also, I am fixing this issue right now :)

**Comment by msoos** [comment]
Oh, on that note, what is the licence on that script? Can I make it MIT and put you as copyright? I want to put it in my bag of fuzzing scripts :)

**Comment by notwa** [comment]
I'll update the link with an ISC license in a few minutes

**Comment by msoos** [comment]
Thanks! Added to: https://github.com/msoos/cnf-utils/ I will add it to the fuzzer in a moment, so I can catch these :) Fixing bug now...

**Comment by notwa** [comment]
well, it really only generates one problem per value of bits (from 1 to 8), although I suppose you can also vary the depth to be less (likely unsatisfiable) or more (likely redundant). you can also play around with similar problems, like replacing `p.ors(i, o)` with `p.ands` or `p.xors`. in any case, I'm glad you find it useful.

by the way, this is basically a *for-all* with every case tested independently, thus the outer `for b in range(1 << bits)` loop.

**Comment by msoos** [comment]
Wow, this is a hard one. So I managed to reproduce it on a 32b ARMv7. It cannot be reproduced on amd64 or ARMv8 (i.e. 64bit). Now I am hoping I will be able to reproduce this on an x86 32 bit because my 32 bit arm is extremely slow and I basically don't have the capacity to do the debug there. It's a weird bug. Maybe something to do with alignement? Or the vector being changed while pointers are saved and used, causing weird behaviour and crash. I can't tell and it's super-frustrating. I have been working on this for hours but no end... oh well. I'll get to the bottom of this soon :)

**Comment by notwa** [comment]
ah, it segfaults for me on x64 Windows as well though — maybe that's unrelated? I only did it on ARM (my raspi) because it was the nearest thing I had running Linux; I didn't think it was specific to architecture. I can try it in a couple more situations in a bit.

**Comment by notwa** [comment]
oops, I wasn't doing a debug build on Windows. now I can confirm it's the same:
`Assertion failed: nelems <= sz, file C:/msys64/home/notwa/src/cryptominisat/src/Vec.h, line 114`

huh, you're right! this doesn't occur on x64 Linux:
`c [matrix] Disabling ALL GJ-elim in this round.  Usefulness was: 0.00%`
I'll try to take a look into it myself, but my knowledge of SAT internals is very limited 😅

**Comment by msoos** [comment]
OK, I have a guess about what's going on :) Depending on your compiler and architecture, the random number generator used runs differently. This is horrid, but it seems to have slipped in. Anyway, this causes the bug not to manifest in certain builds. I will try to make sure to both fix the bug and the RND generator too. In the meanwhile I have tracked down the bug, yay!

**Comment by msoos** [comment]
Hi,

Can you please try with the latest `master-debug` branch? I think I have fixed the issue :) Thanks!

Mate

**Comment by notwa** [comment]
it does appear to be working so far. I'll try it with a few more problems throughout the day.

**Comment by msoos** [comment]
Thanks! Looking forward to your feedback :)

**Comment by notwa** [comment]
I'm pretty sure it's fixed. I ran through the original cnf on both ARMv7 and Windows x64 as before, and they both found a solution, albeit different ones.

here are the [logs for the ARMv7 machine.](https://gist.githubusercontent.com/notwa/058ee8c1dc8fe198a3fab57ce65a5276/raw/8fb3e4195f39582b8b051ff2ab5a0c6da14da800/log.master-debug.armv7.txt) I didn't catch that it built with gcc instead of clang this time, and the git rev is missing because I grabbed an archive from github, but it doesn't seem to matter. the results are the same up to the sls phase where it would've crashed previously.

here's the [logs for the Windows machine.](https://gist.githubusercontent.com/notwa/058ee8c1dc8fe198a3fab57ce65a5276/raw/8fb3e4195f39582b8b051ff2ab5a0c6da14da800/log.master-debug.windows.txt) this diverges from the ARM run after the first round of Luby restarts, so there's still some inconsistencies between platforms, but at least they're not critical.

here's the [logs for the x64 Linux machine.](https://gist.githubusercontent.com/notwa/058ee8c1dc8fe198a3fab57ce65a5276/raw/8fb3e4195f39582b8b051ff2ab5a0c6da14da800/log.master-debug.linux.txt) these match the results of the ARM run, so there's something funky going on with my Windows build.

in any case, I've been running cryptominisat on my problems and some problems from the 2018 competition and haven't had any crashes, so I believe this particular issue is fixed.

**Comment by msoos** [comment]
Cool, thank you so much for the thorough checking! I need to understand why the two diverge. I am pretty sure it's to do with the random number generator used. I'm using MTRand, which is an early implementation of the Mersenne Twister algorithm. I'll switch to `std::mersenne_twister_engine` from C++11.

This issue could be closed, but I don't know how best to verify the problem with the diverging execution. Let me try to fix and then ask you to re-run to check. Would that be OK?

Thanks so much for all your help already,

Mate

**Comment by notwa** [comment]
sure thing, testing things is the easy part.

I've been poking at a couple things, like replacing fpu_control.h with fenv.h (the latter is available on MSYS and MSVC) but that hasn't changed anything. I guess in retrospect, it wouldn't, since it's only active for the yalsat portion of the solver.

I also looked at the sizes of int/long/long long in case they were behaving differently, but it seems they're the same on these platforms. not a bad sanity check though.

**Comment by notwa** [comment]
oh, I remembered why I was looking at integer sizes in the first place. when I built M4RI on windows, I had to replace some unsigned longs with unsigned long longs to properly hold 64-bit pointers. however, this does not appear to be the issue, because I just tried building cryptominisat with everything disabled and it still diverges at Luby restarts. I'll just wait until you have another test ready.

**Comment by msoos** [comment]
Thank you for all the feedback and analysis, it's really useful! I am torn, though, I want to fix this issue, but I would need to pin this thing down before making changes to the code. Give me a few more days, I need to think this through :) Thanks agian for all the analysis!

**Comment by msoos** [comment]
So you confirmed this is fixed in the master-debug branch. I am still unhappy about the ARM vs. x86 issue but I'll close this for now, as the underlying bug has been fixed. I hope that's OK. Let me know if you experience this issue again, I'll then re-open :) Thanks again r the detailed bug report and your patience!

Mate
