### ISSUE TITLE
Option "-p 1" / "-p 2" looks broken

### ISSUE THREAD

**Issue by sschnug** [msoos/cryptominisat#562]
Hi,

when i was trying to use CMSs preprocessing only, the following happens with the current release (windows + linux; nogauss):

Quite a minimal input cnf (just for demo):

    p cnf 5 3
    1 -5 4 0
    -1 5 3 4 0
    -3 -4 0

Version:

    ./cryptominisat5-linux-amd64-nogauss --version
    c CryptoMiniSat version 5.6.8
    c CMS Copyright Mate Soos (soos.mate@gmail.com)
    c CMS SHA revision 6db37867861bf6aec41042d87638c93207064c34
    c CMS is GPL licensed due to M4RI being linked. Build without M4RI to get MIT version
    c CMS compilation env CMAKE_CXX_COMPILER = /usr/lib/ccache/bin/c++ | CMAKE_CXX_FLAGS =  -mtune=native -Wall -Wextra -Wunused -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -ggdb3 -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Wshadow -Wformat=2 -Wextra-semi -pedantic -Wno-class-memaccess | COMPILE_DEFINES =  -DUSE_ZLIB -DUSE_M4RI | STATICCOMPILE = ON | ONLY_SIMPLE = OFF | Boost_FOUND = 1 | STATS = OFF | SQLITE3_FOUND =  | ZLIB_FOUND = TRUE | VALGRIND_FOUND = TRUE | ENABLE_TESTING = OFF | M4RI_FOUND = TRUE | NOM4RI = OFF | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = ON | PYTHON_EXECUTABLE = /usr/bin/python2.7 | PYTHON_LIBRARY = PYTHON_LIBRARY-NOTFOUND | PYTHON_INCLUDE_DIRS =  | MY_TARGETS =  | LARGEMEM = OFF | LIMITMEM = OFF | compilation date time = Feb 19 2019 21:51:55
    c CMS compiled with gcc version 8.2.1 20181127

Then calling CMS:

    ./cryptominisat5-linux-amd64-nogauss bla.cnf 
    ...
    s SATISFIABLE
    v -1 -2 -3 -4 -5 0

    ./cryptominisat5-linux-amd64-nogauss -p 1 bla.cnf 

    terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast> >'
      what():  boost::bad_any_cast: failed conversion using boost::any_cast
    Aborted (core dumped)

**Comment by msoos** [comment]
Hi,

I believe you are using this wrongly. As per the help, it should be used:

```
USAGE 2: ./cryptominisat5 --preproc 1 [options] inputfile simplified-cnf-file
USAGE 2: ./cryptominisat5 --preproc 2 [options] solution-file
```

So first you create a `simplified-cnf-file` then you solve that and put the solution to the `solution-file` then you run the 2nd command. For example:

```
./cryptominisat5 --preproc 1 stuff.cnf simp.cnf
lingeling simp.cnf > solution
./cryptominisat5 --preproc 2 solution
```

I just did this with your input CNF and it worked. Please note that this is **word-for-word** what's in the README here:

https://github.com/msoos/cryptominisat#preprocessor-usage
