### ISSUE TITLE
Potential API Bug

### ISSUE THREAD

**Issue by alex-ozdemir** [msoos/cryptominisat#569]
Hey Mate,

First off, thanks for developing such a great SAT solver! Using it has been a great experience and I am very grateful!

In the course of integrating CMS's proof machinery into CVC4 we encountered some weird behavior with the CMS  C++ API. I've now reproduced a smaller example of that behavior outside of CVC4. I believe that it is a bug in the API, but I cannot say for sure.

The (possible) bug takes the form of an unsatisfiable CNF which:

* the CMS binary produces a valid DRAT proof for, but
* the CMS C++ API does not seem to produce a valid proof for.

The CNF and the (smallish) use of the CMS API can be found in a branch [here](https://github.com/alex-ozdemir/cryptominisat/tree/api-bug/bug). In that branch there is a [description](https://github.com/alex-ozdemir/cryptominisat/tree/api-bug/bug/README.md) of how to reproduce the surprising behavior. I've also copied that description below.

Let me know if you have any ideas about what might be causing this.

# Description

This directory may contain a testcase which may demonstrate a bug in the CMS
API.

The testcase consists of two files:

   * `cms.cpp`: A program which uses CMS's API to produce DRAT proofs for UNSAT
     formulas
   * `cnf`: An UNSAT CNF.

## Seeing the Unusual Behavior

First, build CMS in a directory named `REPO_ROOT/build`. Then change into
`REPO_ROOT/bug`.

Run `make check-bin` to make & check a DRAT proof using the CMS binary.
This proof should be accepted.

Run `make check-api` to make & check a DRAT proof using the CMS API and
the `cms` program. This proof is rejected!

## Three Potential Explanations

There are three putative explanations:

   1. The `cms.cpp` program is misusing the CMS API.
   2. The CMS API has a bug, causing the produced DRAT proof to be
      unacceptable. Flushing?
   3. The DRAT proof *is* acceptable, and `drat-trim` has a bug.

**Comment by msoos** [comment]
Hi! Thank you so much for the detail bug reprot! I'll get to this issue this week :) Hopefully will be relatively easy to fix :)

Thanks again for reporting,

Mate

**Comment by msoos** [comment]
So, I looked into this. First of all, I see you merged in some stuff from Alexander Scheel -- I am just saying, this stuff may not be merged into the mainline CMS. I am confused why you would use them, actually. Do you need these changes?

Secondly, the bug you reported does not seem to be reproducible. I did all the steps you described, and I'm getting:

```
soos@vvv-dejavu:bug$ make check-api 
drat-trim ./cnf ./drat-from-api
c turning on binary mode checking
c parsing input formula with 3623 variables and 10977 clauses
[...]
c 0 RAT lemmas in core; 14145 redundant literals in core lemmas
s VERIFIED
c verification time: 1.290 seconds
```
This is using the drat-trim from https://github.com/marijnheule/drat-trim

So I am very confused. Maybe the example you gave is wrong?

**Comment by alex-ozdemir** [comment]
First of all, thanks for you attention to this. I know reproducing/debugging obscure issues can be a drag, and I appreciate it.

> So, I looked into this. First of all, I see you merged in some stuff from Alexander Scheel -- I am just saying, this stuff may not be merged into the mainline CMS. I am confused why you would use them, actually. Do you need these changes?

My mistake. I used the `master` branch because I assumed that `master` was the most recent version of mainline CMS development. I've now create a [new branch](https://github.com/alex-ozdemir/cryptominisat/tree/api-bug-5.6.8), `api-bug-5.6.8` in my repository which is based on CMS v5.6.8. This new branch seems to exhibit the same issue.

> Secondly, the bug you reported does not seem to be reproducible. I did all the steps you described, and I'm getting [...]

Interesting. I do believe that I've submitted the example that demonstrates odd behavior. Perhaps we're using slightly different procedures.

To help us figure out the difference, I re-executed my procedure and used [`script`](http://man7.org/linux/man-pages/man1/script.1.html) to record it. Here are the commands that I ran:

```
aozdemir@iliad ~ $ mkdir cms-issue
aozdemir@iliad ~ $ cd cms-issue
aozdemir@iliad ~/cms-issue $ git clone git@github.com:alex-ozdemir/cryptominisat.git
aozdemir@iliad ~/cms-issue $ git clone git@github.com:marijnheule/drat-trim.git
aozdemir@iliad ~/cms-issue $ cd drat-trim
aozdemir@iliad ~/cms-issue/drat-trim $ make
aozdemir@iliad ~/cms-issue/drat-trim $ cd ../cryptominisat
aozdemir@iliad ~/cms-issue/cryptominisat $ git checkout api-bug-5.6.8
aozdemir@iliad ~/cms-issue/cryptominisat $ mkdir build
aozdemir@iliad ~/cms-issue/cryptominisat $ cd build
aozdemir@iliad ~/cms-issue/cryptominisat/build $ cmake ..
aozdemir@iliad ~/cms-issue/cryptominisat/build $ make -j 8
aozdemir@iliad ~/cms-issue/cryptominisat/build $ cd ../bug
aozdemir@iliad ~/cms-issue/cryptominisat/bug $ make
aozdemir@iliad ~/cms-issue/cryptominisat/bug $ ../../drat-trim/drat-trim cnf drat-from-bin
// All good!
aozdemir@iliad ~/cms-issue/cryptominisat/bug $ ../../drat-trim/drat-trim cnf drat-from-api
// NOT VERIFIED
```

The full recording produced by `script` is here [here](https://github.com/msoos/cryptominisat/files/3438751/cms-issue-569.txt), and you should be able to `cat` it to see exactly what I did.

I've also placed the CNF, the binaries (`drat-trim`, `cryptominisat5`, `cms`) and the proofs in [this Google Drive folder](https://drive.google.com/drive/folders/19W8Ya2T6m6Y9cP_xXOQJUrosBQTVaa-h?usp=sharing). I can't promise that they'll run on your machine (they were compiled on Arch Linux v5.2.3, gcc 9.1.0, clang 8.0.1, cmake 3.15.0, glibc 2.29), but I include them in case they're helpful.

Let me know if there is any additional information I can provide you with to help you reproduce this.

Cheers,
Alex

**Comment by msoos** [comment]
Hi,

So it was indeed a bug :) Thank you so much! So now if you pull master, the code should work. Please pull the latest master, though, because it has lots of fixes.

Please also let me know if I can use your `bug.cpp` code -- I would need MIT license. Would you be happy to give that? I want to use it for debugging so this doesn't happen again :) Also, I want to use it as an example code in my README so others can use your work. Would that be OK?

Please confirm that the bug is fixed (I have tested it and it is OK on my end). Please also let me know if I can put an MIT license on your code, copyright by "Alex Ozdemir 2019". Thanks!

Mate

**Comment by alex-ozdemir** [comment]
Hi Mate,

Thanks for looking into this so promptly.

> Please also let me know if I can use your bug.cpp code -- I would need MIT license. Would you be happy to give that? I want to use it for debugging so this doesn't happen again :) Also, I want to use it as an example code in my README so others can use your work. Would that be OK?

I'm happy to let you re-use the example program for testing, documentation, and any other purpose, under the MIT license.

> So it was indeed a bug :) Thank you so much! So now if you pull master, the code should work. Please pull the latest master, though, because it has lots of fixes.
[...]
Please confirm that the bug is fixed (I have tested it and it is OK on my end).

Hmm. I haven't been able to confirm the fix. A question: when you say "latest master" do you mean commit `c87a3e4b1`? I rebased the example API use onto this commit, but am still experiencing the bug. My command sequence:

```
aozdemir@iliad ~ $ mkdir cms-issue
aozdemir@iliad ~ $ cd cms-issue
aozdemir@iliad ~/cms-issue $ g clone git@github.com:alex-ozdemir/cryptominisat.git
aozdemir@iliad ~/cms-issue $ g clone git@github.com:marijnheule/drat-trim.git
aozdemir@iliad ~/cms-issue $ cd drat-trim
aozdemir@iliad ~/cms-issue/drat-trim $ make
aozdemir@iliad ~/cms-issue/drat-trim $ cd ../cryptominisat
aozdemir@iliad ~/cms-issue/cryptominisat $ g co api-fix
aozdemir@iliad ~/cms-issue/cryptominisat $ mkdir build
aozdemir@iliad ~/cms-issue/cryptominisat $ cd build
aozdemir@iliad ~/cms-issue/cryptominisat/build $ cmake ..
aozdemir@iliad ~/cms-issue/cryptominisat/build $ make -j 7
aozdemir@iliad ~/cms-issue/cryptominisat/build $ cd ../bug
aozdemir@iliad ~/cms-issue/cryptominisat/bug $ make
aozdemir@iliad ~/cms-issue/cryptominisat/bug $ ../../drat-trim/drat-trim cnf drat-from-bin
// VERIFIED
aozdemir@iliad ~/cms-issue/cryptominisat/bug $ ../../drat-trim/drat-trim cnf drat-from-api
// NOT VERIFIED
```

Mentioned in the above sequence is the [new branch](https://github.com/alex-ozdemir/cryptominisat/tree/api-fix) I created with the example API usage rebased onto commit `c87a3e4b1`.

Perhaps I'm making some mistake?

Cheers,
Alex

**Comment by alex-ozdemir** [comment]
Ah, also
[here](https://github.com/msoos/cryptominisat/files/3439385/cms-issue-569.txt) is a text file with the `script` transcript for the above session.

**Comment by msoos** [comment]
I believe your Makefile for your bug is incorrectly set up :D It doesn't use the library that's being generated. It uses the library that's installed :S You have to re-install your cryptominisat after re-build. I bumped into this issue while debugging. I have fixed this on my end. I am pushing your code to CMS mainline now :)

Please compile with:

```
git submodules update --init
git pull
cd build
rm -rf cm* CM* lib* cryptomini* Testing* tests* pycryptosat include tests cusp* scalmc* utils drat-trim
cmake -DENABLE_PYTHON_INTERFACE=ON -DENABLE_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
make -j6
make test
```

then run:

```
./utils/minimal_cms/minimal_cms cnf drat
drat-trim cnf drat
```

It should now work :) Hope this helps!

Mate

**Comment by alex-ozdemir** [comment]
Whoops! You are correct -- the system `libcryptominisat5` was being used, not the local one.

Great to see that this is now included.

Thanks for your work on this, and for that information.

**Comment by msoos** [comment]
Glad it worked :) Thanks again for reporting!! Was a fun fix :)

Mate
