### ISSUE TITLE
Print/see/dump, what was found?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#573]
Assume I have the following line outputted by CMS5:

```
c [occ-xor] found      2 avg sz 3.0 min sz  3 max sz  3 T: 1.59 T-out: N T-r: 99.85%
```

Can I somehow see what was found? I think it found 2 XORs during occ?
It does not matter if it prints it during runtime e.g. by some debug level,
or local patch, or even dump clauses to a file? For my test it will find them only
very seldom, so dumping all of them what produce almost no additional info
during my test.

**Comment by msoos** [comment]
Hi,

It's possible to print them, but it will NOT be the external variable numbering. In fact, it would be pretty damn difficult to print it with external numbering. Sorry. Also, 2 XORs are not much at all, so it won't be that interesting, I'm quite sure. If you want to, you can print them with internal numbering here: `add_found_xor()`. That's where all the found XORs are handled.

Cheers,

Mate
