### ISSUE TITLE
adding to cmake 

### ISSUE THREAD

**Issue by karakchi** [msoos/cryptominisat#575]
Hello Author, 

I am trying to run cryptominisat without the using the command, by incorporating it inside my tool. 
I modified the main.cpp. Now, I need to add the new main file to cmake to be built. 

Do you know how I can add the new file to cmake ?? 

Thank you for making your tool public, it is very useful software!!

**Comment by msoos** [comment]
Check out src/CMakeLists.txt

I also suggest for you to read through a few cmake  manuals and howto-s on the internet. There is a lot of documentation about it and I cannot help more with cmake -- this has little to do with CryptoMinISat and everything to do with cmake. Hence, please consult on cmake website, cmake documentation, online forums for build systems, etc.

Good luck!
