### ISSUE TITLE
--onlysampling dumps more variables than in c ind

### ISSUE THREAD

**Issue by vlastikw** [msoos/cryptominisat#576]
My file contains header:
c ind 1 2 3 4 ... etc 200 variables ... 200 0
p cnf 25000 70000
1 0
...

run cryptominisat with ./cms -s 0 --maxsol 1000 --dumpresult aaa.sols --onlysampling aaa.cnf

and it outputs solutions to aaa.sols file with about 10000 variables. Some variables are omitted which is weird. I would expect only 200 variables in each solution. Without --onlysampling it outputs all 25000 variables.

**Comment by msoos** [comment]
I hope this resolves it! Thanks for reporting. Please reopen if it's still an issue!

Thanks!
