### ISSUE TITLE
AppVeyor VS2017 builds use VS2015?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#578]
E.g. this one:
https://ci.appveyor.com/project/msoos/cryptominisat/build/job/wabslt7njrh2nixd

When I look or search for 2017, I find the only text in above comment/description,
but not in console output.

Does it really use "Visual Studio 15 2017 Win64"?

Background: Trying to compile with VS2017 and Boost 1.59.0. But getting the following error:

```
D:\boost_1_59_0>b2 --with-program_options address-model=64 toolset=msvc-15.0 variant=release link=static threading=multi runtime-link=static install --prefix="D:\boost_1_59_0_install" > boost_install.out

D:\boost_1_59_0>type boost_install.out
...found 1 target...
...updating 1 target...
msvc.write-setup-script C:\Users\Marie\AppData\Local\Temp\b2_msvc_14.0_vcvarsall_x86.cmd
...updated 1 target...
...found 1 target...
...updating 1 target...
msvc.write-setup-script C:\Users\Marie\AppData\Local\Temp\b2_msvc_14.0_vcvarsall_amd64.cmd
...updated 1 target...
...found 1 target...
...updating 1 target...
msvc.write-setup-script C:\Users\Marie\AppData\Local\Temp\b2_msvc_14.0_vcvarsall_x86_arm.cmd
...updated 1 target...
D:/boost_1_59_0/tools/build/src/tools\msvc.jam:1072: in configure-really
*** argument error
* rule generate-setup-cmd ( version : command : parent : options * : cpu : global-setup : default-global-setup-options : default-setup )
* called with: ( 15.0 : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64 : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64 :  : i386 :  : x86 : vcvars32.bat )
* missing argument global-setup
D:/boost_1_59_0/tools/build/src/tools\msvc.jam:798:see definition of rule 'generate-setup-cmd' being called
D:/boost_1_59_0/tools/build/src/tools\msvc.jam:201: in configure
D:/boost_1_59_0/tools/build/src/tools\msvc.jam:153: in msvc.init
D:/boost_1_59_0/tools/build/src/build\toolset.jam:43: in toolset.using
D:/boost_1_59_0/tools/build/src\build-system.jam:461: in process-explicit-toolset-requests
D:/boost_1_59_0/tools/build/src\build-system.jam:527: in load
D:\boost_1_59_0\tools\build\src/kernel\modules.jam:295: in import
D:\boost_1_59_0\tools\build\src/kernel/bootstrap.jam:139: in boost-build
D:\boost_1_59_0\boost-build.jam:17: in module scope

D:\boost_1_59_0>
```

Compiling Boost 1.65.1 with VS2017 seems to work. But then CMS5 does not seem to recognize suggested Boost version:

(CMS5 Master)

```
D:\cryptominisat-20191013\build>cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DSTATICCOMPILE=ON -DBOOST_ROOT=d:\boost_1_65_1_install ../
-- LIB directory is 'lib'
-- BIN directory is 'bin'
-- Doing a Release build
-- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.18362.
-- The C compiler identification is MSVC 19.16.27034.0
-- The CXX compiler identification is MSVC 19.16.27034.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- build type is Release
-- Performing Test HAVE_FLAG_-fno-stack-protector
-- Performing Test HAVE_FLAG_-fno-stack-protector - Failed
-- GIT hash found: 7dc1881bb966306bd703d4c1a30a67c837b3c752
-- PROJECT_VERSION: 5.6.8
-- PROJECT_VERSION_MAJOR: 5
-- PROJECT_VERSION_MINOR: 6
-- PROJECT_VERSION_PATCH: 8
-- Could NOT find Boost (missing: program_options) (found suitable version "1.65.1", minimum required is "1.46")
-- Not compiling detailed statistics. The system is faster without them
-- Not on Linux, not creating manpage
...
```

D:\boost_1_65_1_install\lib

contains

libboost_program_options-vc150-mt-s-1_65_1.lib

Am I really forced to use VS2015 and Boost 1.59.0 to get it compiling?

Note: https://www.boost.org/users/history/version_1_71_0.html  (latest)
does also not yet list VS2017 (Visual C++: 7.1, 8.0, 9.0, 10.0, 11.0, 12.0, 14.0, 14.1)

Used cmake is cmake version 3.15.4

**Comment by msoos** [comment]
Hi,

First of all, thanks for the bug report! The system uses VS2015 to validate that it builds. However, it should build on VS2017 as well. Please let me know if it doesn't build on 2017. If it does not, I will update. However, it should! :) Please let me know if it builds on 2017 as well, and if it does, please close the issue. Otherwise, I am happy to merge in a fix, all you need to change is the AppVeyor definition file, here, to use VS2017 and then it will fail and I will debug :)

https://github.com/msoos/cryptominisat/blob/master/appveyor.yml

Please clone, fix, then ask for a pull request and I will gladly merge it!

Thanks for letting me know of this issue,

Mate

**Comment by capiman** [comment]
As written above, I assume it is doing this.

I assume

  - IF "%PLATFORM%" == "x64" ( SET CMAKE_GENERATOR="Visual Studio 14 2015 Win64")

forces it to use VS2015. 

You are already compiling 6 times, 2 images, 3 configuration. But above line forces it to
build two times the same? You need a mechanism which distinguish images
or perhaps separate it into 6 configs?

**Comment by capiman** [comment]
https://www.appveyor.com/docs/build-environment/#visual-studio-preview-images

Something like 

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"

or 

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      IMAGE: "Visual Studio 2015"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      IMAGE: "Visual Studio 2017"

**Comment by capiman** [comment]
https://www.appveyor.com/docs/windows-images-software/#boost

**Comment by msoos** [comment]
You can always try all of these :) Appveyor and GitHub are both free, you just need to edit the appveyor file I have mentioned above. Good luck and let me know which setup worked! Thanks,

Mate

**Comment by capiman** [comment]
See my latest version at
https://github.com/capiman/cryptominisat/

I have changed appveyor.yml to compile for VS2015, VS2017 and VS2019.
I removed the "image" entries and put them into environment matrix.
So now 3-4 entries per image.

I tried to change boost version to 1.71 (difficult thing, with power shell subscript appveyor.ps1 downloading fixed version, from a server which does not (yet?) seem to have latest version).
Ok, changed it to different version (1.71.0) and server. It seems to compile, at least with certain compiler. But now I have the problem: cmake seems to request 1.46, but does not accept 1.71 as valide version. Theoretically same shall happen with 1.59.0?

See my example build (where I have remove output redirection to boost-install.out):
https://ci.appveyor.com/project/capiman/cryptominisat/builds/28112441

-- Found Boost 1.71.0 at C:/projects/cryptominisat/boost_install/lib/cmake/Boost-1.71.0
--   Requested configuration: QUIET COMPONENTS program_options
-- BoostConfig: find_package(boost_headers 1.71.0 EXACT CONFIG  QUIET HINTS C:/projects/cryptominisat/boost_install/lib/cmake)
-- Found boost_headers 1.71.0 at C:/projects/cryptominisat/boost_install/lib/cmake/boost_headers-1.71.0
-- BoostConfig: find_package(boost_program_options 1.71.0 EXACT CONFIG  QUIET HINTS C:/projects/cryptominisat/boost_install/lib/cmake)
-- Found boost_program_options 1.71.0 at C:/projects/cryptominisat/boost_install/lib/cmake/boost_program_options-1.71.0
-- Boost toolset is vc140 (MSVC 19.0.24241.7)
-- Scanning C:/projects/cryptominisat/boost_install/lib/cmake/boost_program_options-1.71.0/libboost_program_options-variant*.cmake
--   Including C:/projects/cryptominisat/boost_install/lib/cmake/boost_program_options-1.71.0/libboost_program_options-variant-vc140-mt-s-x64-1_71-static.cmake
--   [ ] libboost_program_options-vc140-mt-s-x64-1_71.lib
-- Could NOT find Boost: missing: program_options (found C:/projects/cryptominisat/boost_install/lib/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.46"))

Last line NOT! found. Any idea? Is removing version 1.46 an idea? Or using 1.46.0 as 4-number-variant?

**Comment by capiman** [comment]
Even without version check at all it fails.

https://ci.appveyor.com/project/capiman/cryptominisat/builds/28113218

**Comment by msoos** [comment]
The above is not very useful :( If you can make it work, that's great. Otherwise, let me try to handle this. However, I won't promise anything.

I don't understand why this is important at all, actually. Few, if any, use the Appveyor scripts to compile, it will compile under VS2017 if it compiled under VS2015 and Appveyor is only for people and me to be able to download a binary and to validate that it can be compiled in Windows. I will work a bit on this but I don't have to much time to spend on this unfortunately :(

**Comment by capiman** [comment]
I think the not found can be explained:

```
[00:01:03] b2 --with-program_options address-model=64 toolset=%BOOST_TOOLSET% variant=release %BOOST_OPTIONS% threading=multi  install --prefix=%BOOST_ROOT%
[00:01:05] Performing configuration checks
[00:01:05]
[00:01:05]     - default address-model    : 32-bit
[00:01:06]     - default architecture     : x86
[00:01:08]
[00:01:08] Component configuration:
[00:01:08]
[00:01:08]     - atomic                   : not building
[00:01:08]     - chrono                   : not building
[00:01:08]     - container                : not building
[00:01:08]     - context                  : not building
[00:01:08]     - contract                 : not building
[00:01:08]     - coroutine                : not building
[00:01:08]     - date_time                : not building
[00:01:08]     - exception                : not building
[00:01:08]     - fiber                    : not building
[00:01:08]     - filesystem               : not building
[00:01:08]     - graph                    : not building
[00:01:08]     - graph_parallel           : not building
[00:01:08]     - headers                  : not building
[00:01:08]     - iostreams                : not building
[00:01:08]     - locale                   : not building
[00:01:08]     - log                      : not building
[00:01:08]     - math                     : not building
[00:01:08]     - mpi                      : not building
[00:01:08]     - program_options          : building
[00:01:08]     - python                   : not building
[00:01:08]     - random                   : not building
[00:01:08]     - regex                    : not building
[00:01:08]     - serialization            : not building
[00:01:08]     - stacktrace               : not building
[00:01:08]     - system                   : not building
[00:01:08]     - test                     : not building
[00:01:08]     - thread                   : not building
[00:01:08]     - timer                    : not building
[00:01:08]     - type_erasure             : not building
[00:01:08]     - wave                     : not building
```

It is building 32 bit version, but later wants to use 64 bit version. Mismatch!

Found a page with useful infos/combinations/needed parameters for boost:

https://github.com/boostorg/boost-ci/blob/master/templates/appveyor.yml

> Few, if any, use the Appveyor scripts to compile

I assume you get the same problems outside AppVeyor, 
when doing a manually compile with VS2017 and newer, 
not the right boost version, not the right parameters for boost.

**Comment by msoos** [comment]
Please don't update this issue unless you have found a complete fix. Thank
you.

Mate

**Comment by msoos** [comment]
Fixed:

https://ci.appveyor.com/project/msoos/cryptominisat/builds/28157839
