### ISSUE TITLE
Is there a reason that get_sum_* functions in the interface are not marked as const?

### ISSUE THREAD

**Issue by horenmar** [msoos/cryptominisat#581]
I am currently in process of testing CMSat for our use again, and noticed that a lot of functions that probably could be marked `const` are not, for example `get_sum_conflicts`, `get_sum_propagations` and `get_sum_decisions`. Judging by their implementation, they are all de-facto const already, as they only read primitive types.

For my use case it is enough to have `get_sum_conflicts` as const, or I can mark the member `mutable`, but is there a reason why the main interface is not properly const?

**Comment by msoos** [comment]
Oh, good catch, thanks! No, there is no particular reason, I think. Could you please create a pull request with the changes? Thanks in advance,
Mate

**Comment by horenmar** [comment]
I can, but there are two ways to go about this and I don't know which one you want to do.

1) Is to provide overloads that are marked `const`. This has the disadvantage of duplicating code, but it won't break anyone who relies on the method being non-const.
2) Is to just change the method to be `const`. This is better in regards to duplicating code, but can (very potentially) break a user who does something sufficiently weird.
