### ISSUE TITLE
CMSat's public interface could use better documentation

### ISSUE THREAD

**Issue by horenmar** [msoos/cryptominisat#582]
For example, `set_max_confl(int64_t)` says "max conflict to run to on next solve() call". I'd also like it to mention that negative values are ignored, but do not unset previously set limits.

Similarly, `set_max_time(double)`'s documentation says "max time to run to on next solve() call", but does not mention what units are used, and unlike with `set_max_confl`, scrutinizing the implementation does not reveal the answer directly... Given that CMSat is already using C++11, you might consider providing overload that uses `<chrono>`, as that would make it properly self-documenting (and type safe).

-----------

As an aside, the "overflow checking" code in both of these functions is wrong. For `set_max_confl` the problem is that overflowing a signed integer is undefined behaviour and a modern compiler will happily remove the check and its associated code. For `set_max_time` the check does not rely on undefined behaviour, but it will not work on any platform I know of, as `double`s do not overflow at all -- on most platforms they just get set to infinity.

**Comment by msoos** [comment]
Ah, great points, thanks for making them! Can you please submit a pull request to fix these? I would be more than happy to merge! Thanks in advance,
Mate

**Comment by horenmar** [comment]
Are you planning on doxygening up the interface? I've noticed that some places in the code do use doxygen-style comments, while other places do not.
