### ISSUE TITLE
Provide a way to set limit on the wall clock time consumed by a solver

### ISSUE THREAD

**Issue by horenmar** [msoos/cryptominisat#584]
The current way to limit time used by the solver, `SATSolver::set_max_time` operates on CPU time. This means that the time, as perceived by user, can vary wildly from the time I provide to the solver itself.

I would like to be able to set a _wall clock_ time limit, so that I can get the solver to stop in x seconds, regardless of how many threads the solver is running with, or how the OS-level scheduling worked out.

**Comment by msoos** [comment]
Hi,

Ah, good point. Unfortunately, timing is a very weird thing. What if the user suspends the machine? What if there is change from summer time to winter time? What if we insert an extra minute (as it sometimes happens), etc? On Windows, we are actually counting physical time (i.e. all these problems come up). It's damn hard to do all of these right :( I did something, it's not fully fledged :( In case you are interested, I'd love to have a nice patch that adds that functionality. You can create a merge request like this: 

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

By the way, if you have single-threaded solving, then the time is pretty deterministic, though not wallclock-precise :(

Mate

**Comment by ykazakov** [comment]
Wouldn't it be more flexible instead of setting a (CPU) timeout to register a callback function that could determine if the solver should be terminated? See, for example, the signature of ipasir_set_terminate from ipasir.h. This could handle custom user timeouts for different kinds of times, as well as situations when a user wants to stop the solver from the UI.

**Comment by msoos** [comment]
This is already possible. You can set your own timer, wake up and change the "interrupt_asap" parameter that you can pass into the constructor of the SAT solver. It will then abort the solver as soon as possible.

Callback -- many people could mess that one up. Many would put some function that would run for 0.01 second and then be very angry that the SAT solver suddenly got slow. But if it doesn't abort in 0.01 second, they'd be upset that it waited too long. So now I have to run this function that takes 0.01 second to run, every 0.01... which means the SAT solver is now 2x as slow. Unfortunately, engineers have lots of things on their minds, and the inner workings of a complicated machinery like a SAT solver is not their top priority -- for a _very_ good reason.

I believe this requirement can be met with the user setting a timer on their own that they like most, that they like best, that is the most beautiful timer that they ever wrote. Or they can run a thread that can flip that switch depending on anything their heart desires -- e.g. the inner workings of their own code, the performance of other threads, etc. I consider this fixed as I have now documented this trick in the header file :)
