### ISSUE TITLE
WalkSAT uses bools weirdly

### ISSUE THREAD

**Issue by horenmar** [msoos/cryptominisat#589]
I noticed that `walksat.cpp` triggers `C4804`, which is "'/': unsafe use of type 'bool' in operation". After closer inspection, this code does not make sense:

```cpp
    if (found_solution) {
        cout << "average flips per assign (over all runs) = " <<
               ((double)totalflip) / found_solution << endl;
        cout << "average seconds per assign (over all runs) = " <<
               (((double)totalflip) / found_solution) * seconds_per_flip << endl;
        cout << "mean flips until assign = " << mean_x << endl;
        cout << "mean seconds until assign = " << mean_x * seconds_per_flip << endl;
        cout << "mean restarts until assign = " << mean_r << endl;
    }
```

Because `found_solution` is guaranteed to be 1 in this block, the calculations can be removed completely (and leaving them in is in fact misleading). Note that the source of `mean_x` and `mean_r` commit the same sin, as they use `found_solution` in a context where it is also guaranteed to be `true` and thus equal to 1.

**Comment by msoos** [comment]
Sounds great! Looking forward to the pull request to fix it! Currently, I don't have the time so I am closing because I can't really spend the effort. However, please create a pull request to fix! Thanks :)
