### ISSUE TITLE
Is it normal that CMS is a magnitude slower than cadical?

### ISSUE THREAD

**Issue by newptcai** [msoos/cryptominisat#599]
I am trying to compare CMS and cadical on a problem [here](https://cs.stackexchange.com/questions/118667/is-it-feasible-to-solve-this-subset-cover-problem-with-sat-solver).

I found CMS preprocessing very helpful. But in solving the simplified formula, it takes much longer than cadical. Is there any parameters that I can try to experiment with to see if CMS can work faster? I know the formula I am trying to solve are satisfiable.

**Comment by msoos** [comment]
It depends :) The type of formula can be a differentiator. Also, you may have an encoding that favours one SAT solver than the other. Also, satisifiable problems are VERY random. When I say very, I mean the *same* SAT solver, with a different random seed can solve a problem in 0.01 seconds, or take over 5000s to solve, 5+ orders of magnitude. Easily. So, is the difference over 5 orders of magnitude? If not, then maybe it's just randomness. CaDiCaL in particular uses a local search solver to adjust its variable phases, which may strongly contribute to this behaviour for satisfiable formulas. So, it's hard to tell. For UNSAT formulas, the difference should be relatively small, within 2-3x factor, favouring either CryptoMiniSat or CaDiCaL.

SAT solving is not as robust as one might think :) It's a _highly_ randomized algorithm, for both satisfiable and unsatisfiable formulas, but for UNSAT there is less randomness involved.

**Comment by newptcai** [comment]
Thanks! 😀

Indeed using different seeds significantly changes the time it takes for both cadical and CMS. And the difference is within 2 orders. So the difference might be simply because the randomness in the algorithm. 

But I did find that setting the option

> —reconfat 0 —reconf 4

speeds things up quite a lot.

**Comment by newptcai** [comment]
And indeed the time difference of unsat is much less different, within about 2-3 X factor.

**Comment by msoos** [comment]
Hi,

Nice, thanks for getting back! It's possible that you get better speed with that  :) But that configuration will most likely not work for many other CNF problems. It's a hit and miss. My belief is that we need automated configuration generators, for example the one I'm building:  https://www.msoos.org/2019/06/crystalball-sat-solving-data-gathering-and-machine-learning/

Cheers and happy holidays,

Mate

**Comment by newptcai** [comment]
Hi I have read the article on crystal ball. I am a bit confused. For this method to be helpful in solving SAT, do we need to first run a normal CMS once over a formula to gather data? But if I have already solved or found the formula unsat, we don’t really need a solve it again even if we can build a faster solver, right?

What I can see where this may be helpful is to gather data through solving formula similar to the one we are interested, build a solver based on these data, and then solve a problem that we are really interested in.

**Comment by msoos** [comment]
The idea is to make it solve a family of problems faster. Usually people have thousands/millions of similar problems to solve. So you solve on 100, get the data, make the heuristic, compile it in, and then it's faster for the remaining 99900. May not be useful for you :( Sorry!
