### ISSUE TITLE
Could preprocessing make a formula unsatisfiable?

### ISSUE THREAD

**Issue by newptcai** [msoos/cryptominisat#600]
I have pretty [large formula](https://www.dropbox.com/s/k5z5r6vv1t5e2or/12-5-3-29.cnf?dl=0) which I run preprocess CMS5 by

    cryptominisat5 -p1 12-5-3-29.cnf 12-5-3-29.cms

The result is [this file](https://www.dropbox.com/s/lfs5veag2jo1gzq/12-5-3-29.cms?dl=0).

After that I run it with [painless v2](https://www.lrde.epita.fr/wiki/Painless) with these parameters

    painless -solver=lingeling -shr-strat=1 -lbd-limit=-1 -shr-sleep=500000 -wkr-strat=2 12-5-3-29.cms

painless finishes quite quickly and reports that 

```
c filename 12-5-3-29.cms
c lbd-limit=-1, shr-sleep=500000, shr-strat=1, solver=lingeling, wkr-strat=2, 
c [44.73] Winner: 3
c [45.21] Sharer 0: received cls 8, shared cls 8
s UNSATISFIABLE
```

But I know for sure the original formula is satisfiable. Here's [the proof](https://www.dropbox.com/s/la58vmoh7g41zdr/12-5-3-29-sol.cnf?dl=0). I added the solution to the end of the original formula, so it can be verified very quickly with any SAT solver.

Now I am not sure which step failed. How can I figure out if it's the preprocessing or the solving part?

I'm not able to solve the simplified formula with any other solver. I run it with treengeling with default parameters on a 12-core machine for 8 hours and it has not finished.

**Comment by msoos** [comment]
Maybe because painless has a bug? Does painless provide a DRAT proof? CMS
can also be buggy but I'd ask for an UNSAT proof from painless first and
validate that with a proof checker. If it validates then it's CMS that's
buggy :S

Cheers,

Mate

**Comment by newptcai** [comment]
Thanks. I will also contact the painless team.  It does seem to finish too quickly (a few minutes), considering no other solver could finish in hours.

On the other hand, is there a way to translate the solution of the original formula to a solution of the preprocessed formula? If this can be done, then I will be able to know for sure if it's painless having a bug.

**Comment by msoos** [comment]
Again, do not trust a solver (unless you *really* have to, like for Gauss
elimination where compact UNSAT DRAT proof does not yet exist) if it does
not provide an UNSAT proof. I can always say UNSAT to any CNF in under
0.001 second. That's easy.

**Comment by a1880** [comment]
I tried Z3, Clasp and CaDiCaL to solve the original CNF.
CaDiCaL 1.0.2 on Windows 10 found a solution in 4644 seconds.

In a second step, I ran the three solvers on the preprocessed CNF.
Again, just CaDiCaL found a solution. It took 6166 seconds this time.

Lingeling bcj in a final round found no solution within 900 seconds.
It did not conclude UNSAT, it just kept searching.

**Comment by newptcai** [comment]
Thanks for looking into this. At least this confirms that it's a problem with painless.

I am actually running CaDiCal 1.0.3 on the preprocessed one linux for a couple of hours. But it's still running. Have you added the --sat flag?

**Comment by a1880** [comment]
CaDiCaL 1.2.1 does not find any solution, neither for the original CNF nor for the preprocessed CNF.

**Comment by newptcai** [comment]
@a1880 I also tried cadical 1.0.2 on Linux and it does not solve the prepossessed CNF.  It seems that SAT solving depends a little bit on luck.
