### ISSUE TITLE
cryptominisat_simple5.1 looks strange

### ISSUE THREAD

**Issue by SnarkBoojum** [msoos/cryptominisat#602]
I'm updating Debian's package for cryptominisat and had a look at the manpages : help2man does a great job for cryptominisat, but for cryptominisat_simple, things look wrong.

I suspect it's something pretty simple in the -h formatting, but haven't laid my hand on it yet.

**Comment by SnarkBoojum** [comment]
Here is a patch giving better results:
[fix_manpage.txt](https://github.com/msoos/cryptominisat/files/4085431/fix_manpage.txt)

Notice that even the other manpage only gives two usages where the help has three (numeroted 1, 2. and 2 again).

**Comment by msoos** [comment]
Thanks!! I'll integrate it when I get home :) Thanks again,

Mate

**Comment by msoos** [comment]
Thanks, incorporated, with kudos at 26aa4b7c1dce1a6ed4634ca0977c2e6056c3908c

Thanks again,

Mate
