### ISSUE TITLE
Odd statement in distill_long_with_implicit_test.cpp

### ISSUE THREAD

**Issue by ajohnson1** [msoos/cryptominisat#604]
This line of code
https://github.com/msoos/cryptominisat/blob/26aa4b7c1dce1a6ed4634ca0977c2e6056c3908c/tests/distill_long_with_implicit_test.cpp#L41
sasys
``
        conf.otfHyperbin - true;
```
which wouldn't do much. Is it meant to be an assignment rather than a subtraction of logical value?

**Comment by msoos** [comment]
Thanks so much! Good catch :) Fixed!
