### ISSUE TITLE
Calling SATSolver constructor in C++ again results in segmentation fault

### ISSUE THREAD

**Issue by Tc14Hd** [msoos/cryptominisat#605]
I tried to run the following code with g++:
`SATSolver Solver;`
`Solver = SATSolver();`
But then I got a segmentation fault.

I did this because I was trying to remove all clauses I previously added to the solver and didn't find a `Solver.reset()` member function. Is there a way to do this?

**Comment by msoos** [comment]
Hi,

I'm a bit surprised that gives you a segfault -- but it does seem wrong :D If you want to reset the solver, just do this:

```
SATSolver *s = new SATSolver;
[use s like: s->add_clause([...]); s->solve(); etc.]
delete s;
s = new SATSolver;
[use s again, it's completely new]
delete s;
```

That's it :) This way, you can reset the solver with delete&new.

I hope this helped,

Mate
