### ISSUE TITLE
function ipasir_set_learn not found

### ISSUE THREAD

**Issue by ykazakov** [msoos/cryptominisat#608]
The function [ipasir_set_learn](https://github.com/msoos/cryptominisat/blob/45b803706d75981538fe0f8ca46bb5fd23ff30db/src/ipasir.cpp#L235) of ipasir.cpp appears outside of the extern "C" block, which results in this function not to be found when using cryptominisat thought the ipasir interface.

Please move this function inside the extern "C" block.

**Comment by msoos** [comment]
Ah, thanks so much! I thanked you in the comment as well. Great catch. Thanks a lot!

**Comment by ykazakov** [comment]
@msoos you are welcome, no need to thank. ;-)
