### ISSUE TITLE
Missing assignment of log2 used for print in clauseallocator.cpp

### ISSUE THREAD

**Issue by ajohnson1** [msoos/cryptominisat#612]
This looks wrong at https://github.com/msoos/cryptominisat/blob/9f20c8556b45d102d04f184d5a6e51878119b2cf/src/clauseallocator.cpp#L383

Introduced by https://github.com/msoos/cryptominisat/commit/9946a1a2a27080cf4eabaabe781a41cc3ed64680

This was fixed in devel branch by https://github.com/msoos/cryptominisat/commit/caf5cbeb2001a469c63565b04bffe9344f46cce3 but I don't know when that branch will be merged into master.

**Comment by msoos** [comment]
Ah, good catch! Thanks fixed!
