### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by SnarkBoojum** [msoos/cryptominisat#616]
Hi,

the Debian tools have found typos ; I'll attach a patch fixing most of them, but I'm annoyed because one of them is in the api : I changed check_assumptions_contradict_foced_assignement to check_assumptions_contradict_foced_assignment.

But even like this, shouldn't it be check_assumptions_contradict_forced_assignment ?

**Comment by SnarkBoojum** [comment]
Here is my patch:
[typos.txt](https://github.com/msoos/cryptominisat/files/4543567/typos.txt)

**Comment by msoos** [comment]
Hi,

That's really useful, thanks! I have merged it all. The call that you pointed to is not an exposed API, so it's all good :) It's now at 19070d3291bd991580fc59525815bf4dc87077c4.

May I ask what tool did you use to generate these? Where can I see them? They are quite useful!

Thanks,

Mate

**Comment by msoos** [comment]
Oh, and by the way, there is a very cool new version coming out in about 1-2 weeks, so if you are planning to package this, please wait! Some super-cool new features are coming, and it's been tested to hell, too, thanks to some competition deadlines coming up :)

**Comment by slel** [comment]
@msoos -- there was also a question whether there
might be an extra typo (`foced` for `forced`) in
`check_assumptions_contradict_foced_assignment`,
can you fix that too, or can you explain why not?

**Comment by msoos** [comment]
I am happy to fix that, sure! Note, however, that the system has performance bugs as well. I would very much appreciate that kind of in-depth bug reports, too :) I would be super happy (and very appreciative) to have another pair of eyes on these, more complicated, issues.

In the meanwhile, please create Pull Request (PR) to fix the force/foced issue, I'm happy to merge!

Thanks again,

Mate

**Comment by SnarkBoojum** [comment]
The tool is called lintian, and is run as part of the package building ; it also found a false positive, saying there was a 'ment' which should be a 'meant'. It's nice if you have a new version coming alone : just tag the release on github and I should get notified and package it quite soon. [Though Debian does have some problems with github recently, so perhaps I'll have to check by hand.]

Cheers!

**Comment by msoos** [comment]
Ah, thanks for the info! I will indeed tag it, will be a really cool release. In the meanwhile, I'll use lintian, thanks! And thanks again for the bug report and for packaging!

Mate
