### ISSUE TITLE
How to install it on VS2019?

### ISSUE THREAD

**Issue by OrchidXu** [msoos/cryptominisat#618]
I'm new with SAT,the README has only told how to install on VS2015,which parameters needs to modify?

**Comment by msoos** [comment]
Nothing, it's the same :) Try and let me know how it went!

**Comment by josiahblaisdell** [comment]
Hi there, I compiled with VS2019, and I have linked/compiled my own program but when I reach this line it crashes: CMSat::SATSolver solver;

The message is:
'sat-fish.exe' (Win32): Loaded 'D:\src\courses\CS517\sat-fish\x64\Debug\sat-fish.exe'. Symbols loaded.
'sat-fish.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'sat-fish.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'sat-fish.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'sat-fish.exe' (Win32): Loaded 'D:\src\courses\CS517\sat-fish\cryptominisat5.exe'. Symbols loaded.
'sat-fish.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140d.dll'. 
'sat-fish.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140d.dll'. 
'sat-fish.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140_1d.dll'. 
'sat-fish.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbased.dll'. 
The thread 0x20ac has exited with code 0 (0x0).
Exception thrown at 0x00000000003E03BC in sat-fish.exe: 0xC0000005: Access violation executing location 0x00000000003E03BC.

In the call stack I see "cryptominisat.exe!_malloc_base(unsigned __int64 size) line 34

**Comment by a1880** [comment]
How do you call cryptominisat5.exe? To me, it looks like a parameter problem which leads to memory exhaustion. Can you debug cryptominisat5.exe standalone to find out, what's going on?

**Comment by josiahblaisdell** [comment]
cryptominisat5.exe seems to work when I run it stand alone. Here is the output: 
c Outputting solution to console
c CryptoMiniSat version 5.7.1
c CMS Copyright Mate Soos (soos.mate@gmail.com)
c CMS SHA revision 0544260ae1d4338c260930dce8a6cc0512d3e1fb
c CMS is MIT licensed
c Using Yalsat by Armin Biere, see Balint et al. Improving implementation of SLS solvers [...], SAT'14
c Using WalkSAT by Henry Kautz, see Kautz and Selman Pushing the envelope: planning, propositional logic, and stochastic search, AAAI'96,
c Using CCAnr from 'CCAnr: A Conf. Checking Based Local Search Solver [...]'
c       by Shaowei Cai, Chuan Luo, and Kaile Su, SAT 2015
c CMS compilation env CMAKE_CXX_COMPILER = C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe | CMAKE_CXX_FLAGS = /DWIN32 /D_WINDOWS /W3 /GR /EHsc | COMPILE_DEFINES =  | STATICCOMPILE = ON | ONLY_SIMPLE = OFF | Boost_FOUND = TRUE | STATS = OFF | SQLITE3_FOUND =  | ZLIB_FOUND =  | VALGRIND_FOUND =  | ENABLE_TESTING = OFF | M4RI_FOUND = FALSE | NOM4RI = OFF | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = ON | PYTHON_EXECUTABLE = D:/python38/python.exe | PYTHON_LIBRARY = D:/python38/libs/python38.lib | PYTHON_INCLUDE_DIRS = D:/python38/include | MY_TARGETS =  | LARGEMEM = OFF | LIMITMEM = OFF | compilation date time = May 26 2020 14:24:07
c CMS compiled with non-gcc compiler
c Executed with command line: D:\src\courses\CS517\sat-fish\cryptominisat5.exe
c Reading from standard input... Use '-h' or '--help' for help.
c -- clauses added: 0
c
*** INTERRUPTED ***c -- xor clauses added: 0
c -- vars added 0

c Parsing time: 18.98 s
No clauses or variables were put into the solver, exiting without stats

**Comment by josiahblaisdell** [comment]
I am not sure what you mean by "how do you call cryptominisat.exe?" And I'm wondering if that has something to do with it. I have placed cryptominisat.exe in the build directory. I have also added the cryptominisat libraries to the "Additional Dependencies". Is this what you mean?

In the example code on the git readme it says to just call:
CMSat::SATSolver solver;

But you seem to suggest there is some way to call cryptominisat5.exe? I don't want to call the executable, I want to use the cryptominisat library. I am trying to implement this paper:
"Satisfiability and Integer Programming As Complementary Tools" (Zhou; Du, 1998)

Hope this helps, thank you for your assistance.

**Comment by josiahblaisdell** [comment]
Oh my gosh I think I fixed it.... To fix I did the following:

1. recompiled the cryptominisat program using the settings from the cmake config below (and Ninja)
2. Set the solution configuration from Debug to Release
3. Visual Studio -> Project Properties -> C/C++ -> Code Generation -> Set Runtime Library to Multi-threaded (/MT)
4. Visual Studio -> Project Properties -> C/C++ -> Code Generation -> Set "Security Check" to Disable
5. Visual Studio -> Project Properties -> Linker -> Input -> added cryptominisat5win.lib;cryptominisat5_simple.lib; to the additional dependencies


cmake Config:
`
########################
# EXTERNAL cache entries
########################

//No help, variable specified on the command line.
BOOST_ROOT:PATH=D:/src/cryptominisat/build/boost_1_59_0_install

//Build the shared library
BUILD_SHARED_LIBS:BOOL=ON

//The directory containing a CMake configuration file for Boost.
Boost_DIR:PATH=Boost_DIR-NOTFOUND

//Path to a file.
Boost_INCLUDE_DIR:PATH=D:/src/cryptominisat/build/boost_1_59_0_install/include/boost-1_59

//Boost library directory RELEASE
Boost_LIBRARY_DIR_RELEASE:PATH=D:/src/cryptominisat/build/boost_1_59_0_install/lib

//Boost program_options library (debug)
Boost_PROGRAM_OPTIONS_LIBRARY_DEBUG:FILEPATH=Boost_PROGRAM_OPTIONS_LIBRARY_DEBUG-NOTFOUND

//Boost program_options library (release)
Boost_PROGRAM_OPTIONS_LIBRARY_RELEASE:FILEPATH=D:/src/cryptominisat/build/boost_1_59_0_install/lib/libboost_program_options-vc140-mt-s-1_59.lib

//Choose the type of build, options are: None Debug Release RelWithDebInfo
// MinSizeRel ...
CMAKE_BUILD_TYPE:STRING=Debug

//CXX compiler
CMAKE_CXX_COMPILER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe

//Flags used by the CXX compiler during all build types.
CMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3 /GR /EHsc

//Default flags for Debug configuration
CMAKE_CXX_FLAGS_DEBUG:STRING=

//Default flags for MinSizeRel configuration
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=

//Default flags for Release configuration
CMAKE_CXX_FLAGS_RELEASE:STRING=

//Default flags for RelWithDebInfo configuration
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=

//Libraries linked by default with all C++ applications.
CMAKE_CXX_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib

//C compiler
CMAKE_C_COMPILER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe

//Flags used by the C compiler during all build types.
CMAKE_C_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3

//Default flags for Debug configuration
CMAKE_C_FLAGS_DEBUG:STRING=

//Default flags for MinSizeRel configuration
CMAKE_C_FLAGS_MINSIZEREL:STRING=

//Default flags for Release configuration
CMAKE_C_FLAGS_RELEASE:STRING=

//Default flags for RelWithDebInfo configuration
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=

//Libraries linked by default with all C applications.
CMAKE_C_STANDARD_LIBRARIES:STRING=kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib

//Flags used by the linker during all build types.
CMAKE_EXE_LINKER_FLAGS:STRING=/machine:x64

//Flags used by the linker during DEBUG builds.
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL

//Flags used by the linker during MINSIZEREL builds.
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO

//Flags used by the linker during RELEASE builds.
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO

//Flags used by the linker during RELWITHDEBINFO builds.
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL

//Enable/Disable output of compile commands during generation.
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF

//User executables (bin)
CMAKE_INSTALL_BINDIR:PATH=bin

//Read-only architecture-independent data (DATAROOTDIR)
CMAKE_INSTALL_DATADIR:PATH=

//Read-only architecture-independent data root (share)
CMAKE_INSTALL_DATAROOTDIR:PATH=share

//Documentation root (DATAROOTDIR/doc/PROJECT_NAME)
CMAKE_INSTALL_DOCDIR:PATH=

//C header files (include)
CMAKE_INSTALL_INCLUDEDIR:PATH=include

//Info documentation (DATAROOTDIR/info)
CMAKE_INSTALL_INFODIR:PATH=

//Object code libraries (lib)
CMAKE_INSTALL_LIBDIR:PATH=lib

//Program executables (libexec)
CMAKE_INSTALL_LIBEXECDIR:PATH=libexec

//Locale-dependent data (DATAROOTDIR/locale)
CMAKE_INSTALL_LOCALEDIR:PATH=

//Modifiable single-machine data (var)
CMAKE_INSTALL_LOCALSTATEDIR:PATH=var

//Man documentation (DATAROOTDIR/man)
CMAKE_INSTALL_MANDIR:PATH=

//C header files for non-gcc (/usr/include)
CMAKE_INSTALL_OLDINCLUDEDIR:PATH=/usr/include

//Install path prefix, prepended onto install directories.
CMAKE_INSTALL_PREFIX:PATH=C:/Program Files (x86)/cryptominisat5

//Run-time variable data (LOCALSTATEDIR/run)
CMAKE_INSTALL_RUNSTATEDIR:PATH=

//System admin executables (sbin)
CMAKE_INSTALL_SBINDIR:PATH=sbin

//Modifiable architecture-independent data (com)
CMAKE_INSTALL_SHAREDSTATEDIR:PATH=com

//Read-only single-machine data (etc)
CMAKE_INSTALL_SYSCONFDIR:PATH=etc

//Path to a program.
CMAKE_LINKER:FILEPATH=C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/link.exe

//Program used to build from build.ninja files.
CMAKE_MAKE_PROGRAM:FILEPATH=D:/Ninja/ninja.exe

//Flags used by the linker during the creation of modules during
// all build types.
CMAKE_MODULE_LINKER_FLAGS:STRING=/machine:x64

//Flags used by the linker during the creation of modules during
// DEBUG builds.
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL

//Flags used by the linker during the creation of modules during
// MINSIZEREL builds.
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO

//Flags used by the linker during the creation of modules during
// RELEASE builds.
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO

//Flags used by the linker during the creation of modules during
// RELWITHDEBINFO builds.
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL

//Path to a program.
CMAKE_MT:FILEPATH=C:/Program Files (x86)/Windows Kits/10/bin/10.0.18362.0/x64/mt.exe

//Value Computed by CMake
CMAKE_PROJECT_DESCRIPTION:STATIC=

//Value Computed by CMake
CMAKE_PROJECT_HOMEPAGE_URL:STATIC=

//Value Computed by CMake
CMAKE_PROJECT_NAME:STATIC=cryptominisat5

//RC compiler
CMAKE_RC_COMPILER:FILEPATH=C:/Program Files (x86)/Windows Kits/10/bin/10.0.18362.0/x64/rc.exe

//Flags for Windows Resource Compiler during all build types.
CMAKE_RC_FLAGS:STRING=-DWIN32

//Flags for Windows Resource Compiler during DEBUG builds.
CMAKE_RC_FLAGS_DEBUG:STRING=-D_DEBUG

//Flags for Windows Resource Compiler during MINSIZEREL builds.
CMAKE_RC_FLAGS_MINSIZEREL:STRING=

//Flags for Windows Resource Compiler during RELEASE builds.
CMAKE_RC_FLAGS_RELEASE:STRING=

//Flags for Windows Resource Compiler during RELWITHDEBINFO builds.
CMAKE_RC_FLAGS_RELWITHDEBINFO:STRING=

//Flags used by the linker during the creation of shared libraries
// during all build types.
CMAKE_SHARED_LINKER_FLAGS:STRING=/machine:x64

//Flags used by the linker during the creation of shared libraries
// during DEBUG builds.
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=/debug /INCREMENTAL

//Flags used by the linker during the creation of shared libraries
// during MINSIZEREL builds.
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=/INCREMENTAL:NO

//Flags used by the linker during the creation of shared libraries
// during RELEASE builds.
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=/INCREMENTAL:NO

//Flags used by the linker during the creation of shared libraries
// during RELWITHDEBINFO builds.
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=/debug /INCREMENTAL

//If set, runtime paths are not added when installing shared libraries,
// but are added when building.
CMAKE_SKIP_INSTALL_RPATH:BOOL=OFF

//If set, runtime paths are not added when using shared libraries.
CMAKE_SKIP_RPATH:BOOL=OFF

//Flags used by the linker during the creation of static libraries
// during all build types.
CMAKE_STATIC_LINKER_FLAGS:STRING=/machine:x64

//Flags used by the linker during the creation of static libraries
// during DEBUG builds.
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during the creation of static libraries
// during MINSIZEREL builds.
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during the creation of static libraries
// during RELEASE builds.
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during the creation of static libraries
// during RELWITHDEBINFO builds.
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//If this value is on, makefiles will be generated without the
// .SILENT directive, and all commands will be echoed to the console
// during the make.  This is useful for debugging only. With Visual
// Studio IDE projects all commands are done without /nologo.
CMAKE_VERBOSE_MAKEFILE:BOOL=OFF

//Build with coverage check
COVERAGE:BOOL=OFF

//Installation directory for cryptominisat5 CMake files
CRYPTOMINISAT5_INSTALL_CMAKE_DIR:PATH=lib/cmake/cryptominisat5

//Generate only emscripten JS
EMSCRIPTEN:BOOL=OFF

//Build with assertions enabled
ENABLE_ASSERTIONS:BOOL=ON

//Enable Python interface
ENABLE_PYTHON_INTERFACE:BOOL=ON

//Enable testing
ENABLE_TESTING:BOOL=OFF

//Use Clang coverage sanitizers
FEEDBACKFUZZ:BOOL=OFF

//OFF
FORCE_PYTHON2:BOOL=OFF

//OFF
FORCE_PYTHON3:BOOL=OFF

//Path to a program.
GIT_EXECUTABLE:FILEPATH=C:/Program Files/Git/cmd/git.exe

//Also build IPASIR
IPASIR:BOOL=OFF

//Allow memory usage to grow to Terabyte values -- uses 64b offsets.
// Slower, but allows the solver to run for much longer.
LARGEMEM:BOOL=OFF

//*Only used for testing*. Limit memory used by CMS through number
// of variables
LIMITMEM:BOOL=OFF

//Path to a file.
M4RI_INCLUDE_DIRS:PATH=M4RI_INCLUDE_DIRS-NOTFOUND

//Path to a library.
M4RI_LIBRARIES:FILEPATH=M4RI_LIBRARIES-NOTFOUND

//Path to a file.
M4RI_ROOT_DIR:PATH=M4RI_ROOT_DIR-NOTFOUND

//Create manpage
MANPAGE:BOOL=ON

//Build with only MIT licensed components
MIT:BOOL=OFF

//Don't use Bosphorus
NOBOSPHORUS:BOOL=ON

//Don't use m4ri
NOM4RI:BOOL=ON

//Don't use valgrind
NOVALGRIND:BOOL=ON

//Don't use zlib
NOZLIB:BOOL=ON

//Only build very simplistic executable -- no Boost needed
ONLY_SIMPLE:BOOL=ON

//pkg-config executable
PKG_CONFIG_EXECUTABLE:FILEPATH=PKG_CONFIG_EXECUTABLE-NOTFOUND

//Path to a library.
PYTHON_DEBUG_LIBRARY:FILEPATH=PYTHON_DEBUG_LIBRARY-NOTFOUND

//Path to a program.
PYTHON_EXECUTABLE:FILEPATH=D:/python38/python.exe

//Path to a file.
PYTHON_INCLUDE_DIR:PATH=D:/python38/include

//Path to a library.
PYTHON_LIBRARY:FILEPATH=D:/python38/libs/python38.lib

//Path to a library.
PYTHON_LIBRARY_DEBUG:FILEPATH=PYTHON_LIBRARY_DEBUG-NOTFOUND

//Must use Bosphorus
REQUIRE_BOSPHORUS:BOOL=OFF

//Must use m4ri
REQUIRE_M4RI:BOOL=OFF

//Use Clang sanitizers. You MUST use clang++ as the compiler for
// this to work
SANITIZE:BOOL=OFF

//Use more debug flags
SLOW_DEBUG:BOOL=OFF

//Compile to static executable
STATICCOMPILE:BOOL=ON

//Don't use statistics at all
STATS:BOOL=OFF

//Build with every-level GAUSS enabled
USE_GAUSS:BOOL=OFF

//Value Computed by CMake
cryptominisat5_BINARY_DIR:STATIC=D:/src/cryptominisat/build

//Value Computed by CMake
cryptominisat5_SOURCE_DIR:STATIC=D:/src/cryptominisat
`

**Comment by a1880** [comment]
I was misled by `cryptominisat5.exe` and `cryptominisat.exe` being mentioned in your message output. Therefore, I thought that you are calling `cryptominisat5.exe` as external process rather than as library call. I am glad that it  works for you by now.
