### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by SnarkBoojum** [msoos/cryptominisat#622]
The Debian scripts found some spelling errors ; I'll provide a patch (real) soon.

**Comment by SnarkBoojum** [comment]
[Here it is](https://github.com/msoos/cryptominisat/files/4906550/spelling_errors.txt)

**Comment by msoos** [comment]
Thanks, merged into 26109ef47541bbd97d7ab183ba8f7fcc6da8b4b4
