### ISSUE TITLE
groff complains about cryptominisat5.1

### ISSUE THREAD

**Issue by SnarkBoojum** [msoos/cryptominisat#623]
It looks like one of the lines in the manpage is too long ; I'll try to provide a patch if I find more on the issue.

**Comment by SnarkBoojum** [comment]
[Here is a patch](https://github.com/msoos/cryptominisat/files/4906571/fix_manpage.txt)

**Comment by msoos** [comment]
Sorry, I will fix this differently. This fix is not right. Also, it's probably only a warning, right? So I think it's OK, we don't need to be perfect, right?

**Comment by SnarkBoojum** [comment]
It's only a warning, but it does mean that the line won't be readable, so it's still a good idea to get rid of the issue.
