### ISSUE TITLE
Support for mingw32

### ISSUE THREAD

**Issue by ykazakov** [msoos/cryptominisat#625]
### Description of the problem

I used to compile windows binaries for cryptominisat using a mingw32 cross-compiler (on MacOS). I observe that for the latest release 5.8.0 this does not work anymore. Is minigw officially supported?

### My environment

- MacOSX 10.15.6
- mingw-w64 7.0.0_2 (homebrew)

### Steps to reproduce

1. Install a `mingw-w64` cross-compiler, e.g.:
```
brew install mingw-w64
```
(on linux there are also mingw-w64 packages)

2. Create `build-ming32.sh` with the following content:

```
#!/bin/bash

set -e
set -x

rm -rf build
mkdir build

export CC=x86_64-w64-mingw32-gcc
export CXX=x86_64-w64-mingw32-g++

(
cd build || exit
cmake -DENABLE_PYTHON_INTERFACE=OFF -DNOVALGRIND=ON -DNOZLIB=ON -DONLY_SIMPLE=ON -DSTATICCOMPILE=ON -DIPASIR=ON -MIT=ON -DCMAKE_BUILD_TYPE=Release -D CMAKE_SYSTEM_NAME=Windows $@ ..
make -j4
)
```

3. Compile cryptominisat

```
$ wget https://github.com/msoos/cryptominisat/archive/5.8.0.tar.gz
$ tar xf 5.8.0.tar.gz
$ cd cryptominisat-5.8.0
$ sh ../build-ming32.sh 
```

### Expected behaviour

This used to compile fine up until version 5.7.1

### Actual behaviour

I get the following compile errors due to `posix_memalign` not available under mingw32

```
In file included from /Users/demo/cryptominisat/cryptominisat-5.8.0/src/gaussian.h:39,
                 from /Users/demo/cryptominisat/cryptominisat-5.8.0/src/clauseallocator.cpp:38:
/Users/demo/cryptominisat/cryptominisat-5.8.0/src/packedmatrix.h: In member function ‘void CMSat::PackedMatrix::resize(uint32_t, uint32_t)’:
/Users/demo/cryptominisat/cryptominisat-5.8.0/src/packedmatrix.h:70:13: error: ‘posix_memalign’ was not declared in this scope
   70 |             posix_memalign((void**)&mp, 16,  size);
      |             ^~~~~~~~~~~~~~
/Users/demo/cryptominisat/cryptominisat-5.8.0/src/packedmatrix.h: In member function ‘CMSat::PackedMatrix& CMSat::PackedMatrix::operator=(const CMSat::PackedMatrix&)’:
/Users/demo/cryptominisat/cryptominisat-5.8.0/src/packedmatrix.h:93:13: error: ‘posix_memalign’ was not declared in this scope
   93 |             posix_memalign((void**)&mp, 16,  size);
      |             ^~~~~~~~~~~~~~
make[2]: *** [cmsat5-src/CMakeFiles/cryptominisat5.dir/clauseallocator.cpp.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 18%] Building CXX object cmsat5-src/CMakeFiles/ipasircryptominisat5.dir/clauseallocator.cpp.obj
[ 19%] Building CXX object cmsat5-src/CMakeFiles/ipasircryptominisat5.dir/sccfinder.cpp.obj
In file included from /Users/demo/cryptominisat/cryptominisat-5.8.0/src/gaussian.h:39,
                 from /Users/demo/cryptominisat/cryptominisat-5.8.0/src/clauseallocator.cpp:38:
/Users/demo/cryptominisat/cryptominisat-5.8.0/src/packedmatrix.h: In member function ‘void CMSat::PackedMatrix::resize(uint32_t, uint32_t)’:
/Users/demo/cryptominisat/cryptominisat-5.8.0/src/packedmatrix.h:70:13: error: ‘posix_memalign’ was not declared in this scope
   70 |             posix_memalign((void**)&mp, 16,  size);
      |             ^~~~~~~~~~~~~~
/Users/demo/cryptominisat/cryptominisat-5.8.0/src/packedmatrix.h: In member function ‘CMSat::PackedMatrix& CMSat::PackedMatrix::operator=(const CMSat::PackedMatrix&)’:
/Users/demo/cryptominisat/cryptominisat-5.8.0/src/packedmatrix.h:93:13: error: ‘posix_memalign’ was not declared in this scope
   93 |             posix_memalign((void**)&mp, 16,  size);
      |             ^~~~~~~~~~~~~~
make[2]: *** [cmsat5-src/CMakeFiles/ipasircryptominisat5.dir/clauseallocator.cpp.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [cmsat5-src/CMakeFiles/cryptominisat5.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [cmsat5-src/CMakeFiles/ipasircryptominisat5.dir/all] Error 2
make: *** [all] Error 2
```

### Possible workaround

If I replace in `src/packedmatrix.h` the lines `#ifdef _MSC_VER` with `#ifdef _WIN32`, the project compiles fine. This also does not seem to impact the (native) MacOS build.

**Comment by msoos** [comment]
Hey Yevgeny,

Thanks for the really detailed bug report! Unfortunately, I didn't catch this issue, thanks for reporting.

Can you try to check [this](https://stackoverflow.com/a/10862288/2029614) solution? It seems that a newer mingw may work? Otherwise, I can also do the solution where we use `__mingw_aligned_malloc` instead, maybe you could try to implement and debug that solution for me, as I don't have a working mingw environment. Can you please check those solution options? Thanks,

Mate

**Comment by ykazakov** [comment]
What do you think about the suggested workaround? The functions  `_aligned_free` and `_aligned_malloc` appear to be available under mingw.

**Comment by msoos** [comment]
Hi,

Sure, that works! Unfortunately I don't have mingw so it'd be hard for me to do. Could you please implement it and test it on your system? Then if you can give me the DIFF (or even better, create a pull request!) than I can merge. Thanks again,

Mate

**Comment by ykazakov** [comment]
@msoos are you on windows or linux? As I mention, most linux distributions have a `mingw-w64` package, wich can be installed in one minute. As I mentioned, I already tested the fix (literally: replace all `_MSC_VER` with `_WIN32` in `src/packedmatrix.h`) and it worked for me, but I can gladly create a PR if you wish. Also note that I can compile the program using mingw, but I cannot run it since it is a cross-compiler and I do not have a windows machine. For the same reason, I cannot test if the Visual Studio built works, but hopefully CI takes care of that ;-).

**Comment by msoos** [comment]
Oh, sorry, I got confused. You mentioned mingw32, but I was pretty sure that'd be difficult to do. I didn't realize I could just use mingw64 to test, sorry! Thank you so much for your PR! I love that you also added a test and it caught that drat-trim is not right. I will fix that too, thanks! I just merged your PR, so I'm closing this. Thank you again,

Mate

**Comment by ykazakov** [comment]
Ah, sorry for the confusion regarding the names.
