### ISSUE TITLE
PVS-Studio Code Analysis - as usual a lot false positive - but some perhaps worth looking

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#628]
V779 Unreachable code detected. It is possible that an error is present. solverconf.h 185
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::glue)' index could reach 255. solverconf.cpp 404
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::activity)' index could reach 255. solverconf.cpp 405
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: data2. watched.h 97
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: buf_len. drat.h 39
V701 realloc() possible leak: when realloc() fails in allocating memory, original pointer 'data' is lost. Consider assigning realloc() to a temporary pointer. Vec.h 250
V630 Instantiation of vec < vec < Watched > >: The 'realloc' function is used to allocate memory for an array of objects which are classes containing constructors and destructors. Vec.h 229
V519 The 'blocked_lit' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 225, 226. cnf.cpp 226
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: red_step. propby.h 77
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: gqhead. cnf.h 98
V764 Possible incorrect order of arguments passed to 'removeWBin' function: 'lit2' and 'lit1'. propengine.h 216
V764 Possible incorrect order of arguments passed to 'removeWBin_change_order' function: 'lit2' and 'lit1'. propengine.h 223
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: lev. propengine.h 75
V690 The 'PackedRow' class implements the copy assignment operator, but lacks a copy constructor. It is dangerous to use such a class. packedrow.h 60
V794 The assignment operator should be protected from the case of 'this == &b'. packedmatrix.h 85
V690 The 'PackedMatrix' class implements the copy assignment operator, but lacks a copy constructor. It is dangerous to use such a class. packedmatrix.h 41
V701 realloc() possible leak: when realloc() fails in allocating memory, original pointer 'mp' is lost. Consider assigning realloc() to a temporary pointer. bitarray.h 55
V794 The assignment operator should be protected from the case of 'this == &b'. bitarray.h 53
V701 realloc() possible leak: when realloc() fails in allocating memory, original pointer 'mp' is lost. Consider assigning realloc() to a temporary pointer. bitarray.h 68
V730 Not all members of a class are initialized inside the compiler generated constructor. Consider inspecting: do_eliminate, new_resp_var, new_resp_row, ret, currLevel. gqueuedata.h 28
V730 It is possible that not all members of a class are initialized inside the constructor. Consider inspecting: max_confl_to_do. searcher.h 334
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: depth_warning_issued, depth. sccfinder.cpp 38
V690 The 'Spec' class implements a move constructor, but lacks the move assignment operator. It is dangerous to use such a class. shareddata.h 42
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: timeAvailable. str_impl_w_impl.h 41
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: oldBogoProps, maxNumProps, orig_maxNumProps. distillerlong.cpp 42
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: var_decay, var_decay_max, maple_step_size, lastConflictCausedBy. propengine.cpp 52
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: cl_marked, cl_ttl, cl_locked_solver. reducedb.cpp 130
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: timeAvailable, lastBin, lastRed. subsumeimplicit.cpp 37
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: comp_no, used_comp_no, bogoprops_remain, orig_bogoprops. compfinder.cpp 49
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: isSubsumed, thisremLitBin, timeAvailable. distillerlongwithimpl.cpp 42
V690 The 'Tri' class implements a copy constructor, but lacks the copy assignment operator. It is dangerous to use such a class. occsimplifier.h 300
V630 Instantiation of vec < Watched >: The 'realloc' function is used to allocate memory for an array of objects which are classes containing constructors. Vec.h 229
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: start, end. occsimplifier.h 61
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: is_xor. occsimplifier.h 455
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: bogoprops_to_use, bogoprops_remain, hyperbin_added, removedIrredBin, removedRedBin. intree.cpp 35
V779 Unreachable code detected. It is possible that an error is present. varreplacer.cpp 678
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: xor_find_time_limit. xorfinder.cpp 38
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: abst, size, rhs. xorfinder.h 50
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: bva_worked, bva_simp_size, bounded_var_elim_time_limit. bva.cpp 36
V555 The expression '(origSize - learnt_clause.size()) > 0' will work as 'origSize != learnt_clause.size()'. searcher.cpp 519
V560 A part of conditional expression is always true: conf.glue_put_lev1_if_below_or_eq != 0. searcher.cpp 1731
V1037 Two or more case-branches perform the same actions. Check lines: 2618, 2626 searcher.cpp 2618
V614 Potentially uninitialized variable 'offs' used. Consider checking the first actual argument of the 'Watched' function. searcher.cpp 3840
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: isize. propbyforgraph.h 69
V730 Not all members of a class are initialized inside the compiler generated constructor. Consider inspecting: sum_var_act_of_cls. vardistgen.h 38
V560 A part of conditional expression is always true. occsimplifier.cpp 650
V581 The conditional expressions of the 'if' statements situated alongside each other are identical. Check lines: 1181, 1189. occsimplifier.cpp 1189
V555 The expression of the 'A - B > 0' kind will work as 'A != B'. occsimplifier.cpp 1978
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: _num_vars, _num_clauses, _best_found_cost, _step, _aspiration_score, _avg_clause_weight, ... ccnr.cpp 40
V630 The 'calloc' function is used to allocate memory for an array of objects which are classes containing constructors. walksat.cpp 417
V630 The 'calloc' function is used to allocate memory for an array of objects which are classes containing constructors. walksat.cpp 418
V522 There might be dereferencing of a potential null pointer 'changed'. Check lines: 425, 420. walksat.cpp 425
V522 There might be dereferencing of a potential null pointer 'numoccurrence'. Check lines: 434, 416. walksat.cpp 434
V630 The 'malloc' function is used to allocate memory for an array of objects which are classes containing constructors. walksat.cpp 440
V560 A part of conditional expression is always true: conf.glue_put_lev1_if_below_or_eq != 0. solver.cpp 779
V581 The conditional expressions of the 'if' statements situated alongside each other are identical. Check lines: 2321, 2327. solver.cpp 2327
V581 The conditional expressions of the 'if' statements situated alongside each other are identical. Check lines: 2327, 2333. solver.cpp 2333
V581 The conditional expressions of the 'if' statements situated alongside each other are identical. Check lines: 2507, 2512. solver.cpp 2512
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::activity)' index could reach 255. solver.cpp 3365
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::glue)' index could reach 255. solver.cpp 3366
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::glue)' index could reach 255. solver.cpp 3417
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::activity)' index could reach 255. solver.cpp 3418
V519 The 'conf.glue_put_lev1_if_below_or_eq' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 3413, 3416. solver.cpp 3416
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::glue)' index could reach 255. solver.cpp 3460
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::activity)' index could reach 255. solver.cpp 3461
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: num. matrixfinder.h 61
V1051 Consider checking for misprints. It's possible that the 'pop_t' should be checked here. packedrow.cpp 191
V677 Custom declaration of a standard 'intptr_t' type. The system header file should be used: #include <STDDEF.H>. stdint.h 115
V677 Custom declaration of a standard 'uintptr_t' type. The system header file should be used: #include <STDDEF.H>. stdint.h 116
V560 A part of conditional expression is always true: n. yals.c 676
V520 The comma operator ',' in array index expression. yals.c 749
V520 The comma operator ',' in array index expression. yals.c 755
V520 The comma operator ',' in array index expression. yals.c 1236
V595 The 'prev' pointer was utilized before it was verified against nullptr. Check lines: 1307, 1310. yals.c 1307
V520 The comma operator ',' in array index expression. yals.c 1868
V520 The comma operator ',' in array index expression. yals.c 1869
V520 The comma operator ',' in array index expression. yals.c 1926
V519 The 'neg' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 1924, 1927. yals.c 1927
V520 The comma operator ',' in array index expression. yals.c 2276
V520 The comma operator ',' in array index expression. yals.c 2277
V510 The 'yals_msg' function is not expected to receive class-type variable as fifth actual argument. yals.c 2393
V520 The comma operator ',' in array index expression. yals.c 3010
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::glue)' index could reach 255. cryptominisat.cpp 175
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::activity)' index could reach 255. cryptominisat.cpp 176
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::glue)' index could reach 255. cryptominisat.cpp 187
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::activity)' index could reach 255. cryptominisat.cpp 188
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::glue)' index could reach 255. cryptominisat.cpp 203
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::activity)' index could reach 255. cryptominisat.cpp 204
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::glue)' index could reach 255. cryptominisat.cpp 223
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::activity)' index could reach 255. cryptominisat.cpp 224
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::glue)' index could reach 255. cryptominisat.cpp 249
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::activity)' index could reach 255. cryptominisat.cpp 250
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::glue)' index could reach 255. cryptominisat.cpp 266
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::activity)' index could reach 255. cryptominisat.cpp 267
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::glue)' index could reach 255. cryptominisat.cpp 284
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::activity)' index could reach 255. cryptominisat.cpp 285
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::glue)' index could reach 255. cryptominisat.cpp 298
V557 Array overrun is possible. The value of 'clean_to_int(ClauseClean::activity)' index could reach 255. cryptominisat.cpp 299
V1037 Two or more case-branches perform the same actions. Check lines: 180, 214, 235 cryptominisat.cpp 180
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: start_time. cryptominisat.cpp 703
V547 Expression '!solver->conf.verbosity' is always false. matrixfinder.cpp 435
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: matrix_no. matrixfinder.cpp 45
V630 Instantiation of vec < GaussWatched >: The 'realloc' function is used to allocate memory for an array of objects which are classes containing constructors. Vec.h 229

**Comment by msoos** [comment]
Hi Marie,

Thanks! It'd be great if you could make a git pull request perhaps to fix
some of these! Some seem perhaps triggerable, some perhaps are a bit harder
to reach. So, fixing some would probably be a good idea. What do you think?

Cheers and thanks again,

Mate

**Comment by msoos** [comment]
Thanks again for this! A lot of code has been fixed/changed in the meanwhile, so I am closing as much of this is outdated now unfortunately :(
