### ISSUE TITLE
Wrong number of clauses in dump after preprocessing

### ISSUE THREAD

**Issue by jvpeetz** [msoos/cryptominisat#634]
Hi Mate,
when preprocessing the attached cnf file, the number of clauses given in the `p cnf` line doesn't match the number of clauses in the dumped cnf file. I get
```
  cryptominisat5-5.8.0 -p1 test.cnf.gz hugo.cnf > /dev/null

  grep '^p cnf' hugo.cnf
  p cnf 1065 25336

  grep -c '^[0-9\-]' hugo.cnf
  25273
```
That is, the number of lines with clauses is smaller than the number of clauses given in the dump file.
Is this to be expected?
By the way, the original file has `p cnf 1110 27721`. Thus, the preprocessing reduced both the number of literals and clauses as intended.

Regards,
Jörg.

[test.cnf.gz](https://github.com/msoos/cryptominisat/files/5660698/test.cnf.gz)

**Comment by msoos** [comment]
Nice find, thanks so much for reporting! Please follow [this process](https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/creating-an-issue-or-pull-request) to create a pull request, I'd be really happy to merge in a fix!

Thanks so much again for reporting the issue, and I'm looking forward to the fix,

Mate

**Comment by msoos** [comment]
This dumping is being deprecated and the new version will remove this feature. Instead, the current CNF will be queryable using a new system that allows for much more flexibility in querying! So I'm closing this issue as it will no longer be an issue :)

**Comment by jvpeetz** [comment]
That sounds good. I didn't find the time to dig into this.
So, I'm looking forward to the new version :-)
