### ISSUE TITLE
output final stats

### ISSUE THREAD

**Issue by vlastikw** [msoos/cryptominisat#635]
Hi,

I think that the output should not print anything after 

c Total time (this thread) : 1190.39     
s SATISFIABLE
c Not printing satisfying assignement. Use the '--printsol 1' option for that

but sometimes it prints something from previous search example attached:

c luby  stb  mp1  2845  688K    3462 11281   25K   12.92    5.37   20K  6213   29K  232K  229.15   46.38
c luby  stb  mp1  2846  696K    3462 11281   25K   12.92    5.37   20K  6218   21K  232K  194.74   35.44
c luby  stb  mp1  2846  704K    3462 11281   25K   12.92    5.37   21K  6088   29K  232K  233.52   47.58
c [g 0] truth-find prop checks  : 90
c [g 0] -> of which prop        :  0.00 %
c [g 0] -> of which confl       :  0.00 %
c [g 0] elim called             : 1792
c [g 0] ---> which lead to prop :  0.00 %
c [g 0] ---> which lead to confl:  0.00 %
c [g 0] size: 5     x 9    
c ------- FINAL TOTAL SEARCH STATS ---------
c UIP search time          : 1133.19     (95.19     % time)
c restarts                 : 2846        (249.13    confls per restart)
c blocked restarts         : 2           (0.00      per normal restart)
c time                     : 1133.19     
c decisions                : 1467072     (0.00      % random)
c propagations             : 353M        (311K      props/s)
c decisions/conflicts      : 2.07        
c conflicts                : 709010      (625.67    / sec)
c conf lits non-minim      : 453405181   (639.49    lit/confl)
c conf lits final          : 364.77      
c red which0               : 1511        (0.21      % of confl)
c props/decision           : 0.00        
c props/conflict           : 0.00        
c 0-depth assigns          : 242         (6.06      % vars)
c 0-depth assigns by CNF   : 195         (4.88      % vars)
c reduceDB time            : 0.72        (0.06      % time)
c OccSimplifier time       : 5.61        (0.47      % time)
c [occur] 1.78 is overhead
c [occur] link-in T: 1.54 cleanup T: 0.24
c [occ-substr] long subBySub: 12741 subByStr: 0 lits-rem-str: 12262 T: 3.68
c SCC time                 : 0.05        (0.00      % time)
c [scc] new: 5797 BP 2M  T: 0.05
c vrep replace time        : 1.54        (0.13      % time)
c vrep tree roots          : 5367        
c vrep trees' crown        : 5612        (1.05      leafs/tree)
c distill time             : 43.27       (3.64      % time)
c strength cache-irred time: 0.74        (0.06      % time)
c strength cache-red time  : 0.69        (0.06      % time)
c Conflicts in UIP         : 709010      (595.61    confl/time_this_thread)
c Mem used                 : 125.41      MB
c Total time (this thread) : 1190.39     
s SATISFIABLE
c Not printing satisfying assignement. Use the '--printsol 1' option for that
c [g 0] truth-find prop checks  : 90
c [g 0] -> of which prop        :  0.00 %
c [g 0] -> of which confl       :  0.00 %
c [g 0] elim called             : 1792
c [g 0] ---> which lead to prop :  0.00 %
c [g 0] ---> which lead to confl:  0.00 %
c [g 0] size: 5     x 9

**Comment by vlastikw** [comment]
output was from cr580x64web 
c CMS SHA revision 6477e8bc43b0fda7038965bb148b64b8637c804b

but latest version from github 
c CMS SHA revision 591b1eb21fa201529201d8afc5ebe594e8bc5d7a
does not print it out, closing.

**Comment by ajohnson1** [comment]
I have seen this with the latest code, for both satisfiable and unsatisfiable cases.

> c CryptoMiniSat version 5.8.0
c CMS Copyright (C) 2009-2020 Authors of CryptoMiniSat, see AUTHORS file
c CMS SHA revision 4b7d22f0b40f2234b5f5dac3de36ecdcdf3a9544

> s UNSATISFIABLE
c [g 0] truth-find prop checks  : 359
c [g 0] -> of which prop        :  0.00 %
c [g 0] -> of which confl       :  0.00 %
c [g 0] elim called             : 244
c [g 0] ---> which lead to prop :  0.00 %
c [g 0] ---> which lead to confl:  0.00 %
c [g 0] size: 6     x 13
c [g 1] truth-find prop checks  : 344
c [g 1] -> of which prop        :  0.00 %
c [g 1] -> of which confl       :  0.00 %
c [g 1] elim called             : 642
c [g 1] ---> which lead to prop :  0.00 %
c [g 1] ---> which lead to confl:  0.00 %
c [g 1] size: 5     x 11
c [g 2] truth-find prop checks  : 64
c [g 2] -> of which prop        :  0.00 %
c [g 2] -> of which confl       :  0.00 %
c [g 2] elim called             : 90
c [g 2] ---> which lead to prop :  0.00 %
c [g 2] ---> which lead to confl:  0.00 %
c [g 2] size: 4     x 9
c [g 3] truth-find prop checks  : 191
c [g 3] -> of which prop        :  0.00 %
c [g 3] -> of which confl       :  0.00 %
c [g 3] elim called             : 24
c [g 3] ---> which lead to prop :  0.00 %
c [g 3] ---> which lead to confl:  0.00 %
c [g 3] size: 4     x 9
c [g 4] truth-find prop checks  : 216
c [g 4] -> of which prop        :  0.00 %
c [g 4] -> of which confl       :  0.00 %
c [g 4] elim called             : 22
c [g 4] ---> which lead to prop :  0.00 %
c [g 4] ---> which lead to confl:  0.00 %
c [g 4] size: 3     x 7

**Comment by msoos** [comment]
Thanks so much for the both of you! I have now fixed this issue. Sorry about it :(
