### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by GoldenHamed** [msoos/cryptominisat#636]
Hello,
I ran a sample code of the Cryptominisat as follows:
g++ -std=c++11 multisol_test.cpp -lcryptominisat5 -o readme_test
The following error occurred while running readme_test
./readme_test: libcryptominisat5.so.5.8: cannot open shared object file: No such file or directory
./readme_test: error while loading shared libraries: libm4ri-0.0.20200125.so: cannot open shared object file: No such file or directory

please help me.

**Comment by msoos** [comment]
Hi,

It's not finding the CryptoMiniSat libraries. Most likely you have a broken CryptoMiniSat installation. Please re-build and re-install CryptoMiniSat. It should then work. Please make sure that whereever you install it is in your library search path. For example, passing `-DCMAKE_INSTALL_PREFIX=/usr` to `cmake` will probably do the trick (you will need `sudo make install` after). Please make sure to do a full new build and install (i.e. don't re-use an old `build` directory).

Good luck,

Mate
