### ISSUE TITLE
Rust binding on crates.io

### ISSUE THREAD

**Issue by maxtremblay** [msoos/cryptominisat#637]
Hello,

I see that there is an "old" crate on [crates.io](https://crates.io/crates/cryptominisat) for the Rust bindings. 
Is it possible to publish a new crate with the latest version?

**Comment by msoos** [comment]
Hey!

Thanks for the reminder! Unfortunately, I don't really know how crates work, but perhaps you can help me with it? I have finally managed to put together a much more modern rust setup, [here](https://github.com/msoos/cryptominisat-rs/). Would you be so kind as to try to explain to me how they work and/or help me make sure the newest crate is this setup that I put together? I believe that setup, based on Leander Tentrup's work, is probably a good approach?

What do you think?

Mate

**Comment by maxtremblay** [comment]
Yeah no problem!

I can work on it later this week and send a PR on your other repo. Then it will be easy for you to publish it or I can publish it and 
give you the ownership after.

You will just need an account there https://crates.io/. I personally login with my Github account.

However, the name `cryptominisat` is already used by Leander Tentrup's crate. Maybe it would be nice to ask him the ownership so you can use the name. Else, you will need to find a new name for the rust library. Maybe `cms`.

**Comment by msoos** [comment]
Wow, that'd be great if you could send me a PR to that repo! I just created an account there through GitHub, so I guess you can find me there now? Sorry, I am not sure how the OAuth thing works (you can probably find me with either "msoos" or "soos.mate@gmail.com"). I also tried to update the `Cargo.toml` file but... this is super-confusing to me, so some help would be really welcome!

@ltentrup What do you think? Could you please let me have the cryptominisat crate on crates.io? Or do you need it for something and I should use a different one?

Thanks to both of you in advance,

Mate

**Comment by ltentrup** [comment]
Hi Mate, I'm not the owner of the cryptominisat crate. I've forked the original authors repository in order to update cryptominisat for my solver.

**Comment by maxtremblay** [comment]
I believe @Storyyeller  is the owner.

**Comment by Storyyeller** [comment]
I just sent an invite to username "msoos" on crates.io to take ownership of the crate. Hopefully I did that right.

**Comment by msoos** [comment]
Oh wow, that's great, I just accepted it, thank you so much @Storyyeller !

**Comment by msoos** [comment]
I have just pushed an update to the latest CryptoMiniSat! Let me know if this works, @maxtremblay . Thanks again for reminding me and thanks for all for the quick turn-around times :)

**Comment by maxtremblay** [comment]
Everything works fine. Thank you!

I updated the dependencies of the package https://github.com/msoos/cryptominisat-rs/pull/1

**Comment by msoos** [comment]
Thanks! All good, closing :)
