### ISSUE TITLE
MPI with CMS

### ISSUE THREAD

**Issue by ntt1985** [msoos/cryptominisat#640]
Hello,
I'd like to know if it is possible to use MPI with cryptominisat? I'm trying to include datasyncserver.h in main_exe.cpp but actually I have an error with linker:

[ 90%] Linking CXX executable ../cryptominisat5
/usr/bin/ld: CMakeFiles/cryptominisat5-bin.dir/main_exe.cpp.o: in function `main':
/home/ubuntu/cryptominisat/cryptominisat-5.8.0/src/main_exe.cpp:59: undefined reference to `CMSat::DataSyncServer::DataSyncServer()'
collect2: error: ld returned 1 exit status
make[2]: *** [cmsat5-src/CMakeFiles/cryptominisat5-bin.dir/build.make:136: cryptominisat5] Error 1
make[1]: *** [CMakeFiles/Makefile2:237: cmsat5-src/CMakeFiles/cryptominisat5-bin.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I just added
#ifdef USE_MPI
#include "mpi.h"
#include "datasyncserver.h"
#endif //USE_MPI

int main(int argc, char** argv)
{
.... 
#ifdef USE_MPI
......
        DataSyncServer server;
....
#endif //USE_MPI
....
}

Please can you give some hint?
Thank you

**Comment by msoos** [comment]
Hi,

Sorry, I haven't worked on this for a long while and it's currently not in a working state. You are more than welcome to resurrect it, but currently, I have no plans to do so. Maybe it could be resurrected and then it could participate in the SAT competition track that allows for many machines to work together. Could be fun! Let me know if you made it work! Unfortunately, I can't really help you much, I'm super busy :( Good luck and let me know how it went,

Mate
