### ISSUE TITLE
posix_memalign return code not checked

### ISSUE THREAD

**Issue by ajohnson1** [msoos/cryptominisat#641]
In this line
https://github.com/msoos/cryptominisat/blob/d64d52f548e9c0dd3b202aca34c9fba983baddac/src/packedmatrix.h#L70
the return code is not checked.
The manual for the function says:

> On Linux (and other systems), posix_memalign() does
       not modify memptr on failure.  A requirement standardizing this
       behavior was added in POSIX.1-2008 TC2.
       
This could give some strange errors on out of memory, where the allocation fails, but the old pointer is still used, but with the
new size, possibly overwriting some other data.
An assert here or an exception might be better.

**Comment by msoos** [comment]
Thanks for catching this! I have now pushed a fix for it at 28bbc7e5f4349cb00d76c8cad0fbf83de4627b6e

Thanks again,

Mate
