### ISSUE TITLE
Massive parallelism/GPU question

### ISSUE THREAD

**Issue by sliedes** [msoos/cryptominisat#647]
Feels a bit weird to ask about this in a Github issue, but perhaps it's the best/preferred way :)

I read the [blog post on cryptominisat's parallelism implementation](https://www.msoos.org/2018/07/cryptominisat-and-parallel-sat-solving/) (from 2018, I assume not much has changed there).

This inspired me to think that this is actually the kind of parallelism that could be easily implemented on a GPU. Amount of available memory could become an issue, perhaps. What it would provide is tons of slow threads.

I guess what I'd like to ask is your expert intuition on whether something like this could be a good idea. I realize it can well be that for SAT solving 2000 slow threads is still much worse than 8 fast threads (though I guess you could have both on a machine with a CPU and a GPU?). I wouldn't promise to work on this at least immediately, but I just might take a look at it maybe sometime this year. It helps that cryptominisat is the only modern SAT solver I know of whose code I can read without getting a headache. :)

Anyway, feel free to close this issue, or whatever. If I end up looking into this, I'll surely be back!

**Comment by msoos** [comment]
Closing because it's stale and not a bug that can be addressed.
