### ISSUE TITLE
Wish: Fix (and not remove) dumping of red (at least binary) clauses

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#648]
I wanted to express my wish, to fix exporting of reducible clauses.
For my cases (most of the time) binary clauses would be enough.
I have used it a lot in the past (e.g. CMS 5.0.2), in the meantime it was not working.
I have debugged it a few days ago and it is now working again (at least with some small hacks).

Background: I often have the case, that I not just want to solve a problem, but also want to learn
what CMS has learned. E.g. a certain combination of variable is not possible.
I can easily verify this, by setting the variables, and see that it returns UNSAT.
And after some thinking, I sometimes can understand why it is not possible.
And perhaps generate a lot more such clauses, even by knowing this knowledge.
I don't know of any other SAT solver, which is able to do this. It is a unique feature of CMS for me.

2. Background: I will open a separate issues for this topic.
But here in short: When I try to solve a problem, and dump red binary clauses,
I see that red clauses are exported, which I fill in as input (irred clauses) for my problem.
I assume, somewhere deep in the code, there is some bug. Perhaps irred clauses are removed.
Or a new red clauses is generated, even when the same irred clause exists.
At this point only speculation. But with exporting the red clauses,
I was able to see that there is something which I cannot explain, why is happens.

Now to my local hacks (only 2! I assume easy ones to fix):

1) When I search for redDumpFname:

https://github.com/msoos/cryptominisat/search?q=redDumpFname

I see where the variable redDumpFname is created and used. I looks like it is a global variable.
I filled the variable redDumpFname with a value "abc.cnf" in signalcode.c when the Ctrl-C or timeout handling takes places.
And the file which is dumped, is now really dumped, but not with name "abc.cnf", but the content of the command line parameter.

2) https://github.com/msoos/cryptominisat/blob/master/src/main.cpp#L1451

    lbool ret = multi_solutions();

    if (conf.preprocess != 1) {
        if (ret == l_Undef && conf.verbosity) {
            cout
            << "c Not finished running -- signal caught or some maximum reached"
            << endl;
        }
        if (conf.verbosity) {
            solver->print_stats();
        }
        if (ret == l_True) {
            dump_red_file();
        }

dump_red_file() is only called, when ret is l_True. I assume this is SAT, because with UNSAT it does not make sense to dump the clauses, because no clauses are left. But when pressing Ctrl-C or timeout, I assume it is l_Undef.
In my local test, I have just commented out the check at all.

With the two bugfixes, I can dump red clauses to a file and they look useable/valid.

**Comment by capiman** [comment]
Closed due to

https://github.com/msoos/cryptominisat/issues/649#issuecomment-917955379

**Comment by msoos** [comment]
I have now added you to the private repository. It may or may not have this issue fixed. Perhaps you can check. Also, it's missing the dumping but it has a much more sophisticated CNF-getting system that can get the clauses as a library:

```
        void start_getting_small_clauses(uint32_t max_len, uint32_t max_glue, bool red = true, bool bva_vars = false, bool simplified = false);
        bool get_next_small_clause(std::vector<Lit>& ret, bool all_in_one = false); //returns FALSE if no more
        void end_getting_small_clauses();
        std::vector<uint32_t> translate_sampl_set(const std::vector<uint32_t>& sampl_set);
        void get_all_irred_clauses(std::vector<Lit>& ret);
```

This can get all clauses, irred, red, etc. in a very cool way, programmatically, from the library. However, `main.cpp` doesn't have the code to dump the clauses. It's probably like 10 lines of code to dump. Also, it should have a much better clause subsumption system so maybe you won't have this issue of things being learned twice.

Sorry, that's the best I can do right now, I am _very_ much overwhelmed with 100s of things :(

**Comment by capiman** [comment]
Thank you!
