### ISSUE TITLE
Try to find the root cause (if there is any) of duplicate red clauses (duplicate to same irred clauses)

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#649]
As already mentioned in https://github.com/msoos/cryptominisat/issues/648
I see red clauses, which I assume are perhaps worth to look at.

I fill in (via --input) a file which e.g. contains 

-1 -2 0

(and of course a lot other clauses)

When looking at the red dumped file, I see exact the same clause (even multiple times).
When it is a thing not to worry about, could happen by design, then ok.

Otherwise perhaps can we (you and others reading this issue) discuss how to narrow and clarify the problem?

Would it perhaps be possible to put additional checks inside binary clause adding?
For certain clauses? I see the possibility to add check clauses, at least when I get back the real numbers of the variables.
Or perhaps add a check, if a red clauses is added, if the same irred clause is alrrady existing?
I assume if we can immediately assert at this point, it would be much easier to find out the cause.

What I don't know: Perhaps it is no problem at all. It could be normal that this type of duplicate clauses can be generated.
Perhaps they are checked and erased later? Or perhaps not erased at all, because finding this clauses would be more
expensive than working with them?

**Comment by msoos** [comment]
Hi Marie,

I have been updating this whole setup lately, it should be a lot better! Give me a bit of time, maybe 2 weeks, and I can give you access. I can't make it mainline because there are some papers I still need to publish about it :disappointed: Please ping me in 2 weeks if I forget to give you access, I will keep this open in the meanwhile!

Sorry for the backlog, I got a bit burned out in the past weeks and I had a bit of a medical hiccup. Sorry. I'll get back to you in 2 weeks!

Sorry, and thanks for your patience,

Mate

**Comment by capiman** [comment]
Hi Mate,

thanks for your answer. No hurry, take the time you need. Your health is more important. Best wishes for a speedy recovery!

Best regards,
Marie

**Comment by capiman** [comment]
With latest publicly available version, when I try

cat dumped-red-clauses-shorter-than-or-equal-2.cnf | grep -v "c " | sort | wc -l
cat dumped-red-clauses-shorter-than-or-equal-2.cnf | grep -v "c " | sort | uniq | wc -l

There is sometimes a significant difference in the reported numbers.

**Comment by capiman** [comment]
Just a link to a first test version:

https://github.com/capiman/cryptominisat/commit/49f58fdd1a4448d4441e77bb1b60ba754675c7bb

**Comment by msoos** [comment]
I have improved the setup, but frankly, I don't intend to maintain CryptoMinISat as a SAT solver much longer. I suggest you move to kissat, it's a better solver. Sorry, but I can't keep up with these requests, I simply don't have time. Unfortunately, I really-really don't have time, I am squashed. Sorry.

**Comment by capiman** [comment]
Many thanks for everything. CryptoMiniSat is a great program with a lot of special and useful features.
I wish you all the best!

**Comment by msoos** [comment]
I have now added you to our private repository and in the other thread I explain how to get the clauses in a much more sophisticated way, as a library. I hope that helped. Sorry, I am overwhelmed. Really, months of work needs to be published.
