### ISSUE TITLE
Support cross-compilation by removing check_float_precision

### ISSUE THREAD

**Issue by Wimmerer** [msoos/cryptominisat#650]
Hi! I'm trying to cross-compile CryptoMiniSat for a large number of different environments. Unfortunately the CheckFloatPrecision.cmake file gets in the way of doing that on Linux. I believe it's because it's trying to run a compiled file on the target, but obviously that's not possible in cross-compilation.

What is the exact purpose of this check, and can it be safely removed? I've removed it myself in testing, and everything builds just fine, but I could be silently creating a lot of problems down the line. Running cmake twice works (the dummy values are cached?) or just removing that section of CMakeLists.txt.

Thanks!

**Comment by andrewvaughanj** [comment]
It seems that all this check does is to set `HAVE__FPU_SETCW` and, if that's set, it enables `YALSAT_FPU` -- however, if you're commenting out that check, then `YALSAT_FPU` won't be enabled, so you won't be building with it. I presume that CMS functions fine without `YALSAT_FPU`.

Maybe CMS needs something like:

- https://github.com/getdnsapi/getdns/pull/472/commits/320dd098a8d4d936f439348821e2d7cb707503d5

to avoid having these kind of issues when you're cross-compiling.

Maybe make a PR if this solves it for you?

**Comment by Wimmerer** [comment]
That does work for me. I'll put in a PR this afternoon, although I'd like to know what is lost by removing yalsat. I'll read the Yalsat + CMS paper.

**Comment by andrewvaughanj** [comment]
My understanding of YalSAT is that it is similar to CCAnr, which @msoos describes very briefly [here](https://www.msoos.org/2020/07/cryptominisat-5-8-0-released/) (see: "CCAnr Local Search Solver").

**Comment by Wimmerer** [comment]
This is also related to cross-compiling so I'll note it here to avoid polluting the issues: On musl platforms we get a `/workspace/srcdir/cryptominisat/src/main_exe.cpp:34:5: error: ‘feenableexcept’ was not declared in this scope`, which is caused by a block of code in a `#if defined(__GNUC__) && defined(__linux__)` block. Should this be `(__GLIBC__)`?

**Comment by andrewvaughanj** [comment]
It probably should be `_GNU_SOURCE` based on https://linux.die.net/man/3/feenableexcept

**Comment by msoos** [comment]
Diet of all thank you so much for your packaging work, I really appreciate it!  I I'm so sorry for being late on responding. Indeed, Yalsat is not used by default. It can be ripped out and maybe I will do just that so don't worry about disabling it!

Sorry, not near a computer right now and the past days were very busy :( I'll respond tomorrow in detail, but for now, don't worry about Yalsat, just disable it :)

Thanks so much again,

Mate

**Comment by msoos** [comment]
Hey @Wimmerer  can you please check if 9c557ab82974a012297793324d12cfdf00e4c744 solved it? I basically made `yalsat` optional :)

Thanks,

Mate

**Comment by Wimmerer** [comment]
Looks like it! Everything looks good [here](https://github.com/JuliaPackaging/Yggdrasil/pull/2923)! Thanks very much @msoos and @andrewvaughanj!

Will
