### ISSUE TITLE
Try to use 5.6.8 windows exe to simplify a cnf file, but the return simplified.cnf is blank

### ISSUE THREAD

**Issue by AlvinSeyir** [msoos/cryptominisat#653]
Hi, I was trying to use the exe to simplify a cnf file, here is the log appeared on the cmd.
[test.zip](https://github.com/msoos/cryptominisat/files/6738598/test.zip)
`
c Outputting solution to console
c CryptoMiniSat version 5.6.8
c CMS Copyright Mate Soos (soos.mate@gmail.com)
c CMS SHA revision 6db37867861bf6aec41042d87638c93207064c34
c CMS is MIT licensed
c CMS compilation env CMAKE_CXX_COMPILER = C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe | CMAKE_CXX_FLAGS = /DWIN32 /D_WINDOWS /W3 /GR /EHsc | COMPILE_DEFINES =  -DNDEBUG -D_FORTIFY_SOURCE=0 | STATICCOMPILE = ON | ONLY_SIMPLE = OFF | Boost_FOUND = 1 | STATS = OFF | SQLITE3_FOUND =  | ZLIB_FOUND =  | VALGRIND_FOUND = FALSE | ENABLE_TESTING = OFF | M4RI_FOUND = FALSE | NOM4RI = OFF | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = OFF | PYTHON_EXECUTABLE = C:/Python36-x64/python.exe | PYTHON_LIBRARY = C:/Python36-x64/libs | PYTHON_INCLUDE_DIRS = C:/Python36-x64/include | MY_TARGETS =  | LARGEMEM = OFF | LIMITMEM = OFF | compilation date time = Feb 19 2019 23:31:18
c CMS compiled with non-gcc compiler
c Executed with command line: cryptominisat5.exe -p1 test.cnf simplified.cnf
c Reading file 'test.cnf'
c -- header says num vars:             31
c -- header says num clauses:          42
c -- clauses added: 42
c -- xor clauses added: 0
c -- vars added 31
c Parsing time: 0.01 s
c --> Executing strategy token: handle-comps
c --> Executing strategy token: scc-vrepl
c [scc] new: 0 BP 0M T: 0.00
c [vrep] vars 0 lits 0 rem-bin-cls 0 rem-long-cls 0 BP 0M T: 0.00
c --> Executing strategy token: cache-clean
c --> Executing strategy token: cache-tryboth
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 T: 0.00 T-out: N w-visit: 62
c --> Executing strategy token: sub-str-cls-with-bin
c [distill] cache-based irred--  cl tried       14 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.00 T-out: N
c [distill] cache-based   red--  cl tried        0 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.00 T-out: N
c --> Executing strategy token: distill-cls
c [distill] long cls tried: 7/4 cl-short:2 lit-r:3 T: 0.00 T-out: N T-r: 100.00%
c [distill] long useful: 4/14/14 lits-rem: 6 0-depth-assigns: 20 T: 0.01 T-out: N
c --> Executing strategy token: scc-vrepl
c [scc] new: 0 BP 0M T: 0.00
c [vrep] vars 0 lits 0 rem-bin-cls 0 rem-long-cls 0 BP 0M T: 0.00
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 T: 0.00 T-out: N w-visit: 62
c --> Executing OCC strategy token(s): 'occ-backw-sub-str,occ-clean-implicit,occ-bve,occ-bva,occ-ternary-res,occ-xor,'
c [occ] mem usage for occur      0 MB
c [occ] mem usage for occur      0 MB
c Mem for watch alloc      : 0           MB (0.00      %)
c Mem for watch array      : 0           MB (0.00      %)
c --> Executing OCC strategy token: occ-backw-sub-str
c [occ-backw-sub-str-long-w-bins] subs: 0 str: 0 tried: 18 0-depth ass: 0 T: 0.00 T-out: N T-r: 100.00%
c [occ-sub-long-w-long] rem cl: 0 tried: 2/1 (200.0%) T: 0.00 T-out: N T-r: 100.00%
c [occ-sub-str-long-w-long] sub: 0 str: 0 tried: 3/1 (300.0)  T: 0.00 T-out: N T-r: 100.00%
c --> Executing OCC strategy token: occ-clean-implicit
c --> Executing OCC strategy token: occ-bve
c [occ-empty-res] Empty resolvent elimed: 3 T: 0.00 T-out: N
c [occ-bve] iter v-elim 7
c cl_inc_rate=0.0, var_dec_rate=1.0 (grow=0)
c Reduced to 0 vars, 0 cls (grow=0)
c [occ-bve] iter v-elim 0
c cl_inc_rate=2.0, var_dec_rate=1.0 (grow=8)
c Reduced to 0 vars, 0 cls (grow=8)
c x n vars       : 0
c  #try to eliminate:      7
c  #var-elim        :      7
c  #T-o: N
c  #T-r: 100.00%
c  #T  : 0.02
c [occur] 0.00 is overhead
c [occur] link-in T: 0.00 cleanup T: 0.00
c --> Executing OCC strategy token: occ-bva
c --> Executing OCC strategy token: occ-ternary-res
c --> Executing OCC strategy token: occ-xor
c [occ-xor] sort occur list T: 0.00
c [occ-xor] found      0 T: 0.00 T-out: N T-r: 100.00%
c [xor-add-lem] added unit 0 bin 0 T: 0.00
c --> Executing strategy token: cl-consolidate
c Not consolidating memory.
c --> Executing strategy token: str-impl
c [impl str] lit bin: 0 (by stamp: 0) set-var: 0 T: 0.00 T-out: N T-r: 100.00% w-visit: 62
c --> Executing strategy token: cache-clean
c --> Executing strategy token: sub-str-cls-with-bin
c [distill] cache-based irred--  cl tried        0 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.00 T-out: N
c [distill] cache-based   red--  cl tried        0 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.00 T-out: N
c --> Executing strategy token: distill-cls
c [distill] long cls tried: 0/0 cl-short:0 lit-r:0 T: 0.00 T-out: N T-r: 100.00%
c [distill] long useful: 0/0/0 lits-rem: 0 0-depth-assigns: 0 T: 0.01 T-out: N
c --> Executing strategy token: scc-vrepl
c [scc] new: 0 BP 0M T: 0.00
c [vrep] vars 0 lits 0 rem-bin-cls 0 rem-long-cls 0 BP 0M T: 0.00
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 T: 0.00 T-out: N w-visit: 62
c --> Executing strategy token: str-impl
c [impl str] lit bin: 0 (by stamp: 0) set-var: 0 T: 0.00 T-out: N T-r: 100.00% w-visit: 62
c --> Executing strategy token: sub-impl
c [impl sub] bin: 0 T: 0.00 T-out: N w-visit: 62
c --> Executing strategy token: sub-str-cls-with-bin
c [distill] cache-based irred--  cl tried        0 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.00 T-out: N
c [distill] cache-based   red--  cl tried        0 cl-sh     0 cl-rem    0 lit-rem      0 T: 0.00 T-out: N
c --> Executing strategy token: intree-probe
c [scc] new: 0 BP 0M T: 0.00
c [vrep] vars 0 lits 0 rem-bin-cls 0 rem-long-cls 0 BP 0M T: 0.00
c [intree] Set 0 vars hyper-added: 0 trans-irred::0 trans-red::0 T: 0.00 T-out: N T-r: 100.00%
c --> Executing strategy token: probe
c --> Executing strategy token: must-renumber
c [renumber] T: 0.00
c [consolidate] mini T: 0.00
c global_timeout_multiplier: 6.60
Wrote solver state to file savedstate.dat and simplified CNF to file simplified.cnf
s INDETERMINATE
`

However, the simplified file is blank
[simplified.zip](https://github.com/msoos/cryptominisat/files/6738593/simplified.zip)
Here is the dat file.
[savedstate.zip](https://github.com/msoos/cryptominisat/files/6738605/savedstate.zip)

Could you please offer me some help? Thanks a lot!

**Comment by msoos** [comment]
Hi,

You can now save the simplified file. It's a valid CNF -- and it's satisfiable. And then, you can use the stated way to feed the solution to the empty but valid CNF to the solver, along with the saved state, and get a solution to the whole file. In other words, the system worked perfectly.


Note that simplification **does not** guarantee to preserve the **number of solutions**. What the system did is in fact eliminate everything from your CNF and saved it in savedstate. You now need to feed it a trivial SATISFIABLE solution (with `v 0` as the trivial solution itself), and it will extend that solution to a solution of your whole problem.

You can solve that empty CNF any way you like, all SAT solvers should understand and solve it. Then feed that to the solver, and it will work like charm.

The above should do the trick,

Mate

PS: You kinda stumbled upon an "edge case" but it's an edge case that actually is meant to work flawlessly. Just follow the example how to extend the solution to the simplified CNF to the full CNF and it will work fine.
