### ISSUE TITLE
Wish: Description of internal data structures and methods acting on them

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#66]
I wish (BTW: happy easter!) there would be some pages or documents describing 
internals data structures and methods, which are working on them.

Also it would be great if there are descriptions of big parts, like the searcher
(search, new_decision, pickBranchLit, handle_conflict, burstSearch, 
analyzeHelper, analyze, ...), propagation, ...

Here is a list of some variables/notes, which i have written down some time ago,
which is perhaps a start:

Fixed variables:
-> unitaries
-> trail[x]
-> trail.size()
-> trail_lim
-> trail_lim.size()
-> trail_lim[0] seems to be something special

XOR:
-> table[x]
-> table.size()

binary clauses:
-> watches
-> goes from watches.begin() to watches.end()
-> isBinary()

tri clauses:
-> watches
-> goes from watches.begin() to watches.end()
-> isTri()

normal clauses:
-> longIrredCls
-> goes from longIrredCls.begin () to longIrredCls.end()

blocked clauses: 
-> blockedClauses
-> goes from blockedClauses.begin() to blockedClauses.end()

Are there perhaps info documents from Minisat which could be taken
also for CMS and are still valid for describing at least on a high level,
even when only describing part of them?
Or too much new development, which is not comparable?

I know it takes time and cannot be done in a day or two,
but perhaps with distributed help such a description could be created.
How about doing it with / like a Wiki? Github seems to offer a Wiki,
but at the moment it only seems to redirect to a not Wiki page?

**Comment by msoos** [comment]
There are about a million things to do, and describing the internals won't help much -- plus it changes all the time. It's not the data structures that are complicated. It's the algorithms that are described in about 20 different research papers that are hard to read. Knowing the data structures won't help unless the algorithm is described, but that is the hard part.
