### ISSUE TITLE
BreakID cannot be linked with -DSTATICCOMPILE=ON

### ISSUE THREAD

**Issue by tobipaxe** [msoos/cryptominisat#661]
We had the issue on some Linux machines that BreakID cannot be linked as it tries to link the *.so variant into the static version of CMS or does not find BreakID at all.

Our fix is:
BreakID
-----
With the following steps you can get BreakID and install it (tested on Ubuntu).

```
git clone https://github.com/meelgroup/breakid
mkdir build 
cd build 
cmake -DSTATICCOMPILE=ON ..
make -j
```

Then you should be able to run `cmake (-DSTATICCOMPILE=ON) ..` at your CMS repository. For me it was necessary to delete all files from the build folder first.

**Comment by msoos** [comment]
Hey hey! Thanks so much for letting me know, I fixed it with a note in the README, let me know if this is OK :) I hope you find CryptoMiniSat helpful. The BreakID integration is especially powerful actually :)

**Comment by tobipaxe** [comment]
You're welcome :-) - It would still be helpful to add to the readme where to checkout BreakID: git clone https://github.com/meelgroup/breakid; or maybe add it as subproject...

**Comment by msoos** [comment]
Ah, OK good point! Added the location now too! Yay! :)
