### ISSUE TITLE
Would like to have compiled binaries in each release

### ISSUE THREAD

**Issue by S0mbre** [msoos/cryptominisat#663]
It would be super cool to have precompiled Windows and Linux binaries in each release! The compilation toolchain (especially in Windows) is very tedious and many just don't have the compiler installed (or are unable to do so). For now, I have rather to browse for cryptominisat5.exe elsewhere on the web.

**Comment by slel** [comment]
Cryptominisat is packaged for Conda on Linux and macOS,
but not Windows, in the conda-forge channel:

https://anaconda.org/conda-forge/cryptominisat

**Comment by slel** [comment]
Providing a Conda version for Windows is discussed at

https://github.com/conda-forge/cryptominisat-feedstock/issues/1

**Comment by WonJayne** [comment]
Hi,

> I am working on PyPI. It's actually a lot harder than one would imagine, but I finally (less than a week ago!) got access to the pycryptosat package! Soon there will be a pip package, yay!

Any updates on that? That would be awesome! I am really looking forward to that.
