### ISSUE TITLE
preprocessing time

### ISSUE THREAD

**Issue by johannaSommer** [msoos/cryptominisat#668]
Hi,

thank you msoos for this great repository. 

I am trying to get the timings of two kinds of run configs:
1. solve with cryptominisat (default arguments)
2. preprocess with cryptominisat, save simplified files, load them and solve with cryptominisat (without any further preprocessing)

on a subset of the SATLIB benchmark data. I would expect these runtimes to be somewhat similar.

However, when I time:
`
for entry in ls satlib/; do
    cryptominisat5 --verb 0 satlib/$entry
done
`
I get 
`
real    0m10,636s
user    0m7,000s
sys     0m3,042s
`

and for 
`
for entry in ls satlib/; do
    cryptominisat5 -p1 --verb 0 satlib/$entry satlib-sim/$entry
done
`
I get 
`
real    0m23,349s
user    0m11,104s
sys     0m3,592s
`
which tells me that the preprocessing alone takes longer than actually solving the instances. I also tried to set the `preschedule` of the preprocessing to the schedule that is used at startup, but it still takes longer and couldn't find any further information in the docs or other issues.

What am I missing here? Thank you in advance!

**Comment by johannaSommer** [comment]
Hi Msoos,

thank you so much for the thorough answer, that did indeed clarify a lot of things. Cheers!

**Comment by msoos** [comment]
Glad to hear! Cheers!
