### ISSUE TITLE
Function `CMSat::add_xor_clause` does not take literals

### ISSUE THREAD

**Issue by vuphan314** [msoos/cryptominisat#672]
Hi Mate @msoos 

Using the CMS C++ library, how can I add an XOR constraint such as `v1 XOR -v2 = 1`?

The function `CMSat::add_xor_clause` takes variables, not literals:

https://github.com/msoos/cryptominisat/blob/7909d81f377687bc38df0ac2c04b0c14518acc7f/src/cryptominisat.h.in#L65

Thank you.

**Comment by vuphan314** [comment]
Actually, your blog post helped me:
https://www.msoos.org/xor-clauses/

Now I know that an odd number of negated variables is equivalent to a `0` right-hand side.

**Comment by msoos** [comment]
Glad you figured it out. Sorry it wasn't clear!

Mate
