### ISSUE TITLE
how to find the max number of solution? and the meaning of '--nobansol'

### ISSUE THREAD

**Issue by ywang9-12** [msoos/cryptominisat#673]
for examlple, the test.cnf is contained:
p cnf 3 1
1 -2 3 0
i  want to find the max number of solution. now, i through setting a huge number to '--maxsol', like 'cryptominisat5 test.cnf --maxsol 10000', and get the result
![image](https://user-images.githubusercontent.com/51410548/154465217-aca2b26e-d5c8-494e-883a-e6037ad7ba95.png)
so, i can know the max number of solution is 7.
![image](https://user-images.githubusercontent.com/51410548/154465838-ce1a98b5-ba66-4d83-b7fb-2a1451b50aca.png)
but it's not convient. if i run the command 'cryptominisat5 test.cnf', i can only get one solution.
i found another parameter '--nobansol', the explain in help is 'Don't ban the solution once it's found'.
but when i run the command 'cryptominisat5 test.cnf --nobansol', The results did not change.
![image](https://user-images.githubusercontent.com/51410548/154468652-5c99e261-0165-4d20-9a63-5fdafd9b8bc8.png)
so i don't understand how to use '--nobansol', and how to find the max number of solution?

**Comment by msoos** [comment]
Hi,

You can use the `--maxsol 10000` option, but if there are more than 10000 solutions, this will only list 10000. Instead, I suggest using https://github.com/meelgroup/approxmc as mentioned above! That will count the solutions to your CNF even if there are billions or trillons, or more, solutions.

I hope this helped,

Mate
