### ISSUE TITLE
Cryptominisat 3 visualization backend code open?

### ISSUE THREAD

**Issue by msoos** [msoos/cryptominisat#675]

**Comment by msoos** [comment]
Well... it used to be part of CryptoMiniSat. I think you may be able to find a version that works, but it'll be quite old. The PHP code is part of CryptoMiniSat code. You can reder it all. It's probably around year ~2012. You will need to compile with -DUSE_STATS=ON (a cmake parameter) and run a MySQL database. It will then dump all the data to MySQL. You can then launch an Apache web server, point it to the PHP, and it should work. But it's been a looong while. Anyway, the code is open, both the PHP and the code to dump the SQL to the database. You'll need to pass some parameters, check out files that are named with sql. There should be one with mysql. Again, beware, this code has been stale/removed since around ~2014. So you probably need to look at it earlier. The GIT history should help.

I seem to have blogged about this in November 2012: https://www.msoos.org/2012/11/collecting-solver-data/ So the code around that time should be suitable, maybe a bit later, when it was perhaps debugged/improved :) The JavaScript on the static page's data I think is generated by a shell script from a subdirectory, probably "web/" or something. The HTML+Javascript should be under the same folder in old CryptoMiniSat I think (maybe "web/"?). I don't hide any of this work, and it should all be open-source. If you have issues with licensing, let me know. I even changed the graphing JS library, because it was too slow. It's called "dygraphs", also part of the code.

Do not forget to call  "git submodules init" "git submodules update".

Good luck and let me know if it works!

**Comment by msoos** [comment]
Ah, I found it. The file that generates the static data dump is called `file_creator.py`, see under `web`: https://github.com/msoos/cryptominisat/blob/master/web/file_creator.py

**Comment by msoos** [comment]
Yep, so I just checked, the `web/` directory should contain all you need, once the data is dumped to MySQL. But modern CrytpoMiniSat doesn't dump to MySQL, and the database format has changed. So you need an old CryptoMiniSat, dump to MySQL, then use the `file_creator.py` to generate the static file. Then you can just render index.html, without PHP, and it should just work :_

**Comment by Geremia** [comment]
@msoos Thanks. Are there any other good visualization tools?
The Java-based [DPvis](https://web.archive.org/web/20070627003352if_/http://www-sr.informatik.uni-tuebingen.de/~sinz/DPvis/downloads/DPvis-Linux.zip) is slow on CNF files with millions of variables and clauses.

**Comment by Geremia** [comment]
@msoos 
>modern CrytpoMiniSat doesn't dump to MySQL, and the database format has changed.

I can't simply [convert the sqlite to MySQL](https://stackoverflow.com/a/52177105/1429450)?

**Comment by Geremia** [comment]
@msoos  `file_creator.py` throws:

```
Traceback (most recent call last):
  File "./file_creator.py", line 4, in <module>
    import MySQLdb as mdb
ImportError: No module named MySQLdb
```
I [couldn't find MySQLdb on PyPi](https://pypi.org/search/?q=MySQLdb).

**Comment by msoos** [comment]
MySQL is a database. It needs to be properly installed an configured. It's not a PyPi package.

No, you can't convert the sqlite to MySQL because the schema is different. You need to get CMS from 2012-1013. Create a MySQL DB and run it the solver that way. Then you can use that python package to dump the data to a file.

Good luck,

Mate

**Comment by msoos** [comment]
The visualization backend is no longer maintained. I am now deleting all of `web/` and removing the submodules associated.
