### ISSUE TITLE
Cryptominisat does not seem to support complemented variables for XOR clauses

### ISSUE THREAD

**Issue by LeandreBl** [msoos/cryptominisat#677]
Hi,
As I've witnessed at the moment, there is no way to have complemented variables in a XOR clause in the current API ?
`add_clause` takes a `std::vector` of `Lit`, where `add_xor_clause` takes a `std::vector` of `unsigned int`.
So I have tried to simply apply the constructor of `Lit` to a simple `unsigned int` by doing
```c
unsigned int get_complemented_variable_from_variable_id(unsigned int variable_id, bool is_complemented)
{
    return variable_id + variable_id + is_complemented;
}
```

Then I simply create a vector of this by pushing back the result of my function, but the results are far from being valid.

Note that, I'm trying it in C++ for the moment for testing purposes, but the main goal is to use it in C.
As it does not trigger anything in C++, it does `throw` in C at:
```
cryptominisat/src/solver.h:340: void CMSat::Solver::back_number_from_outside_to_outer(const std::vector<CMSat::List>&): Assertion `lit.var() < nVarsOutside()' failed.
```
So I don't think it's the proper way (in case of C maybe ?), is there one way to add xor clauses with complemented variables ?

Best regards.

**Comment by a1880** [comment]
The cryptominisat DimacsParser simply inverts the right-hand-side for inverted variables:

```
    bool rhs = true;
    vars.clear();
    for(Lit& lit: lits) {
        vars.push_back(lit.var());
        if (lit.sign()) {
            rhs ^= true;
        }
    }
    solver->add_xor_clause(vars, rhs);
```

**Comment by msoos** [comment]
Hi,

Thanks @a1880 for the description! Indeed, that's what it does. So if you want to add `a+b+c=0`, then you push in Literals that have their sign as `false`. If you want to have `a+b+c=1` then you push in Literals with signs `false` for `a` and `b` and for `c` you set the sign `true`. For example:

```
add_xor_clause(vector<Lit>{Lit(0, false), Lit(1, false), Lit(2, true)});
```

Adds an XOR clause: `v1+v2+v3=true`.

Let me know @LeandreBl if this helped!

Cheers,

Mate

**Comment by LeandreBl** [comment]
Hi again, sorry I just think I understand now.
Tell me if I'm wrong,
A xor clause can be simplified by only keeping one complemented variable if the number of complemented variables is odd and none if it's even.
`x -1 2 -3 -4 0` (=1) turns into an implicit `x -1 2 3 4 0` (=1) and for cmsat `x 1 2 3 4 0` (=0) ?
So I need to create fully non-complemented clauses and just change the awaited result ?

**Comment by msoos** [comment]
I don't understand what you mean by "fully complemented clauses", sorry. You can write: `x 1 2 0` or you can write `x -1 -2 0`, and they BOTH mean the same thing: `v1 XOR v2 = 1`. If you want to write `v1 XOR v2 = 0` you can write: `x 1 -2 0` or `x -1 2 0`, they both mean the same thing.

I hope this helped,

Mate

**Comment by LeandreBl** [comment]
Ok I got it, it works now, thank you so much.
