### ISSUE TITLE
How to recover XORs from a CNF

### ISSUE THREAD

**Issue by flybfb** [msoos/cryptominisat#680]
Hi,sir

Can I use Cryptominisat5 to convert a CNF file to a mixture of CNF and XNF through Recover XORs and write it out?
How to use the command to operate Cryptominisat5.

I would be grateful if you could answer my questions.

**Comment by msoos** [comment]
Hi,

You can see the command line by issuing `--hhelp` (with two `h`). CMS cannot convert CNF to CNF-XOR. You can, however, see the XORs CryptoMiniSat recovers if you increase the verbosity. You can also implement our XOR recovery in e.g. python. See the algorithm here "BIRD: Engineering an Efficient CNF-XOR SAT Solver and its Applications to Approximate Model Counting", PDF: https://ojs.aaai.org/index.php/AAAI/article/download/3974/3852

Good luck, I hope the above helped,

Mate

**Comment by flybfb** [comment]
Thanks for the comments. I will try it according to your comments.
