### ISSUE TITLE
Install Error in macOS Monterey 12.3

### ISSUE THREAD

**Issue by Zhaowenqing** [msoos/cryptominisat#684]
I want to use cmake to install in my macOS.But when I execute "make" command, errors as figures shows appear
. What should I do to solve these problems?

<img width="646" alt="make error" src="https://user-images.githubusercontent.com/27285838/171884539-f11d727f-fc52-4f9b-a945-364a507b0d31.png">

**Comment by msoos** [comment]
Hi,

I need a full log of everything you did and got back. Please delete the `build` directory, and then issue cmake and make, and send me all the logs of everything it output. Please also include all the commands you typed. Please also make sure not to include it as a screenshot but as text so it's easier to read.

Looking forward to helping,
Mate

**Comment by msoos** [comment]
Sorry for the late response.

Ah! This actually built `cryptominista5`! You only have trouble with the Python bindings. Do you need the Python bindings? If not, you can build with:

```
cmake -DENABLE_PYTHON_INTERFACE=OFF ..
make -j4
sudo make install
```

And then it will work. Unfortunately, the Python bindings seems to try to compile without the `-std=c++11`. That makes the compiler very sad when it encounters `constexpr`. What's weird is that I have:
```
        config_vars['CFLAGS'] = '-g -W -Wall -Wno-deprecated -std=c++11'
        config_vars['OPT'] = '-g -W -Wall -Wno-deprecated -std=c++11'
```
in `python/setup.py.in` So it ought to add that `-std=c++11` -- but it doesn't? Very weird. Maybe you can check how to make sure it's added by playing around with `python/setup.py.in`? Sorry, I really don't understand how that's not added in MacOS.

Sorry again for the late response. Let me know if the above helped,

Mate

**Comment by mkoeppe** [comment]
Just ran into the same problem in https://trac.sagemath.org/ticket/25374#comment:115. 
The homebrew folks seem to have a workaround: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/cryptominisat.rb#L39

**Comment by msoos** [comment]
Hi,

Can you please check again? I have completely removed the `cconf` and so I believe it should build now?

Thanks,

Mate

**Comment by Zhaowenqing** [comment]
Hi, I build and install the project successfully now after your modification. Thank you for your reply.

**Comment by msoos** [comment]
Glad to see!
