### ISSUE TITLE
Segmentation fault on CNFXOR files

### ISSUE THREAD

**Issue by maxzinkus** [msoos/cryptominisat#694]
I've been noticing `cryptominisat5` (and `_simple`) segfaulting on some CNFXOR files in my experiments.

Interestingly, `approxmc` and `arjun` also error on these files due to `arjun` attempting to `add_xor_clause` and hitting an `assert false` with a message about BVAs.

`cryptominisat5 -v`:
```
c CryptoMiniSat version 5.11.0
c CMS Copyright (C) 2009-2020 Authors of CryptoMiniSat, see AUTHORS file
c CMS SHA revision dbb873659b7bf7fdba47a8896922128b040d9b55
c CMS is MIT licensed
c Using VMTF code by Armin Biere from CaDiCaL
c Using Yalsat by Armin Biere, see Balint et al. Improving implementation of SLS solvers [...], SAT'14
c Using WalkSAT by Henry Kautz, see Kautz and Selman Pushing the envelope: planning, propositional logic, and stochastic search, AAAI'96,
c Using code from 'When Boolean Satisfiability Meets Gauss-E. in a Simplex Way'
c       by C.-S. Han and J.-H. Roland Jiang in CAV 2012. Fixes by M. Soos
c Using CCAnr from 'CCAnr: A Conf. Checking Based Local Search Solver [...]'
c       by Shaowei Cai, Chuan Luo, and Kaile Su, SAT 2015
c CMS compilation env CMAKE_CXX_COMPILER = /usr/bin/c++ | CMAKE_CXX_FLAGS =  -fvisibility=hidden -Wall -Wextra -Wunused -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -g -Wno-class-memaccess -mpopcnt -msse4.2 -ggdb3 -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Wshadow -Wformat=2 -Wextra-semi -pedantic | COMPILE_DEFINES =  -DRDB0_ONLY_FEATURES -DBOOST_TEST_DYN_LINK -DUSE_ZLIB -DYALSAT_FPU | STATICCOMPILE = OFF | ONLY_SIMPLE = OFF | Boost_FOUND = TRUE | STATS = OFF | SQLITE3_FOUND =  | ZLIB_FOUND = TRUE | VALGRIND_FOUND =  | ENABLE_TESTING = OFF | M4RI_FOUND =  | NOM4RI = ON | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = ON | PYTHON_EXECUTABLE =  | PYTHON_LIBRARY =  | PYTHON_INCLUDE_DIRS =  | MY_TARGETS =  | LARGEMEM = OFF | LIMITMEM = OFF | BREAKID_LIBRARIES =  | BREAKID-VER = . | BOSPHORUS_LIBRARIES =  | BOSPH-VER = . | compilation date time = Oct  7 2022 16:51:08
c CMS compiled with gcc version 8.4.0
```

`approxmc --version`:
```
c ApproxMC SHA revision 860f89394fcb0214eb7254e527322eb9e3044a0c
c ApproxMC version 4.1.4
c ApproxMC compilation env CMAKE_CXX_COMPILER = /usr/bin/c++ | CMAKE_CXX_FLAGS =  -Wall -Wextra -Wunused -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -fvisibility=hidden -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -g -fvisibility=hidden -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Wshadow -Wformat=2 -Wextra-semi -pedantic | COMPILE_DEFINES =  -DBOOST_TEST_DYN_LINK | STATICCOMPILE = OFF | Boost_FOUND = TRUE | ZLIB_FOUND = TRUE | VALGRIND_FOUND =  | GMP_FOUND = TRUE | ENABLE_ASSERTIONS = ON | MY_TARGETS =  | compilation date time = Oct  7 2022 17:27:16
c ApproxMC compiled with gcc version 8.4.0
c CryptoMiniSat version 5.11.0
c CMS Copyright (C) 2009-2020 Authors of CryptoMiniSat, see AUTHORS file
c CMS SHA revision dbb873659b7bf7fdba47a8896922128b040d9b55
c CMS is MIT licensed
c Using VMTF code by Armin Biere from CaDiCaL
c Using Yalsat by Armin Biere, see Balint et al. Improving implementation of SLS solvers [...], SAT'14
c Using WalkSAT by Henry Kautz, see Kautz and Selman Pushing the envelope: planning, propositional logic, and stochastic search, AAAI'96,
c Using code from 'When Boolean Satisfiability Meets Gauss-E. in a Simplex Way'
c       by C.-S. Han and J.-H. Roland Jiang in CAV 2012. Fixes by M. Soos
c Using CCAnr from 'CCAnr: A Conf. Checking Based Local Search Solver [...]'
c       by Shaowei Cai, Chuan Luo, and Kaile Su, SAT 2015
c CMS compilation env CMAKE_CXX_COMPILER = /usr/bin/c++ | CMAKE_CXX_FLAGS =  -fvisibility=hidden -Wall -Wextra -Wunused -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -g -Wno-class-memaccess -mpopcnt -msse4.2 -ggdb3 -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Wshadow -Wformat=2 -Wextra-semi -pedantic | COMPILE_DEFINES =  -DRDB0_ONLY_FEATURES -DBOOST_TEST_DYN_LINK -DUSE_ZLIB -DYALSAT_FPU | STATICCOMPILE = OFF | ONLY_SIMPLE = OFF | Boost_FOUND = TRUE | STATS = OFF | SQLITE3_FOUND =  | ZLIB_FOUND = TRUE | VALGRIND_FOUND =  | ENABLE_TESTING = OFF | M4RI_FOUND =  | NOM4RI = ON | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = ON | PYTHON_EXECUTABLE =  | PYTHON_LIBRARY =  | PYTHON_INCLUDE_DIRS =  | MY_TARGETS =  | LARGEMEM = OFF | LIMITMEM = OFF | BREAKID_LIBRARIES =  | BREAKID-VER = . | BOSPHORUS_LIBRARIES =  | BOSPH-VER = . | compilation date time = Oct  7 2022 16:51:08
c CMS compiled with gcc version 8.4.0
```

`arjun --version`:
```
c [arjun] SHA revision: 407ea7f5c66ee66693fa0d6cda60558d0d554564
c [arjun] Compilation environment: CMAKE_CXX_COMPILER = /usr/bin/c++ | CMAKE_CXX_FLAGS =  -fvisibility=hidden -Wall -Wextra -Wunused -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -g -Wno-class-memaccess -mpopcnt -msse4.2 -ggdb3 -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Wshadow -Wformat=2 -Wextra-semi -pedantic | COMPILE_DEFINES =  -DRDB0_ONLY_FEATURES -DBOOST_TEST_DYN_LINK -DUSE_ZLIB -DYALSAT_FPU | STATICCOMPILE = OFF | ONLY_SIMPLE = OFF | Boost_FOUND = TRUE | STATS =OFF | SQLITE3_FOUND =  | ZLIB_FOUND = TRUE | VALGRIND_FOUND =  | ENABLE_TESTING = OFF | M4RI_FOUND =  | NOM4RI = ON | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = ON | PYTHON_EXECUTABLE =  | PYTHON_LIBRARY =  | PYTHON_INCLUDE_DIRS =  | MY_TARGETS =  | LARGEMEM = OFF | LIMITMEM = OFF | BREAKID_LIBRARIES =  | BREAKID-VER = . | BOSPHORUS_LIBRARIES =  | BOSPH-VER = . | compilation date time = Oct  7 2022 16:51:08
```

Erroring CNF(XOR) examples:
[errors.zip](https://github.com/msoos/cryptominisat/files/9737734/errors.zip)

`STDOUT` and `STDERR` for `cryptominisat5`, `approxmc`, and `arjun` for one of those erroring CNFXOR files:
[error_72a2ab6ca220c18fcd41.zip](https://github.com/msoos/cryptominisat/files/9737735/error_72a2ab6ca220c18fcd41.zip)

**Comment by msoos** [comment]
Hi,

The newer versions of Arjun don't give a SEGFAULT, but error out (at least if assertions are enabled):

```
arjun: /home/soos/development/sat_solvers/arjun/src/arjun.cpp:91: bool ArjunNS::Arjun::add_xor_clause(const std::vector<unsigned int>&, bool): Assertion `false && "Funnily enough this does NOT work. The XORs would generate a BVA variable, and that would then not be returned as part of the simplified CNF. We could calculate a smaller independent set, but that's all."' failed.
```

In other words, an input that contains XORs doesn't work for Arjun. You can still run the problem with `--arjun 0` with ApproxMC. Then it will run. However, Arjun currently does not support XOR constraints. I could make it work, actually, but it would be quite a major architectural change. I can keep this issue open, as a reminder that XOR constraints are not handled by Arjun.

Sorry to disappoint,

Mate

**Comment by msoos** [comment]
Notice that this is not **completely** insane, just partially. We don't write XOR+CNF, only CNF. Hence, when Arjun simplifies an XOR+CNF, how would we write the simplified CNF? We couldn't, because it could be exponentially large, and introducing variables would be rather insane (even though that's what's happening under the hood). So... it's a bit hard. We'd need to make CMS write XOR+CNF and not blast XORs into CNF. So that would be like a 1000 lines of code change. Not a small change. Possible, though...

**Comment by maxzinkus** [comment]
No that totally makes sense. I think the surprise was in CMS segfaulting when Arjun threw an error.

Thanks for explaining and the quick reply :)

What about a heuristic compromise between the two to prevent erroring out: something like Arjun accepting and outputting CNFXOR but just naively assuming that all xor variables are in the minimum independent set?

Otherwise I can tune my code to do that (`Arjun` over the regular CNF and then append the XOR variables to the MIS) if it's not a reasonable approach in general :)

**Comment by msoos** [comment]
Hi! Beware... adding the XORs after Arjun will LIKELY lead to incorrect independent support! Then the count will VERY likely be WRONG. You can, however, blast the XOR into CNF, then feed that to Arjun. It will accept it, and it should then be able to minimize, etc. Should be... I am not 100% sure, but I think it should work. The other option is for me to fix this. Sorry :S It really takes a lot of time to get all the things right. I am re-opening because this is definitely an issue that needs resolving. Sorry!

Mate

**Comment by maxzinkus** [comment]
Ah- thank you for the tip! I'll let you know if I run into any issues with that approach. Much appreciated!

**Comment by maxzinkus** [comment]
Does CMS have a `--arjun 0` equivalent like `approxmc`?

**Comment by msoos** [comment]
Hi,

What do you mean `--arjun 0`? What would you use it for? Sorry, but I don't understand the question. What do you want to do?

**Comment by maxzinkus** [comment]
<img width="811" alt="Screen Shot 2022-10-09 at 1 51 17 PM" src="https://user-images.githubusercontent.com/5474655/194774422-6e9d17e5-5001-4859-9daf-f56d5ea3279d.png">

Referring to your earlier message. I assume this disables `arjun` for `approxmc`?

**Comment by msoos** [comment]
An input that contains XORs works for CryptoMiniSat. Hence no such option needed. I am closing this issue because it's been fixed.

**Comment by maxzinkus** [comment]
It seems like CryptoMiniSat is calling `arjun` while processing these files (like the ones attached to the issue) and is therefore failing out when it shouldn't. Am I using an old version / doing something incorrectly when invoking it?

**Comment by msoos** [comment]
I think you got something wrong. Anyway, it does not segfault anymore -- just `git pull` both CryptoMiniSat and Arjun, re-build them all, and now you should get an assert-fail instead of a segfault :)

**Comment by maxzinkus** [comment]
Got it. Thanks for the help as always!
