### ISSUE TITLE
multi-thread cannot work well

### ISSUE THREAD

**Issue by SJTUwwz** [msoos/cryptominisat#698]
Hi,
I met error "void CMSat::Searcher::setup_branch_strategy(): Assertion `!select.empty()' failed." when I tried to use 20 threads(cryptominisat5 sim_cnf2.cnf -t 20). However, everything went well when the number of thread is 5.  
![6b561cb9fa478554689e7c3b6f279b1](https://user-images.githubusercontent.com/43675300/199384627-fc69937d-9d5b-451b-ab45-da56476f1c82.png)
It confused me since I am just new to SAT.
Thanks!

**Comment by msoos** [comment]
Oooops, great catch! I have now fixed this. Sorry for that :(

**Comment by SJTUwwz** [comment]
It works now. Thanks for your fast fixing!
