### ISSUE TITLE
CodeQL to help to find optimizations/speed up code

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#712]
See here
1) https://sean.heelan.io/2023/02/14/combining-static-and-dynamic-analysis-in-performance-optimisation-part-1-60-improvements-with-continuous-profiling-and-library-matching/
2) https://sean.heelan.io/2023/03/01/finding-10x-performance-improvements-in-c-with-codeql-part-2-2-on-combining-dynamic-and-static-analysis-for-performance-optimisation/

There seems to be a switch in github, which prepares usage of CodeQL...? It does not work on forks, so I cannot try it out with CMS, without downloading and re-uploading cryptominisat in a new generated test repo. Or I can use some project independant from CMS and try it with this.

https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql

https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning-for-a-repository#configuring-code-scanning-automatically

It creates a file codeql.yml or similar. I am unsure if configuration is needed or it works automatically.

Does someone perhaps have more knowledge about it or has already tried it out?

**Comment by msoos** [comment]
Thanks. It's actually not that good. Also, it's already running for CryptoMiniSat:

https://github.com/msoos/cryptominisat/actions/workflows/codeql-analysis.yml

Closing because CodeQL is already set up.

**Comment by capiman** [comment]
Thanks for the answer!
