### ISSUE TITLE
LARGEMEM=ON, but ID of stats/frat is uint32_t/int32_t, gives assertion in very special case (high number of 3 long clauses)

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#714]
c CMS compilation env CMAKE_CXX_COMPILER = /usr/bin/c++ | CMAKE_CXX_FLAGS =  -fvisibility=hidden -Wall -Wextra -Wunused -Wsign-compare -fno-omit-frame-pointer -Wtype-limits -Wuninitialized -Wno-deprecated -Wstrict-aliasing -Wpointer-arith -Wpointer-arith -Wformat-nonliteral -Winit-self -Wparentheses -Wunreachable-code -g -Wno-class-memaccess -mpopcnt -msse4.2 -ggdb3 -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Wshadow -Wformat=2 -Wextra-semi -pedantic | COMPILE_DEFINES =  -DLARGE_OFFSETS -DRDB0_ONLY_FEATURES -DBOOST_TEST_DYN_LINK -DUSE_ZLIB -DYALSAT_FPU | STATICCOMPILE = OFF | ONLY_SIMPLE = OFF | Boost_FOUND = TRUE | STATS = OFF | SQLITE3_FOUND =  | ZLIB_FOUND = TRUE | VALGRIND_FOUND =  | ENABLE_TESTING = OFF | M4RI_FOUND =  | NOM4RI = ON | SLOW_DEBUG = OFF | ENABLE_ASSERTIONS = ON | PYTHON_EXECUTABLE =  | PYTHON_LIBRARY =  | PYTHON_INCLUDE_DIRS =  | MY_TARGETS =  | LARGEMEM = ON | LIMITMEM = OFF | BREAKID_LIBRARIES =  | BREAKID-VER = . | BOSPHORUS_LIBRARIES =  | BOSPH-VER = . | compilation date time = Dec 31 2022 10:51:56
c CMS compiled with gcc version 11.3.0

SegFault:

#5  0x00007ffff78d171b in __assert_fail_base (fmt=0x7ffff7a86150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ffff7f392aa "_ID > 0",
    file=0x7ffff7f32570 "/media/e2/cryptominisat-20221226/src/clause.h", line=407, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007ffff78e2e96 in __GI___assert_fail (assertion=0x7ffff7f392aa "_ID > 0",
    file=0x7ffff7f32570 "/media/e2/cryptominisat-20221226/src/clause.h", line=407,
    function=0x7ffff7f3a050 "CMSat::Clause::Clause(const V&, uint32_t, uint32_t) [with V = std::vector<CMSat::Lit>; uint32_t = unsigned int]")
    at ./assert/assert.c:101
#7  0x00007ffff7ec42e6 in CMSat::Clause::Clause<std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > > (this=0x7feaaba93c78,
    ps=std::vector of length 3, capacity 3 = {...}, _introduced_at_conflict=0, _ID=0) at /media/e2/cryptominisat-20221226/src/clause.h:402
#8  CMSat::Clause::Clause<std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > > (_ID=0, _introduced_at_conflict=0,
    ps=std::vector of length 3, capacity 3 = {...}, this=0x7feaaba93c78) at /media/e2/cryptominisat-20221226/src/clause.h:402
#9  CMSat::ClauseAllocator::Clause_new<std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > > (ID=0, conflictNum=0,
    ps=std::vector of length 3, capacity 3 = {...}, this=0x5555555d1d50) at /media/e2/cryptominisat-20221226/src/clauseallocator.h:68
#10 CMSat::Solver::add_clause_int (this=0x5555555d1cf0, lits=std::vector of length 3, capacity 4 = {...}, red=<optimized out>,
    cl_stats=0x7fffffff5bd0, attach_long=<optimized out>, finalLits=<optimized out>, addDrat=true, frat_first=..., sorted=true, remove_frat=true)
    at /media/e2/cryptominisat-20221226/src/solver.cpp:488

clause.h:

    template<class V>
    Clause(const V& ps, const uint32_t _introduced_at_conflict, const uint32_t _ID)
    {
        //assert(ps.size() > 2);

        stats.last_touched_any = _introduced_at_conflict;
        assert(_ID > 0);
        stats.ID = _ID;

solver.cpp:

Clause* Solver::add_clause_int(
    const vector<Lit>& lits
    , const bool red
    , const ClauseStats* const cl_stats
    , const bool attach_long
    , vector<Lit>* finalLits
    , bool addDrat
    , const Lit frat_first
    , const bool sorted
    , const bool remove_frat
) {
...
    int32_t ID;
    if (remove_frat) {
        assert(cl_stats);
        assert(frat_first == lit_Undef);
        assert(addDrat);
        ID = cl_stats->ID;
        if (ps != lits) {
            ID = ++clauseID;
            *frat << add << ID << ps << fin;
            *frat << del << cl_stats->ID << lits << fin;
        }
    } else {
        ID = ++clauseID;

cnf.h:    int32_t clauseID = 0;

If I don't use frat, nor stats, can I just comment out assert? Only for local testing... Or not a good idea?

(I have not tried latest version/sources)

**Comment by capiman** [comment]
Commenting out the assert seem to work and is enough for my special tests.

**Comment by msoos** [comment]
Hi,

Yeah, that ID assert can be commented out for such work. I am sorry, the ID is only 32 bit and you likely went over that... FRAT can be painful. 64b would take way too much memory and overhead :( I'll think about it. But it's a nice catch actually!

Thanks again,

Mate

PS: Next time you paste in stuff from the console, can I ask you to put it in triple-backticks? Then it's a lot easier to read:

```
my console text
now correctly formatted
```

Please see here: https://www.markdownguide.org/basic-syntax for more info. Thanks again!
