### ISSUE TITLE
Ask cryptominisat to work only on a subset of variables

### ISSUE THREAD

**Issue by LeandreBl** [msoos/cryptominisat#715]
Hi,

I'm looking if there is a feature (I didn't find it for the moment) to ask cryptominisat to find solutions only on a subset of variables (other than c ind)
The goal would be to start N cryptominisat instances on the same file, give them N different ranges of variables to find solutions for and merge all the solutions at the end when they all finished.
I'm thinking it could be possible using the Shannon decomposition to split the problem into subproblems, but maybe you already have a way of doing it.

Best regards,
Léandre

**Comment by LeandreBl** [comment]
Hi,
The real final usage would be to solve a cnf file across multiple computers (not just threads).

**Comment by msoos** [comment]
That's what cube and conquer did, solved it on thousands of machines. Check it out!

Cheers and good luck,

Mate

**Comment by LeandreBl** [comment]
Ok thanks I'll check it out, have a nice day !
