### ISSUE TITLE
import pycryptosat failed

### ISSUE THREAD

**Issue by Flians** [msoos/cryptominisat#717]
Hello,
When I import pycryptosat in Python3, there is an error: `undefined symbol: _ZTIN5boost7archive6detail14basic_iarchiveE`.
Besides, although I compile pycryptosat locally, this error still exists.
Do you know how I can solve this? Thank you.

The environment:
- Ubuntu 22.04
- Python 3.10.6
- C++ 11.3.0
- Boost 1.74.0

**Comment by msoos** [comment]
Hi,

Oh, interesting, thanks for letting me know! I thought all libraries would be packaged into pypi... You'd need to do the following to fix:

```
sudo apt-get install libboost-serialization-dev
```

Can you please install that and see what happens? I'll fix this so it won't bother others, soon. In the meanwhile, it'd be nice if you could let me know about the output of the above.

Thanks,

Mate

**Comment by msoos** [comment]
Wow, interesting. That's good to know. OK, let me try to fix it today, I'll get back to you soon!

Mate

**Comment by msoos** [comment]
Hmmm... I am not convinced this should be an issue for everyone. I am just a bit hesitant to apply the only fix I know, which would make a mess of the compilation pipeline. I thought that pypi would package all the dependencies statically when necessary. Maybe not. I'll look into this further tomorrow. Sorry, I can't fix it now :( Do you know how to package in a dependency like Boost's `archive` library into a pypi module?

**Comment by aytey** [comment]
You could probably take a look at:

- https://github.com/pypa/auditwheel

which should help create the "portable" shared objects.

I also noticed that you're using `ubuntu-latest` for building these wheels; it is probably advisable to move to one of the "ManyLinux" images:

- https://github.com/pypa/manylinux

to build the objects in a way that will work on the most number of platforms (e.g., avoiding glibc issues and such).

**Comment by dmusican** [comment]
I'm having exactly the same problem, which more-or-less the same configuration as the original poster. I was able to work around it by using

```
pip install pycryptosat==5.11.7
```

This version seems to work fine, but 5.11.8 definitely causes the problems listed above for me.

**Comment by msoos** [comment]
Thanks to your feedback, it's really helpful. I am now trying to fix this. It's actually a lot harder than I'd like it to be, but I'm trying :) Thanks again!

**Comment by msoos** [comment]
Hi All,

I have now tried to re-compile & re-release the wheel with https://github.com/pypa/cibuildwheel which seems to be THE choice to build wheels on GitHub.  The new pypi release is at: https://pypi.org/project/pycryptosat/5.11.9/#files

Can you perhaps check if it works for you now?

In case you have some time to examine further, the full set of wheels and artifacts is available: https://github.com/msoos/cryptominisat/actions/runs/4855249274 at the bottom, called "artifacts". Perhaps you could have a look at the GitHub build action itself, maybe you have some pro tips to improve/fix? I really tried this time to use something bog-standard, and I truly hope that `cibuildwheel` is the right tool. However, it may need some parameters, in case it doesn't work. There is an extension documentation for it that I tried to understand: https://cibuildwheel.readthedocs.io/en/stable/ but maybe I missed something.

Please let me know how it goes! Thanks so much and sorry for the trouble,

Mate

**Comment by Flians** [comment]
Hello,
I tried thepycryptosat 5.11.9. There is still an error: `undefined symbol: _ZTIN5boost7archive6de`.

**Comment by msoos** [comment]
Thank you so much! Well, it was worth a try. I'll see how to fix with this
new system. Otherwise I'll add a fix that's a bit clunky but works :)

Thanks again,

Mate

**Comment by msoos** [comment]
Hi All,

Thanks all for your patience. I believe it should be OK now. Can you please check?

Thank you in advance,

Mate

**Comment by Flians** [comment]
Hello,
I have tried the pycryptosat 5.11.10. It can work normally.
Thank you.

**Comment by msoos** [comment]
Great to hear! I have a question to all of you... What would you think if we moved to a more standard API, where we have this kind of interface:

```
import pycryptosat
s = pycryptosat.Solver()
s.add_clause([-1, 2])
s.add_clause([-1, -2])
s.solve()
>>> True
print(s.get_model())
>>> [-1, -2]
```

It's this model: https://pysathq.github.io/docs/html/api/solvers.html which is also the same as used by `optilog` and of course `pysat`.

Let me know what you think. This of course would be a breaking change, but it would allow all of you to use PySAT, etc. Also, I will be integrating CryptoMiniSat into PySAT soon :)

**Comment by Flians** [comment]
Hello,
I think that must be great. Users can easily choose SAT solver, which may make CryptoMiniSat used by more people. Besides, It would be wonderful if CryptoMiniSat could support GPU acceleration, just like GpuShareSat (https://github.com/nicolasprevot/GpuShareSat). 
Look forward to your improvements on CryptoMiniSat.
Thank you.

**Comment by msoos** [comment]
Hi,

Porting GpuShareSat would be about 1-2 months of work, and I am very overwhelmed, I don't have 1-2 months, sorry. However, I might switch over to a newer python API interface :) Thanks for the feedback,

Mate
