### ISSUE TITLE
Extended resolution in Cryptominisat

### ISSUE THREAD

**Issue by amatuag** [msoos/cryptominisat#719]
Hi Mate,

I came across a blog post of yours about a form of lightweight extended resolution you had integrated into your solver back in 2010.

https://www.msoos.org/2010/12/extended-resolution-is-working/ 

Q1. Is this still a part of your solver ? I was trying to find it in your source code briefly and couldn't see where this was being done. I assume this happens under the hood and as a user one doesn't need to enable ER ?
Q2. Could you explain what are the heuristics involved and the targeting method you mentioned in your blog posts.

**Comment by msoos** [comment]
Hi,

I removed that system and then added another called `bva.cpp` based on this paper [1] . It's not enabled by default, but you can enable with `--bva 1`.  Please see the heuristics explained in the paper.

Good luck,

Mate

```
[1] N. Manthey, M. J. H. Heule, and A. Biere. Automated reencoding of
Boolean formulas. In A. Biere, A. Nahir, and T. E. J. Vos, editors,
Hardware and Software: Verification and Testing - 8th International
Haifa Verification Conference, HVC 2012, Haifa, Israel, November
6-8, 2012. Revised Selected Papers, volume 7857 of Lecture Notes in
Computer Science, pages 102–117. Springer, 2012.
```

PDF:  https://research.ibm.com/haifa/conferences/hvc2012/papers/paper16.pdf
