### ISSUE TITLE
Limit the number of truth values in the xor+cnf file

### ISSUE THREAD

**Issue by Han-sx** [msoos/cryptominisat#721]
Hi sir, I don't know much about sat, it might be a basic question.

I am trying to use cryptominisat 5 to solve XOR system of equations. Because it can give all solutions when the number of unknowns is more than the number of equations.

But I don't know how to limit the total number of truth values when constructing a file of the form XOR+CNF.

For example, in the opb file of minisat+, it can be constructed as `+1*x1 +1*x2 +1*x3 +1*x4 == 2`, to indicate that there are 2 truth values in 4 unknowns.

I wonder if there is a similar restriction clause in cryptominisat? Or can it be constrained in other ways?

I would appreciate any insight or help you can provide.

**Comment by msoos** [comment]
Hi,

Those are is called a cardinality constraints. CryptoMiniSat does not support this natively. However, you can use

https://github.com/master-keying/pblib

To translate your cardinality constraint into CNF. Then you can copy-paste that into your CNF, and solve with CryptoMiniSat. Beware, pblib may add extra variables to express your cardinality constraint, so you have to take care not to clash with those variables -- they must not be used for anything. Notice that you can use PBLib to represent all sorts of constraints, so it's quite powerful.

I hope the above helps,

Mate
