### ISSUE TITLE
cryptominisat5_simple outputs a string without prefix 'c ' 

### ISSUE THREAD

**Issue by vale1410** [msoos/cryptominisat#724]
cryptominisat5_simple outputs the following line when reading from a pipe : 

```
...
Reading from standard input... Use '-h' or '--help' for help.
...
```

It might be better if this is prepended with 'c ' because other tools might expect this to be a comment. 

It works correctly in cryptominisat5.

**Comment by msoos** [comment]
Ooops. Thaaks! Sorry! Fixed :)
