### ISSUE TITLE
Version of the c++ compiler required has not been specified

### ISSUE THREAD

**Issue by tekeuange23** [msoos/cryptominisat#725]
### Installed Compiler
<details>
<summary>gcc-7.5.0</summary>

``````
$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
``````
</details>

<details>
<summary>gcc-12.2.0</summary>

``````
$ gcc-12 --version
gcc-12 (Homebrew GCC 12.2.0) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
``````
</details>

### Code
```cpp
#include <cryptominisat5/cryptominisat.h>
#include <assert.h>
#include <vector>
using std::vector;
using namespace CMSat;

int main()
{
  SATSolver solver;
  vector<Lit> clause;

  // Let's use 4 threads
  solver.set_num_threads(4);

  // We need 3 variables. They will be: 0,1,2
  // Variable numbers are always trivially increasing
  solver.new_vars(3);

  // add "1 0"
  clause.push_back(Lit(0, false));
  solver.add_clause(clause);

  // add "-2 0"
  clause.clear();
  clause.push_back(Lit(1, true));
  solver.add_clause(clause);

  // add "-1 2 3 0"
  clause.clear();
  clause.push_back(Lit(0, true));
  clause.push_back(Lit(1, false));
  clause.push_back(Lit(2, false));
  solver.add_clause(clause);

  lbool ret = solver.solve();
  assert(ret == l_True);
  std::cout
      << "Solution is: "
      << solver.get_model()[0]
      << ", " << solver.get_model()[1]
      << ", " << solver.get_model()[2]
      << std::endl;

  // assumes 3 = FALSE, no solutions left
  vector<Lit> assumptions;
  assumptions.push_back(Lit(2, true));
  ret = solver.solve(&assumptions);
  assert(ret == l_False);

  // without assumptions we still have a solution
  ret = solver.solve();
  assert(ret == l_True);

  // add "-3 0"
  // No solutions left, UNSATISFIABLE returned
  clause.clear();
  clause.push_back(Lit(2, true));
  solver.add_clause(clause);
  ret = solver.solve();
  assert(ret == l_False);

  return 0;
}
```

### Errors I get
<details>
<summary>gcc-7.5.0</summary>

``````
$ gcc spc.cpp 
/tmp/cctxLoU0.o: In function `main':
spc.cpp:(.text+0x2a): undefined reference to `CMSat::SATSolver::SATSolver(void*, std::atomic<bool>*)'
spc.cpp:(.text+0x47): undefined reference to `CMSat::SATSolver::set_num_threads(unsigned int)'
spc.cpp:(.text+0x58): undefined reference to `CMSat::SATSolver::new_vars(unsigned long)'
spc.cpp:(.text+0x94): undefined reference to `CMSat::SATSolver::add_clause(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const&)'
spc.cpp:(.text+0xdc): undefined reference to `CMSat::SATSolver::add_clause(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const&)'
spc.cpp:(.text+0x176): undefined reference to `CMSat::SATSolver::add_clause(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const&)'
spc.cpp:(.text+0x18c): undefined reference to `CMSat::SATSolver::solve(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const*, bool)'
spc.cpp:(.text+0x1d5): undefined reference to `std::cout'
spc.cpp:(.text+0x1da): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
spc.cpp:(.text+0x1e9): undefined reference to `CMSat::SATSolver::get_model() const'
spc.cpp:(.text+0x210): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
spc.cpp:(.text+0x21f): undefined reference to `CMSat::SATSolver::get_model() const'
spc.cpp:(.text+0x246): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
spc.cpp:(.text+0x255): undefined reference to `CMSat::SATSolver::get_model() const'
spc.cpp:(.text+0x277): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)'
spc.cpp:(.text+0x282): undefined reference to `std::ostream::operator<<(std::ostream& (*)(std::ostream&))'
spc.cpp:(.text+0x2cf): undefined reference to `CMSat::SATSolver::solve(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const*, bool)'
spc.cpp:(.text+0x320): undefined reference to `CMSat::SATSolver::solve(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const*, bool)'
spc.cpp:(.text+0x3a3): undefined reference to `CMSat::SATSolver::add_clause(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const&)'
spc.cpp:(.text+0x3b9): undefined reference to `CMSat::SATSolver::solve(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const*, bool)'
spc.cpp:(.text+0x41d): undefined reference to `CMSat::SATSolver::~SATSolver()'
spc.cpp:(.text+0x45c): undefined reference to `CMSat::SATSolver::~SATSolver()'
/tmp/cctxLoU0.o: In function `__static_initialization_and_destruction_0(int, int)':
spc.cpp:(.text+0x49c): undefined reference to `std::ios_base::Init::Init()'
spc.cpp:(.text+0x4b1): undefined reference to `std::ios_base::Init::~Init()'
/tmp/cctxLoU0.o: In function `CMSat::operator<<(std::ostream&, CMSat::lbool)':
spc.cpp:(.text._ZN5CMSatlsERSoNS_5lboolE[_ZN5CMSatlsERSoNS_5lboolE]+0x38): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
spc.cpp:(.text._ZN5CMSatlsERSoNS_5lboolE[_ZN5CMSatlsERSoNS_5lboolE]+0x64): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
spc.cpp:(.text._ZN5CMSatlsERSoNS_5lboolE[_ZN5CMSatlsERSoNS_5lboolE]+0x90): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
/tmp/cctxLoU0.o: In function `void std::vector<CMSat::Lit, std::allocator<CMSat::Lit> >::_M_realloc_insert<CMSat::Lit>(__gnu_cxx::__normal_iterator<CMSat::Lit*, std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > >, CMSat::Lit&&)':
spc.cpp:(.text._ZNSt6vectorIN5CMSat3LitESaIS1_EE17_M_realloc_insertIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN5CMSat3LitESaIS1_EE17_M_realloc_insertIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x1ee): undefined reference to `__cxa_begin_catch'
spc.cpp:(.text._ZNSt6vectorIN5CMSat3LitESaIS1_EE17_M_realloc_insertIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN5CMSat3LitESaIS1_EE17_M_realloc_insertIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x257): undefined reference to `__cxa_rethrow'
spc.cpp:(.text._ZNSt6vectorIN5CMSat3LitESaIS1_EE17_M_realloc_insertIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN5CMSat3LitESaIS1_EE17_M_realloc_insertIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x25f): undefined reference to `__cxa_end_catch'
/tmp/cctxLoU0.o: In function `std::vector<CMSat::Lit, std::allocator<CMSat::Lit> >::_M_check_len(unsigned long, char const*) const':
spc.cpp:(.text._ZNKSt6vectorIN5CMSat3LitESaIS1_EE12_M_check_lenEmPKc[_ZNKSt6vectorIN5CMSat3LitESaIS1_EE12_M_check_lenEmPKc]+0x5b): undefined reference to `std::__throw_length_error(char const*)'
/tmp/cctxLoU0.o: In function `__gnu_cxx::new_allocator<CMSat::Lit>::deallocate(CMSat::Lit*, unsigned long)':
spc.cpp:(.text._ZN9__gnu_cxx13new_allocatorIN5CMSat3LitEE10deallocateEPS2_m[_ZN9__gnu_cxx13new_allocatorIN5CMSat3LitEE10deallocateEPS2_m]+0x1c): undefined reference to `operator delete(void*)'
/tmp/cctxLoU0.o: In function `__gnu_cxx::new_allocator<CMSat::Lit>::allocate(unsigned long, void const*)':
spc.cpp:## Environment information (required)

### Installed Compiler
<details>
<summary>gcc-7.5.0</summary>

``````
$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
``````
</details>

<details>
<summary>gcc-12.2.0</summary>

``````
$ gcc-12 --version
gcc-12 (Homebrew GCC 12.2.0) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
``````
</details>



### Code
```cpp
#include <cryptominisat5/cryptominisat.h>
#include <assert.h>
#include <vector>
using std::vector;
using namespace CMSat;

int main()
{
  SATSolver solver;
  vector<Lit> clause;

  // Let's use 4 threads
  solver.set_num_threads(4);

  // We need 3 variables. They will be: 0,1,2
  // Variable numbers are always trivially increasing
  solver.new_vars(3);

  // add "1 0"
  clause.push_back(Lit(0, false));
  solver.add_clause(clause);

  // add "-2 0"
  clause.clear();
  clause.push_back(Lit(1, true));
  solver.add_clause(clause);

  // add "-1 2 3 0"
  clause.clear();
  clause.push_back(Lit(0, true));
  clause.push_back(Lit(1, false));
  clause.push_back(Lit(2, false));
  solver.add_clause(clause);

  lbool ret = solver.solve();
  assert(ret == l_True);
  std::cout
      << "Solution is: "
      << solver.get_model()[0]
      << ", " << solver.get_model()[1]
      << ", " << solver.get_model()[2]
      << std::endl;

  // assumes 3 = FALSE, no solutions left
  vector<Lit> assumptions;
  assumptions.push_back(Lit(2, true));
  ret = solver.solve(&assumptions);
  assert(ret == l_False);

  // without assumptions we still have a solution
  ret = solver.solve();
  assert(ret == l_True);

  // add "-3 0"
  // No solutions left, UNSATISFIABLE returned
  clause.clear();
  clause.push_back(Lit(2, true));
  solver.add_clause(clause);
  ret = solver.solve();
  assert(ret == l_False);

  return 0;
}
```



### Errors I get
<details>
<summary>gcc-7.5.0</summary>

``````
$ gcc main.cpp 
/tmp/cctxLoU0.o: In function `main':
spc.cpp:(.text+0x2a): undefined reference to `CMSat::SATSolver::SATSolver(void*, std::atomic<bool>*)'
spc.cpp:(.text+0x47): undefined reference to `CMSat::SATSolver::set_num_threads(unsigned int)'
spc.cpp:(.text+0x58): undefined reference to `CMSat::SATSolver::new_vars(unsigned long)'
spc.cpp:(.text+0x94): undefined reference to `CMSat::SATSolver::add_clause(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const&)'
spc.cpp:(.text+0xdc): undefined reference to `CMSat::SATSolver::add_clause(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const&)'
spc.cpp:(.text+0x176): undefined reference to `CMSat::SATSolver::add_clause(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const&)'
spc.cpp:(.text+0x18c): undefined reference to `CMSat::SATSolver::solve(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const*, bool)'
spc.cpp:(.text+0x1d5): undefined reference to `std::cout'
spc.cpp:(.text+0x1da): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
spc.cpp:(.text+0x1e9): undefined reference to `CMSat::SATSolver::get_model() const'
spc.cpp:(.text+0x210): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
spc.cpp:(.text+0x21f): undefined reference to `CMSat::SATSolver::get_model() const'
spc.cpp:(.text+0x246): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
spc.cpp:(.text+0x255): undefined reference to `CMSat::SATSolver::get_model() const'
spc.cpp:(.text+0x277): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)'
spc.cpp:(.text+0x282): undefined reference to `std::ostream::operator<<(std::ostream& (*)(std::ostream&))'
spc.cpp:(.text+0x2cf): undefined reference to `CMSat::SATSolver::solve(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const*, bool)'
spc.cpp:(.text+0x320): undefined reference to `CMSat::SATSolver::solve(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const*, bool)'
spc.cpp:(.text+0x3a3): undefined reference to `CMSat::SATSolver::add_clause(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const&)'
spc.cpp:(.text+0x3b9): undefined reference to `CMSat::SATSolver::solve(std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > const*, bool)'
spc.cpp:(.text+0x41d): undefined reference to `CMSat::SATSolver::~SATSolver()'
spc.cpp:(.text+0x45c): undefined reference to `CMSat::SATSolver::~SATSolver()'
/tmp/cctxLoU0.o: In function `__static_initialization_and_destruction_0(int, int)':
spc.cpp:(.text+0x49c): undefined reference to `std::ios_base::Init::Init()'
spc.cpp:(.text+0x4b1): undefined reference to `std::ios_base::Init::~Init()'
/tmp/cctxLoU0.o: In function `CMSat::operator<<(std::ostream&, CMSat::lbool)':
spc.cpp:(.text._ZN5CMSatlsERSoNS_5lboolE[_ZN5CMSatlsERSoNS_5lboolE]+0x38): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
spc.cpp:(.text._ZN5CMSatlsERSoNS_5lboolE[_ZN5CMSatlsERSoNS_5lboolE]+0x64): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
spc.cpp:(.text._ZN5CMSatlsERSoNS_5lboolE[_ZN5CMSatlsERSoNS_5lboolE]+0x90): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
/tmp/cctxLoU0.o: In function `void std::vector<CMSat::Lit, std::allocator<CMSat::Lit> >::_M_realloc_insert<CMSat::Lit>(__gnu_cxx::__normal_iterator<CMSat::Lit*, std::vector<CMSat::Lit, std::allocator<CMSat::Lit> > >, CMSat::Lit&&)':
spc.cpp:(.text._ZNSt6vectorIN5CMSat3LitESaIS1_EE17_M_realloc_insertIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN5CMSat3LitESaIS1_EE17_M_realloc_insertIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x1ee): undefined reference to `__cxa_begin_catch'
spc.cpp:(.text._ZNSt6vectorIN5CMSat3LitESaIS1_EE17_M_realloc_insertIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN5CMSat3LitESaIS1_EE17_M_realloc_insertIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x257): undefined reference to `__cxa_rethrow'
spc.cpp:(.text._ZNSt6vectorIN5CMSat3LitESaIS1_EE17_M_realloc_insertIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN5CMSat3LitESaIS1_EE17_M_realloc_insertIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x25f): undefined reference to `__cxa_end_catch'
/tmp/cctxLoU0.o: In function `std::vector<CMSat::Lit, std::allocator<CMSat::Lit> >::_M_check_len(unsigned long, char const*) const':
spc.cpp:(.text._ZNKSt6vectorIN5CMSat3LitESaIS1_EE12_M_check_lenEmPKc[_ZNKSt6vectorIN5CMSat3LitESaIS1_EE12_M_check_lenEmPKc]+0x5b): undefined reference to `std::__throw_length_error(char const*)'
/tmp/cctxLoU0.o: In function `__gnu_cxx::new_allocator<CMSat::Lit>::deallocate(CMSat::Lit*, unsigned long)':
spc.cpp:(.text._ZN9__gnu_cxx13new_allocatorIN5CMSat3LitEE10deallocateEPS2_m[_ZN9__gnu_cxx13new_allocatorIN5CMSat3LitEE10deallocateEPS2_m]+0x1c): undefined reference to `operator delete(void*)'
/tmp/cctxLoU0.o: In function `__gnu_cxx::new_allocator<CMSat::Lit>::allocate(unsigned long, void const*)':
spc.cpp:(.text._ZN9__gnu_cxx13new_allocatorIN5CMSat3LitEE8allocateEmPKv[_ZN9__gnu_cxx13new_allocatorIN5CMSat3LitEE8allocateEmPKv]+0x2c): undefined reference to `std::__throw_bad_alloc()'
spc.cpp:(.text._ZN9__gnu_cxx13new_allocatorIN5CMSat3LitEE8allocateEmPKv[_ZN9__gnu_cxx13new_allocatorIN5CMSat3LitEE8allocateEmPKv]+0x3c): undefined reference to `operator new(unsigned long)'
/tmp/cctxLoU0.o: In function `CMSat::Lit* std::__uninitialized_copy<false>::__uninit_copy<std::move_iterator<CMSat::Lit*>, CMSat::Lit*>(std::move_iterator<CMSat::Lit*>, std::move_iterator<CMSat::Lit*>, CMSat::Lit*)':
spc.cpp:(.text._ZNSt20__uninitialized_copyILb0EE13__uninit_copyISt13move_iteratorIPN5CMSat3LitEES5_EET0_T_S8_S7_[_ZNSt20__uninitialized_copyILb0EE13__uninit_copyISt13move_iteratorIPN5CMSat3LitEES5_EET0_T_S8_S7_]+0x77): undefined reference to `__cxa_begin_catch'
spc.cpp:(.text._ZNSt20__uninitialized_copyILb0EE13__uninit_copyISt13move_iteratorIPN5CMSat3LitEES5_EET0_T_S8_S7_[_ZNSt20__uninitialized_copyILb0EE13__uninit_copyISt13move_iteratorIPN5CMSat3LitEES5_EET0_T_S8_S7_]+0x8f): undefined reference to `__cxa_rethrow'
spc.cpp:(.text._ZNSt20__uninitialized_copyILb0EE13__uninit_copyISt13move_iteratorIPN5CMSat3LitEES5_EET0_T_S8_S7_[_ZNSt20__uninitialized_copyILb0EE13__uninit_copyISt13move_iteratorIPN5CMSat3LitEES5_EET0_T_S8_S7_]+0x97): undefined reference to `__cxa_end_catch'
/tmp/cctxLoU0.o:(.data.rel.local.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status

``````
</details>

<details>
<summary>gcc-12.2.0</summary>

``````
$ gcc-12 --version
gcc-12 (Homebrew GCC 12.2.0) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
``````
</details>

(.text._ZN9__gnu_cxx13new_allocatorIN5CMSat3LitEE8allocateEmPKv[_ZN9__gnu_cxx13new_allocatorIN5CMSat3LitEE8allocateEmPKv]+0x2c): undefined reference to `std::__throw_bad_alloc()'
spc.cpp:(.text._ZN9__gnu_cxx13new_allocatorIN5CMSat3LitEE8allocateEmPKv[_ZN9__gnu_cxx13new_allocatorIN5CMSat3LitEE8allocateEmPKv]+0x3c): undefined reference to `operator new(unsigned long)'
/tmp/cctxLoU0.o: In function `CMSat::Lit* std::__uninitialized_copy<false>::__uninit_copy<std::move_iterator<CMSat::Lit*>, CMSat::Lit*>(std::move_iterator<CMSat::Lit*>, std::move_iterator<CMSat::Lit*>, CMSat::Lit*)':
spc.cpp:(.text._ZNSt20__uninitialized_copyILb0EE13__uninit_copyISt13move_iteratorIPN5CMSat3LitEES5_EET0_T_S8_S7_[_ZNSt20__uninitialized_copyILb0EE13__uninit_copyISt13move_iteratorIPN5CMSat3LitEES5_EET0_T_S8_S7_]+0x77): undefined reference to `__cxa_begin_catch'
spc.cpp:(.text._ZNSt20__uninitialized_copyILb0EE13__uninit_copyISt13move_iteratorIPN5CMSat3LitEES5_EET0_T_S8_S7_[_ZNSt20__uninitialized_copyILb0EE13__uninit_copyISt13move_iteratorIPN5CMSat3LitEES5_EET0_T_S8_S7_]+0x8f): undefined reference to `__cxa_rethrow'
spc.cpp:(.text._ZNSt20__uninitialized_copyILb0EE13__uninit_copyISt13move_iteratorIPN5CMSat3LitEES5_EET0_T_S8_S7_[_ZNSt20__uninitialized_copyILb0EE13__uninit_copyISt13move_iteratorIPN5CMSat3LitEES5_EET0_T_S8_S7_]+0x97): undefined reference to `__cxa_end_catch'
/tmp/cctxLoU0.o:(.data.rel.local.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status

``````
</details>

<details>
<summary>gcc-12.2.0</summary>

``````
$ gcc-12 spc.cpp
spc.cpp:1:10: fatal error: cryptominisat5/cryptominisat.h: No such file or directory
    1 | #include <cryptominisat5/cryptominisat.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
``````
</details>

### Question
- which version of the c++ compiler is required to use the SAT-Solver API ?

**Comment by msoos** [comment]
None of these issues have anything to do with CryptoMiniSat as far as I can tell. You forgot to (1) install cryptominisat and (2) link in the cryptominisat library into your application.

Please read up on how linking libraries works. Basically, you need to:

```
[build cryptominisat]
sudo make install
g++ myprogram.cpp -lcryptominisat -o myprogram
```

Please read around on forums how linking and compilation works for C++ programs. My guess is that you forgot to install cryptominisat, and you forgot to link in the cryptominisat library. Nothing in what you wrote above is cryptominsat-specific, it will happen to any system.

Good luck,

Mate

**Comment by tekeuange23** [comment]
Thanks! It works
(1) I forgot the last linking command on the installation which is
``````
$ sudo ldconfig
``````


(2) Also the loading value that is working is `cryptominisat5`. Therefore we should have something like
``````
$ g++ myprogram.cpp -lcryptominisat5 -o myprogram
``````

Cheers :)

Mate
