### ISSUE TITLE
C++ interface linker issues

### ISSUE THREAD

**Issue by KranNaut** [msoos/cryptominisat#727]
After building the project and including the necessary header files and shared libraries in my project the code still throws an undefined reference to CMSat::SATSolver error

> encoding.cpp:34: undefined reference to 'CMSat::SATSolver::SATSolver(void*, std::atomic<bool>*)'
> encoding.cpp:34: undefined reference to 'CMSat::SATSolver::~SATSolver()'

Line 34 referenced in the error

`
CMSat::SATSolver solver;
`

**Comment by KranNaut** [comment]
There were some environment issues on my side.

**Comment by msoos** [comment]
Hi,

Glad it got resolved! Next time, as a feedback, always give a full run of the build process, with `VERBOSE=1` for `cmake` and `-v` for make. Without it, it will be very difficult for someone to help you :)

Glad it all worked out and I hope you will enjoy using CryptoMiniSat,

Mate
