### ISSUE TITLE
Louvain Libraries needed if DSTATS=ON

### ISSUE THREAD

**Issue by marino-mrc** [msoos/cryptominisat#731]
Hello,
it would be really helpful to add in the README.markdown file a short procedure for installing the Louvain community libraries in order to have stats enabled.

After a few hours, I found the files [here](https://github.com/meelgroup/louvain-community) and I installed the libraries following the instructions in the README file in that repository

Thanks,
Marco

**Comment by msoos** [comment]
Ah, good point. I now made it a requirement for STATS and explained it in the README. Sorry about that.

**Comment by msoos** [comment]
Sorry you wasted so much time! I think I had that louvain explained somehwere, probably in the Arjun repository, but not here. Sorry!

**Comment by msoos** [comment]
Now I also added it to the CrystalBall documentation. Sorry about that.
