### ISSUE TITLE
Compilation fails when DSTATS=ON

### ISSUE THREAD

**Issue by marino-mrc** [msoos/cryptominisat#732]
Hello,
make fails when DSTATS=ON with the following error:
`src/satzilla_features.h:52:23: error: ‘numeric_limits’ was not declared in this scope; did you mean ‘std::numeric_limits’?
   52 |     double horn_min = numeric_limits<double>::max();
`
In order to fix the problem, I had to change the satzilla_features.h file. 
More specifically, I changed all lines using the following rule:
double horn_min = numeric_limits<double>::max();

substituted by:
double horn_min = std::numeric_limits<double>::max();

Thanks,
Marco

**Comment by msoos** [comment]
Ah, crap. Yeah, I just fixed this. I'm sorry!

**Comment by msoos** [comment]
Please let me know if you bump into stuff like this. It was not supposed to happen, this is kind of a new thing that `<limits>` needs a separate import here :S Thanks again!
