### ISSUE TITLE
parsing of dimacs for c++ library usage

### ISSUE THREAD

**Issue by na3na3na** [msoos/cryptominisat#735]
just wondering if there is a built in api call to read a cnf file in DIMACS format for c++ library usage instead of adding clauses manually

could you point me in the right direction or show me an example usage?

**Comment by a1880** [comment]
There is a class `DimacsParser` defined in `dimacsparser.h`.
Sample usage can be found in `main_simple.cpp`.

**Comment by msoos** [comment]
Hey,

Yes indeed @a1880 said it perfectly! Please check out `main_simple.cpp` -- it shows how to parse in a DIMACS CNF file using CryptoMiniSat and `dimacsparser.h`. It should work out-of-the-box :)

In case that does not help, please either re-open this issue, or open a new one and I/we'll be happy to help!

Good luck,

Mate
