### ISSUE TITLE
Extracting contradictions from UNSAT

### ISSUE THREAD

**Issue by na3na3na** [msoos/cryptominisat#739]
Hello,

Baed on my understanding, a SAT solver returns UNSAT when it has a contradiction between its original clauses as well as the learnt clauses. I was wondering if there is an easy way to get this contradiction that led to the UNSAT result?

Thanks in advance.

**Comment by msoos** [comment]
Hi,

You need what's called the UNSAT proof and its associated UNSAT core and learnt clauses. You can extract it by generating a FRAT proof and then using frat-rs.  You can get this FRAT file (i.e. the proof) by running:

```
./cryptominisat file.cnf proof.frat
```

If you open the `proof.frat` file, it's actually quite readable by humans, too. However,  you can use the frat-rs tool to transform the `proof.drat` file. Please see: https://github.com/digama0/frat/ for frat-rs. This tool can validate the proof and it can also generate the set of clauses that actually lead to the UNSAT result (so-called UNSAT core) and it can trim your proof, and then you can see what learnt clauses were definitely needed to generate the proof, step by step. Basically, (1) generate the proof with CryptoMiniSat, then (2) use frat-rs to trim the proof,  (3) examine the simplified proof file, it will contain the set of clauses needed as "o ...", i.e. "original" clauses needed for UNSAT, and the set of learnt clauses "a .... " for the learnt clauses.

I hope this helped! Good luck,

Mate
