### ISSUE TITLE
c [occ-empty-res] Empty resolvent elimed: 101 T: 0.45 T-out: N *** picosat: compiled without trace support

### ISSUE THREAD

**Issue by PeterMacGonagan** [msoos/cryptominisat#741]
Hello,

Could you explain me this error, please?

```
c [occ-empty-res] **Empty resolvent elimed:** 101 T: 0.45 T-out: N
*** picosat: compiled without trace support
```

Note: the CNF is SAT (I've already got the solution).

Best regards

**Comment by msoos** [comment]
Hi,

Thanks for the issue! That sounds like a compilation issue, actually. What did you use to compile CryptoMiniSat? Can you tell me your OS, and the way you compiled it? Maybe you can recompile it for me and give the full compile log? That would help. If you do, please run with `make VERBOSE=1` so I can see the full log. Basically, delete the `build` directory, re-run the `cmake` command and then `make VERBOSE=1`, and post everything, including the `cmake` and the `make [...]` output here. That would help me debug. I can certainly fix this if it's what I think it is, but I wanna make sure I fix the right thing :)

Thanks again for the bugreport,

Mate

PS: It's 1:35am here, so I will only be able to get back to you in about 17h. Sorry about that, I have to sleep & go to work :)

**Comment by PeterMacGonagan** [comment]
Hello,

I didn't compile it myself
I'm on Windows and I didn't compile ti myself on it (https://github.com/msoos/cryptominisat/releases  - version 5.11.2).

Here are the infos:
```
c BreakID not compiled in, disabling
c CryptoMiniSat version 5.11.2
c CMS Copyright (C) 2009-2020 Authors of CryptoMiniSat, see AUTHORS file
c CMS SHA revision 3be6e0f56ce55685e029afb93bfcc2d0800d8c1f
c CMS is GPL licensed due to M4RI being linked. Build without M4RI to get MIT version
c Using VMTF code by Armin Biere from CaDiCaL
c Using Yalsat by Armin Biere, see Balint et al. Improving implementation of SLS solvers [...], SAT'14
c Using WalkSAT by Henry Kautz, see Kautz and Selman Pushing the envelope: planning, propositional logic, and stochastic search, AAAI'96,
c Using code from 'When Boolean Satisfiability Meets Gauss-E. in a Simplex Way'
c       by C.-S. Han and J.-H. Roland Jiang in CAV 2012. Fixes by M. Soos
c Using CCAnr from 'CCAnr: A Conf. Checking Based Local Search Solver [...]'
c       by Shaowei Cai, Chuan Luo, and Kaile Su, SAT 2015
c Ported to Microsoft Visual C++ 2022 by Axel Kemper, Springe
c CMS compilation env CMAKE_CXX_COMPILER = VC++ 2022 | CMAKE_CXX_FLAGS =  | COMPILE_DEFINES =  | STATICCOMPILE = yes | ONLY_SIMPLE = no | Boost_FOUND = yes | STATS = no | SQLITE3_FOUND = no | ZLIB_FOUND = no | VALGRIND_FOUND = no | ENABLE_TESTING = no | M4RI_FOUND = yes | NOM4RI = 0 | SLOW_DEBUG = 0 | ENABLE_ASSERTIONS = yes | PYTHON_EXECUTABLE = no | PYTHON_LIBRARY = no | PYTHON_INCLUDE_DIRS = n/a | MY_TARGETS = n/a | LARGEMEM = no | LIMITMEM = n/a | BREAKID_LIBRARIES = n/a | BREAKID-VER = n/a | BOSPHORUS_LIBRARIES = n/a | BOSPH-VER = n/a | compilation date time = Sep 28 2022 23:13:31
c CMS compiled with Microsoft Visual C++ 2022 64-bit compiler
c Executed with command line: cryptominisat5
c Reading from standard input... Use '-h' or '--help' for help.
```

Thank you in advance.

**Comment by msoos** [comment]
Ah I see! Thanks, I’ll provide a new release in about 10h and then you can
use that :) Thanks again,

Mate

**Comment by msoos** [comment]
Hmmm... would it be a possibility to use the pypi package of CryptoMiniSat? It works well on Windows, and is available as a pre-built: https://pypi.org/project/pycryptosat/ Building a Windows binary is always a bit of a hassle. Let me know if that works for you,

Mate

**Comment by PeterMacGonagan** [comment]
No, sorry the problem is "too big" for pycryptosat ... but I've tried the last version of cryptominisat on Ubuntu (I compile it myself) and it works :)
I've searched for more instructions to compile cryptominisat on Windows without success...

`C:\> [ download cryptominisat-version.zip ]
C:\> unzip cryptominisat-version.zip
C:\> rename cryptominisat-version cms
C:\> cd cms
C:\cms> mkdir build
C:\cms> cd build`

Ok

`C:\cms\build> [ download http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.zip ]
C:\cms\build> unzip boost_1_59_0.zip
C:\cms\build> mkdir boost_1_59_0_install
C:\cms\build> cd boost_1_59_0
C:\cms\build\boost_1_59_0> bootstrap.bat --with-libraries=program_options
C:\cms\build\boost_1_59_0> b2 --with-program_options address-model=64 toolset=msvc-14.0 variant=release link=static threading=multi runtime-link=static install --prefix="C:\cms\build\boost_1_59_0_install" > boost_install.out
C:\cms\build\boost_1_59_0> cd .. `

I've got all the libs for boost_1_59_0. I didn't compile them. I've installed the release. 
I don't know if we are stuck with this version (last: 1.84) ?
![image](https://github.com/msoos/cryptominisat/assets/8655251/da7553c7-80ad-4691-af8a-192c73f46f34)
...

`C:\cms\build> git clone https://github.com/madler/zlib
C:\cms\build> cd zlib
C:\cms\build\zlib> git checkout v1.2.8
C:\cms\build\zlib> mkdir build
C:\cms\build\zlib> mkdir myinstall
C:\cms\build\zlib> cd build
C:\cms\build\zlib\build> cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\cms\build\zlib\myinstall ..
C:\cms\build\zlib\build> msbuild /t:Build /p:Configuration=Release /p:Platform="x64" zlib.sln
C:\cms\build\zlib\build> msbuild INSTALL.vcxproj
C:\cms\build> cd ..\..`

Is this lib mandatory?

```
C:\compile\cms\build\zlib\build> cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\cms\build\zlib\myinstall ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Error at CMakeLists.txt:4 (project):
  Failed to run MSBuild command:
```

  `  MSBuild.exe`

```
 to get the value of VCTargetsPath:

    MSBuild version 17.7.2+d6990bcfa for .NET Framework
    Build started 1/7/2024 9:37:50 AM.

    Project "C:\compile\cms\build\zlib\build\CMakeFiles\3.28.1\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: The build tools for Visual Studio 2015 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install Visual Studio 2015 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\compile\cms\build\zlib\build\CMakeFiles\3.28.1\VCTargetsPath.vcxproj]
    Done Building Project "C:\compile\cms\build\zlib\build\CMakeFiles\3.28.1\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\compile\cms\build\zlib\build\CMakeFiles\3.28.1\VCTargetsPath.vcxproj" (default target) (1) ->
    (PrepareForBuild target) ->
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: The build tools for Visual Studio 2015 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install Visual Studio 2015 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\compile\cms\build\zlib\build\CMakeFiles\3.28.1\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.23


  Exit code: 1
```



```
-- Configuring incomplete, errors occurred!`

Is it possible to compile it with Visual Studio 2022 or do I need to install Visual Studio 2015?

`C:\cms\build> cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DSTATICCOMPILE=ON -DZLIB_ROOT=C:\cms\build\zlib\myinstall -DBOOST_ROOT=C:\cms\build\boost_1_59_0_install ..
C:\cms\build> cmake --build --config Release .`
```

Ok, I've installed CMAKE. 
I've launched, in administrator, a developper console:
![image](https://github.com/msoos/cryptominisat/assets/8655251/f75449c2-4dd1-440b-8a67-ebd01a9f7f36)
I've tried 2019 and 2022 without success.

**Comment by a1880** [comment]
It is in fact tricky o build Cryptominisat with Visual Studio 2022.

However, there are two easy workarounds to get cryptominisat under Windows:
First is to install a Linux subsystem [WSL2 ](https://learn.microsoft.com/en-us/windows/wsl/install)under Windows.
This allows to build cryptominisat with the Linux build instructions.
The resulting executable can be run with "wsl cryptominisat5".

The second way is to install [MSys2](https://www.msys2.org/).
This provides a Linux look-alike environment under Windows.
The installation then works as follows:

```
# Install prerequisites
pacman -S cmake
pacman -S mingw-w64-x86_64-boost
pacman -S zlib-devel
pacman -S git

#  Assuming that your c++ code directory is ~/cppsrc
cd ~/cppsrc
#  remove old directory, if there is one
[ -d cryptominisat ] && rm -rf cryptominisat

#  download current sources
git clone https://github.com/msoos/cryptominisat

cd cryptominisat
mkdir build
cd build
#  add further switches as desired
cmake -DSTATICCOMPILE=ON ..
cd ..
#  here, "make" is replaced by cmake --build
cmake --build build

```

This should compile and link cryptominisat5.exe in ~/cppsrc/cryptominisat/build.
You can copy and use this file as normal Windows executable.

I have opted for static compilation which grows the executable to more than 31 mb.
With the default of dynamic libraries, I have not managed to get around missing .dll files.

**Comment by msoos** [comment]
Hi,

While I know you had to wait a long time, but I now did a 1600+ line change so this will compile in Windows without the boost libraries. Which means that GitHub will build the binary for me, so you can have the most up-to-date binary at any point :) I am now fixing the builder on GitHub, shouldn't be more than 10 minutes, then I'll put here the link where you can get the built binary from GitHub -- that way, you don't have to trust anyone with binaries, only the GitHub runner and the source code that is available to see :)

Sorry it took so long,

Mate

**Comment by msoos** [comment]
Hi,

You can download the Windows binary here:

https://github.com/msoos/cryptominisat/actions/runs/7514415633

At the bottom under `Artifacts`, it says `cryptominisat5-win64.exe` You need to unzip it and my understanding is that it should "just work". Let me know how it goes. In the meanwhile, I'm closing this issue -- but feel free to reopen/comment in case that doesn't work for you.

Thanks again for this issue,

Mate
