### ISSUE TITLE
`--pre-proc` gone in v5.11.21

### ISSUE THREAD

**Issue by Geremia** [msoos/cryptominisat#745]
I haven't used CMS since v5.11.3, and it appears 5.11.21 no longer has the `--pre-proc` option to output a simplified CNF. Is there a away to do this in v5.11.21?

**Comment by msoos** [comment]
Hi,

Thanks for notifying us! We'll add an update to the README about this. We have moved all our preprocessing system to arjun: https://github.com/meelgroup/arjun This uses CryptoMiniSat and does a much better job :) Just call it like so:

```
./arjun input.cnf preprocessed.cnf
```

I hope this helps. Let me know if it doesn't work, etc!

Cheers,

Mate

**Comment by Geremia** [comment]
Thanks.

**Comment by Geremia** [comment]
@msoos How's in compare with [SBVA](https://github.com/hgarrereyn/SBVA)?
