### ISSUE TITLE
Building CBMC with CMS backend via IPASIR?

### ISSUE THREAD

**Issue by Geremia** [msoos/cryptominisat#746]
I'm trying to build [CBMC](https://github.com/diffblue/cbmc/) using CMS as its backend, via [IPASIR](https://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index-seo.php/IPASIR____IPASIR), but I'm running into [this build problem](https://github.com/diffblue/cbmc/issues/8249):

> CBMC version: 5.95.1 Operating system: Linux kernel 6.6.21
> 
> I have these flags in my `cmake` command:
> 
> ```
>     -Dsat_impl=ipasir-custom \
>     -DIPASIR=/tmp/SBo/cryptominisat-5.11.21/src \
>     -DIPASIR_LIB=/usr/lib$LIBDIRSUFFIX/libcryptominisat5.a \
> ```
> 
> But when making, I get:
> 
> ```
> -- Building CBMC version 5.95.1
> -- Rule launch compile: /usr/bin/ccache
> -- Building with IPASIR solver linking: custom solver provided
> CMake Error at src/libcprover-cpp/CMakeLists.txt:70 (message):
>   libcprover-cpp cannot be linked as dependency dep_path-NOTFOUND does not
>   have a static correspondent file (dep_path-NOTFOUND)
> ```

Perhaps you, @msoos,  can help me with this?
Thanks in advance. 🙏

**Comment by Geremia** [comment]
Well, it seems to be a `cmake` issue. I was able to compile CBMC with CMS backend successfully, simply using `make`. 😄

Testing:
```c
#include <assert.h>

int main()
{
  unsigned x;
  unsigned y = x / 1.00009;
  assert(y != x);
  assert(y <= x);
  return 0;
}
```

```
CBMC version 6.0.0-preview (7d013747) 64-bit x86_64 linux
Parsing test.c
Converting
Type-checking test
Generating GOTO Program
Adding CPROVER library (x86_64)
Removal of function pointers and virtual functions
Generic Property Instrumentation
Running with 8 object bits, 56 offset bits (default)
Starting Bounded Model Checking
Runtime Symex: 0.00072506s
size of program expression: 24 steps
simple slicing removed 5 assignments
Generated 2 VCC(s), 2 remaining after simplification
Runtime Postprocess Equation: 7.44e-06s
Passing problem to propositional reduction
converting SSA
Runtime Convert SSA: 0.000829781s
Running propositional reduction
Post-processing
Runtime Post-process: 4.56e-06s
Solving with cryptominisat-5.11.21
353 variables, 1076 clauses
SAT checker: instance is SATISFIABLE
Runtime Solver: 0.00018027s
Runtime decision procedure: 0.00105989s
Running propositional reduction
Solving with cryptominisat-5.11.21
354 variables, 1077 clauses
SAT checker: instance is UNSATISFIABLE
Runtime Solver: 1.291e-05s
Runtime decision procedure: 4.279e-05s

** Results:
test.c function main
[main.assertion.1] line 7 assertion y != x: FAILURE
[main.assertion.2] line 8 assertion y <= x: SUCCESS

** 1 of 2 failed (2 iterations)
VERIFICATION FAILED
```
😇

**Comment by msoos** [comment]
Ooops, sorry. I was on a trip, still on a trip, so couldn't really respond in time. BTW, it could be that if you use the version of the IPASIR library of CryptoMiniSat submitted to the 2020 SAT Competition, you may get better performance. Mathias Fleury alerted me to this -- there may be a performance degradation somewhere in CryptoMiniSat. I'll debug in the coming weeks/month. Sorry for that. But if it works OK, then no need to touch it :) Likely not as serious, especially when used from an outside solver like CBMC.

Cheers,

Mate
