### ISSUE TITLE
moving from toml to tomli?

### ISSUE THREAD

**Issue by dimpase** [msoos/cryptominisat#747]
[`toml`](https://github.com/msoos/cryptominisat/blame/4c9a6b6b459b7c1381744115ccfe744f1121794b/setup.py#L30) is more or less abandonware now, everybody has moved to `tomli`.
Found this while working on https://github.com/sagemath/sage/issues/34687

Would you mind moving to `tomli` too?

**Comment by msoos** [comment]
Sure! The PRs are open, and I'd be very happy to review and accept a pull request to make the move!
