### ISSUE TITLE
-DSTATS=ON → "Could NOT find SQLITE3 (missing: SQLITE3_LIBRARY)"

### ISSUE THREAD

**Issue by Geremia** [msoos/cryptominisat#748]
I have Louvain communities installed, but `-DSTATS=ON` yields:
```
CMake Error at /usr/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SQLITE3 (missing: SQLITE3_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSQLITE3.cmake:20 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:472 (find_package)
```
I have sqlite-3.45.2, too:
```
usr/
usr/bin/
usr/bin/sqldiff
usr/bin/sqlite3
usr/bin/sqlite3_analyzer
usr/doc/
usr/doc/sqlite-3.45.2/
usr/doc/sqlite-3.45.2/COPYRIGHT
usr/doc/sqlite-3.45.2/README.md
usr/doc/sqlite-3.45.2/VERSION
usr/include/
usr/include/sqlite3.h
usr/include/sqlite3ext.h
usr/lib64/
usr/lib64/libsqlite3.so.0.8.6
usr/lib64/pkgconfig/
usr/lib64/pkgconfig/sqlite3.pc
usr/lib64/tcl8.6/
usr/lib64/tcl8.6/sqlite3/
usr/lib64/tcl8.6/sqlite3/libtclsqlite3.so
usr/lib64/tcl8.6/sqlite3/pkgIndex.tcl
usr/man/
usr/man/man1/
usr/man/man1/sqlite3.1.gz
```

**Comment by msoos** [comment]
Hi,

You also need to install `libsqlite3-dev` or similar package that installs the sqlite headers, then it should work! Let me know how it goes,

Mate

**Comment by Geremia** [comment]
@msoos My distro (Slackware) doesn't have such a package (that I can find), just [an sqlite one](https://mirror.slackbuilds.org/slackware/slackware64-current/source/ap/sqlite/). How do I build the developer version?

**Comment by msoos** [comment]
Sorry, I don't know how I can help you with slackware. You need the header files to be able to build CMS with stats. I suggest looking around on the internet how your distro handles development/header files for libraries. There likely is a way. Perhaps called "lib..." or somesuch.

**Comment by a1880** [comment]
It looks like `cmake` is unable to find `sqlite3`.
Could it be that `/usr/bin` is not on your search `PATH`?
Perhaps, [this post](https://stackoverflow.com/a/25396791/1911064) could be helpful.
Another obstacle might be your `usr/lib64` rather than `usr/lib`.

**Comment by Geremia** [comment]
@a1880 Yes, it was a path issue. I had to add `CMAKE_PREFIX_PATH "/usr/lib64"` to my `cmake` argument list. Thanks & happy Easter!

**Comment by msoos** [comment]
Ah nice! Thank you @a1880 for helping out. Sorry I gave up so fast :S Happy Easter everyone! :)
