### ISSUE TITLE
Parsing for multiple 'c ind' lines

### ISSUE THREAD

**Issue by tanyongkiam** [msoos/cryptominisat#754]
Hi,

I think https://github.com/msoos/cryptominisat/commit/d477b0db9cf066f3c2852e6fe5b22f7d4946b8b4 removed support for having multiple `c ind` lines.

I'm not sure if this is intended but, in particular, it seems like only the very last `c ind` line is supported now.

This happens because https://github.com/msoos/cryptominisat/commit/d477b0db9cf066f3c2852e6fe5b22f7d4946b8b4#diff-b7c0761469162299827d62d4782bc7596370cf7a0a28d47d1e7a193a00efd91dR458 sets the sampling vars by overwriting the old ones.

It might be nice to add an error for multi-line `c ind` files if this is an intended change.

```
p cnf 3 1
c ind 1 0
c ind 2 0
c ind 3 0
1 2 3 0
```

ApproxMC truncated output:

```
c ApproxMC SHA revision 98a3147c368cf17cb10d65b41a5a52ac4f6c166e
...
c executed with command line: approxmc --arjun 0 03B-2.cnf.gz.no_w.cnf
c -- header says num vars:              3
c -- header says num clauses:           1
c -- clauses added: 1
c -- xor clauses added: 0
c -- vars added 3
c ind 3 0
c [arjun] final set size:            1 percent of original:      0 %
c [arjun] of which empty occs:       0 percent of original:      0 %
c [appmc] Sampling set size: 1
...
s SATISFIABLE
s mc 2
```

**Comment by msoos** [comment]
Oh wow, great find, thank you! OK, let me abort when there is more than one. Sorry about that. I'll fix and close this. Sorry again. 

Mate

**Comment by msoos** [comment]
Yay, fixed with https://github.com/msoos/cryptominisat/commit/bdd46777d70989b932dcbdb64140d742dddd57d4

Sorry for that, and thank you for spotting this!

Mate
