### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TrevorHansen** [msoos/cryptominisat#757]
Hi @msoos 

@gussmith23 has reported that CMS segfaults on this STP generated CNF:

[output_0.cnf.txt](https://github.com/user-attachments/files/15813324/output_0.cnf.txt)

**Comment by msoos** [comment]
Thanks! Sorry, I bumped into this bug and I fixed it already in  another branch. Let me cherry-pick the fix :)

**Comment by msoos** [comment]
OK, fixed, closing. Sorry for this! :S
