### ISSUE TITLE
Make error - Cadiback Issue

### ISSUE THREAD

**Issue by anna-guinet** [msoos/cryptominisat#758]
Hello! 

I installed successfully Cadiback and Cadical, and downloaded the recent version of cryptominisat with `git clone --depth 1 https://github.com/msoos/cryptominisat.git` (as instructed in Bosphorus repository). 
My version is `commit b735c944a6c87dea36b485ddb299098dd61e0e22`.

While running 'make', I get this error: 
```
/cryptominisat/src/backbone.cpp: In member function ‘bool CMSat::Solver::backbone_simpl(int64_t, bool&)’:
/home/my/path/cryptominisat/src/backbone.cpp:53:54: error: too few arguments to function ‘int CadiBack::doit(const std::vector<int>&, int, std::vector<int>&, std::vector<int>&)’
   53 |     int sat = CadiBack::doit(cnf, conf.verbosity, ret);
      |                                                      ^
In file included from /home/my/path/cryptominisat/src/backbone.cpp:24:
/home/my/path/cryptominisat/../cadiback/cadiback.h:5:5: note: declared here
    5 | int doit (const std::vector<int>& cnf,
      |     ^~~~
/home/my/path/cryptominisat/src/backbone.cpp:28:37: warning: unused parameter ‘orig_max_confl’ [-Wunused-parameter]
   28 | bool Solver::backbone_simpl(int64_t orig_max_confl, bool& finished)
      |                             ~~~~~~~~^~~~~~~~~~~~~~
make[2]: *** [cmsat5-src/CMakeFiles/cryptominisat5.dir/build.make:102: cmsat5-src/CMakeFiles/cryptominisat5.dir/backbone.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:180: cmsat5-src/CMakeFiles/cryptominisat5.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

Do have any idea why? I am running it on Ubuntu 22.04.4 LTS

**Comment by anna-guinet** [comment]
Found the error! It's because of the last commit to Cadiback (`commit 741e01681d90b5e6e8a4955de63a57d993d9e540`). 
Had to revert back to `commit 69255f55e411207c4bdea02c6c2ab1ef29740ce1` to make it work.

**Comment by msoos** [comment]
Oops sorry for that. I’ll revert back tonight so others don’t face this
issue. I’m sorry.

Mate

**Comment by msoos** [comment]
I just force-pushed a change so others won't face this issue :)
