### ISSUE TITLE
Question about simplify() Function and Variable Freezing in CryptoMiniSat

### ISSUE THREAD

**Issue by tzzht** [msoos/cryptominisat#767]
Hello msoos,

I have a somewhat silly question regarding the use of CryptoMiniSat in an IC3 implementation that involves incremental SAT solving.

1. Deleting Clauses by Setting a Literal to True:
During the process, there are moments when certain clauses are no longer necessary. I want to delete them by setting a literal within those clauses to true. Can the simplify() function handle this, or is there an alternative approach I should consider?

2. Behavior of simplify() Function & Variable Freezing:
In CryptoMiniSat, I haven't found a feature analogous to MiniSAT's "Frozen" for certain variables. Could you clarify the behavior of the simplify() function:
    - Does it only remove clauses that are already true without modifying other clauses?
    - Does it keep xor clauses that have free variables?
    - Does it preserve the number and index of variables, ensuring they remain unchanged?

Your insights would be greatly appreciated!
Thank you in advance for your help.

Best regards

**Comment by msoos** [comment]
Hi,

There is not even a need to call simplify(). Just set it to true via an `addClause()` and it'll be fine. Don't worry about the internals. You should not normally need to call `simplify()`, ever.

There is no need to freeze variables as in MiniSat. CMS (i.e. CryptoMiniSat) is smart enough not to have to do all that nonsense. It just does everything under the hood as you'd like it to be, without all the nonsense of freezing and thawing and I don't know what. You can just add any variable any time, assume it, whatever.

Basically, don't worry about simplify() and don't worry about freezing and thawing. All that is not required. Just use it, and it will do what it's supposed to do, without you having to do all sorts of bookkeeping.

I hope this helped! Unfortunately CMS nowadays is somehow not doing well on incremental solving... so please don't be alarmed, it may be a bit slower than it should be. I'll look into it in the coming days. Something got messed up. I'll get back to you in a few days. Let's keep this issue open, so you can ask more questions and I can get back to you about fixing the slowdown.

Let me know if you have any further issues,

Mate

PS: 

- `Does it keep xor clauses that have free variables?` -- it removes them internally, but you won't notice that. It's designed not to put the burden on the user but on the solver
- `Does it only remove clauses that are already true without modifying other clauses?` it removes many clauses that are useless, e.g. already satisfied ones, subsumed ones, etc. But again, this is not something you should worry about, as the user doesn't even know what the internals are supposed to be ;) 
- `Does it preserve the number and index of variables, ensuring they remain unchanged?` -- you mean `nVars()` ? Yes.

**Comment by msoos** [comment]
I am closing because I think I answered it all :) Please re-open if you have any further questions!
