### ISSUE TITLE
Why does cryptominisat expect the libcadiback library?

### ISSUE THREAD

**Issue by yurivict** [msoos/cryptominisat#773]
cmake expects it [here](https://github.com/msoos/cryptominisat/blob/8c265503cfc02eeda3fcbf101578e8eea9f398f5/CMakeLists.txt#L537).

Cadiback only builds one executable, see the makefile [here](https://github.com/arminbiere/cadiback/blob/main/makefile.in).

**Comment by msoos** [comment]
Hi,

CryptoMiniSat needs a CadiBack library. The README explains how to build it:

```
sudo apt-get install build-essential cmake libgmp-dev

# not required but very useful
sudo apt-get install zlib1g-dev

git clone https://github.com/meelgroup/cadical
cd cadical
git checkout mate-only-libraries-1.8.0
./configure
make
cd ..

git clone https://github.com/meelgroup/cadiback
cd cadiback
git checkout mate
./configure
make
cd ..

git clone https://github.com/msoos/cryptominisat
cd cryptominisat
mkdir build && cd build
cmake ..
make
sudo make install
sudo ldconfig
```

That will build a cadiback library. I hope this helps,

Mate

**Comment by yurivict** [comment]
Thanks.
