### ISSUE TITLE
DRUP: What is it? How can one use it? What else is needed?

### ISSUE THREAD

**Issue by capiman** [msoos/cryptominisat#79]
I saw you changes in the sources the last days about DRUP.
I also saw your post in minisat mailing list about DRUP,
with the following link:

http://www.cs.utexas.edu/~marijn/drup/

Can you explain a bit what DRUP is for?
How can it be used? What command line options to use for it?

Does it create a file which can be used with a drup checker mentioned
in the URL above?

Can it be used for verifying internal handling of CMS?
Something like a logfile which can be automatically checked for correctness?

There was also a change compfinder.\* and comphandler.*
Is this something related to DRUP, or something completely different?

**Comment by Storyyeller** [comment]
In case anyone else was wondering like me how to actually generate the proof, you just need to pass a second filename to the solver, and the proof will be written to that file.
